### ISSUE TITLE
KSP thru CKAN wont launch'

### ISSUE THREAD

**Issue by leoponka** [KSP-CKAN/CKAN#3544] opened 2022-03-13 17:19 UTC
Operating System: Windows 10
*CKAN Version: 1.30.4
*KSP Version: 1.05.1028

Problem

When i try to launch ksp through ckan it shows error

![Zrzut ekranu (1)](https://user-images.githubusercontent.com/101520025/158071324-19653174-8055-43b6-b1db-a09c21ea356d.png)

**Comment by HebaruSan** [comment] 2022-03-13 17:23
Duplicate of #3493
Duplicate of #3513

**Comment by HebaruSan** [comment] 2022-03-13 17:23
Duplicate of #3513

**Comment by HebaruSan** [comment] 2022-03-13 17:24
Hi, the problem is you're using a version of KSP that only shipped a 32-bit executable, and the default is now to use the 64 bit executable. You can either use a more recent version (recommended), or configure CKAN to launch the 32-bit executable. See either of those issues for details.

**Closed by HebaruSan** 2022-03-13 17:24 UTC
Labels: Support, Duplicate
