### ISSUE TITLE
Unable to open CKAN

### ISSUE THREAD

**Issue by kungfufishstick** [KSP-CKAN/CKAN#2496] opened 2018-08-12 05:01 UTC
**CKAN Version:** 
Newest version as of August 11, 2018

**KSP Version:** 
Steam version 1.4.5.2243

**Operating System:** 
Windows 7

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

Problem
-------

**What steps did you take in CKAN?**
Downloaded the latest ckan.exe file. Tried running it from the downloads folder, the desktop, and the KSP directory. I also attempted to install .NET 4.5. Prompted that I am running 4.5 or higher already.

**What did you expect to happen?**
CKAN to open like it did with previous versions

**What happened instead?**
It crashes whenever I try to run

**Screenshots:**
![image](https://user-images.githubusercontent.com/13251417/43998745-aa75794e-9dc2-11e8-993d-c2876ab54cc1.png)

**CKAN error codes (if applicable):** 
DOS prompt shows "unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object."

**Comment by kungfufishstick** [comment] 2018-08-12 05:35
Issue can be closed. I deleted CKAN and ran CCleaner. CKAN opened on the first try.

**Comment by HebaruSan** [comment] 2018-08-12 14:17
Duplicate of #2483, fixed in #2482.

**Closed by HebaruSan** 2018-08-12 14:17 UTC
