### ISSUE TITLE
SSL-Certificate-issue

### ISSUE THREAD

**Issue by olsvse** [KSP-CKAN/CKAN#3583] opened 2022-06-01 13:54 UTC
Hello,

I start to download and install StarshipExpansionProject v1.0.1 with CKAN and get the following message:
--------------------------------------------
Error downloading StarshipExpansionProject v1.0.1: Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
  at /builddir/build/BUILD/mono-6.12.0.122/external/boringssl/ssl/handshake_client.c:1132
--------------------------------------------
I have yesterday reported this behaviour to the responsible of the StarshipExpansionProject. 
She says that from her side is all OK and I should contact the CKAN-Responsible.

How I can resolve the Issue with the Certificate?

Thanks for your help.

Regards,
Oliver

**Comment by DasSkelett** [comment] 2022-06-01 14:28
Hey, please try the steps listed here: https://github.com/KSP-CKAN/CKAN/wiki/SSL-certificate-errors#removing-expired-lets-encrypt-certificates

**Comment by HebaruSan** [comment] 2022-06-01 14:54
Duplicate of #3468

**Comment by HebaruSan** [comment] 2022-06-02 18:07
Closing as known issue with solution/workaround provided. @olsvse, please let us know if you still have trouble after following those instructions.

**Closed by HebaruSan** 2022-06-02 18:07 UTC
Labels: Support, Linux, Network
