### ISSUE TITLE
CKAN complains about temp files when upgrading a mod and installing another one at the same time

### ISSUE THREAD

**Issue by judemille** [KSP-CKAN/CKAN#1367] opened 2015-08-10 16:08 UTC
When I download a large amount of mods, CKAN barfs, complaining that it can't access this ONE temp file.

```
Unhandled exception:
System.IO.IOException: The process cannot access the file 'C:\Users\FireFaced\AppData\Local\Temp\tmp8C0B.tmp' because it is being used by another process.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.File.InternalDelete(String path, Boolean checkHost)
at CKAN.NetAsyncDownloader.ModuleDownloadsComplete(Ne tFileCache cache, Uri[] urls, String[] filenames, Exception[] errors)
at CKAN.NetAsyncDownloader.<DownloadModules>c__AnonSt orey2.<>m__1(Uri[] _uris, String[] paths, Exception[] errors)
at System.Threading.ExecutionContext.RunInternal(Exec utionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionCon text executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.QueueUserWorkItemCallback.System. Threading.IThreadPoolWorkItem.ExecuteWorkItem()
at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by Postremus** [comment] 2015-08-10 20:16
May be related to #801

**Comment by FireFaced** [comment] 2015-08-10 20:39
I don't think so.

**Comment by FireFaced** [comment] 2015-08-12 16:10
Okay, I cleared my temp file, issue doesn't seem to come up. Closing this, and it seems that it is related to #801

**Comment by FireFaced** [comment] 2015-08-12 23:22
All right, I'm sick of this. Now it's holding onto a different temp file EVEN THOUGH my temp folder is merely 1MB

**Comment by FireFaced** [comment] 2015-08-12 23:22
*facepalm* Remind me NOT to click the close button

**Comment by FireFaced** [comment] 2015-08-12 23:23
Ugh. @pjf can you please reopen this? I didn't mean to click "comment and close"

**Comment by FireFaced** [comment] 2015-08-13 12:39
Thank you, I didn't mean to close it after I reopened it.

**Comment by squizzeak** [comment] 2015-08-13 14:37
I am able to reliably reproduce temp file issues by trying to both upgrade a mod and install a new one at the same time.  Not sure if it's related.

**Comment by FireFaced** [comment] 2015-08-13 14:53
Yeah, usually when I install mods, I also just run through the upgrades. Strange

**Comment by FireFaced** [comment] 2015-08-14 17:48
Anyone?

**Comment by Postremus** [comment] 2015-08-14 17:54
Can you Point the issue down to a specific mod?

**Comment by FireFaced** [comment] 2015-08-14 17:57
No, it's pretty broad. It usually comes up when I install a lot of mods AND upgrade a bunch of mods.

**Comment by squizzeak** [comment] 2015-08-14 18:06
I've had it occur with as little as a single new mod install and a single mod update in the same change list.

**Comment by FireFaced** [comment] 2015-08-14 18:13
Huh. Yeah, the issue is quite broad.

**Comment by Postremus** [comment] 2015-08-14 18:21
@FireFaced @squizzeak I am unable to reproduce this bug. Would you mind testing a dev version which may fix this issue?

**Comment by FireFaced** [comment] 2015-08-14 18:23
Sure

**Comment by Postremus** [comment] 2015-08-14 18:25
https://dl.dropboxusercontent.com/u/46071056/CKAN/ckan.exe
Please paste the new exception.

**Comment by Postremus** [comment] 2015-08-14 18:40
I gave this issue a higher priority, since it is a bad thing if ckan doesn't do it's job (installing mods).

**Comment by squizzeak** [comment] 2015-08-14 19:14
Same result with the version you posted, attempting to update 3 mods and install 1 new one.

Unhandled exception:
System.IO.IOException: The process cannot access the file because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at ChinhDo.Transactions.TxFileManager.Move(String srcFileName, String destFileName)
   at CKAN.NetFileCache.Store(Uri url, String path, String description, Boolean move)
   at CKAN.NetAsyncDownloader.ModuleDownloadsComplete(NetFileCache cache, Uri[] urls, String[] filenames, Exception[] errors)
   at CKAN.NetAsyncDownloader.<>c__DisplayClass19_0.<DownloadModules>b__1(Uri[] _uris, String[] paths, Exception[] errors)
   at CKAN.NetAsyncDownloader.FileDownloadComplete(Int32 index, Exception error)
   at CKAN.NetAsyncDownloader.<>c__DisplayClass16_0.<DownloadNative>b__1(Object sender, AsyncCompletedEventArgs args)
   at System.ComponentModel.AsyncCompletedEventHandler.Invoke(Object sender, AsyncCompletedEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()


OS: Windows 8.1 Pro x64

**Comment by FireFaced** [comment] 2015-08-17 15:03
Okay, it's confirmed: Upgrade mods, and install at least one mod at the same time, get this:
 > Unhandled exception:
System.IO.IOException: The process cannot access the file 'C:\Users\FireFaced\AppData\Local\Temp\tmpB938.tmp' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at CKAN.NetAsyncDownloader.ModuleDownloadsComplete(NetFileCache cache, Uri[] urls, String[] filenames, Exception[] errors)
   at CKAN.NetAsyncDownloader.<DownloadModules>c__AnonStorey2.<>m__1(Uri[] _uris, String[] paths, Exception[] errors)
   at CKAN.NetAsyncDownloader.FileDownloadComplete(Int32 index, Exception error)
   at System.ComponentModel.AsyncCompletedEventHandler.Invoke(Object sender, AsyncCompletedEventArgs e)
   at System.Net.WebClient.OnDownloadFileCompleted(AsyncCompletedEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch() 

I'm on Win 10 Home x64

**Comment by plague006** [comment] 2015-08-17 15:20
I actually got the same (with a different temp file name). Win7 64-bit.
Upgrading `Chatterer` and installing `KAL9000`

**Comment by FireFaced** [comment] 2015-08-17 15:20
So, it's most versions of Windows.

**Comment by FireFaced** [comment] 2015-08-17 15:36
@plague006 I don't think that's relevant, TBH. It seems to not matter which mod is installed/upgraded, just that you upgrade and install mods at the same time.

**Comment by plague006** [comment] 2015-08-17 15:37
You're correct that it's not about which mods. I just provide information if it's available.

**Comment by FireFaced** [comment] 2015-08-17 15:38
Okay.

**Comment by FireFaced** [comment] 2015-08-19 00:41
Anybody? I REALLY just want to have CKAN manage mods properly.

**Comment by Postremus** [comment] 2015-08-19 05:20
@FireFaced @plague006 Does the .zip of the mod already exists in your CKAN/dowloads Folder before you install / update the mod? Does it still exists after the install / update ?

**Comment by FireFaced** [comment] 2015-08-19 12:33
@Postremus, it wouldn't matter, the ZIP file has a different name in each version. Also, the mods I've been installing in the tests were never in my cache.

**Comment by plague006** [comment] 2015-08-19 12:46
In my case the files weren't cached @Postremus, and the .zips are present after the transaction.

**Comment by Postremus** [comment] 2015-08-19 14:33
Ok, ckan is srupid.

----- Ursprüngliche Nachricht -----
Von: "Matthew" <notifications@github.com>
Gesendet: ‎19.‎08.‎2015 14:46
An: "KSP-CKAN/CKAN" <CKAN@noreply.github.com>
Cc: "Martin Panzer" <postremus1996@googlemail.com>
Betreff: Re: [CKAN] CKAN complains about temp files when upgrading a mod andinstalling another one at the same time (#1367)

In my case the files weren't cached @Postremus, and the .zips are present after the transaction.

**Comment by FireFaced** [comment] 2015-08-19 14:44
@Postremus 
Very srupid.

**Comment by Postremus** [comment] 2015-08-19 14:55
That was my mobil phone, not me. :)

----- Ursprüngliche Nachricht -----
Von: "FireFaced, AKA TheCrazyCarts" <notifications@github.com>
Gesendet: ‎19.‎08.‎2015 16:45
An: "KSP-CKAN/CKAN" <CKAN@noreply.github.com>
Cc: "Martin Panzer" <postremus1996@googlemail.com>
Betreff: Re: [CKAN] CKAN complains about temp files when upgrading a mod andinstalling another one at the same time (#1367)

@Postremus 
Very srupid.

**Comment by FireFaced** [comment] 2015-08-19 14:57
I know @Postremus

**Comment by Postremus** [comment] 2015-08-19 16:30
@FireFaced another dev version:
https://dl.dropboxusercontent.com/u/46071056/CKAN/ckan.exe

**Comment by squizzeak** [comment] 2015-08-21 16:30
Tried another install + upgrade with the dev version you just posted, @Postremus.  Results are below.

Install: Water Sounds 
Upgrade: A visor for Valentina

---

Downloading "https://kerbalstuff.com/mod/1094/A visor for Valentina/download/1.01"
About to install...

 * WaterSounds 1.1

Downloading "https://kerbalstuff.com/mod/1094/A visor for Valentina/download/1.01"
Downloading "https://kerbalstuff.com/mod/823/Water Sounds/download/1.1"

---

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
CKAN.FileNotFoundKraken: Trying to install WaterSounds 1.1, but it's not downloaded or download is corrupted
   at CKAN.ModuleInstaller.Install(CkanModule module, String filename)
   at CKAN.ModuleInstaller.InstallList(ICollection`1 modules, RelationshipResolverOptions options, IDownloader downloader)
   at CKAN.ModuleInstaller.InstallList(List`1 modules, RelationshipResolverOptions options, IDownloader downloader)
   at CKAN.Main.<>c__DisplayClass230_0.<InstallList>b__0()
   at CKAN.Main.WasSuccessful(Action action)
   at CKAN.Main.InstallList(HashSet`1 toInstall, RelationshipResolverOptions options, IDownloader downloader)
   at CKAN.Main.InstallMods(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by FireFaced** [comment] 2015-08-22 15:32
> Unhandled exception:
System.IO.IOException: The process cannot access the file 'C:\Users\FireFaced\AppData\Local\Temp\tmp6B83.tmp' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at CKAN.NetAsyncDownloader.ModuleDownloadsComplete(NetFileCache cache, Uri[] urls, String[] filenames, Exception[] errors)
   at CKAN.NetAsyncDownloader.<DownloadModules>c__AnonStorey2.<>m__1(Uri[] _uris, String[] paths, Exception[] errors)
   at CKAN.NetAsyncDownloader.FileDownloadComplete(Int32 index, Exception error)
   at System.ComponentModel.AsyncCompletedEventHandler.Invoke(Object sender, AsyncCompletedEventArgs e)
   at System.Net.WebClient.OnDownloadFileCompleted(AsyncCompletedEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch() 

Still getting this D:

**Comment by Kemp-J** [comment] 2015-08-25 12:37
I'm also seeing this issue. Has anyone confirmed that it *doesn't* happen when only installing or only upgrading? I only see people confirming that is *does* happen when doing both.

My initial guess was that AV software is locking the file based on the fact that it's a file that is created and then very soon after deleted. I've seen similar issues before. AV software is supposed to be nice about it, but many aren't.

**Comment by FireFaced** [comment] 2015-08-27 12:59
@Kemp-J The point of a temp file is to be used for a bit, then deleted. But AV could be doing that. Also, for others: Workaround for now is just not to install AND upgrade mods in one changeset.

**Comment by KSPjohnFX** [comment] 2016-04-19 14:38
"Workaround for now is just not to install AND upgrade mods in one changeset."

Could that not be the internal solution CKAN uses?

What is to stop an update being done first then install mods once that has completely finished?

If the issue is installing and upgrading at the same time then just don`t do that by coding the `apply changes` to run twice, one for upgrade, one for install.

Then it does not matter what causes the bug as the trigger for the cause is avoided.

**Comment by Sakata-MC** [comment] 2016-05-06 01:37
Still occurs. If you're going to throw it under the bus as unfixable, then make CKAN not allow the user to both select a mod to install while upgrades are selected.
''''
Unhandled exception:
System.IO.IOException: The process cannot access the file 'C:\Users\liath\AppData\Local\Temp\tmpD6DE.tmp' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at CKAN.NetAsyncDownloader.ModuleDownloadsComplete(NetFileCache cache, Uri[] urls, String[] filenames, Exception[] errors)
   at CKAN.NetAsyncDownloader.<DownloadModules>c__AnonStorey2.<>m__1(Uri[] _uris, String[] paths, Exception[] errors)
   at CKAN.NetAsyncDownloader.FileDownloadComplete(Int32 index, Exception error)
   at System.ComponentModel.AsyncCompletedEventHandler.Invoke(Object sender, AsyncCompletedEventArgs e)
   at System.Net.WebClient.OnDownloadFileCompleted(AsyncCompletedEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch() 
''''

**Comment by politas** [comment] 2016-05-06 02:19
What makes you think this has been given a "won't fix" label? Look at the labels on this issue - Bug, CKAN.DLL, and urgent. There's a workaround, and we are giving out that advice until its gets fixed, but this is definitely going to be fixed.

It's quite common in bug tracking systems to close off duplicates of accepted bug reports, retaining the one that has the most useful information.

**Comment by tjanke42** [comment] 2018-03-22 03:07
Bump

This bug is still alive and well as of March 2018, ckan version 1.24.0.

**Comment by HebaruSan** [comment] 2018-03-22 03:11
@tjanke42 , obviously, the issue status says "Open". Please don't "Bump".

**Comment by HebaruSan** [comment] 2024-01-14 16:58
- This call stack was changed drastically in #2756; instead of `ModuleDownloadsComplete` storing files to the cache in a batch at the end, they're stored individually as they finish
- #3512 disabled the arbitrary 10-minute transaction timeout that may have been involved (exception thrown by `File.InternalDelete` related to "because it is being used by another process")
- The download path is not a temp file anymore as of #3666
- Another user reported the same issue for installing **without** upgrading or vice versa (see #1712), so that detail was probably a red herring

Closing as probably fixed. If there's still an issue here, we'd need to start over collecting info about it anyway because almost none of the related code still works the same.

**Closed by HebaruSan** 2024-01-14 16:58 UTC
Labels: Bug, Core (ckan.dll), ★★☆
