### ISSUE TITLE
Bug to launch a fake KSP instance

### ISSUE THREAD

**Issue by ToxicR11** [KSP-CKAN/CKAN#3177] opened 2020-10-15 18:44 UTC
Background
----------
* Operating System: Windows 10
* CKAN Version:  1.28.0
* KSP Version:  1.3.0.1804

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
After creating a fake ksp instance, i try to launch KSP and there is a message "Couldn't start KSP. Le fichier spécifié est introuvable" (traduction : the specified file cannot be found )

**Steps to reproduce**
* Go to create fake KSP instance
Create a fake ksp instance
* Click on launch KSP
* See error

**Expected behavior**
launch the game

**Screenshots (if applicable)**

https://postimg.cc/F7sbhp2f/3b493da8

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment] 2020-10-15 18:45
Duplicate of #2850

**Comment by HebaruSan** [comment] 2020-10-15 18:46
@ToxicR11, a "fake" instance is not a real instance, the game is not installed there. You're not supposed to be able to run it.

**Closed by HebaruSan** 2020-10-15 18:45 UTC
