### ISSUE TITLE
[Bug] Mods fail to install due to trying to install a completely unrelated mod that is already installed

### ISSUE THREAD

**Issue by billbobbill** [KSP-CKAN/CKAN#3587] opened 2022-06-02 19:13 UTC
Background
----------
* Operating System: 
* CKAN Version: 
* KSP Version: 

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**

Problem
-------
After deleting all of my mods to try and solve a problem where all modules capable of holding crew seem to have vanished, I'm reinstalling them as close to one by one as I can, and while installing B9 Part Switch V2.20.0 and its dependency, Module Manager 4.2.1, CKAN gives me a conflict error stating that Scatterer 3:v0.0835 conflicts with Scatterer. I have Scatterer v0.0835, Scatterer Default Config, and Astroniki Sunflare for Scatterer installed, and they installed without issue.

**Comment by HebaruSan** [comment] 2022-06-02 19:15
Duplicate of #KSP-CKAN/NetKAN#8866

**Comment by HebaruSan** [comment] 2022-06-02 19:16
Hi @billbobbill, thanks for contacting us. This is a known issue that we've already investigated and will be fixed in a future CKAN release.

See #3479 for details of what's happening. You can probably work around it by opening your GameData folder and renaming the `scatterer` folder (all lowercase) to `Scatterer` (first letter capitalized).

**Closed by HebaruSan** 2022-06-02 19:16 UTC
Labels: Support, Duplicate
