### ISSUE TITLE
[Bug]: instance not detected

### ISSUE THREAD

**Issue by TeddyDD** [KSP-CKAN/CKAN#4062] opened 2024-03-21 18:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Linux

### CKAN Version

v1.34.4

### Games

KSP 1

### Game Version

1.12.5 03190 Steam, Windows version

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

Clean install from steam.

### Describe the bug

Vaild KSP instance is not detected

### Steps to reproduce

```
$ ckan instance add -v def '/home/teddy/.local/share/Steam/steamapps/common/Kerbal Space Program'
Sorry, /home/teddy/.local/share/Steam/steamapps/common/Kerbal Space Program does not appear to be a game instance
```
![image](https://github.com/KSP-CKAN/CKAN/assets/4397533/3be71b12-27ac-47e2-818c-8bab28edfc56)

### Relevant log output

261 [1] INFO CKAN.CmdLine.CommonOptions (null) - Verbose logging enabled
Sorry, /home/teddy/.local/share/Steam/steamapps/common/Kerbal Space Program does not appear to be a game instance
282 [1] INFO CKAN.CmdLine.MainClass (null) - CKAN exiting.

**Comment by HebaruSan** [comment] 2024-03-21 18:51
Duplicate of #4041

**Comment by HebaruSan** [comment] 2024-03-21 18:52
Hi @TeddyDD, the next release of CKAN will support these Proton-style instances that Steam has been creating lately. In the meantime you can `touch KSP.x86_64` in the game dir to make it look like a native instance.

**Closed by HebaruSan** 2024-03-21 18:51 UTC
Labels: Support, Linux
