### ISSUE TITLE
[Bug]: ckan has no apply checkmark

### ISSUE THREAD

**Issue by robt083** [KSP-CKAN/CKAN#3830] opened 2023-04-22 00:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

windows 11

### CKAN Version

1.32

### Game Version

1.12

### Did you make manual changes?

Yes

Manually removed mods. However, not knowing any better until after the fact, I also deleted the CKAN history folder and purged the cache. I don't know how to get a log file for you.

### Describe the bug

no gren apply checkmark no way to install mods through ckan,how ever i added an extrnal drive which also contained an instance of ckan,also no auddit recomendations is grayed out

i do have 2 instances one on c drive and 1 on d drive

### Steps to reproduce

* Go to...
* Click on...
* See error

**Comment by HebaruSan** [comment] 2023-04-22 15:42
What manual changes did you make? The more details the better; this could be the key to the investigation.

**Comment by robt083** [comment] 2023-04-23 22:56
manually removed mods , howerver not noing any better until after the fact i also deleted ckan history folder and purged the cashe  dont know how to get a log file for you

**Comment by HebaruSan** [comment] 2023-04-24 20:37
> no gren apply checkmark no way to install mods through ckan

> no auddit recomendations is grayed out

These two things use the exact same logic (`changeset != null && changeset.Any()`):

https://github.com/KSP-CKAN/CKAN/blob/d9a68dc3cca2cd8902b6d39ccf80d4036a694d6a/GUI/Controls/ManageMods.cs#L112-L121

https://github.com/KSP-CKAN/CKAN/blob/d9a68dc3cca2cd8902b6d39ccf80d4036a694d6a/GUI/Main/Main.cs#L706-L718

So what's described should be impossible; disabling the audit recommendations menu item necessarily entails enabling the apply changes button.

@robt083, can you try this with a fresh install and report whether it helps?

- <https://github.com/KSP-CKAN/CKAN/wiki/Clean-and-reinstall-process>

**Comment by robt083** [comment] 2023-04-25 09:23
Thank you again Hebsrusan, if I could ask you one more question the script
you gave me is that to just a drag and drop or do I need to initiate it in
a sort of way I am not program Sally at this particular time as part of the
reason I want to get I would like to learn the code

**Comment by robt083** [comment] 2023-04-26 13:08
need to apologize for my lack of participation at this timthe as i'm
moving ,however as im a nubie ii am spending time wih github tutorials to
become more familiar with the process ,i will start a repository as soon as
i can make time this week ,thankyou team

**Comment by HebaruSan** [comment] 2023-05-06 17:27
@robt083, is the button disabled, or not visible? We just had someone share this screenshot on Discord, which just happens because the window isn't wide enough to fit all the toolbar buttons, and I thought maybe you were having the same problem:

![image](https://user-images.githubusercontent.com/1559108/236638486-6da684cf-d9b5-4844-8a93-ebfef3afa48d.png)

If that's what you're seeing, you can make the window wider or click the little dropdown arrow button:

![image](https://user-images.githubusercontent.com/1559108/236638514-603b68e4-0b60-491c-8f11-b769a91ac898.png)

**Comment by robt083** [comment] 2023-05-12 16:15
i attempted to email you that i was moving ,but i was also forced to reinstall windows. please accept my apologies for any time waited on me at this time .thank you and have a great day

**Comment by HebaruSan** [comment] 2023-05-12 16:18
Closing because the cause is probably the width of the toolbar as indicated above, and the reply didn't contradict that.

**Closed by HebaruSan** 2023-05-12 16:18 UTC
Labels: Support, Needs more info
