### ISSUE TITLE
[Bug] CKAN stops responding after clicking certain buttons

### ISSUE THREAD

**Issue by InvitedRhino683** [KSP-CKAN/CKAN#3716] opened 2022-11-20 03:04 UTC
Background
----------
* Operating System: Windows 10
* CKAN Version: 1.31.0 - 1.31.2
* KSP Version: KSP v1.12.4.3187

Have you made any manual changes to your GameData folder (i.e., not via CKAN)?
Yes (after issue manifested)

Problem
-------
Whenever I click on the "Add available updates" or the "Apply changes" button, CKAN stops responding immediately. Both buttons are coloured, indicating usability, but when I click on either one of them, CKAN crashes. Restarting my PC has not fixed this issue.

Steps to reproduce
* Go to home screen
* Click on "Add available updates"
* CKAN stops responding

Expected behavior
* Click on "Add available updates"
* CKAN continues to work as normal

Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/69878624/202880501-4ec7ea37-94c7-4f7a-9ff7-6986c4b7913b.png)
![image](https://user-images.githubusercontent.com/69878624/202880514-c283d348-b7d2-4312-98bb-8f471e52745d.png)

**Comment by HebaruSan** [comment] 2022-11-20 03:22
Thanks, we just finished fixing this, you can try the latest dev build if you'd like to test:

- https://ksp-ckan.s3-us-west-2.amazonaws.com/ckan.exe

**Comment by HebaruSan** [comment] 2022-11-20 03:22
Duplicate of #3707

**Comment by InvitedRhino683** [comment] 2022-11-20 03:23
oh ok lol

thanks

**Closed by HebaruSan** 2022-11-20 03:22 UTC
