### ISSUE TITLE
Add an option to disable the list of incompatible mods

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/CKAN#2955] opened 2019-12-27 19:25 UTC
At game startup.

**Comment by HebaruSan** [comment] 2020-02-10 18:27
Novice users do not install incompatible mods on purpose and they do not know how versioning or compatibility work, but they can nonetheless get into a situation where they have incompatible mods installed by upgrading KSP. The main intent of this feature was to alert such users after KSP upgrades, since CKAN is partly responsible for getting them into that state. (It was also meant to provide some of the benefits of KSP-AVC to users who don't install that mod.)

We can add a "don't show again" checkbox, but it may make sense to make it version-specific; so I can suppress all warnings on KSP 1.8.1 once I have a tested and confirmed working version, but when I upgrade to KSP 1.9.0, the warning would come back again since there may be new problems with the installed mods. We would also need a settings screen somewhere that would allow you to uncheck the checkbox in case you check it by accident.

**Comment by fat-lobyte** [comment] 2021-06-17 18:16
> We can add a "don't show again" checkbox

Hi guys, just wanted to ask if there's plans to implement that in the near future. 

I fully understand that the warning is an important feature, but I feel like it should be OK for power users to disable the whole thing and take responsibility. I have carefully selected the versions that I need, and I would prefer to not have to comfirm this decision every time I launch the game.

**Comment by Xetaxheb** [comment] 2021-09-04 16:32
#3444 was marked duplicate but I was asking for something different that would provide a solution to this as well:
A simple label like hidden that overrides version checking entirely on the labeled mod, treating it as "game version: any"... allowing it to be installed without going through the motions of checking and unchecking game compatibility boxes or triggering the prompt. 
In the most basic usage of only ever installing once, this lowers the clicks needed from (current) 8*apply+1*launch to 2*mod but gets more useful as mods are un/re-applied, has the benefit of not needing to be done again when transferring labels to a new install, keeps the ability to have a warning on outdated mods, makes installing an individual 'outdated' mod easier, and is a more deliberate and focused action than "yadda yadda checkbox just launch my game".

I'm not objecting to the checkbox either (and easier to implement ig) but the label would still be nice.

**Comment by HebaruSan** [comment] 2021-09-04 17:35
@Xetaxheb, thanks for the clarification. Which mods are you finding that consistently have outdated compatibility info? (And which [game versions have you marked compatible globally](https://github.com/KSP-CKAN/CKAN/wiki/User-guide#Choosing-compatible-game-versions)?)

New methods for bypassing compatibility checks need to be considered carefully lest users start advising each other to abuse them when not appropriate and break their installs, so if we could accomplish the same goal by making the metadata more accurate, that would be preferable.

**Comment by Xetaxheb** [comment] 2021-09-04 21:06
I'm only using 3 at the moment (fairly fresh install), KEI / AutomatedScienceSampler / KerboKatzUtilities
But many things by dmagic and others i've yet to look at and check compatibility will be on down the line

Currently (on 1.12.2.3167) I leave 1.12/1.11/1.10 and all subversions selected but for obvious reasons i'm hesitant to leave 1.9/1.8 checked and accidentally install something I don't realize is outdated without checking on it manually

The label i'm suggesting would let end users pick specific mods and deliberately choose those individual ones at their own risk, as well as a sort of checklist for those they've reviewed;
 versus a checkbox "ignore outdated warning" is likely to get checked and ignored by the masses causing that very abuse

**Comment by HebaruSan** [comment] 2021-09-26 17:37
If anybody wants to try a test build, see the Artifacts dropdown here:

- https://github.com/KSP-CKAN/CKAN/pull/3453/checks

**Comment by Xetaxheb** [comment] 2021-09-26 22:22
Test build seems to have no issues for me. It immediately works as described.

**Comment by Xetaxheb** [comment] 2021-09-26 22:51
I'd still like to request some quicker function to install than going through game version menus (or worse, leaving them enabled) if that's an option, maybe allowing the (re)install process in right click menu on any mod? 
With an incredibly small skim it looks like it would only need a change to https://github.com/KSP-CKAN/CKAN/blob/master/GUI/Controls/ManageMods.cs#L926 for enabling the button?  
The language text could be changed to "(Re-)Install" if it really matters.

The changeset already seems to silently handle missing mod files so I could be wrong but it doesn't seem like reinstallToolStripMenuItem_Click() would need changes.

**Closed** 2021-11-01 13:52 UTC
Labels: Enhancement, GUI
