### ISSUE TITLE
"Device not ready" IO exception running CKAN on reassembled machine

### ISSUE THREAD

**Issue by Pommpie** [KSP-CKAN/CKAN#3363] opened 2021-05-13 03:17 UTC
Short version: this machine has had KSP and CKAN running on it in the past. Since the last time I ran CKAN, the drive architecture has changed. KSP is installed on a different drive than it used to be, and drive letters that once would have been hard disks are now CD drives, etc.

Installed CKAN today, ran on KSP 1.11.2. Error message:

```
PS G:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program> .\ckan

Unhandled Exception: System.IO.IOException: The device is not ready.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at CKAN.GameInstanceManager.LoadInstancesFromRegistry()
   at CKAN.CmdLine.MainClass.Execute(GameInstanceManager manager, CommonOptions opts, String[] args)
   at CKAN.CmdLine.MainClass.Main(String[] args)
```

Deleting `G:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program\GameData` and `G:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program\CKAN` did not help. Uninstalling and reinstalling KSP through Steam did not help. I even searched the registry for "CKAN" to see if there were some old references; no joy.

**Comment by HebaruSan** [comment] 2021-05-13 04:32
Looks likely to be a duplicate of #3333.

@Pommpie, would you mind trying out the latest dev build? If it's the same problem we fixed in #3334, then it should discard the download path setting with the old drive letter on startup.

- https://ksp-ckan.s3-us-west-2.amazonaws.com/ckan.exe

**Comment by Pommpie** [comment] 2021-05-13 13:32
Resolved in the dev build; thank you!

**Comment by HebaruSan** [comment] 2021-05-13 13:34
Duplicate of #3333.

**Closed** 2021-05-13 13:34 UTC
