### ISSUE TITLE
Loading mods from a .ckan file causes unhandled exception

### ISSUE THREAD

**Issue by Thorimus** [KSP-CKAN/CKAN#3012] opened 2020-03-01 20:38 UTC
Background
----------
* Operating System: Windows 10
* CKAN Version: 1.27.0
* KSP Version: 1.9.1.2788

Problem
-------
I tried to load a .ckan file containing my mods from my 1.9.0 install so I could install them into a clean 1.9.1 install. CKAN got most of the way through installing the mods until it threw this error:

Unhandled exception (etc.).
InvalidArgument=Value of '2' is not valid for "index".
Parameter name: index.

************** Exception Text **************
System.ArgumentOutOfRangeException: InvalidArgument=Value of '2' is not valid for 'index'.
Parameter name: index
   at System.Windows.Forms.TabControl.GetTabPage(Int32 index)
   at System.Windows.Forms.TabControl.TabPageCollection.get_Item(Int32 index)
   at CKAN.ThemedTabControl.OnDrawItem(DrawItemEventArgs e)
   at System.Windows.Forms.TabControl.WmReflectDrawItem(Message& m)
   at System.Windows.Forms.TabControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Can provide .ckan mods file if necessary

**Comment by HebaruSan** [comment] 2020-03-01 20:43
Duplicate of #3007

**Closed by HebaruSan** 2020-03-01 20:43 UTC
