### ISSUE TITLE
"Commit log" with rollback functionality

### ISSUE THREAD

**Issue by krillr** [KSP-CKAN/CKAN#1504] opened 2015-10-27 22:20 UTC
When it comes to debugging what mods are causing problems, a "commit log" which lists every change you've made would be a huge help. Having a rollback button would help get the game back into a known-good state where the user can then move forward from. Rollbacks should of course be their own commits to the log.

**Comment by ayan4m1** [comment] 2016-11-13 14:39
Text logging of transactions and their results is one thing, fairly straightforward and low-effort.

The rollback ability on the other hand is quite a bit more complex. At that point we'd be serializing a list of install/update/remove operations to represent a "transaction," such that a transaction could be replayed later without an understanding of the logic that generated it... we might as well consider moving to a more strongly transaction-oriented architecture in that case.

**Comment by politas** [comment] 2016-11-13 22:35
Hey, lets just implement our own version of git!

**Comment by ayan4m1** [comment] 2016-11-14 03:01
Hah, I was going to say "It'd be easier to just move to Git" but stopped because I didn't want to give anyone the idea...

**Comment by politas** [comment] 2016-11-14 21:06
I'm somewhat concerned about the filesystem overhead for rollback functionality. I suppose it could be an option. But lets do the commit log first and worry about rollbacks later.

**Comment by krillr** [comment] 2016-11-14 21:07
What about a filesystem overlay structure like how ModManager works for
Skyrim?

**Comment by politas** [comment] 2016-11-14 21:20
I have no knowledge of Skyrim or its ModManager. @ayan4m1?

**Comment by techman83** [comment] 2016-11-15 08:26
Using git for managing KSP mods inspired @pjf to start CKAN. https://github.com/pjf/ksp-gamedata

**Comment by ayan4m1** [comment] 2016-11-15 14:28
Well, depends on what you're talking about... "Nexus Mod Manager" sure we have no idea how it works because it's closed source, so not going to be a useful pattern to follow. Mod Organizer is hopefully what you're talking about, and there are multiple repos for the different install strategies it has.

That begs the question, are we going to modularize the various ways that conflicts could be resolved? It's taking a huge scope of work and making it even bigger.

https://github.com/TanninOne/modorganizer-installer_quick
https://github.com/TanninOne/modorganizer-installer_manual
https://github.com/TanninOne/modorganizer-installer_fomod
https://github.com/TanninOne/modorganizer-installer_bundle
https://github.com/TanninOne/modorganizer-installer_bain

Three of those strategies are specific package/plugin formats - CKAN defines its own package/plugin format so we likely have one of those.

Regardless, I think it's worth having the high level discussion of how we want to handle "changes we make to the KSP install directory," ideally by writing a new spec that details exactly what the code is supposed to do. Right now the issue is that there are ten classes (Repo, MainModList, ModuleInstaller, etc) that each make assumptions about the others, and trying to do anything major like adding a transaction log is going to create new issues.

**Comment by Dazpoet** [comment] 2016-11-15 14:44
Before this grows out of control I think we should all remember that we already have the ability to take snap-shots of known-good installs via the `Export installed mods...` option in the (GUI)client.

Say I e.g. want to try adding more mods to my already heavily modded game, I then follow these steps:

1. Take a snapshot of my installed mods
2. Install new mods I'm unsure how stable they'll be together.
3. TIAS (Try It And See)
4. ???
5. Profit OR Remove all mods and restart from your snapshot.

The solution does demand user interaction and planning but using it should not present a large problem nor be esspecially onerous.

**Comment by krillr** [comment] 2016-11-15 15:09
ModOrganizer was the one I meant, sorry

**Comment by HebaruSan** [comment] 2018-01-02 23:47
Continuing @Dazpoet's thought, it should be pretty easy to auto-generate a `KSP/CKAN/installed-YYYY-MM-DD-HH-mm-ss.ckan` file after each batch of changes. Storing just the identifiers should limit the size and complexity, and the `remove --all` and `install -c` commands would make reverting trivial.

**Comment by politas** [comment] 2018-01-03 01:44
I like that idea, especially if we include mod version numbers in the timestamped ckan files. We would need a config toggle to let people turn it off if they are concerned about space. Might also be good to create a new subfolder under CKAN to store the timestamped logs in.

**Comment by HebaruSan** [comment] 2018-01-03 03:41
Yup, the version numbers are in there. Each file is less than 4 KB in my testing, so space shouldn't be a concern. I like the subfolder idea though; what would you call it? It's not quite a log or a cache... "history"?

**Closed** 2018-01-05 07:35 UTC
Labels: Enhancement, ★★☆
