### ISSUE TITLE
[Feature] Add label to disable game version checking on mod

### ISSUE THREAD

**Issue by Xetaxheb** [KSP-CKAN/CKAN#3444] opened 2021-09-04 00:07 UTC
Problem
-------
I'm always frustrated when... trying to launch the game with a mod installed that lists version i've unchecked from game compatible throws a warning up between "Launch game" and actually launching

Additionally being able to flag a not installed mod to install it without needing to go change compatible game versions

Suggestions
-----------
A label that can be set on individual mods (similar to how hidden works) that just interprets max_game_version as any for that mod in all circumstances.

**Comment by HebaruSan** [comment] 2021-09-04 00:23
Duplicate of #2955

**Closed by HebaruSan** 2021-09-04 00:23 UTC
