### ISSUE TITLE
[Bug]: CKAN Crashes on startup

### ISSUE THREAD

**Issue by Ketris** [KSP-CKAN/CKAN#4206] opened 2024-09-28 15:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows 11

### CKAN Version

1.35.0.24270

### Games

KSP 1

### Game Version

Steam

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

No, empty game folder.

### Describe the bug

CKAN crashes on launch. 
![image](https://github.com/user-attachments/assets/405d5256-ab6d-457d-9721-4b7cdba39224)

### Steps to reproduce

Clean install CKAN.
Crashes.

**Comment by Ketris** [comment] 2024-09-28 16:01
I deleted **all** CKAN files, including from AppData, and completely reinstalled KSP from scratch. CKAN still crashes on launch with the above error.

**Comment by HebaruSan** [comment] 2024-09-28 16:31
Duplicate of #4197

**Closed by HebaruSan** 2024-09-28 16:31 UTC
