### ISSUE TITLE
CKAN crashes if you try to write in a search field with Japanese input in macOS

### ISSUE THREAD

**Issue by MaltYebisu** [KSP-CKAN/CKAN#2733] opened 2019-04-16 11:16 UTC
Background
----------

**CKAN Version:** 
v1.26.0+3bc537637e8f
(Built from Master Branch April 12 2019)

**KSP Version:** 
1.7.0.2483

**Operating System:** 
macOS 10.14.4 (18E226)

Problem
-------

I discovered this because I forgot that my keyboard input was still in Japanese when using CKAN. This is how to reproduce it:

**What steps did you take in CKAN?**
Switch to Japanese input and start typing in the search field.

**What did you expect to happen?**
Japanese characters to be added in the search field.

**What happened instead?**
CKAN became unresponsive for a few seconds and then I was prompted for a password to let 'Developer Tools Access' access a different process to continue debugging. I pressed 'cancel' a few times and then CKAN crashed.

**Screenshots:**

<img width="1019" alt="スクリーンショット 0031-04-16 19 29 40" src="https://user-images.githubusercontent.com/37108951/56204304-17092100-6082-11e9-8f04-63ff613663ae.png">

<img width="1023" alt="スクリーンショット 0031-04-16 19 30 29" src="https://user-images.githubusercontent.com/37108951/56204303-17092100-6082-11e9-8b6f-1538a876826b.png">

**CKAN error codes:** 
[TerminalOutput.txt](https://github.com/KSP-CKAN/CKAN/files/3084604/TerminalOutput.txt)

```
  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) System.Windows.Forms.XplatUICarbon.ReceiveNextEvent (uint,intptr,double,bool,intptr&) <0x00012>
  at System.Windows.Forms.XplatUICarbon.GetMessage (object,System.Windows.Forms.MSG&,intptr,int,int) [0x000f3] in <556a6ba2c0a546f1ad2318c309ce0945>:0
  at System.Windows.Forms.XplatUI.GetMessage (object,System.Windows.Forms.MSG&,intptr,int,int) [0x00000] in <556a6ba2c0a546f1ad2318c309ce0945>:0
  at System.Windows.Forms.Application.RunLoop (bool,System.Windows.Forms.ApplicationContext) [0x0034e] in <556a6ba2c0a546f1ad2318c309ce0945>:0
  at System.Windows.Forms.Application.Run (System.Windows.Forms.ApplicationContext) [0x00011] in <556a6ba2c0a546f1ad2318c309ce0945>:0
  at System.Windows.Forms.Application.Run (System.Windows.Forms.Form) [0x00006] in <556a6ba2c0a546f1ad2318c309ce0945>:0
  at CKAN.Main..ctor (string[],CKAN.KSPManager,CKAN.GUIUser,bool) [0x0033f] in <19cb53ea697747c3a388201d25d23f0a>:0
  at (wrapper remoting-invoke-with-check) CKAN.Main..ctor (string[],CKAN.KSPManager,CKAN.GUIUser,bool) [0x0001d] in <19cb53ea697747c3a388201d25d23f0a>:0
  at CKAN.GUI.Main_ (string[],CKAN.KSPManager,bool) [0x00047] in <19cb53ea697747c3a388201d25d23f0a>:0
  at CKAN.CmdLine.MainClass.Gui (CKAN.KSPManager,CKAN.CmdLine.GuiOptions,string[]) [0x00009] in <19cb53ea697747c3a388201d25d23f0a>:0
  at CKAN.CmdLine.MainClass.RunSimpleAction (CKAN.CmdLine.Options,CKAN.CmdLine.CommonOptions,string[],CKAN.IUser,CKAN.KSPManager) [0x002e3] in <19cb53ea697747c3a388201d25d23f0a>:0
  at CKAN.CmdLine.MainClass.Execute (CKAN.KSPManager,CKAN.CmdLine.CommonOptions,string[]) [0x001b2] in <19cb53ea697747c3a388201d25d23f0a>:0
  at CKAN.CmdLine.MainClass.Main (string[]) [0x000a1] in <19cb53ea697747c3a388201d25d23f0a>:0
  at (wrapper runtime-invoke) <Module>.runtime_invoke_int_object (object,intptr,intptr,intptr) [0x00054] in <19cb53ea697747c3a388201d25d23f0a>:0
```

**macOS Crash Report:**
[CrashReport.txt](https://github.com/KSP-CKAN/CKAN/files/3084603/CrashReport.txt)

**Comment by HebaruSan** [comment] 2019-04-24 01:40
I tried searching for モジュールマネージャ (Google Translate's rendition of "Module Manager") on Ubuntu, and it didn't crash. Probably something OSX-specific.

![image](https://user-images.githubusercontent.com/1559108/56626594-ea1bb780-6607-11e9-85e6-a138136799db.png)

**Comment by MaltYebisu** [comment] 2019-04-24 05:34
Did you enter it using keyboard input, or did you copy and paste it into the field?

It seems to be a problem with keyboard inputs that translates input like "joudan" to "じょうだん" or "冗談" or "上段", like the Japanese Keyboard input does. I tried with Russian input (Direct change of input keys, "a" to "ф") and had no problem. But when I tried Simplified Chinese ("si" to "死" or "四") then it also crashed in a similar manner.

I tried to copy and paste, but I couldn't get it to work. Both command + c and the secondary mouse press menu did not work.

**Comment by HebaruSan** [comment] 2019-04-24 13:19
Ahh interesting, no I just pasted it. I'll try to figure out how to type Japanese characters on Ubuntu...

**Comment by HebaruSan** [comment] 2019-04-24 13:31
Well, it doesn't crash (on Ubuntu), but it doesn't enter the characters into the field, either. Maybe there's some keystroke that I'm supposed to use to complete the entry? I'm not seeing any mention of that in various tutorials though.

![image](https://user-images.githubusercontent.com/1559108/56662966-aefea000-666a-11e9-9d27-5c055d727df0.png)

**Comment by HebaruSan** [comment] 2019-04-24 13:36
Oh, it's space bar to commit a string. Still no crash, like the copy/paste case:

![image](https://user-images.githubusercontent.com/1559108/56663550-fafe1480-666b-11e9-92c4-d82876ba1697.png)

**Comment by MaltYebisu** [comment] 2019-04-24 15:17
I noticed something when I tried it again now.

Usually the Japanese input alternatives show up right under where you are typing. Like this:
<img width="814" alt="Screenshot 0031-04-24 at 23 55 38" src="https://user-images.githubusercontent.com/37108951/56670433-cb8fec00-66ed-11e9-9e37-0573a9a03991.png">

But when I try to write something with Japanese input in CKAN then a "window" pops up on the lower parts of the screen. Like this:
![Screenshot 0031-04-24 at 23 57 22](https://user-images.githubusercontent.com/37108951/56670663-3b05db80-66ee-11e9-84ff-dd8b1af170fb.png)
(notice the "k" in the window. I started to type "konnichiha" like the example above)

I'm not sure what causes this. I have seen it before, when running a program that don't have Japanese support (a game for eksample) sometimes I experience that key inputs are not registered only to see the same small window with gibberish in it. This is the first time, however, I have experienced a crash because of this. It is usually just an annoyance.

**Comment by HebaruSan** [comment] 2019-05-09 21:32
@MaltYebisu, can you please try the same thing with the text fields in this simple test app from mono's samples collection? This would help us to confirm whether this is caused by something CKAN is doing (and can fix) or is just a bug in Mono on OSX (as seems likely given the lack of CKAN code in the stack trace):

- [mailclient.zip](https://github.com/KSP-CKAN/CKAN/files/3164076/mailclient.zip)

![image](https://user-images.githubusercontent.com/1559108/57488079-a9fb3c80-7277-11e9-9337-137122354c26.png)

**Comment by MaltYebisu** [comment] 2019-05-10 00:26
Mailclient crashed in a similar way when I tried to write with Japanese input in the "Message" text-box. 
[TerminalOutput.txt](https://github.com/KSP-CKAN/CKAN/files/3164442/TerminalOutput.txt)

**Comment by HebaruSan** [comment] 2019-05-10 00:28
Thanks! Closing as CKAN isn't responsible and can't fix. Someone at mono might be able to help:

https://github.com/mono/mono/issues/new

**Closed by HebaruSan** 2019-05-10 00:28 UTC
Labels: GUI, Mono, OS X

**Comment by MaltYebisu** [comment] 2019-05-10 00:31
I will make a new issue in mono, but I'm not sure what kind of info they need. Would they know what mailclient is or should I explain it more?

**Comment by HebaruSan** [comment] 2019-05-10 00:36
They may not know it off the top of their heads but they'd be able to find it in their own code if they knew where to look:

https://github.com/mono/mono/blob/master/mcs/class/System.Windows.Forms/samples/mailclient.cs

But mailclient isn't the problem; it seems all instances of `TextBox` are affected, and maybe other controls as well.

**Comment by MaltYebisu** [comment] 2019-05-10 00:38
Thank you

**Comment by MaltYebisu** [comment] 2019-05-10 01:43
Here it is for reference: https://github.com/mono/mono/issues/14434
