### ISSUE TITLE
[Bug] CKAN "Not Responding" during/after loading.

### ISSUE THREAD

**Issue by daantimmer** [KSP-CKAN/CKAN#3379] opened 2021-05-23 21:49 UTC
Background
----------
* Operating System: Windows 10
* CKAN Version: 1.30.2
* KSP Version: 1.10.1.2939

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
I have

Problem
-------
When opening CKAN it loads, updates repositories, loads local goes to 'updating tray...' and stops.

**Steps to reproduce**
Open CKAN, 
Select my normal (modded) instance
* See error

**Expected behavior**
To see the mod list and

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/8293597/119277701-718de780-bc21-11eb-9b06-42986592dda8.png)

**CKAN error code (if applicable):**
N/A

```
PLACE CODE HERE !
```

**Comment by daantimmer** [comment] 2021-05-23 21:50
Reverted back to 1.30.0, which works fine :-)

**Comment by DasSkelett** [comment] 2021-05-23 21:59
Thanks for the report.
The bug is already known, and is caused by a threading issue. It only happens on some systems, and only if "Refresh on startup"/"Update repositories on launch" is enabled.

As a workaround, you can edit `<KSP>\CKAN\GUIConfig.xml`, where `<KSP>` is the path to your KSP installation, e.g. `C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program` if you are on Windows and got it via Steam.

In this file, replace
```xml
  <RefreshOnStartup>true</RefreshOnStartup>
```
with
```xml
  <RefreshOnStartup>false</RefreshOnStartup>
```
so change `true` to `false` for `RefreshOnStartup`. Don't touch `RefreshOnStartupNoNag`, that's a different setting.
If you have multiple KSP installations registered in CKAN, you need to change it for all of them.

Alternatively, while you're still back on v1.30.0, you can also go into the settings and disable "Update repositories on launch", then upgrade again.

This will disable the automatic repository refresh when CKAN launches (where it downloads the latest metadata to get information about new mod releases). You can still refresh it manually using the "Refresh" button, which should still work without problems.

Sorry for the inconvenience, we're working on a fix.

**Comment by HebaruSan** [comment] 2021-05-23 22:30
The Discord report from @linuxgurugamer:

https://discord.com/channels/601452466017665040/601456737203126281/845428320710557727

The forum report:

https://forum.kerbalspaceprogram.com/index.php?/topic/197082-ckan-the-comprehensive-kerbal-archive-network-v1302-hawking/&do=findComment&comment=3976823

Thanks for giving us something we can track properly, it really does help. There's no way to mark a bug fixed on Discord or the forum, or bring up the list of open bugs.

**Closed** 2021-05-24 14:11 UTC
Labels: Bug, GUI
