### ISSUE TITLE
Mac High Sierra Issues

### ISSUE THREAD

**Issue by maxthrustau** [KSP-CKAN/CKAN#2612] opened 2018-12-16 01:37 UTC
Background
----------

**CKAN Version:** 
Kennedy (latest version)

**KSP Version:** 
1.4.1

**Operating System:** 
macOS High Sierra

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
Yes (manually installed some visual mods)

Problem
-------

**What steps did you take in CKAN?**
open terminal and start ckan

**What did you expect to happen?**
that ckan would load

**What happened instead?**
The GUI never loads, Application not responding

**Screenshots:**
<img width="1012" alt="screen shot 2018-12-16 at 11 56 44 am" src="https://user-images.githubusercontent.com/45907084/50049010-594d4080-012a-11e9-883e-94d445a44e2e.png">

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment] 2018-12-16 02:03
This is a duplicate of #2595, fixed in #2600.

**Closed by HebaruSan** 2018-12-16 02:03 UTC
