### ISSUE TITLE
Unauthorized Access

### ISSUE THREAD

**Issue by buazzardbombpick** [KSP-CKAN/CKAN#2044] opened 2017-05-09 02:00 UTC
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

**CKAN Version:** 

**Operating System:** 

**The issue you are experiencing:** 

**How to recreate this issue:** 

**CKAN error codes (if applicable):** 

```
************** Exception Text **************
System.UnauthorizedAccessException: Access to the path 'c:/program files (x86)/steam/SteamApps/common/Kerbal Space Program/GameData/UnmannedBeforeManned/UnmannedBeforeManned.version' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at ChinhDo.Transactions.TxEnlistment.Rollback(Enlistment enlistment)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ckan
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Users/Thomas/Downloads/ckan.exe
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
```

**Comment by politas** [comment] 2017-05-09 05:59
Do you have some Group or Local Policies on your PC that are limiting your ability to control your machine?

**Comment by buazzardbombpick** [comment] 2017-05-10 19:25
No, it's my personal laptop. It will lock up a folder and I have to restart
the computer to even be able to delete the folder manually

**Comment by politas** [comment] 2017-05-12 00:01
All I can suggest is to tell Steam to store games outside the "Program Files(x86)" folder. Somewhere the system doesn't insist on administrative access, and make sure your KSP is in that bit.

**Comment by macdjord** [comment] 2017-05-22 02:01
I'm having the same issue. This was never a problem before; what changed?

One minor difference from what @buazzardbombpick reported: in my case, once I restarted the machine, the problematic folder was already gone. I didn't have to delete it manually. However, when I tried again, I got the same error for a _different_ folder.

**Comment by politas** [comment] 2017-05-22 09:49
Maybe there was a Windows update that locked down the Program File (x86) folder structure a bit more. Windows security is weird.

**Comment by moeilijk** [comment] 2017-05-22 21:42
Seems the issue has been there at least since 2015 https://github.com/KSP-CKAN/CKAN/issues/1472 it seems.
And has been reported on Reddit https://www.reddit.com/r/KerbalSpaceProgram/comments/5yzsmq/ckan_access_denied_error/
I have the same problem installing or updating mods for several monthst now. Random locks on files or folders being updated. 
Somehow when cleaning up mods for update CKAN seems to lock and improperly removes the old stuff. 
Also KSP is unable to start with a failed update since deleted folders are ghosting there with no owner or rights making KSP hang indefinitely on loading the mods.
I have tried moving the installation folder of KSP to different drives and different filesystems with no real change in behavior. Also changing or disabling anti-virus didn't make any difference.
My workaround so far has been rebooting and manually removing the mod folders ready for update before letting CKAN loose on the updates.
Posting here since it seems appropriate and the dev seems to respond.

**Comment by macdjord** [comment] 2017-05-23 07:42
Copying my KSP folder from STEAM to my desktop seems to have fixed it for me.

**Comment by 8749236** [comment] 2017-05-27 19:35
**One possible solution**:
Download Process [Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx)/[Hacker](http://processhacker.sourceforge.net/).
Press Ctrl + F to search handles: "Kerbal Space Program/GameData" or your game's root directory name + "/GameData".
In order for CKAN to operate correctly, **there should not be any handle opening** the folder-in-question other than _file explorer_ and _CKAN_ itself. 
**Note**: File Explorer may cause problem if you opened the mod you are trying to modify/delete, depends on what Operating System you are running).

**Observations**:
Also, in computer that has Intel Graphics Control Panel installed, igfxEM.exe is known to load some resources (used during rendering) before they are being used.
Terminating igfxEM.exe should resolve the problem. (Although this action may have some side-effects to Intel software).
Recommend rebooting systems afterwards to prevent possible side effects.

Suggest others who does not have Intel Graphics Control Panel installed use Process Explorer/Hacker to determine whether there are any executables locking the file question.

**Recommendations to CKAN's file operation logic**:
I am suggesting following changes:
 - Rename the folder-in-question before performing actual file operation. 
Reason: If any files within the folder-in-question is locked, renaming operation should automatically fail, thus serve as a _makeshift lock-check_.
Note: A reliable lock-check logic is necessary and should replace the makeshift lock check to guarantee that the file/folder-in-question is not locked before commencing file operations.

**Comment by edickey6** [comment] 2017-06-02 01:21
I've been having the same issue when trying to update or remove most mods for quite a while and finally got around to real troubleshooting today, it turns out that in my case it's caused by an intel graphics driver holding folders open so they are deleted but still held in memory so even file explorer can't do anything with them. The driver for some reason holds almost all Steam folders as well as a ton of others open constantly, but there is an update which you have to download from Intel, not just the Microsoft Update mechanism which supposedly fixes the issue. I'm updating now so can't confirm if it actually fixes it but thought I would let people know that is a potential fix. At least in my case, there isn't really anything that CKAN could do other than handle the error better by not crashing.

**Comment by politas** [comment] 2017-06-03 11:15
@edickey6, does closing the Steam client make any difference?

**Comment by edickey6** [comment] 2017-06-03 11:45
@politas, no it really has nothing to do with steam other than where the folders are. 

By the way, the update did seem to fix the issue completely. I don't even actually use the intel graphics, I just keep it enabled in the BIOS because of some rare things it can help with despite using a discrete graphics card for actual graphics. I hope they put it in the normal Microsoft Update way of getting driver updates so people don't keep running into the issue (it's not just us, not even just steam stuff, it's really a graphics driver bug). I would imagine that if you use discrete graphics then disabling the onboard graphics in BIOS would also fix the issue since it doesn't load the problem driver at all that way but the driver update directly from the intel website fixes it also.

**Comment by 8749236** [comment] 2017-06-03 13:36
@edickey6 If that update works, would you mind to put a link in this issue? So others can benefit from that update too, while CKAN works on this to preventing similar issue in the future?

**Comment by edickey6** [comment] 2017-06-03 13:49
@8749236, I just used the auto detect tool they makea  vaialbe at https://downloadcenter.intel.com/ and installed the one update it found, I think that gave me the same as this: https://downloadcenter.intel.com/download/26772/Graphics-Intel-Graphics-Driver-for-Windows-15-45- but there is actually a newer one out already (was probalby still beta a couple days ago,it shows it was out before the day before I updated to the older one) at: https://downloadcenter.intel.com/download/26836/Graphics-Intel-Graphics-Driver-for-Windows-15-45- which probalby works as well. It would also very likely depend on which specific chip you have so the auto detect tool is probably your best bet if you don't want to do a lot of digging.

**Comment by edickey6** [comment] 2017-06-03 13:51
Just for more info, the release notes on the one I had already updated to (https://downloadmirror.intel.com/26772/eng/ReleaseNotes_GFX_154518.4664.pdf) specifically call out them fixing "Access to Steam* folders may be denied"

**Closed** 2017-09-25 00:00 UTC
Labels: Support

**Comment by aboutetdorval** [comment] 2017-10-07 17:30
Just give CKAN admin access (Win 7 thru 10).

**Comment by politas** [comment] 2017-10-07 21:23
>Just give CKAN admin access (Win 7 thru 10).
I can't stress enough how bad an idea this is. Fix your Windows filesystem permission, and don't give the CKAN client admin rights!

**Comment by aboutetdorval** [comment] 2017-10-07 22:07
This is a terrible idea, but not as terrible as CKAN itself breaking up the permission system each friggin time KSP crashes (every other game, actually).

You don’t have to leave the admin right, just give it a go once to let it put its file in order and then cancel it.

**Comment by edickey6** [comment] 2017-10-07 22:20
Please read the whole thread and stop posting false information in it. It was an Intel graphics driver issue, it had nothing to do with actual permissions and admin rights did not even get around the issue. CKAN didn't break the permissions either it just revealed that there already was an issue caused by the Intel graphics driver, if anyone still has the issue, you just need to update that driver and reboot, that's it.
