### ISSUE TITLE
[Bug] SSL Error even though I've updated SSL certificates

### ISSUE THREAD

**Issue by simcye** [KSP-CKAN/CKAN#3485] opened 2021-11-21 20:17 UTC
Background
----------
* Operating System: Debian 11 Bullseye
* CKAN Version: 1.30.4
* KSP Version: 1.12.2.3167
```
$ mono --version
Mono JIT compiler version 6.8.0.105 (Debian 6.8.0.105+dfsg-3.2 Tue Jun 29 21:01:01 UTC 2021)
```

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
**Describe the bug**
CKAN fails on certain downloads (sometimes it redirects to a fallback, sometimes it doesn't.
I've already gone through updating SSL certs but it still isn't working.

**CKAN error code (if applicable):**

```
 * TweakScale - Rescale Everything! v2.4.6.2 (spacedock.info, 333.2 KiB)
Downloading "https://spacedock.info/mod/127/TweakScale/download/2.4.6.2"
One or more downloads were unsuccessful:

Error downloading TweakScale v2.4.6.2: Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
  at ./external/boringssl/ssl/handshake_client.c:1132
```

**Comment by HebaruSan** [comment] 2021-11-21 20:24
What exactly do you mean by "updated SSL certificates"? Have you removed the expired LetsEncrypt root cert?

https://github.com/KSP-CKAN/CKAN/wiki/SSL-certificate-errors#removing-expired-lets-encrypt-certificates

**Comment by HebaruSan** [comment] 2021-11-21 20:24
Duplicate of #3468

**Closed** 2021-11-21 20:48 UTC
Labels: Support, Linux, Mono, Network
