### ISSUE TITLE
Simple Construction Fails to load

### ISSUE THREAD

**Issue by Bit-Fiddler** [KSP-CKAN/CKAN#1683] opened 2016-04-26 11:53 UTC
This is the text from the error message.  This is For Simple Construction, so not sure why it is talking about a SCANsat Contract pack.

````
************** Exception Text **************
CKAN.ModuleNotFoundKraken: Cannot install ContractConfigurator-SCANsat, module not available
   at CKAN.CkanModule.FromIDandVersion(IRegistryQuerier registry, String mod, KSPVersion ksp_version)
   at CKAN.RelationshipResolver.<RelationshipResolver>c__AnonStorey0.<>m__0(String name)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CKAN.RelationshipResolver..ctor(IEnumerable`1 module_names, RelationshipResolverOptions options, IRegistryQuerier registry, KSPVersion kspversion)
   at CKAN.MainModList.ComputeConflictsFromModList(IRegistryQuerier registry, IEnumerable`1 change_set, KSPVersion ksp_version)
   at CKAN.Main.<UpdateChangeSetAndConflicts>c__async1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKAN.Main.<ModList_CellValueChanged>c__async0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
````

**Comment by plague006** [comment] 2016-04-26 11:54
It's complaining about `ContractConfigurator-SCANsat` because you it installed and it's not compatible with KSP 1.1.

It *shouldn't* complain about it, but it's an issue we're aware of. To avoid it you'll need to uninstall `ContractConfigurator-SCANsat`.

**Comment by ayan4m1** [comment] 2016-08-03 20:05
I'd propose closing this as a duplicate of #1686 in that case.

**Comment by politas** [comment] 2016-08-04 00:22
Agreed

**Closed by politas** 2016-08-04 00:22 UTC
Labels: support
