### ISSUE TITLE
[Bug]: Unable to update mods

### ISSUE THREAD

**Issue by Dominiquini** [KSP-CKAN/CKAN#3971] opened 2023-12-21 03:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows 10 x64

### CKAN Version

1.34.2

### Games

KSP 1

### Game Version

1.12.5

### Describe the bug

When I press the "Refresh" button, the tab "Updating repositories" show this message:

```
Scanning for DLCs and manually installed modules...
Loading cached repository data
Updating repositories...
Refreshing game version data
One or more errors occurred.
Repository update failed!
```

It take a really long time on the message "Refreshing game version data"!

### Steps to reproduce

1) Open CKAN
2) Wait it to check for CKAN updates
3) Click on the Refresh button to look for mod updates
4) Wait a while for the error!

**Comment by HebaruSan** [comment] 2023-12-21 03:33
Duplicate of #3950

**Closed by HebaruSan** 2023-12-21 03:33 UTC

**Comment by Dominiquini** [comment] 2023-12-21 03:39
I fix the bug removing the [Kopernicus_BE] repository!
