### ISSUE TITLE
[Bug] Briefly summarize your issue here

### ISSUE THREAD

**Issue by DaniLucky06** [KSP-CKAN/CKAN#3799] opened 2023-03-02 16:09 UTC
Background
----------
Windows 11
1.31.2
1.12.5.3190

Yes, but deleted every mod before using ckan

Problem
-------
I want to install some mods my friend has, too, but ckan won't show the latest mod versions (more specific we tried kOS. He has 1.4 as latest version, i see only 1.3.2). I tried reinstalling ckan, changing versions of ckan, installing latest dev releases, but i can't see 1.4. 
This doesn't allow for me to use kOS in 1.12.5 KSP
kOS 1.4.0.0 was released 2 weeks ago

**Steps to reproduce**
I don't know. My friend has the same exact version and it works for him

**Expected behavior**
I'd be able to see the newest versions

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/121113019/222484541-a77180ab-50b9-4718-9f64-74f8e40b2f94.png)
![image](https://user-images.githubusercontent.com/121113019/222484607-5e0b5fcb-02f4-4600-baae-500ee12c69b9.png)
![image](https://user-images.githubusercontent.com/121113019/222484699-e90ce643-968c-4f3e-936a-36692780f289.png)

**CKAN error code (if applicable):**
```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment] 2023-03-02 16:11
Thanks for the report! This issue is already pinned: #3699

**Comment by HebaruSan** [comment] 2023-03-02 16:11
Duplicate of #3699

**Closed by HebaruSan** 2023-03-02 16:11 UTC

**Comment by DaniLucky06** [comment] 2023-03-02 19:46
[registry.zip](https://github.com/KSP-CKAN/CKAN/files/10875278/registry.zip)
Hebaru my registry
