### ISSUE TITLE
System.DllNotFoundException: libgdiplus.dylib

### ISSUE THREAD

**Issue by viveleroi** [KSP-CKAN/CKAN#1876] opened 2016-08-27 18:55 UTC
**CKAN Version:**  v1.18.1

Mono v 4.4.1.0

**Operating System:** Mac OS X: 10.11.5

**The issue you are experiencing:** Error on startup.

**How to recreate this issue:** 

- Installed mono via brew: `brew install mono`
- Download ckan.exe, ran`mono ckan.exe`

**CKAN error codes (if applicable):** 

```
$ mono ckan.exe
WARNING: The Carbon driver has not been ported to 64bits, and very few parts of Windows.Forms will work properly, or at all
exception inside UnhandledException handler: Object reference not set to an instance of an object

[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'System.Windows.Forms.WindowsFormsSynchronizationContext' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Windows.Forms.ThemeEngine' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Windows.Forms.ThemeWin32Classic' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Drawing.KnownColors' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Drawing.GDIPlus' threw an exception. ---> System.DllNotFoundException: libgdiplus.dylib
  at (wrapper managed-to-native) System.Drawing.GDIPlus:GdiplusStartup (ulong&,System.Drawing.GdiplusStartupInput&,System.Drawing.GdiplusStartupOutput&)
  at System.Drawing.GDIPlus..cctor () <0x10b5dbad0 + 0x001d5> in <filename unknown>:0
  --- End of inner exception stack trace ---
  at System.Drawing.KnownColors..cctor () <0x10b5db840 + 0x00064> in <filename unknown>:0
  --- End of inner exception stack trace ---
  at System.Drawing.Color.get_Black () <0x10b5db5d0 + 0x0001e> in <filename unknown>:0
  at System.Windows.Forms.ThemeWin32Classic..cctor () <0x10b5db4c0 + 0x00015> in <filename unknown>:0
  --- End of inner exception stack trace ---
  at System.Windows.Forms.ThemeVisualStyles..ctor () <0x10b5db3f0 + 0x00014> in <filename unknown>:0
  at System.Windows.Forms.ThemeEngine..cctor () <0x10b5db2d0 + 0x0008f> in <filename unknown>:0
  --- End of inner exception stack trace ---
  at System.Windows.Forms.SystemInformation.get_MenuAccessKeysUnderlined () <0x10b5daea0 + 0x00010> in <filename unknown>:0
  at System.Windows.Forms.Control..ctor () <0x10b5d97e0 + 0x00288> in <filename unknown>:0
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.Control:.ctor ()
  at System.Windows.Forms.WindowsFormsSynchronizationContext..cctor () <0x10b5dad90 + 0x00031> in <filename unknown>:0
  --- End of inner exception stack trace ---
  at System.Windows.Forms.Control..ctor () <0x10b5d97e0 + 0x0005e> in <filename unknown>:0
  at System.Windows.Forms.ScrollableControl..ctor () <0x10b5d9180 + 0x00017> in <filename unknown>:0
  at System.Windows.Forms.ContainerControl..ctor () <0x10b5d8fa0 + 0x0002d> in <filename unknown>:0
  at System.Windows.Forms.Form..ctor () <0x10b5d8610 + 0x000f9> in <filename unknown>:0
  at CKAN.Main..ctor (System.String[] cmdlineArgs, CKAN.GUIUser User, Boolean showConsole) <0x10b5d52d0 + 0x001d1> in <filename unknown>:0
  at (wrapper remoting-invoke-with-check) CKAN.Main:.ctor (string[],CKAN.GUIUser,bool)
  at CKAN.GUI.Main_ (System.String[] args, Boolean showConsole) <0x108760140 + 0x0016c> in <filename unknown>:0
  at CKAN.CmdLine.MainClass.Gui (CKAN.CmdLine.GuiOptions options, System.String[] args) <0x10875f3c0 + 0x0002a> in <filename unknown>:0
  at CKAN.CmdLine.MainClass.Main (System
```

**Comment by ayan4m1** [comment] 2016-08-27 20:57
Duplicate of https://github.com/KSP-CKAN/CKAN/issues/1501

Relates to https://github.com/KSP-CKAN/CKAN/issues/1840 and https://github.com/KSP-CKAN/CKAN/issues/1272

**Closed** 2016-09-04 00:00 UTC
Labels: OSX, support

**Comment by 100ideas** [comment] 2016-09-23 04:32
I think it's because homebrew mono only includes a precompiled 64-bit mono runtime, and winforms is trying to indicate that it only works with the 32-bit mono runtime, which is what you get by default when you download it from mono-project.
