### ISSUE TITLE
Subdirectory not being deleted on mod uninstall

### ISSUE THREAD

**Issue by DaMachinator** [KSP-CKAN/CKAN#1856] opened 2016-08-04 18:16 UTC
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

**CKAN Version:** 

1.18.1 "Star Trimmer"

**Operating System:** 

Windows 10

**The issue you are experiencing:** 

CKAN is not removing the GameData subdirectory of mods it uninstalls.

**How to recreate this issue:** 

Install a mod. Locate the GameData subdirectory of said mod. Uninstall said mod. The subdirectory is still there.
Sometimes, subfolders, .cfg files, and .xml files are also left behind.

Why this is a problem:

https://github.com/sarbian/ModuleManager/wiki/Module%20Manager%20Syntax#mod-dependency-checking

> The stuff within the needs section is based on either:
- A plugin .dll with the same assembly name.
- _**A subdirectory name under GameData. (Names with spaces can be used, just remove the spaces: GameData/My Mod/ => :NEEDS[MyMod]**_
- A FOR[Blah] defined would allow NEEDS[Blah]

**CKAN error codes (if applicable):** 

N/A

**Comment by politas** [comment] 2016-08-04 18:53
This issue has been talked about a lot. You need to manually clean up some mods' directories after uninstalling the mod in CKAN. #1610 contains a pretty comprehensive discussion of the problem. In short, it's a really complex issue to make CKAN do it right in all cases, and we haven't yet worked out an algorithm to do so.

Closing as  a duplicate of #1610

**Closed by politas** 2016-08-04 18:53 UTC

**Comment by DaMachinator** [comment] 2016-08-04 19:14
Odd, I checked for duplicates first. I was surprised that there were none.
