### ISSUE TITLE
CKAN GUI throws "module not found"-error again and again

### ISSUE THREAD

**Issue by DasSkelett** [KSP-CKAN/CKAN#2419] opened 2018-04-22 20:33 UTC
Background
----------

**CKAN Version:** 
v1.25.0

**KSP version**
v1.4.2.2110

**Operating System:** 
Windows10 64bit

Problem
-------

**What steps did you take in CKAN?**
Selected AJE Extended by seanyoung247.
CKAN raised error:
```
Module AdvancedJetEngine has not been found.
This may be because it is not compatible with the currently installed version of KSP
```
Clicked `Dismiss` and selected different mod to install (with AJE Extended still checked!).

**What did you expect to happen?**
Nothing.

**What happened instead?**
CKAN throws the error again on each new selection AND deselection of other mods as long as AJE is selected.

**What should happen?**
CKAN already deenables the `Apply changes`-button, so there is no need to inform the user again and again (which happens surely not intentional).

**Comment by HebaruSan** [comment] 2018-04-22 20:39
KSP 1.4.2, I assume?

**Comment by DasSkelett** [comment] 2018-04-22 20:42
Oh crap, deleted that accidentally. Yes.

**Comment by HebaruSan** [comment] 2018-04-22 20:47
This is happening because AJE Extended depends on AJE which depends on FAR, and FAR isn't available for 1.4.2 (the forum thread title says specifically 1.3.1). So at one level this is a duplicate of #2231, since AJE Extended should be marked as incompatible (note that AJE itself _is_ marked incompatible because of the incompatible dependency, but that doesn't propagate through multiple levels of dependencies).

At another level, it would be nice to automatically uncheck AJE Extended after the error is dismissed. Not sure how feasible that would be.

**Comment by DasSkelett** [comment] 2018-04-22 20:55
Yes, the first level doesn't matter to me, as I just wanted to install it for testing pusposes for #2416 :D 
I think your second approach is the way to go, as just suppressing the error is both more complicated (I think, didn't check the code yet) and also not recommended, because suppressing errors always is a welcome opportunity for more errors to sneak in.

**Comment by HebaruSan** [comment] 2018-04-24 23:05
This should be easy, but WinForms continues to embody the principle of maximum surprise by not changing the checkbox's display until after I click somewhere else in the grid. The (new) code to uncheck the box runs, the mod is removed from the changeset, but the UI is sitting there with a check mark in the box. It's a wonder to me that people have been able to get anything done with this toolkit at all.

**Closed** 2018-04-25 02:53 UTC
Labels: GUI, Pull request, Relationships
