### ISSUE TITLE
CKAN is installing my mod incorrectly

### ISSUE THREAD

**Issue by MOARdV** [KSP-CKAN/CKAN#1672] opened 2016-04-21 13:04 UTC
I am not a CKAN user, but RasterPropMonitor is available through CKAN.  However, it is being installed incorrectly, and I've got about half a dozen posts for support over the last day from users unable to use the mod after installing through CKAN.

Please either fix whatever you do to install RPM, or remove it from CKAN.  I do not need the extra support overhead of automated bad installations.

**Comment by plague006** [comment] 2016-04-21 13:15
I see exactly what the issue is and it'll be addressed in https://github.com/KSP-CKAN/NetKAN/pull/3653. Thanks for the heads up and apologies that we caused you undue reports.

**Closed** 2016-04-21 13:22 UTC
