### ISSUE TITLE
Problems opening CKAN on MacOS maybe related to GUIConfig.xml

### ISSUE THREAD

**Issue by MaltYebisu** [KSP-CKAN/CKAN#2661] opened 2019-01-18 09:27 UTC
Background
----------

**CKAN Version:** 
CKAN version v1.25.4+7413c232f2ff

**KSP Version:** 
KSP 1.6.1

**Operating System:** 
MacOS 10.14.2 (18C54)
Mono JIT compiler version 5.18.0.225

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

Problem
-------

**What steps did you take in CKAN?**
Fresh install of KSP 1.6.1 with ckan.exe in the folder.

Ran `mono --arch=32 ckan.exe` in terminal

Quit CKAN

Ran `mono --arch=32 ckan.exe` in terminal again

**What did you expect to happen?**
CKAN to open both times

**What happened instead?**
The first time CKAN opens like normal (I can install mods etc)
The second time CKAN stop responding before it loads

If I delete GUIConfig.xml from the CKAN folder then CKAN starts normally again

**CKAN relevant files:** 
The CKAN folder created in the KSP directory:
[CKAN folder.zip](https://www.dropbox.com/s/favywbgmv7hm1xz/CKAN%20folder.zip?dl=0)

The output in my terminal window:
[Terminal output.txt](https://www.dropbox.com/s/g2jr7z9d9j1w5wd/Terminal%20output.txt?dl=0)

**Comment by DasSkelett** [comment] 2019-01-18 11:50
The stack trace seems like it's a duplicate of #2595, which is fixed in #2600, but not released yet.
There's a test build in #2595 if you want to use the GUI until a new CKAN release, else I think the problem is not existing in the consoleUI nor with the normal command line interface, so you could use them.

**Comment by MaltYebisu** [comment] 2019-01-18 12:40
Thank you. It looks like the same bug. ConsoleUI and command line interface works fine.

Sorry for reporting a duplicate issue.

**Closed as completed** 2019-01-18 16:24 UTC
Labels: macOS, Duplicate
