### ISSUE TITLE
CKAN.DependencyNotSatisfiedKraken on checking a suggested mod that depends on incompatible mod being force-installed

### ISSUE THREAD

**Issue by Arkhorse** [KSP-CKAN/CKAN#3303] opened 2021-02-23 20:40 UTC
## Background

Game version: 1.11.1.3066
OS: Windows 10
CKAN version: 1.29.2 CKAN

## Problem

I am installing a bunch of mods to test if they work still on the current version of KSP. These mods all have the max KSP version as 1.9.9. This used to be the "any" selection in the past. But I see CKAN now has an any option.

Anyways, Im not sure if this will help you, or maybe it will help you fix another issue. 

1. Click Raster Prop Monitor, which is incompatible; go to the Versions tab to force-install the latest version
2. Do the same with Raster Prop Monitor Core
2. Apply
3. Select the ASETPRops mod in the suggestions list

```
CKAN.DependencyNotSatisfiedKraken: ASETProps dependency on RasterPropMonitor-Core 1:v0.30.2 or later version (any) not satisfied
   at CKAN.RelationshipResolver.ResolveStanza(IEnumerable`1 stanza, SelectionReason reason, RelationshipResolverOptions options, Boolean soft_resolve, IEnumerable`1 old_stanza)
   at CKAN.RelationshipResolver.Resolve(CkanModule module, RelationshipResolverOptions options, IEnumerable`1 old_stanza)
   at CKAN.RelationshipResolver.AddModulesToInstall(IEnumerable`1 modules)
   at CKAN.ChooseRecommendedMods.FindConflicts()
   at CKAN.ChooseRecommendedMods.MarkConflicts()
   at CKAN.ChooseRecommendedMods.RecommendedModsListView_ItemChecked(Object sender, ItemCheckedEventArgs e)
   at System.Windows.Forms.ListView.OnItemChecked(ItemCheckedEventArgs e)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

<details><summary>Installed mod list:</summary>

```
Animated Decouplers (AnimatedDecouplers v1.4.2.2)
ASET PRC (Portable Rover Components) (ASET-PRC 0.1.0.1)
Astrogator (Astrogator v0.10.2)
BARIS Bridge (BarisBridge v1.10)
Better SR Bs (BetterSRBs 1.2.4)
BetterBurnTime (BetterBurnTime 1.10)
Buffalo (Buffalo v2.10.2)
Buffalo Classic Stock Play Mode (Buffalo-PlayMode-ClassicStock v2.10.2)
CommNet Antennas Consumptor (CommNetAntennasConsumptor 3.0.3)
CommNet Antennas Extension (CommNetAntennasExtension 2.1.4)
CommNet Antennas Info (CommNetAntennasInfo 3.0.3)
CommNet Relays (ContractConfigurator-CommNetRelays v2.1.0)
Community Category Kit (CommunityCategoryKit v5.2.0.0)
Community Delta-V Maps (CommunityDeltaVMaps 2:2.8)
Community Parts Titles (CommunityPartsTitles 0.7.0)
Community Parts Titles Extras: Categories (CommunityPartsTitlesExtrasCategory 0.7.0)
Community Parts Titles Extras: CCK - No Duplicates (CommunityPartsTitlesExtrasNoCCKDup 0.7.0)
Community Resource Pack (CommunityResourcePack 1.4.2)
Community Tech Tree (CommunityTechTree 1:3.4.3)
Connected Living Space (ConnectedLivingSpace 2.0.0.6)
Contract Configurator (ContractConfigurator 1.30.5)
Contract Pack: Bases and Stations Reborn (ContractConfigurator-KerbinSpaceStation 2:3.7.2.3)
Contract Pack: Clever Sats (ContractConfigurator-CleverSats 1.4)
Contract Pack: Exploration Plus (ContractConfigurator-ExplorationPlus 2.0.1)
Contract Pack: Field Research (ContractConfigurator-FieldResearch 1.2.2)
Contract Pack: Kerbal Academy (ContractConfigurator-KerbalAcademy 1.1.10)
Corvus CF (Corvus125mTwoKerbalPod 2:1.3.6)
Critical Temperature Gauge (CriticalTemperatureGauge 1.11.0.0)
Crowd Sourced Flags (CrowdSourcedFlags 1.55.5)
Crowd Sourced Science (CrowdSourcedScience v6.0)
Cryo Tanks (CryoTanks 1.6.0)
Cryo Tanks Core (CryoTanks-Core 1.6.0)
Distant Object Enhancement Continued (DistantObject v2.0.2.0)
Distant Object Enhancement Continued default config (DistantObject-default v2.0.2.0)
DMModuleScienceAnimateGeneric (DMagicScienceAnimate v0.23)
Docking Port Alignment Indicator (DockingPortAlignmentIndicator 6.9.2.2)
Docking Port Sound FX (DockingPortSoundFX v2.1.12)
DSEV (DSEV v3.7.1)
DSEV Classic Stock Play Mode (DSEV-PlayMode-ClassicStock v3.7.1)
Dynamic Battery Storage (DynamicBatteryStorage 2:2.2.2.0)
Easy Vessel Switch (EVS) (EasyVesselSwitch 2.2)
Environmental Visual Enhancements - Stock Planet Config files (EnvironmentalVisualEnhancements-HR 2:EVE-1.2.2-1)
Environmental Visual Enhancements Redux (EnvironmentalVisualEnhancements 3:1.11.2.1)
Firespitter (Firespitter v7.17)
Firespitter Core (FirespitterCore v7.17)
Firespitter Resources config (FirespitterResourcesConfig v7.17)
Hide Empty Tech Tree Nodes (HideEmptyTechNodes 1.3.0)
Interstellar Fuel Switch (InterstellarFuelSwitch 3.25)
Interstellar Fuel Switch Core (InterstellarFuelSwitch-Core 3.25)
Keep It Straight (KeepItStraight 1.3.0)
Kerbal Actuators (KerbalActuators v1.8.3)
Kerbal Attachment System (KAS 1.7)
Kerbal Engineer Redux (KerbalEngineerRedux 1.1.8.3)
Kerbal Inventory System (KIS 1.28)
Kerbal Joint Reinforcement Continued (KerbalJointReinforcementContinued v3.5.2)
Kerbal Occupation Colors (KerbalOccupationColors v1.2.0.1)
Kerbal Reusability Expansion (SpaceXLegs 2.9.1)
Kerbalism (Kerbalism 3.12)
Kerbalism - Default Config (Kerbalism-Config-Default 3.12)
KSP Achievements (Achievements 1.9.4.2)
KSP Craft Organizer (VAB/SPH tags + craft searching) (KspCraftOrganizer 1.6.0)
KSP Interstellar Extended (KSPInterstellarExtended 1.26.19)
LoreFriendly Serious Parody Flag Pack (LSPFlags v2.1)
MechJeb 2 (MechJeb2 2.12.0.0)
Module Manager (ModuleManager 4.1.4)
MOLE (MOLE v1.26.0)
MOLE Classic Stock Play Mode (MOLE-PlayMode-ClassicStock v1.26.0)
Near Future Electrical Core (NearFutureElectrical-Core 1.2.1)
Near Future IVA Props (NearFutureProps 1:0.6.4)
Near Future Solar Core (NearFutureSolar-Core 1.3.1)
Parking Brake (ParkingBrake 0.4.0)
Planet Wiki (PlanetWiki 1:4.1)
Planning Node (PlanningNode v0.1.2)
Precise Editor (PreciseEditor v1.4.1)
Precise Maneuver (PreciseManeuver 2:2.4.4)
RCS Build Aid (RCSBuildAid v1.0.6)
RemoteTech Redev Antennas (RemoteTechRedevAntennas 0.1.1)
ReStock (ReStock 1.3.1)
ReStock+ (ReStockPlus 1.3.1)
Science Lab Info (and 6 Crew Lab) (ScienceLabInfo 2.0.0)
Sounding Rockets! (SoundingRockets 1.4.0)
Space Age (SpaceAge v1.3.1)
Speed Unit Annex (SpeedUnitAnnex 1.3.7)
TweakScale - Rescale Everything! (TweakScale v2.4.4.5)
USI Asteroid Recycling Technologies (USI-ART 1:1.4.0)
USI Core (USI-Core 1.4.0)
USI Exploration Pack (USI-EXP 1.4.0)
USI Tools (USITools 1.4.0)
Wild Blue Tools (WildBlueTools v1.82)
WildBlueIndustries Classic Stock Play Mode (WildBlue-PlayMode-ClassicStock v1.82)
```

</details>

**Comment by HebaruSan** [comment] 2021-02-23 20:46
Please share the list of mods you're trying to install; without that we don't have enough information to investigate.

**Comment by Arkhorse** [comment] 2021-02-23 21:28
> Please share the list of mods you're trying to install; without that we don't have enough information to investigate.

Um, ASETPRops and Raster prop monitor + the core. (It does say this in the error)

**Comment by HebaruSan** [comment] 2021-02-23 21:32
> Um, ASETPRops and Raster prop monitor + the core. (It does say this in the error)

Is that all? The description also says:

> I am installing a bunch of mods

Also, do you have any mods already installed, and if so, which ones?

**Comment by Arkhorse** [comment] 2021-02-23 21:34
> > Um, ASETPRops and Raster prop monitor + the core. (It does say this in the error)
> 
> Is that all? The description also says:
> 
> > I am installing a bunch of mods
> 
> Also, do you have any mods already installed, and if so, which ones?

Yeah, sorry. I post alot of bug reports in the past for another dev, and he likes to know what I was doing at the time of the error. 

Yes, I have other mods installed.
[2020-02-23.txt](https://github.com/KSP-CKAN/CKAN/files/6031948/2020-02-23.txt)

**Comment by HebaruSan** [comment] 2021-02-23 21:38
OK, and what are your installed and compatible game versions?

(In future, it's probably easiest to just fill in the template we made for this: 
https://github.com/KSP-CKAN/.github/blob/master/.github/ISSUE_TEMPLATE/bug_report.md )

**Comment by Arkhorse** [comment] 2021-02-23 21:41
> OK, and what are your installed and compatible game versions?
> 
> (In future, it's probably easiest to just fill in the template we made for this:
> https://github.com/KSP-CKAN/.github/blob/master/.github/ISSUE_TEMPLATE/bug_report.md )

For some reason it didnt give me that template..

I only have one install: 1.11.1.3066, windows 10, 1.29.2 CKAN version.

**Comment by HebaruSan** [comment] 2021-02-23 21:48
Oh, so this appears when it's trying to display recommendations? Just noticed `RecommendedModsListView_ItemChecked` in the stack trace. Possibly the same or similar root cause as #3291, fixed in #3292.

@Arkhorse can you please try this with the current bleeding edge test build to see whether it helps?

- https://ksp-ckan.s3-us-west-2.amazonaws.com/ckan.exe

**Comment by Arkhorse** [comment] 2021-02-23 21:55
> Oh, so this appears when it's trying to display recommendations? Just noticed `RecommendedModsListView_ItemChecked` in the stack trace. Possibly the same or similar root cause as #3291, fixed in #3292.
> 
> @Arkhorse can you please try this with the current bleeding edge test build to see whether it helps?
> 
> * https://ksp-ckan.s3-us-west-2.amazonaws.com/ckan.exe

No, still does it. Select the most recent version of raster prop monitor, and its core. Then apply, then select the ASETPRops mod. 

```
CKAN.DependencyNotSatisfiedKraken: ASETProps dependency on RasterPropMonitor-Core 1:v0.30.2 or later version (any) not satisfied
   at CKAN.RelationshipResolver.ResolveStanza(IEnumerable`1 stanza, SelectionReason reason, RelationshipResolverOptions options, Boolean soft_resolve, IEnumerable`1 old_stanza)
   at CKAN.RelationshipResolver.Resolve(CkanModule module, RelationshipResolverOptions options, IEnumerable`1 old_stanza)
   at CKAN.RelationshipResolver.AddModulesToInstall(IEnumerable`1 modules)
   at CKAN.ChooseRecommendedMods.FindConflicts()
   at CKAN.ChooseRecommendedMods.MarkConflicts()
   at CKAN.ChooseRecommendedMods.RecommendedModsListView_ItemChecked(Object sender, ItemCheckedEventArgs e)
   at System.Windows.Forms.ListView.OnItemChecked(ItemCheckedEventArgs e)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by HebaruSan** [comment] 2021-02-23 22:00
> compatible game versions?

How about this info? None of these three mods seems to be compatible with just KSP 1.11. Are you doing a force-install of each mod, or do you have compatible versions set, or what?

**Comment by Arkhorse** [comment] 2021-02-23 22:01
> > compatible game versions?
> 
> How about this info? None of these three mods seems to be compatible with just KSP 1.11. Are you doing a force-install of each mod, or do you have compatible versions set, or what?

I am going to the version tab and manually selecting the version. Its the top one.

**Comment by HebaruSan** [comment] 2021-02-23 22:08
OK, somehow I _still_ don't get an error, even with those specific steps. Anything else that's not been mentioned yet that we should know about?

**Comment by Arkhorse** [comment] 2021-02-23 22:11
> OK, somehow I _still_ don't get an error, even with those specific steps. Anything else that's not been mentioned yet that we should know about?

I cant really think of anything that would cause it for me, but not you. My exact windows version is 2004 19041.804. CKAN is not on the same drive as KSP, The folder it is in is part of an mklink for my documents (OS is on a small ssd).

**Comment by HebaruSan** [comment] 2021-02-23 22:15
OK, if I revert to the CKAN v1.29.2 release instead of the test build, then I do see the error with the given steps. Perhaps your files got mixed up and you didn't run the file you thought.

Closing as fixed by #3292, since the current builds look fine.

**Comment by Arkhorse** [comment] 2021-02-23 22:20
> OK, if I revert to the CKAN v1.29.2 release instead of the test build, then I do see the error with the given steps. Perhaps your files got mixed up and you didn't run the file you thought.
> 
> Closing as fixed by #3292, since the current builds look fine.

No, I renamed the old exe before I copied the new version in. The date for the files are also shown, so its not possible for me to run the wrong one. I even checked the version to make sure.
This is the exact order I did it in, incase you did it another way:
![ckan issue 2021-02-23 1](https://user-images.githubusercontent.com/20694721/108915757-b941aa80-7603-11eb-9177-0500e851a5e3.png)
![ckan issue 2021-02-23 2](https://user-images.githubusercontent.com/20694721/108915793-c8285d00-7603-11eb-863d-20a3a0739c56.png)
![ckan issue 2021-02-23 3](https://user-images.githubusercontent.com/20694721/108915812-ceb6d480-7603-11eb-8e4d-0c2e37af5bbf.png)
![ckan issue 2021-02-23 4](https://user-images.githubusercontent.com/20694721/108915821-d1192e80-7603-11eb-9c7c-f7ae3e81ab78.png)

**Comment by HebaruSan** [comment] 2021-02-23 22:25
> This is the exact order I did it in, incase you did it another way (other than selecting the suggested mod, as that instantly causes this error):

Now I'm confused. In the newest round of screenshots, it looks like the error appears immediately after you click Apply; if that's the case, then how can "selecting the suggested mod" even be an option, if it isn't available to be selected yet?

**Comment by Arkhorse** [comment] 2021-02-23 22:31
> > This is the exact order I did it in, incase you did it another way (other than selecting the suggested mod, as that instantly causes this error):
> 
> Now I'm confused. In the newest round of screenshots, it looks like the error appears immediately after you click Apply; if that's the case, then how can "selecting the suggested mod" even be an option, if it isn't available to be selected yet?

Like I said, that step is excluded, as my screenshot wont show it, due to this error window taking precedence.

**Comment by HebaruSan** [comment] 2021-02-23 22:36
So that means what? You check the checkbox, or the error appears after Apply?

**Comment by HebaruSan** [comment] 2021-02-23 22:43
Anyway, thanks for the screenshots. Re-opening because the version in the title bar confirms this happens with the test build.

**Comment by HebaruSan** [comment] 2021-02-23 22:51
Aha! Sorry, that was my mistake. I was running the test build from my system menus, and v1.29.2 from the command line. When I saw the error, it was printed at the command line; but that output isn't visible when running from the system menu!

If I run the test build from the command line, the error _is_ printed!

```
CKAN.DependencyNotSatisfiedKraken: ASETProps dependency on RasterPropMonitor-Core 1:v0.30.2 or later version (any) not satisfied
  at CKAN.RelationshipResolver.ResolveStanza (System.Collections.Generic.IEnumerable`1[T] stanza, CKAN.SelectionReason reason, CKAN.RelationshipResolverOptions options, System.Boolean soft_resolve, System.Collections.Generic.IEnumerable`1[T] old_stanza) [0x002ee] in <5010cf03c7d34829aad7e793c615f379>:0 
  at CKAN.RelationshipResolver.Resolve (CKAN.CkanModule module, CKAN.RelationshipResolverOptions options, System.Collections.Generic.IEnumerable`1[T] old_stanza) [0x00043] in <5010cf03c7d34829aad7e793c615f379>:0 
  at CKAN.RelationshipResolver.AddModulesToInstall (System.Collections.Generic.IEnumerable`1[T] modules) [0x0016d] in <5010cf03c7d34829aad7e793c615f379>:0 
  at CKAN.RelationshipResolver..ctor (System.Collections.Generic.IEnumerable`1[T] modulesToInstall, System.Collections.Generic.IEnumerable`1[T] modulesToRemove, CKAN.RelationshipResolverOptions options, CKAN.IRegistryQuerier registry, CKAN.Versioning.GameVersionCriteria GameVersion) [0x00018] in <5010cf03c7d34829aad7e793c615f379>:0 
  at CKAN.ChooseRecommendedMods.FindConflicts () [0x00039] in <5010cf03c7d34829aad7e793c615f379>:0 
  at CKAN.ChooseRecommendedMods.MarkConflicts () [0x00000] in <5010cf03c7d34829aad7e793c615f379>:0 
  at CKAN.ChooseRecommendedMods.RecommendedModsListView_ItemChecked (System.Object sender, System.Windows.Forms.ItemCheckedEventArgs e) [0x00038] in <5010cf03c7d34829aad7e793c615f379>:0 
  at System.Windows.Forms.ListView.OnItemChecked (System.Windows.Forms.ItemCheckedEventArgs e) [0x00019] in <6d635ac3dc1c4424ad385ded79f1e868>:0 
  at System.Windows.Forms.ListViewItem.set_Checked (System.Boolean value) [0x0006c] in <6d635ac3dc1c4424ad385ded79f1e868>:0 
  at System.Windows.Forms.ListView+ItemControl.ItemsMouseDown (System.Object sender, System.Windows.Forms.MouseEventArgs me) [0x000dd] in <6d635ac3dc1c4424ad385ded79f1e868>:0 
  at System.Windows.Forms.Control.OnMouseDown (System.Windows.Forms.MouseEventArgs e) [0x00019] in <6d635ac3dc1c4424ad385ded79f1e868>:0 
  at System.Windows.Forms.Control.WmLButtonDown (System.Windows.Forms.Message& m) [0x0008b] in <6d635ac3dc1c4424ad385ded79f1e868>:0 
  at System.Windows.Forms.Control.WndProc (System.Windows.Forms.Message& m) [0x001bc] in <6d635ac3dc1c4424ad385ded79f1e868>:0 
  at System.Windows.Forms.ListView+ItemControl.WndProc (System.Windows.Forms.Message& m) [0x00071] in <6d635ac3dc1c4424ad385ded79f1e868>:0 
  at System.Windows.Forms.Control+ControlWindowTarget.OnMessage (System.Windows.Forms.Message& m) [0x00000] in <6d635ac3dc1c4424ad385ded79f1e868>:0 
  at System.Windows.Forms.Control+ControlNativeWindow.WndProc (System.Windows.Forms.Message& m) [0x0000b] in <6d635ac3dc1c4424ad385ded79f1e868>:0 
  at System.Windows.Forms.NativeWindow.WndProc (System.IntPtr hWnd, System.Windows.Forms.Msg msg, System.IntPtr wParam, System.IntPtr lParam) [0x00085] in <6d635ac3dc1c4424ad385ded79f1e868>:0 
```

Cool, that means we can investigate. Sorry again for the confusion.

**Comment by Arkhorse** [comment] 2021-02-23 23:14
> Aha! Sorry, that was my mistake. I was running the test build from my system menus, and v1.29.2 from the command line. When I saw the error, it was printed at the command line; but that output isn't visible when running from the system menu!
> 
> If I run the test build from the command line, the error _is_ printed!
> 
> ```
> CKAN.DependencyNotSatisfiedKraken: ASETProps dependency on RasterPropMonitor-Core 1:v0.30.2 or later version (any) not satisfied
>   at CKAN.RelationshipResolver.ResolveStanza (System.Collections.Generic.IEnumerable`1[T] stanza, CKAN.SelectionReason reason, CKAN.RelationshipResolverOptions options, System.Boolean soft_resolve, System.Collections.Generic.IEnumerable`1[T] old_stanza) [0x002ee] in <5010cf03c7d34829aad7e793c615f379>:0 
>   at CKAN.RelationshipResolver.Resolve (CKAN.CkanModule module, CKAN.RelationshipResolverOptions options, System.Collections.Generic.IEnumerable`1[T] old_stanza) [0x00043] in <5010cf03c7d34829aad7e793c615f379>:0 
>   at CKAN.RelationshipResolver.AddModulesToInstall (System.Collections.Generic.IEnumerable`1[T] modules) [0x0016d] in <5010cf03c7d34829aad7e793c615f379>:0 
>   at CKAN.RelationshipResolver..ctor (System.Collections.Generic.IEnumerable`1[T] modulesToInstall, System.Collections.Generic.IEnumerable`1[T] modulesToRemove, CKAN.RelationshipResolverOptions options, CKAN.IRegistryQuerier registry, CKAN.Versioning.GameVersionCriteria GameVersion) [0x00018] in <5010cf03c7d34829aad7e793c615f379>:0 
>   at CKAN.ChooseRecommendedMods.FindConflicts () [0x00039] in <5010cf03c7d34829aad7e793c615f379>:0 
>   at CKAN.ChooseRecommendedMods.MarkConflicts () [0x00000] in <5010cf03c7d34829aad7e793c615f379>:0 
>   at CKAN.ChooseRecommendedMods.RecommendedModsListView_ItemChecked (System.Object sender, System.Windows.Forms.ItemCheckedEventArgs e) [0x00038] in <5010cf03c7d34829aad7e793c615f379>:0 
>   at System.Windows.Forms.ListView.OnItemChecked (System.Windows.Forms.ItemCheckedEventArgs e) [0x00019] in <6d635ac3dc1c4424ad385ded79f1e868>:0 
>   at System.Windows.Forms.ListViewItem.set_Checked (System.Boolean value) [0x0006c] in <6d635ac3dc1c4424ad385ded79f1e868>:0 
>   at System.Windows.Forms.ListView+ItemControl.ItemsMouseDown (System.Object sender, System.Windows.Forms.MouseEventArgs me) [0x000dd] in <6d635ac3dc1c4424ad385ded79f1e868>:0 
>   at System.Windows.Forms.Control.OnMouseDown (System.Windows.Forms.MouseEventArgs e) [0x00019] in <6d635ac3dc1c4424ad385ded79f1e868>:0 
>   at System.Windows.Forms.Control.WmLButtonDown (System.Windows.Forms.Message& m) [0x0008b] in <6d635ac3dc1c4424ad385ded79f1e868>:0 
>   at System.Windows.Forms.Control.WndProc (System.Windows.Forms.Message& m) [0x001bc] in <6d635ac3dc1c4424ad385ded79f1e868>:0 
>   at System.Windows.Forms.ListView+ItemControl.WndProc (System.Windows.Forms.Message& m) [0x00071] in <6d635ac3dc1c4424ad385ded79f1e868>:0 
>   at System.Windows.Forms.Control+ControlWindowTarget.OnMessage (System.Windows.Forms.Message& m) [0x00000] in <6d635ac3dc1c4424ad385ded79f1e868>:0 
>   at System.Windows.Forms.Control+ControlNativeWindow.WndProc (System.Windows.Forms.Message& m) [0x0000b] in <6d635ac3dc1c4424ad385ded79f1e868>:0 
>   at System.Windows.Forms.NativeWindow.WndProc (System.IntPtr hWnd, System.Windows.Forms.Msg msg, System.IntPtr wParam, System.IntPtr lParam) [0x00085] in <6d635ac3dc1c4424ad385ded79f1e868>:0 
> ```
> 
> Cool, that means we can investigate. Sorry again for the confusion.

Oh its ok :). I just couldnt think of why I was getting it, and you werent. I do deal with some dev stuff, so I was thinking through my setup to see if anything else was odd. Good to see (or bad, depending on the view) that you can replicate it.

**Comment by HebaruSan** [comment] 2021-02-24 02:40
Alright, the technical cause of this is that the conflict checker for the recommendations list bases its analysis on the already-installed mods plus the recommendations you choose; the change set that you pick before clicking Apply is not included. If the dependencies are compatible, then the relationship resolver finds them; otherwise this exception is thrown. If we could add the change set into that, then force-installed incompatible mods could satisfy dependencies.

**Closed** 2021-02-24 21:46 UTC
Labels: Needs more info
