### ISSUE TITLE
Add a "favourite" flag

### ISSUE THREAD

**Issue by slizzered** [KSP-CKAN/CKAN#1215] opened 2015-06-28 14:24 UTC
The idea:
Provide a `favourite` / `star` / `wishlist` flag additional to `installed`. This would allow to track interesting mods.  
If mods can't be installed since they are not yet updated to a new version of KSP, they can still be tracked easily and installed as soon as they are available. This could be combined with the regular "update" feature of CKAN: if a favourite mod becomes compatible, there could be some message telling the user, that the long wait for compatibility is over.

**Comment by plague006** [comment] 2015-07-09 16:38
Closing this as it's a duplicate of #730.

**Closed by plague006** 2015-07-09 16:38 UTC
