### ISSUE TITLE
Cannot open CKAN

### ISSUE THREAD

**Issue by The-DapAttack** [KSP-CKAN/CKAN#3965] opened 2023-12-19 00:22 UTC
Hello, I am attempting to open ckan.exe and it flashes a command line box then it disappears and nothing. 
I ran an update roughly 3 days ago and after the update I have not been able to open it successfully.

Any help is appreciated.
Apologies in advance if this is a duplicate question. I have looked all over and can find nothing.

**Comment by HebaruSan** [comment] 2023-12-19 00:24
Hi @The-DapAttack, thanks for the report. Can you try the suggestions in #3956 to see if your issue is the same? This sounds exactly the same as what was reported there so far.

**Comment by The-DapAttack** [comment] 2023-12-19 00:38
This worked, thank you!

**Comment by HebaruSan** [comment] 2023-12-19 00:38
You're welcome, glad you got it working! :tada:

**Comment by HebaruSan** [comment] 2023-12-19 00:39
Duplicate of #3956

**Closed by HebaruSan** 2023-12-19 00:39 UTC

**Comment by Armour9** [comment] 2023-12-31 02:22
I am having this error as well.  I have uninstalled CKAN and have reinstalled it and I am getting the immediate popup and CKAN closes. When I did a quick screenshot is says because I am trying to run as Admin.  I have ensured "run as admin" is unchecked.  Now CKAN does not work at all.
