### ISSUE TITLE
CKAN stuck at downloading ".../CKAN-meta/archive/master.tar.gz"

### ISSUE THREAD

**Issue by TheBlueHat1** [KSP-CKAN/CKAN#3750] opened 2022-12-23 18:15 UTC
Background
----------
* Operating System: Win11
* CKAN Version: 1.31.2
* KSP Version: KSP 1.12.4.3187

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
**Describe the bug**
Whenever launching CKAN and agreeing for automatic repository updates, it immideately gets stuck at said file and the process freezes, cancelling mid-process would result in an error window (see code)

**Steps to reproduce**
* open CKAN in the .../common/kerbal space program directory
* agree to auto updates
* See error

**Expected behavior**
CKAN finishes auto-updating and downloading the file

**Screenshots (if applicable)**

![CKAN](https://user-images.githubusercontent.com/121312441/209388820-7658978f-0c2a-4d95-b161-f7865842a1c3.png)

**CKAN error code (if applicable):**

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at CKAN.GUI.ManageMods.MarkAllUpdates()
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.MenuStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by HebaruSan** [comment] 2022-12-23 18:17
Thanks, we just finished fixing this, you can try the latest dev build if you'd like to test:

- https://ksp-ckan.s3-us-west-2.amazonaws.com/ckan.exe

**Comment by HebaruSan** [comment] 2022-12-23 18:17
Duplicate of #3707

**Closed by HebaruSan** 2022-12-23 18:17 UTC
