### ISSUE TITLE
Nothing within CKAN is installing/not connecting at all

### ISSUE THREAD

**Issue by tytyguy15** [KSP-CKAN/CKAN#2289] opened 2018-02-20 01:50 UTC
Background
----------

**CKAN Version:**
1.22.6

**KSP Version:**
1.3.1

**Operating System:**
windows 10 pro (up to date)

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------

**What steps did you take in CKAN?**
What was i supposed to do. It gave me no troubleshooting steps

**What did you expect to happen?**
For it to work as advertised

**What happened instead?**
It didnt work;.; Nothing installs, and Ckan doesnt connect to anything

**Screenshots:**

**CKAN error codes (if applicable):**
I either get connection error messages or the program completely freezes

**Comment by tytyguy15** [comment] 2018-02-20 03:13
https://youtu.be/dgc3QY-sLmM

Here is a video of the issue im having. Includes all error codes ive encountered

**Comment by HebaruSan** [comment] 2018-02-20 03:19
Yeah, [SpaceDock is down again](http://downforeveryoneorjustme.com/spacedock.info). That'll break 40% of downloads in CKAN by itself, and many of the remaining mods probably depend on mods from SpaceDock.
We've been making various improvements to failed download handling (#2277, #2279, #2284), but they're not available in a released version yet, unfortunately. Hopefully soon.

Thanks for the video! It leaves absolutely no room for doubt as to the issue you're experiencing, and you have no idea how immensely helpful that is (or maybe you do?)!

**Comment by tytyguy15** [comment] 2018-02-20 03:32
Ah okay. Thanks for clearing that up. sorry if i seemed like i was being too pushy. any idea when it will be back?

**Comment by HebaruSan** [comment] 2018-02-20 03:36
I do not have an inside track on SpaceDock's status, but previous incidents have tended to be resolved within a day or two or three. Supposedly it's a one-man show now and he just started a new job, so it all depends on what the problem is, how hard it is to solve, and how tired he is after work:

- https://forum.kerbalspaceprogram.com/index.php?/topic/170865-spacedockinfo-mod-hosting-site/&do=findComment&comment=3295533

**Comment by HebaruSan** [comment] 2018-02-20 15:27
Looks like it's back up.

**Closed by HebaruSan** 2018-02-20 15:27 UTC
Labels: Network, Support

**Comment by tytyguy15** [comment] 2018-02-20 20:44
Thanks!!

**Comment by kenshin23** [comment] 2018-02-20 21:14
I've been trying to install Scatterer from Spacedock; the site itself is back up, but the downloads folder returns a 403 error. Is there a feature in CKAN where you can specify an alternate download location for a mod?

**Comment by HebaruSan** [comment] 2018-02-20 21:47
@kenshin23 , I just tried installing Scatterer, and the download worked. I guess I would suggest trying again.
