### ISSUE TITLE
[Feature] Date added (to CKAN)

### ISSUE THREAD

**Issue by Gabyalufix** [KSP-CKAN/CKAN#2924] opened 2019-11-19 13:13 UTC
I often recheck CKAN to see if any of my favorite mods have been ported over to the newest KSP version. But I basically have to check each mod manually.

Could you possibly add a "date added to CKAN" column that I could sort by? Is that something that is, or could be, stored internally?

**Comment by HebaruSan** [comment] 2019-11-19 13:23
Duplicate of #1155

**Comment by HebaruSan** [comment] 2019-11-19 13:23
We're working on this, see #2916.

**Closed by HebaruSan** 2019-11-19 13:23 UTC
