### ISSUE TITLE
[Feature] Custom Quickslots for Mods

### ISSUE THREAD

**Issue by Johnkurveen** [KSP-CKAN/CKAN#2965] opened 2020-01-18 22:49 UTC
Problem
-------
I play KSP with about 70 mods, but sometimes I would like to simplify that down, or change the mods I'm playing with, without having to uninstall and reinstall the mods later. 

Suggestions
-----------
Allow users to create "custom mod selections" where you could save one selection of mods, and with one click, change the selected mods almost like a quickslot selection. Example below. 

Alternatives include, but are not limited to, getting off the computer and doing my homework. 

Example: I play with about 70 mods, including realism overhaul, but sometimes I would like to do multiplayer with a simpler set of mods. I could save my list of 70 under quickslot 1, and under quickslot 2, just have Macjeb, Darkmultiplayer, and some visual mods. Under quickslot 3, I could have a selection of 20 mods specific to a server. If I want to do multiplayer, I can just click on the respective quickslot and run the game, making sure not to load the wrong save.

**Comment by HebaruSan** [comment] 2020-01-18 23:12
Duplicate of #1638

**Comment by HebaruSan** [comment] 2020-01-18 23:12
Thanks for the suggestion!

**Closed by HebaruSan** 2020-01-18 23:12 UTC
