### ISSUE TITLE
Exception when trying to install mod with suggested mods

### ISSUE THREAD

**Issue by zskamljic** [KSP-CKAN/CKAN#2505] opened 2018-08-18 08:24 UTC
Background
----------

**CKAN Version:** 
1.25.1

**KSP Version:** 
1.4.5

**Operating System:** 
ArchLinux 4.18.1

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No.

Problem
-------

**What steps did you take in CKAN?**
Select Kerbal Alarm clock to be installed, click apply changes, click apply, uncheck or leave Trigger AuFlags checked, click continue

**What did you expect to happen?**
The mod to be installed

**What happened instead?**
The GUI content was replaced by a red rectangle with diagonals, the following exception was thrown:

```
System.ArgumentOutOfRangeException: ControlCollection does not have that many controls
Parameter name: index
Actual value was 3.
  at System.Windows.Forms.Control+ControlCollection.get_Item (System.Int32 index) [0x00027] in <206d6d7865674caba761ab5f5b301dc0>:0 
  at System.Windows.Forms.TabControl.GetTab (System.Int32 index) [0x00006] in <206d6d7865674caba761ab5f5b301dc0>:0 
  at System.Windows.Forms.TabControl.GetTabRect (System.Int32 index) [0x00000] in <206d6d7865674caba761ab5f5b301dc0>:0 
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.TabControl.GetTabRect(int)
  at System.Windows.Forms.Theming.Default.TabControlPainter.Draw (System.Drawing.Graphics dc, System.Drawing.Rectangle area, System.Windows.Forms.TabControl tab) [0x000df] in <206d6d7865674caba761ab5f5b301dc0>:0 
  at System.Windows.Forms.ThemeWin32Classic.DrawTabControl (System.Drawing.Graphics dc, System.Drawing.Rectangle area, System.Windows.Forms.TabControl tab) [0x0000a] in <206d6d7865674caba761ab5f5b301dc0>:0 
  at System.Windows.Forms.TabControl.Draw (System.Drawing.Graphics dc, System.Drawing.Rectangle clip) [0x00005] in <206d6d7865674caba761ab5f5b301dc0>:0 
  at System.Windows.Forms.TabControl.OnPaintInternal (System.Windows.Forms.PaintEventArgs pe) [0x00017] in <206d6d7865674caba761ab5f5b301dc0>:0 
  at System.Windows.Forms.Control.WmPaint (System.Windows.Forms.Message& m) [0x0006d] in <206d6d7865674caba761ab5f5b301dc0>:0 
  at System.Windows.Forms.Control.WndProc (System.Windows.Forms.Message& m) [0x001a4] in <206d6d7865674caba761ab5f5b301dc0>:0 
  at System.Windows.Forms.TabControl.WndProc (System.Windows.Forms.Message& m) [0x00057] in <206d6d7865674caba761ab5f5b301dc0>:0 
  at System.Windows.Forms.Control+ControlWindowTarget.OnMessage (System.Windows.Forms.Message& m) [0x00000] in <206d6d7865674caba761ab5f5b301dc0>:0 
  at System.Windows.Forms.Control+ControlNativeWindow.WndProc (System.Windows.Forms.Message& m) [0x0000b] in <206d6d7865674caba761ab5f5b301dc0>:0 
  at System.Windows.Forms.NativeWindow.WndProc (System.IntPtr hWnd, System.Windows.Forms.Msg msg, System.IntPtr wParam, System.IntPtr lParam) [0x00085] in <206d6d7865674caba761ab5f5b301dc0>:0 
```

The error does not occur if you select to install suggested items along with the main mod.

**Screenshots:**
![image](https://user-images.githubusercontent.com/14160663/44297385-d5e12700-a2d0-11e8-84fe-bcedc9f4a145.png)

**CKAN error codes (if applicable):** 
Exception noted above.

**Comment by HebaruSan** [comment] 2018-08-18 08:50
Duplicate of #2499, fixing in #2501.

**Closed by HebaruSan** 2018-08-18 08:50 UTC
