### ISSUE TITLE
Suggestion: Central Storage location for downloaded mods

### ISSUE THREAD

**Issue by PiggyWhiskey** [KSP-CKAN/CKAN#1699] opened 2016-05-02 15:00 UTC
I'm currently running 3 "modpacks" with CKAN.
1. Steam + Helper mods
2. SETI: Unmanned before Manned
3. RemoteTech

As I've been creating these over the last few days, I've had to download the same mods over and over as it stores them in the Game Directory.

Would it be possible to add a config for an Archive location to have a central storage area.
This would help users with limited/slow data and save time with loading/installing.

**Comment by plague006** [comment] 2016-05-03 00:21
An absolutely legit feature request. In the interim you can use symlinks to keep your downloads consolidated. If you're on windows you can download a small program to integrate into windows explorer. http://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/

**Comment by mame98** [comment] 2016-05-08 17:50
This would be really cool!

**Comment by Postremus** [comment] 2016-07-04 20:05
closing as duplicate of #584

**Closed by Postremus** 2016-07-04 20:05 UTC
Labels: ckan.dll, enhancement, ★☆☆
