### ISSUE TITLE
An exception occurred during a WebClient request - downloading mods on linux

### ISSUE THREAD

**Issue by beomagi** [KSP-CKAN/CKAN#2409] opened 2018-04-13 22:13 UTC
Background
----------

**CKAN Version:** 
v1.24.1+9712f94116e8

**KSP Version:** 
1.4.2

**Operating System:** 
Mint 18.2 (ubuntu xenial)

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
no

Problem
-------

**What steps did you take in CKAN?**
check off mod kerbal engineer redux or precise manouver, tried one then the other, both etc...
click apply changes
click apply

**What did you expect to happen?**
install the checked mods

**What happened instead?**
gets the error:

 * Kerbal Engineer Redux 1.1.4.9 (github.com, 903.5 KB)

Downloading "https://github.com/jrbudda/KerbalEngineer/releases/download/1.1.4.9/KerbalEngineer-1.1.4.9.zip"
One or more downloads were unsuccessful:

Error downloading KerbalEngineerRedux 1.1.4.9: An exception occurred during a WebClient request.

Error!

**Screenshots:**
![image](https://user-images.githubusercontent.com/12766711/38759903-2fab007e-3f46-11e8-8552-17c9346e1beb.png)

**CKAN error codes (if applicable):**

**Comment by politas** [comment] 2018-04-27 11:03
Have you retried the install with a newer CKAN client?

**Comment by HebaruSan** [comment] 2018-08-26 13:37
I think this was caused by #2342, fixed by #2492. Before #2399, the nonexistence of `CdFileMgr` raised a simple WebClient exception like this when it happened during a download. Now the folder should always be there (and if it's not, the error should be more verbose).

Closing; please let us know if you see this happen with 1.25.3.

**Closed by HebaruSan** 2018-08-26 13:37 UTC
Labels: Linux, Mono, Network
