### ISSUE TITLE
Error installing the deb package

### ISSUE THREAD

**Issue by UnderwearWarrior** [KSP-CKAN/CKAN#2471] opened 2018-07-09 21:33 UTC
Background
----------

**CKAN Version:** 
Multiple

**KSP Version:** 
Latest non-beta, multiple, this has been happening for a while now (months) I keep trying again and it's never been fixed.

**Operating System:** 
Ubuntu 16.04

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

**Problem**
I cannot install CKAN. At all. The .deb installer won't even install anything unless the version is older than "ckan_1.24.0-PRE_all.deb" Any version of CKAN after this gives the error "Error: Dependency is not satisfiable: mono-runtime (>= 5.0)" and will not install. If I try to install a version of CKAN at  "ckan_1.24.0-PRE_all.deb" or older, it will install but it is unusable and will always give an error
"Oh no! Our download failed with a certificate error!

If you're on Linux, try running:
	mozroots --import --ask-remove
on the command-line to update your certificate store, and try again."

**What steps did you take in CKAN?**
None. I couldn't install it.

**What did you expect to happen?**
I expected it to install.

**What happened instead?**
It didn't install.

**Screenshots:**

![image](https://user-images.githubusercontent.com/12115209/42476885-52dc5944-839d-11e8-868e-73fbe7ff248d.png)
![image](https://user-images.githubusercontent.com/12115209/42476901-6697db52-839d-11e8-950a-53bc9438a2a2.png)

**CKAN error codes (if applicable):** 
See above.

**Comment by HebaruSan** [comment] 2018-07-09 22:50
This is a duplicate of #2321. You can get a more recent version of Mono here:
https://www.mono-project.com/download/stable/#download-lin

**Closed by HebaruSan** 2018-07-09 22:50 UTC

**Comment by ketsa** [comment] 2018-11-25 11:36
So forcing users to install mono 5 is your accepted solution to this problem ?

I'm on debian Buster and it still doesn't have mono 5. 
It looks like next release of Ubuntu will also not include mono 5...

**Comment by HebaruSan** [comment] 2018-11-25 17:35
Hi @ketsa, that's one way to solve it, but #2321 is still open, which means we don't consider it solved. If someone finds a way to make CKAN work on Mono 4 (specifically, using TLS 1.2 for HTTPS URLs), we would be happy to adopt it.
