### ISSUE TITLE
[Bug] Changset shows wrong Version for Updates

### ISSUE THREAD

**Issue by hinneLinks** [KSP-CKAN/CKAN#2908] opened 2019-10-30 17:50 UTC
Background
----------
* Operating System: Ubuntu 18.04
* CKAN Version: 1.26.4
* KSP Version: 1.8.0.2686

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
The "Changeset" Tab shows the wrong Version for Updates in the Column "Reason for Action".
This is just a View-Issue, CKAN downloads and update to the correct Version.

**Steps to reproduce**
Have some Mods that need an Update
See Screenshot 1 - you'll see the current and updated Version in their columns
Click "Add available updates"
"Reason for action" Column shows wrong (old) Version, see Screenshot 2
**Expected behavior**
"Reason for action" Column shows the new Version, that will be downloaded and installed

**Screenshots (if applicable)**
![screenshot-1](https://user-images.githubusercontent.com/15357388/67884264-d49ec180-fb45-11e9-9b6e-592669190e93.png)
![screenshot-2](https://user-images.githubusercontent.com/15357388/67884277-d8324880-fb45-11e9-863e-2833e4ff83aa.png)

**Comment by HebaruSan** [comment] 2019-10-30 18:25
Duplicate of #2873

**Closed by HebaruSan** 2019-10-30 18:25 UTC
