### ISSUE TITLE
Slow downloads

### ISSUE THREAD

**Issue by Gandon1** [KSP-CKAN/CKAN#3618] opened 2022-08-05 08:27 UTC
Background
----------
* Operating System: Windows 10
* CKAN Version: v1.31.0
* KSP Version: 1.12.3.3173

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
Yes, but deleted the data soon afterwards since Tweak Scale wasn't downloading via CKAN

Problem
-------
**Describe the bug**
Mulitiple times I have attempted to download a mod but I'm stuck with a zero bit rate for hours or get a "please wait" for hours. 

**Steps to reproduce**
* Go to... Any mod
* Click on... Install check box
* See error

**Image of "Please Wait"**
![image](https://user-images.githubusercontent.com/52172566/183035723-f3601cae-1624-4059-84f2-08a6dd6be885.png)

**Image of GameData Folder**
![image](https://user-images.githubusercontent.com/52172566/183036155-eeb563a8-eaa2-44a4-875b-aee4e83547cf.png)

**Comment by HebaruSan** [comment] 2022-08-05 18:20
Sounds like SpaceDock was having problems that day. Are you able to download it in your browser?

- https://spacedock.info/mod/1909/Kerbal%20Inventory%20System%20(KIS)

If that works, you can import it into CKAN via:

![image](https://user-images.githubusercontent.com/1559108/183137864-b7f9c548-8f58-4bfb-a03c-5afb5df18463.png)

Could also be one of the remaining SpaceDock performance problems such as KSP-SpaceDock/SpaceDock#416. This mod has a lot of releases and could be susceptible to that.

**Comment by Gandon1** [comment] 2022-08-05 18:57
I would like to say thank you for getting back to me so soon and writing an answer to my question. I understand that my problems are minor compared to the massive undertaking of the second link you sent. If I have any further issues I'll let you know. Have a wonderful day.

**Comment by Gandon1** [comment] 2022-08-05 19:52
An issue has occurred with getting Interstellar to work nicely with CKAN, I've attempted to used the method presented before but it's not recognized in the index. Using the link that CKAN wishes to download from:

**"About to install:

 * KSP Interstellar Extended 1.29.6 (spacedock.info, 272.1 MiB)
Downloading "https://spacedock.info/mod/172/KSP%20Interstellar%20Extended/download/1.29.6"
One or more downloads were unsuccessful:

Error downloading KSPInterstellarExtended 1.29.6: The remote name could not be resolved: 'spacedock.info'

Error during installation!**"

None of the other download links provided to Interstellar Extended function either. I apologies if this has been a common issue that can be solved with a link but I am stumped by my own lack of knowledge of coding and modding.

**Comment by HebaruSan** [comment] 2022-08-07 18:04
> The remote name could not be resolved: 'spacedock.info'

This means there is an unusual problem with your computer's network configuration, specifically your DNS. `spacedock.info` seems to be set up fine on the server side, so something is blocking you from accessing it, maybe some firewall software on your PC or something at your ISP. We can't really solve this for you, since we can't access your PC to investigate.

Closing this seems to be caused by things outside the control of the CKAN team.

**Closed by HebaruSan** 2022-08-07 18:04 UTC
Labels: Support, Network
