### ISSUE TITLE
Profiles.

### ISSUE THREAD

**Issue by Necessarycoot72** [KSP-CKAN/CKAN#1946] opened 2016-11-24 23:20 UTC
Since nobody Smited me for putting suggestions in the issues tab I will continue to put suggestions here. I come from the modding community on the [Skyrim nexus](http://www.nexusmods.com/skyrim/?) and we used to have this modding tool called [Mod organizer](http://www.nexusmods.com/skyrim/mods/1334/?). Mod organizer has the ability to make profiles which means you can have a different setup for mods with having to deselect each one independently and remembering what mod you had. Just at a couple of click and you can set up what mod you want for that specific playthrough. I know you have a similar system but that requires to have a different ksp install? nevertheless the less mod organizer does it far superior. I have no idea if it's even possible to add such a system with how you're doing mods with CKAN.

Here's a website detailing how mod organizers works on the [S.T.E.P wiki](http://wiki.step-project.com/Guide:Mod_Organizer) a trusted source for people modding Skyrim. Here's the[source code](https://github.com/TanninOne/modorganizer/releases) be warned it's in apha. He's tried to make it work with the 64bit game fallout 4 but stopped when given the offer to remake the nexus mod manager.

**Comment by politas** [comment] 2016-11-25 14:39
We've discussed this before. Given the fairly anarchic nature of KSP mods, swapping sets of mods in and out is a recipe for disaster. KSP has no DRM, so making multiple installs is really easy, and a much more reliable method for the outcome you want.

**Comment by HebaruSan** [comment] 2019-11-26 22:24
Duplicate of #1638

**Closed by HebaruSan** 2019-11-26 22:24 UTC
Labels: Enhancement
