### ISSUE TITLE
[Bug] Mac OSX Catalina does not support 32-bit code anymore; GUI won't run

### ISSUE THREAD

**Issue by djroelfsema** [KSP-CKAN/CKAN#2906] opened 2019-10-27 09:32 UTC
Background
----------
* Operating System: Mac OSX 10.15
* CKAN Version: latest
* KSP Version: latest

No manual changes were made!

Problem
-------
Apple stopped supporting 32-bit applications as of the latest version of Mac OSX. As the CKAN app uses 32-bit code (in the GUI-related code, from what I understand) the CKAN app just won't run anymore.

**Comment by HebaruSan** [comment] 2019-10-27 14:50
Duplicate of #2272

**Closed by HebaruSan** 2019-10-27 14:50 UTC
