### ISSUE TITLE
[Bug] Installation failure while installing RP-1 Express Install

### ISSUE THREAD

**Issue by BreadBox64** [KSP-CKAN/CKAN#3522] opened 2022-01-23 05:31 UTC
Background
----------
* Operating System: Windows 10
* CKAN Version: 1.30.4
* KSP Version: 1.10.1.2939

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No, this was a fresh install

Problem
-------
**Describe the bug**
While express-installing RO / RP-1 it crashed after producing the error below

**Steps to reproduce**
* Get a KSP 1.10.1 install
* Install "Realistic Progression One (RP-1) Express Install"
* See error

**Expected behavior**
Mod successfully installs

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/62221340/150666270-e334901e-bb71-4418-80be-2ee38eb12175.png)

**CKAN error code (if applicable):**

> Unhandled exception:
> System.Transactions.TransactionException: Failed to roll back. ---> System.IO.IOException: The process cannot access the file 'E:\ksp\rss-ro-rp1\GameData\ROEngines\Assets\TheBeastlyPig\XLR99.mu' because it is being used by another process.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.File.InternalDelete(String path, Boolean checkHost)
>    at ChinhDo.Transactions.FileManager.Operations.SingleFileOperation.Rollback()
>    at ChinhDo.Transactions.FileManager.TxEnlistment.Rollback(Enlistment enlistment)
>    --- End of inner exception stack trace ---
>    at ChinhDo.Transactions.FileManager.TxEnlistment.Rollback(Enlistment enlistment)
>    at System.Transactions.VolatileEnlistmentAborting.EnterState(InternalEnlistment enlistment)
>    at System.Transactions.TransactionStateAborted.EnterState(InternalTransaction tx)
>    at System.Transactions.EnlistableStates.Timeout(InternalTransaction tx)
>    at System.Transactions.Bucket.TimeoutTransactions()
>    at System.Transactions.BucketSet.TimeoutTransactions()
>    at System.Transactions.TransactionTable.ThreadTimer(Object state)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.TimerQueueTimer.CallCallback()
>    at System.Threading.TimerQueueTimer.Fire()
>    at System.Threading.TimerQueue.FireNextTimers() 
>

**Comment by HebaruSan** [comment] 2022-01-23 06:13
Duplicate of #3483

**Comment by HebaruSan** [comment] 2022-01-23 06:13
Thanks, this is a duplicate of #3483, which we are fixing in #3512.

**Closed by HebaruSan** 2022-01-23 06:13 UTC
