### ISSUE TITLE
[Bug] Mods wont install, changeset blank, Recommended blank

### ISSUE THREAD

**Issue by Ecte86** [KSP-CKAN/CKAN#3161] opened 2020-09-26 07:47 UTC
Background
----------
* Operating System: Windows 10 64x
* CKAN Version: v1.28.0
* KSP Version: 1.10.1.2939

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
After picking what mods I wish to install, they don't appear in the changeset tab. The Recommended tab is blank also.
The status bar shows "Error during installation."

**Steps to reproduce**
1. Select a mod (or multiple mods) to install
2. Click continue

**Expected behavior**
Mods show up in the changeset tab.
Recommended mods appear in Recommended tab.

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/218118/94335634-0b15e280-001c-11eb-89cc-e5ee83f5a146.png)

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment] 2020-09-26 16:44
Which mods are you trying to install?
Which mods do you already have installed?

**Comment by Ecte86** [comment] 2020-09-28 13:02
I was trying to install mods like MechJeb2, and AutoAsparagus, and at the time I had no mods installed.

**Comment by HebaruSan** [comment] 2020-10-02 20:33
I'm not able to reproduce this. I tried installing MechJeb2 and AutoAsparagus, and the changeset, recommendations, and installation worked fine. We'll need to know what's different about your scenario to proceed.

**Comment by Ecte86** [comment] 2020-10-11 21:40
I'm gonna retry reinstalling and using CKAN. The problem may be related to the fact that I played KSP ages ago, in steam, uninstalled it, then reinstalled it recently through steam. Basically what that means is I have super old saves, but none of the mods that those saves use.
No idea why that'd be causing issues but I will see what I can do.

**Comment by HebaruSan** [comment] 2021-04-15 00:13
No clues to follow here; closing. Please let us know if you are able to find a way to make this happen reliably, and we can re-open this.

**Closed by HebaruSan** 2021-04-15 00:13 UTC
Labels: Needs more info
