### ISSUE TITLE
[Bug]: cannot have both Windows and Linux game instances

### ISSUE THREAD

**Issue by Nightside101010** [KSP-CKAN/CKAN#4124] opened 2024-07-14 20:02 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Linux/Steam Deck

### CKAN Version

1.34.4

### Games

KSP 1

### Game Version

1.12.5

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

Install mods not on clan

### Describe the bug

I have a few Linux instances that work. I switched my main steam install back to the Windows version of the game and now the Manage Instances window reports it as invalid. If I try to add it as a new instance it cannot find the ksp EXE.

### Steps to reproduce

Go to the Manage Instances window reports it as invalid. If I try to add it as a new instance it cannot find the ksp EXE.

**Comment by HebaruSan** [comment] 2024-07-14 20:20
Duplicate of #4041

**Comment by HebaruSan** [comment] 2024-07-14 20:21
Hi @aguimorefran, thanks for the report. The Linux version of CKAN currently looks for the Linux native binary `KSP.x86_64`, not the Windows binary `KSP_x64.exe`. It will check for both in the next release, but in the time being you can work around this by creating a file called `KSP.x86_64` in your KSP dir.

**Closed by HebaruSan** 2024-07-14 20:20 UTC
Labels: Linux, Duplicate

**Comment by Nightside101010** [comment] 2024-07-14 21:34
Awesome thanks for the advice!
