### ISSUE TITLE
Ckan not launching

### ISSUE THREAD

**Issue by daclark47** [KSP-CKAN/CKAN#2510] opened 2018-08-21 21:02 UTC
Background
----------

**CKAN Version:** 
1.25.2

**KSP Version:** 
1.4.5/latest

**Operating System:** 
windows 10
Processor AMD Ryzen 7 1700X Eight-Core Processor
3.75 GHz
Ram 16.0GB

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
no

Problem
-------

**What steps did you take in CKAN?**
just trying to open it

**What did you expect to happen?**
open the app

**What happened instead?**
it didnt open

**Screenshots:**

**CKAN error codes (if applicable):** 
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at CKAN.GUIUser.DisplayMessage(String message, Object[] args)
   at CKAN.KSP.SetupCkanDirectories()
   at CKAN.KSP..ctor(String gameDir, String name, IUser user)
   at CKAN.KSPManager.LoadInstancesFromRegistry()
   at CKAN.Main..ctor(String[] cmdlineArgs, KSPManager mgr, GUIUser user, Boolean showConsole)
   at CKAN.GUI.Main_(String[] args, KSPManager manager, Boolean showConsole)
   at CKAN.CmdLine.MainClass.Main(String[] args)

**Comment by HebaruSan** [comment] 2018-08-21 21:24
Duplicate of #2483, fixed in #2482.

**Closed by HebaruSan** 2018-08-21 21:24 UTC
