### ISSUE TITLE
ckan cannot open - experiences Unhandled Exception on startup

### ISSUE THREAD

**Issue by Auraxis012** [KSP-CKAN/CKAN#2500] opened 2018-08-15 07:12 UTC
Background
----------

**CKAN Version:** 
v1.24.0

**KSP Version:** 
v1.4.5

**Operating System:** 
Windows 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
Yes. However, this did not stop CKAN running previously

Problem
-------

**What steps did you take in CKAN?**
When I opened it, it experienced a 'krakenNotFound' error (so ckan would open, but could not check for mod updates). In an attempt to solve it, I first tried to check for updates within the client and then when that froze, I tried to redownload and rerun ckan. After deleting the old ckan.exe, I ran the new one.

**What did you expect to happen?**
For ckan to open normally, without the 'krakenNotFound' error

**What happened instead?**
ckan.exe displayed that it had had a unhandled exception and closed itself. It now does this every time I run it.

**Screenshots:**

![error message](https://user-images.githubusercontent.com/23095318/44135926-d34852e0-a062-11e8-9710-a987254a638f.png)

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment] 2018-08-15 14:53
Duplicate of #2483, fixed in #2482.

**Closed by HebaruSan** 2018-08-15 14:53 UTC
