### ISSUE TITLE
[Bug] All mods installed via CKAN listed as AD

### ISSUE THREAD

**Issue by Funtime60** [KSP-CKAN/CKAN#2864] opened 2019-09-09 04:00 UTC
Background
----------
* Operating System:  Windows 10 Home 1903 18362.295
* CKAN Version: v1.26.4
* KSP Version: 1.7.3

No manual changes to Gamedata folder

Problem
-------
I have installed 20 mods with CKAN, but after installation CKAN lists all of them as AD.

**Steps to reproduce**
Select a mod
Install said mod
No error message, but the mod will be installed and listed as AD

**Expected behavior**
Select a mod
Install said mod
Able to unistall said mod with CKAN

**Screenshots**
![image](https://user-images.githubusercontent.com/24595923/64502553-fa18f880-d283-11e9-9d62-432bb51837e4.png)
All of these were installed manually.

**Comment by HebaruSan** [comment] 2019-09-09 14:48
Last reported in #2262. Still no info about how to make it happen; this issue's steps to reproduce don't work (obviously).

**Comment by Orca3006** [comment] 2019-09-09 21:01
_**EVERY TIME**_ I try to install any mods after updating to the orion version, ckan crashes or refuses to install anything.  It does not matter if I am doing one mod or many it does the same thing over and over and over.  Going back to the old version until the problem is fixed.  FYI I have the newest version of the game installed before I updated ckan.

**Comment by HebaruSan** [comment] 2019-09-09 21:14
@Orca3006, I know it's tempting to vent about problems, but please try to refrain from doing that on unrelated issues. Posting here just distracts from someone else's problem and makes it more confusing for those reading, and has a 0% chance of helping you. If you would like help with your problem, please document it in a new issue:
https://github.com/KSP-CKAN/CKAN/issues/new/choose

**Comment by DasSkelett** [comment] 2019-09-09 21:36
Maybe CKAN can't write to the registry.json anymore? Thus it can't add the mods in the installed section?
But I heavily suspect this would throw an error somewhere during mod installations.

**Comment by HebaruSan** [comment] 2019-09-09 21:56
> Maybe CKAN can't write to the registry.json anymore?

Sounds plausible. We could always mock up a test case with `chown`/`chmod`.

**Comment by HebaruSan** [comment] 2019-09-09 22:25
@Funtime60, do you have this problem with the previous release? Knowing the answer to that would help us to determine which code changes might be related.

https://github.com/KSP-CKAN/CKAN/tree/v1.26.2

**Comment by DasSkelett** [comment] 2019-09-28 12:57
So I tried chmodding the registry, but CKAN hangs on `Updating registry - 70%`.
Also the mod folder is present for a short time (<1s), but disappears again (most likely the transaction kicking in).
So the mod is not installed at all afterwards, ans as a result not even marked as AD.

Need to test on Windows too, might behave differently there.

**Comment by HebaruSan** [comment] 2019-10-09 21:49
Issue author not responsive to follow-up questions, closing.
@Funtime60, if you have a chance to return to this issue, see above regarding testing on previous versions. We can't reproduce this, so we need to tease more information out of your system to figure out what's going on.

**Closed by HebaruSan** 2019-10-09 21:49 UTC
Labels: Bug, GUI, Needs more info, Registry, Windows

**Comment by Funtime60** [comment] 2019-10-09 22:07
I can't reproduce it either anymore.
