### ISSUE TITLE
[Bug] CKAN v1.30.2 hangs for about 5 minutes at updating tray

### ISSUE THREAD

**Issue by paperclip** [KSP-CKAN/CKAN#3381] opened 2021-05-24 18:18 UTC
Background
----------
* Operating System: Windows 10 
* CKAN Version: v1.30.2
* KSP Version: v1.11.2

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**

Installed KRPC build by nullprofile: https://github.com/nullprofile/krpc

Problem
-------
After selecting the KSP installation to work against CKAN updates packages, and gets as far as "Updating tray", where it sits for about 5 minutes. 

v1.30.0 doesn't hang.

**Steps to reproduce**
* (Auto-upgraded CKAN)
* Start CKAN
* Select  KSP 1.11.2 (also 1.10.1, so I don't think KSP version specific?)

**Expected behavior**

Should load in about the same amount of time as v1.30.0 (a few seconds)

**Screenshots (if applicable)**

![CKAN hung 2021-05-24 191444](https://user-images.githubusercontent.com/195586/119390058-6049e700-bcc4-11eb-9987-34a31e072230.png)

I have a process monitor log if it's helpful:
18:43:37.9868571	ckan.exe	19160	Thread Exit		SUCCESS	Thread ID: 18276, User Time: 0.0000000, Kernel Time: 0.0000000
18:43:38.0026596	ckan.exe	19160	QueryNameInformationFile	C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll	SUCCESS	Name: \Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
18:43:38.0026790	ckan.exe	19160	Thread Create		SUCCESS	Thread ID: 2416
18:43:50.0146864	ckan.exe	19160	Thread Exit		SUCCESS	Thread ID: 2416, User Time: 0.0000000, Kernel Time: 0.0000000
18:43:50.0307322	ckan.exe	19160	QueryNameInformationFile	C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll	SUCCESS	Name: \Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
18:43:50.0307658	ckan.exe	19160	Thread Create		SUCCESS	Thread ID: 16992
18:44:02.0363753	ckan.exe	19160	Thread Exit		SUCCESS	Thread ID: 16992, User Time: 0.0000000, Kernel Time: 0.0000000
18:44:02.0681016	ckan.exe	19160	QueryNameInformationFile	C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll	SUCCESS	Name: \Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
18:44:02.0681359	ckan.exe	19160	Thread Create		SUCCESS	Thread ID: 19808
18:44:10.2302050	ckan.exe	19160	QueryNameInformationFile	C:\Windows\System32\ntdll.dll	SUCCESS	Name: \Windows\System32\ntdll.dll
18:44:10.2302274	ckan.exe	19160	Thread Create		SUCCESS	Thread ID: 14224
18:44:14.0767990	ckan.exe	19160	Thread Exit		SUCCESS	Thread ID: 19808, User Time: 0.0000000, Kernel Time: 0.0000000
18:44:14.1085624	ckan.exe	19160	QueryNameInformationFile	C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll	SUCCESS	Name: \Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
18:44:14.1085961	ckan.exe	19160	Thread Create		SUCCESS	Thread ID: 17784
18:44:26.1100149	ckan.exe	19160	Thread Exit		SUCCESS	Thread ID: 17784, User Time: 0.0000000, Kernel Time: 0.0000000
18:44:26.1420004	ckan.exe	19160	QueryNameInformationFile	C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll	SUCCESS	Name: \Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
18:44:26.1420320	ckan.exe	19160	Thread Create		SUCCESS	Thread ID: 18908
18:44:37.6540575	ckan.exe	19160	Thread Exit		SUCCESS	Thread ID: 18908, User Time: 0.0000000, Kernel Time: 0.0000000
18:44:37.6707742	ckan.exe	19160	QueryNameInformationFile	C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll	SUCCESS	Name: \Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
18:44:37.6708061	ckan.exe	19160	Thread Create		SUCCESS	Thread ID: 18748
18:44:49.6789449	ckan.exe	19160	Thread Exit		SUCCESS	Thread ID: 18748, User Time: 0.0000000, Kernel Time: 0.0000000
18:44:49.6949006	ckan.exe	19160	QueryNameInformationFile	C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll	SUCCESS	Name: \Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
18:44:49.6949313	ckan.exe	19160	Thread Create		SUCCESS	Thread ID: 20228
18:45:01.7073650	ckan.exe	19160	Thread Exit		SUCCESS	Thread ID: 20228, User Time: 0.0000000, Kernel Time: 0.0000000
18:45:01.7223191	ckan.exe	19160	QueryNameInformationFile	C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll	SUCCESS	Name: \Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
18:45:01.7223562	ckan.exe	19160	Thread Create		SUCCESS	Thread ID: 17588
18:45:13.7363159	ckan.exe	19160	Thread Exit		SUCCESS	Thread ID: 17588, User Time: 0.0000000, Kernel Time: 0.0000000
18:45:13.7519999	ckan.exe	19160	QueryNameInformationFile	C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll	SUCCESS	Name: \Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
18:45:13.7520258	ckan.exe	19160	Thread Create		SUCCESS	Thread ID: 18996
18:45:17.9447695	ckan.exe	19160	ReadFile	C:\Windows\System32\ucrtbase_clr0400.dll	SUCCESS	Offset: 736,256, Length: 15,360, I/O Flags: Non-cached, Paging I/O, Synchronous Paging I/O, Priority: Normal
18:45:17.9460820	ckan.exe	19160	ReadFile	C:\Windows\System32\ucrtbase_clr0400.dll	SUCCESS	Offset: 679,936, Length: 12,288, I/O Flags: Non-cached, Paging I/O, Synchronous Paging I/O, Priority: Normal
18:45:17.9462373	ckan.exe	19160	ReadFile	C:\Windows\System32\ucrtbase_clr0400.dll	SUCCESS	Offset: 390,144, Length: 4,096, I/O Flags: Non-cached, Paging I/O, Synchronous Paging I/O, Priority: Normal
18:45:17.9463795	ckan.exe	19160	ReadFile	C:\Windows\System32\ucrtbase_clr0400.dll	SUCCESS	Offset: 390,144, Length: 8,192, I/O Flags: Non-cached, Paging I/O, Synchronous Paging I/O, Priority: Normal
18:45:17.9465435	ckan.exe	19160	ReadFile	C:\Windows\System32\ucrtbase_clr0400.dll	SUCCESS	Offset: 598,016, Length: 12,288, I/O Flags: Non-cached, Paging I/O, Synchronous Paging I/O, Priority: Normal
18:45:25.2530124	ckan.exe	19160	Thread Exit		SUCCESS	Thread ID: 18996, User Time: 0.0000000, Kernel Time: 0.0000000
18:45:25.2693183	ckan.exe	19160	QueryNameInformationFile	C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll	SUCCESS	Name: \Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
18:45:25.2693413	ckan.exe	19160	Thread Create		SUCCESS	Thread ID: 19508
18:45:37.2739581	ckan.exe	19160	Thread Exit		SUCCESS	Thread ID: 19508, User Time: 0.0000000, Kernel Time: 0.0000000
18:45:37.3048354	ckan.exe	19160	QueryNameInformationFile	C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll	SUCCESS	Name: \Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
18:45:37.3048626	ckan.exe	19160	Thread Create		SUCCESS	Thread ID: 1276
18:45:49.3055768	ckan.exe	19160	Thread Exit		SUCCESS	Thread ID: 1276, User Time: 0.0000000, Kernel Time: 0.0000000
18:45:49.3373306	ckan.exe	19160	QueryNameInformationFile	C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll	SUCCESS	Name: \Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
18:45:49.3373650	ckan.exe	19160	Thread Create		SUCCESS	Thread ID: 8212
18:46:01.3491669	ckan.exe	19160	Thread Exit		SUCCESS	Thread ID: 8212, User Time: 0.0000000, Kernel Time: 0.0000000
18:46:01.3647851	ckan.exe	19160	QueryNameInformationFile	C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll	SUCCESS	Name: \Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
18:46:01.3648194	ckan.exe	19160	Thread Create		SUCCESS	Thread ID: 19232
18:46:13.3664451	ckan.exe	19160	Thread Exit		SUCCESS	Thread ID: 19232, User Time: 0.0000000, Kernel Time: 0.0000000
18:46:13.3982242	ckan.exe	19160	QueryNameInformationFile	C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll	SUCCESS	Name: \Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
18:46:13.3982532	ckan.exe	19160	Thread Create		SUCCESS	Thread ID: 19712
18:46:24.8992273	ckan.exe	19160	Thread Exit		SUCCESS	Thread ID: 19712, User Time: 0.0000000, Kernel Time: 0.0000000
18:46:24.9312384	ckan.exe	19160	QueryNameInformationFile	C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll	SUCCESS	Name: \Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
18:46:24.9312746	ckan.exe	19160	Thread Create		SUCCESS	Thread ID: 19440
18:46:37.4387850	ckan.exe	19160	Thread Exit		SUCCESS	Thread ID: 19440, User Time: 0.0000000, Kernel Time: 0.0000000
18:46:37.4678189	ckan.exe	19160	QueryNameInformationFile	C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll	SUCCESS	Name: \Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
18:46:37.4678528	ckan.exe	19160	Thread Create		SUCCESS	Thread ID: 19992
18:46:49.4768258	ckan.exe	19160	Thread Exit		SUCCESS	Thread ID: 19992, User Time: 0.0000000, Kernel Time: 0.0000000
18:46:49.5077482	ckan.exe	19160	QueryNameInformationFile	C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll	SUCCESS	Name: \Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
18:46:49.5077841	ckan.exe	19160	Thread Create		SUCCESS	Thread ID: 2076
18:47:01.0098006	ckan.exe	19160	Thread Exit		SUCCESS	Thread ID: 2076, User Time: 0.0000000, Kernel Time: 0.0000000
18:47:01.0257472	ckan.exe	19160	QueryNameInformationFile	C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll	SUCCESS	Name: \Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
18:47:01.0257770	ckan.exe	19160	Thread Create		SUCCESS	Thread ID: 7664
18:47:13.0306995	ckan.exe	19160	Thread Exit		SUCCESS	Thread ID: 7664, User Time: 0.0000000, Kernel Time: 0.0000000
18:47:13.0626850	ckan.exe	19160	QueryNameInformationFile	C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll	SUCCESS	Name: \Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
18:47:13.0627187	ckan.exe	19160	Thread Create		SUCCESS	Thread ID: 1388
18:47:24.0770497	ckan.exe	19160	Thread Exit		SUCCESS	Thread ID: 1388, User Time: 0.0000000, Kernel Time: 0.0000000
18:47:24.0927669	ckan.exe	19160	QueryNameInformationFile	C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll	SUCCESS	Name: \Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
18:47:24.0927987	ckan.exe	19160	Thread Create		SUCCESS	Thread ID: 8724
18:47:37.1050663	ckan.exe	19160	Thread Exit		SUCCESS	Thread ID: 8724, User Time: 0.0000000, Kernel Time: 0.0000000
18:47:37.1510396	ckan.exe	19160	QueryNameInformationFile	C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll	SUCCESS	Name: \Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
18:47:37.1510616	ckan.exe	19160	Thread Create		SUCCESS	Thread ID: 4504
18:47:49.1543774	ckan.exe	19160	Thread Exit		SUCCESS	Thread ID: 4504, User Time: 0.0000000, Kernel Time: 0.0000000
18:47:49.1716402	ckan.exe	19160	QueryNameInformationFile	C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll	SUCCESS	Name: \Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
18:47:49.1716659	ckan.exe	19160	Thread Create		SUCCESS	Thread ID: 19696
18:48:01.6845376	ckan.exe	19160	Thread Exit		SUCCESS	Thread ID: 19696, User Time: 0.0000000, Kernel Time: 0.0000000
18:48:01.6994437	ckan.exe	19160	QueryNameInformationFile	C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll	SUCCESS	Name: \Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
18:48:01.6994753	ckan.exe	19160	Thread Create		SUCCESS	Thread ID: 6624
18:48:03.9150044	ckan.exe	19160	ReadFile	C:\Windows\assembly\NativeImages_v4.0.30319_64\System\ad022fbac6ab2d67af1c6482eeb14147\System.ni.dll	SUCCESS	Offset: 3,971,072, Length: 4,096, I/O Flags: Non-cached, Paging I/O, Synchronous Paging I/O, Priority: Normal
18:48:03.9152287	ckan.exe	19160	ReadFile	C:\Windows\assembly\NativeImages_v4.0.30319_64\System\ad022fbac6ab2d67af1c6482eeb14147\System.ni.dll	SUCCESS	Offset: 4,130,816, Length: 24,576, I/O Flags: Non-cached, Paging I/O, Synchronous Paging I/O, Priority: Normal
18:48:03.9154493	ckan.exe	19160	ReadFile	C:\Windows\assembly\NativeImages_v4.0.30319_64\System\ad022fbac6ab2d67af1c6482eeb14147\System.ni.dll	SUCCESS	Offset: 10,917,888, Length: 28,672, I/O Flags: Non-cached, Paging I/O, Synchronous Paging I/O, Priority: Normal
18:48:03.9156620	ckan.exe	19160	ReadFile	C:\Windows\assembly\NativeImages_v4.0.30319_64\System\ad022fbac6ab2d67af1c6482eeb14147\System.ni.dll	SUCCESS	Offset: 4,577,280, Length: 32,768, I/O Flags: Non-cached, Paging I/O, Synchronous Paging I/O, Priority: Normal
18:48:13.2007599	ckan.exe	19160	Thread Exit		SUCCESS	Thread ID: 6624, User Time: 0.0000000, Kernel Time: 0.0000000
18:48:13.2153792	ckan.exe	19160	QueryNameInformationFile	C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll	SUCCESS	Name: \Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
18:48:13.2154067	ckan.exe	19160	Thread Create		SUCCESS	Thread ID: 7584
18:48:22.7307584	ckan.exe	19160	Thread Exit		SUCCESS	Thread ID: 7584, User Time: 0.0000000, Kernel Time: 0.0000000
18:48:41.0674104	ckan.exe	19160	Thread Exit		SUCCESS	Thread ID: 19396, User Time: 0.0468750, Kernel Time: 0.0000000
18:48:41.0740518	ckan.exe	19160	ReadFile	C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Windows.Forms\29542c9ae08fb154b57032fa97975aaa\System.Windows.Forms.ni.dll	SUCCESS	Offset: 3,580,416, Length: 16,384, I/O Flags: Non-cached, Paging I/O, Synchronous Paging I/O, Priority: Normal
18:48:41.0754591	ckan.exe	19160	ReadFile	C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Windows.Forms\29542c9ae08fb154b57032fa97975aaa\System.Windows.Forms.ni.dll	SUCCESS	Offset: 3,789,312, Length: 32,768, I/O Flags: Non-cached, Paging I/O, Synchronous Paging I/O, Priority: Normal
18:48:41.0756772	ckan.exe	19160	ReadFile	C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Windows.Forms\29542c9ae08fb154b57032fa97975aaa\System.Windows.Forms.ni.dll	SUCCESS	Offset: 15,081,984, Length: 32,768, I/O Flags: Non-cached, Paging I/O, Synchronous Paging I/O, Priority: Normal
18:48:41.0759239	ckan.exe	19160	ReadFile	C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Windows.Forms\29542c9ae08fb154b57032fa97975aaa\System.Windows.Forms.ni.dll	SUCCESS	Offset: 3,891,712, Length: 32,768, I/O Flags: Non-cached, Paging I/O, Synchronous Paging I/O, Priority: Normal
18:48:41.0761499	ckan.exe	19160	ReadFile	C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Windows.Forms\29542c9ae08fb154b57032fa97975aaa\System.Windows.Forms.ni.dll	SUCCESS	Offset: 3,924,480, Length: 20,480, I/O Flags: Non-cached, Paging I/O, Synchronous Paging I/O, Priority: Normal
18:48:41.0763252	ckan.exe	19160	ReadFile	C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Windows.Forms\29542c9ae08fb154b57032fa97975aaa\System.Windows.Forms.ni.dll	SUCCESS	Offset: 3,469,824, Length: 12,288, I/O Flags: Non-cached, Paging I/O, Synchronous Paging I/O, Priority: Normal
18:48:41.0764700	ckan.exe	19160	ReadFile	C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Windows.Forms\29542c9ae08fb154b57032fa97975aaa\System.Windows.Forms.ni.dll	SUCCESS	Offset: 3,428,864, Length: 4,096, I/O Flags: Non-cached, Paging I/O, Synchronous Paging I/O, Priority: Normal
18:48:41.0767129	ckan.exe	19160	RegQueryKey	HKLM	SUCCESS	Query: HandleTags, HandleTags: 0x0
18:48:41.0767557	ckan.exe	19160	RegOpenKey	HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer	SUCCESS	Desired Access: Query Value
18:48:41.0767914	ckan.exe	19160	RegQueryValue	HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer\TurnOffSPIAnimations	NAME NOT FOUND	Length: 16
18:48:41.0768176	ckan.exe	19160	RegCloseKey	HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer	SUCCESS	
18:48:41.0768388	ckan.exe	19160	RegQueryKey	HKCU	SUCCESS	Query: HandleTags, HandleTags: 0x0
18:48:41.0768569	ckan.exe	19160	RegOpenKey	HKCU\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer	NAME NOT FOUND	Desired Access: Query Value
18:48:41.0847250	ckan.exe	19160	ReadFile	C:\Windows\assembly\NativeImages_v4.0.30319_64\System\ad022fbac6ab2d67af1c6482eeb14147\System.ni.dll	SUCCESS	Offset: 4,032,512, Length: 32,768, I/O Flags: Non-cached, Paging I/O, Synchronous Paging I/O, Priority: Normal
18:48:41.0850836	ckan.exe	19160	ReadFile	C:\Windows\assembly\NativeImages_v4.0.30319_64\System\ad022fbac6ab2d67af1c6482eeb14147\System.ni.dll	SUCCESS	Offset: 4,012,032, Length: 16,384, I/O Flags: Non-cached, Paging I/O, Synchronous Paging I/O, Priority: Normal
18:48:41.0855208	ckan.exe	19160	ReadFile	C:\Windows\assembly\NativeImages_v4.0.30319_64\System\ad022fbac6ab2d67af1c6482eeb14147\System.ni.dll	SUCCESS	Offset: 10,627,072, Length: 32,768, I/O Flags: Non-cached, Paging I/O, Synchronous Paging I/O, Priority: Normal
18:48:41.0857647	ckan.exe	19160	ReadFile	C:\Windows\assembly\NativeImages_v4.0.30319_64\System\ad022fbac6ab2d67af1c6482eeb14147\System.ni.dll	SUCCESS	Offset: 10,618,880, Length: 8,192, I/O Flags: Non-cached, Paging I/O, Synchronous Paging I/O, Priority: Normal

**Comment by HebaruSan** [comment] 2021-05-24 18:18
Thanks for the report. 
Duplicate of #3379.

**Closed by HebaruSan** 2021-05-24 18:18 UTC
