### ISSUE TITLE
Sorting by download-size doesn't sort by download-size

### ISSUE THREAD

**Issue by sundhaug92** [KSP-CKAN/CKAN#2368] opened 2018-03-17 15:49 UTC
Background
----------

**CKAN Version:** 1.24.0

**KSP Version:** 1.3.1

**Operating System:** Windows 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?:** AFAIK no

Problem
-------

**What steps did you take in CKAN?**
Pressed the "Download"-button

**What did you expect to happen?**
Mods to be sorted by amount downloaded

**What happened instead?**
Mods not sorted by amount downloaded

**Screenshots:**
![image](https://user-images.githubusercontent.com/519283/37557318-1c748302-2a03-11e8-88e7-ce4e0419d87d.png)

**Comment by HebaruSan** [comment] 2018-03-17 16:57
Thanks for the report. We first saw this mentioned on the forum and fixed it in #2311, so it's not a duplicate of another issue, but we did do the development already. Closing as fixed...

**Closed by HebaruSan** 2018-03-17 16:57 UTC
