### ISSUE TITLE
Fatal .Net 4.0 issue on v1.6.21

### ISSUE THREAD

**Issue by RichardLake** [KSP-CKAN/CKAN#1074] opened 2015-06-05 13:27 UTC
@pjf 
Due to our use of ILRepack v1.6.21 has a fatal issue on windows machines without .net 4.5 installed. This is due being unable to locate the correct assemblies as they moved between 4.0 and 4.5. The [TypeForwardedTo] system to migrate this doesn't work with our build system. 
* Stop using ILRepack or equivalents. 
* Rewrite away from await/async to the older .net 4 system. 
* Build on a .Net 4.0 windows system
* Have people upgrade to .net 4.5. 

Of these I prefer the last. Adding the "--targetplatform:v4" option to ILRepack generates a exe which will popup a message on start on .net 4.0 which states the need for a upgrade. As it is quite late, and due to lack of testing on mono 3.2.8, I decided against making a new release. A note has been added to the issue and it has been flagged as a pre-release.

**Comment by erendrake** [comment] 2015-06-05 20:53
I would prefer having people upgrade, 4.5. it has a ton of cool features and has been available for years.

**Comment by pjf** [comment] 2015-06-06 02:31
Potentially relevant issues:

* gluck/il-repack#58
* gluck/il-repack#99 (apparently duplicate of 58 above)

**Comment by pjf** [comment] 2015-06-06 02:33
Potentially relevant StackOverflow discussion:

* https://stackoverflow.com/questions/13748055/could-not-load-type-system-runtime-compilerservices-extensionattribute-from-as

**Comment by pjf** [comment] 2015-06-06 03:40
From my discussions with @RichardLake on IRC, it sounds like async/await are .NET 4.5 only features. If that's the case, .NET 4.0 users won't be able to use them *anyway*.

In which case the real question is how many users are on .NET 4.0? Richard mentioned Vista SP1, but that's a tiny (less than 2%) of market share, and like XP users they can use mono to run the code if required.

I'm totally fine requiring users be on .NET 4.5 if it's widely distributed.

If we have figures on what comes default with Windows 7/8/10, that would be even better.

**Comment by pjf** [comment] 2015-06-06 03:43
Windows 8 and above has 4.5 installed. Windows 7 seems to have 3.5SP1, so Windows users will have always had to install .NET *anyway* to use our software.

**Comment by pjf** [comment] 2015-06-07 03:03
From our IRC discussions, my understanding is we'l be requiring new users to be using mono or .NET 4.5.  The latest release now has that mentioned in the release notes, and after almost 4k downloads we're not seeing too many complaints. :)

**Closed** 2015-06-08 05:13 UTC
Labels: bug, build, policy, pull request, Windows
