### ISSUE TITLE
Tweakable Everything

### ISSUE THREAD

**Issue by pikachu01** [KSP-CKAN/CKAN#1531] opened 2015-12-07 11:32 UTC
Was Tweakable Everything removed from CKAN? I can't seem to find it though I remember installing it from CKAN previously.

**Comment by plague006** [comment] 2015-12-07 14:35
`TweakableEverything` was not removed from CKAN. You currently can't find it in the mods list due to its dependency on `EVAManager` which hasn't been updated (or confirmed working for) 1.0.4. This is a bug and was previously reported in https://github.com/KSP-CKAN/CKAN/issues/1529. Sorry for the inconvenience and/or confusion this may have caused. If the un-updated mod I mentioned is compatible with 1.0.5, re-open this issue and let us know, this will result in a faster fix for this particular mod.

Thanks for bringing us this report, but closing this for now as it's a duplicate of #1529.

**Closed by plague006** 2015-12-07 14:35 UTC
