### ISSUE TITLE
Unhandled Exception - Couldn't find rest of path file

### ISSUE THREAD

**Issue by CYT-SubZer0** [KSP-CKAN/CKAN#2461] opened 2018-06-13 14:12 UTC
Background
----------

**CKAN Version:** 
1.25.1

**KSP Version:** 
1.3.1

**Operating System:** 
Win10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
I tried to install Dark Multiplayer manually but deleted it shortly after. Mods and installing worked fine up until now.

Problem
Unhandled Exception... Could not find a part of the path 'C:\Users\[my name]\AppData\Local\Temp\CdFileMgr\fcbee72f-99ce-46.json'

**What steps did you take in CKAN?**
Tried to install a few mods, and it failed.

**What did you expect to happen?**
I would've installed the mods and kept installing new ones and testing the game for a new modpack series.

**What happened instead?**
Got an error.

**Screenshots:**

None (Don't want to expose full name)

**CKAN error codes (if applicable):** 
************** Exception Text **************
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\[my name]\AppData\Local\Temp\CdFileMgr\fcbee72f-99ce-46.json'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at ChinhDo.Transactions.WriteAllTextOperation.Execute()
   at ChinhDo.Transactions.TxFileManager.EnlistOperation(IRollbackableOperation operation)
   at CKAN.RegistryManager.Save(Boolean enforce_consistency)
   at CKAN.ModuleInstaller.InstallList(ICollection`1 modules, RelationshipResolverOptions options, IDownloader downloader)
   at CKAN.Main.InstallMods(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)

**Comment by HebaruSan** [comment] 2018-06-13 14:17
Looks like a duplicate of #2342. Same error, same stack trace.
If you are able to figure out why your system is either deleting or preventing the creation of that CdFileMgr folder, please post a reply on that issue.

**Closed by HebaruSan** 2018-06-13 14:17 UTC
