### ISSUE TITLE
Select KSP Install Problem on Mac OS X

### ISSUE THREAD

**Issue by aallan** [KSP-CKAN/CKAN#1276] opened 2015-07-12 17:42 UTC
Attempting to do "File > Select KSP Install..." and then hitting the "Add New" gives the following popup,

![screenshot 2015-07-12 18 38 21](https://cloud.githubusercontent.com/assets/53625/8639035/57ff9868-28c5-11e5-9a89-f87a7ba62825.png)

clicking on "My Computer" shows a directory called "Personal" which contains the contents of my user account (i.e. /Users/<username>) rather than the top level root directory of the machine. 

![screenshot 2015-07-12 18 41 13](https://cloud.githubusercontent.com/assets/53625/8639040/96a1e1a2-28c5-11e5-93c0-2f5fa2550f67.png)

There's therefore no way to navigate to the /Applications directory which contains my KSP_osx directory to tell CKAN where my KSP install is located..? Or am I being incredibly stupid here?

**Comment by plague006** [comment] 2015-07-12 18:02
As a workaround for the time being, you can try adding an install via the command line. `CKAN KSP` to get the help screen for it

**Comment by LuciusMartius** [comment] 2016-05-12 12:37
I can confirm an additional problem under Linux where I only have the filesystems mounted on top of "/" available as "HDDs" but not the root filesystem itself. My steam games are under /opt/steam which resides in the root filesystem.

Adding via command line naturally works for the time being.

**Comment by politas** [comment] 2016-05-13 01:08
On my Linux, the root is one of those HDDs, so /opt is available that way:
![linux browse for folder](https://cloud.githubusercontent.com/assets/2109967/15235000/f96714c6-18fa-11e6-952d-55ec252bf601.png)

**Comment by politas** [comment] 2016-05-13 01:12
@aallan, do you have any non-default security options enabled that may be preventing mono from seeing your full filesystem? That kind of looks like some kind of chroot setup (he says, knowing of such things only vaguely).

**Comment by LuciusMartius** [comment] 2016-05-13 12:21
@politas For me it is probably because of my root filesystem being ZFS as zfs does not live on a single "hdd". I think I had a similar issue with BTRFS on my Notebook, but I currently don't have it here to test.

This is clearly a bug with the mono file picker, not CKAN. The filepicker should make all mountpoints (like they are listed with the "mount" command) available, regardless whether they were mounted as "real" devices or subvolumes of larger filesystems spanning multiple devices.

**Comment by politas** [comment] 2016-05-13 22:36
Or just the entire filesystem as the OS sees it, starting at "/"

**Comment by HebaruSan** [comment] 2018-03-13 17:34
See #2347, this is a bug in Mono, which tries to use a Linux-specific `/proc/` file to find mounted devices.
Closing this issue and keeping the other one open since it has more useful info.

**Closed by HebaruSan** 2018-03-13 17:34 UTC
Labels: Bug, GUI, OS X, ★★☆
