### ISSUE TITLE
[Bug] Clicking on anything locks the whole program

### ISSUE THREAD

**Issue by charliesoap4** [KSP-CKAN/CKAN#3737] opened 2022-12-07 05:17 UTC
Background
----------
* Operating System: Windows 11
* CKAN Version: v1.31.2
* KSP Version: 1.12.3.3173

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
The program loads up correctly, and loads my installed mods.  However, if I click on a mod, or click on any button on the top, the program locks up solid and hangs.  I have to Force close it from Task Manager

**Steps to reproduce**
Try to do anything once it's loaded

**Expected behavior**
Anything but crash

**Screenshots (if applicable)**
Nothing to see

**CKAN error code (if applicable):**
None
```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment] 2022-12-07 05:31
Thanks, we just finished fixing this, you can try the latest dev build if you'd like to test:

- https://ksp-ckan.s3-us-west-2.amazonaws.com/ckan.exe

**Comment by HebaruSan** [comment] 2022-12-07 05:31
Duplicate of #3707

**Closed by HebaruSan** 2022-12-07 05:31 UTC
