### ISSUE TITLE
[Bug] the warning of DLC is unstable 

### ISSUE THREAD

**Issue by StevenLi-phoenix** [KSP-CKAN/CKAN#3306] opened 2021-02-25 08:34 UTC
Background
----------
* Operating System: windows 7
* CKAN Version: v1.29.2
* KSP Version: 1.11.1.3066

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
NO

Mods:(maybe no uses)
Animated Decouplers (AnimatedDecouplers v1.4.2.2)
AtmosphereAutopilot (Fly-By-Wire) (AtmosphereAutopilot v1.5.16)
BDArmory for Runway Project (BDArmoryForRunwayProject 1.4.1.0)
BreakingGround-DLC (BreakingGround-DLC (unmanaged))
Corvus CF (Corvus125mTwoKerbalPod 2:1.3.6)
Firespitter (Firespitter v7.17)
Firespitter Core (FirespitterCore v7.17)
Firespitter Resources config (FirespitterResourcesConfig v7.17)
Kerbal Reusability Expansion (SpaceXLegs 2.9.1)
Making History (MakingHistory-DLC 1.11.0)
MechJeb 2 (MechJeb2 2.12.0.0)
Module Manager (ModuleManager 4.1.4)
Physics Range Extender  (PhysicsRangeExtender 1.20.0)
Retrofuture Space Plane Parts Modernized (RetroFuture 2:0.3.0.2)
TweakScale - Rescale Everything! (TweakScale v2.4.4.5)

Problem
-------
**Describe the bug**
When starting the KSP, it notice that it didn't fit 'MakingHistory-DLC 1.11.0 (KSP 1.11.0)'
It's a part of game,DLC, and should not be unstable.

**Steps to reproduce**
* Go to CKAN
* Click on 'Start KSP'
* See error

**Expected behavior**
No notice of the unstable 'MakingHistory-DLC 1.11.0 (KSP 1.11.0)'

**Screenshots (if applicable)**
<img width="325" alt="WeChat Screenshot_20210225163229" src="https://user-images.githubusercontent.com/75846119/109125469-11ed8080-7787-11eb-9650-d9e779b21c48.png">

**CKAN error code (if applicable):**

```
None, warnning
```

**Comment by DasSkelett** [comment] 2021-02-25 10:35
Duplicate of #3302

**Closed by DasSkelett** 2021-02-25 10:35 UTC
