### ISSUE TITLE
[Bug]: CKAN closes when starting says I am trying to run as Admin

### ISSUE THREAD

**Issue by Armour9** [KSP-CKAN/CKAN#3985] opened 2023-12-31 02:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Win10

### CKAN Version

v1.34.2 

### Games

KSP 2

### Game Version

KSP2 Latest

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

No

### Describe the bug

I have uninstalled CKAN and have reinstalled it and I am getting the immediate popup and CKAN closes. When I did a quick screenshot is says because I am trying to run as Admin.  I have ensured "run as admin" is unchecked.  Now CKAN does not work at all.  

### Steps to reproduce

Click on Ckan

**Comment by HebaruSan** [comment] 2023-12-31 02:31
Duplicate of #3956

**Closed by HebaruSan** 2023-12-31 02:31 UTC

**Comment by Armour9** [comment] 2023-12-31 02:55
Is it the same?  I sounds like that other bug was resolved.  If it was resolved, why it is still occuring on a new build?

**Comment by HebaruSan** [comment] 2023-12-31 02:56
It's not a bug, and "a new build" is not applicable here.

**Comment by Armour9** [comment] 2023-12-31 03:04
Fair enough, however, can you give some insight or guidance on how to prevent that from happening so CKAN can run?  Thanks.

**Comment by HebaruSan** [comment] 2023-12-31 03:15
You could try the `--asroot` parameter as the error message says.

**Comment by Armour9** [comment] 2023-12-31 05:31
I honestly have no idea what you mean by "try the --asroot parameter".  I have googled it and nothing relevant came up.  I am sure it is second nature to people that know about coding, but to average joes like me that click on icons it is literally like you are telling me something in German and I don't have Google Translate available.  

How do I "try the --asroot parameter"?  I really do appreciate the help.  Thanks.

**Comment by Muleo-MIR** [comment] 2024-03-03 11:52
> How do I "try the --asroot parameter"? I really do appreciate the help. Thanks.

I've encountered the same issue, I'm on Windows 7. Try running ckan.exe using the Windows command prompt - you will find many guides online on how to do this. To avoid the same error, include '--asroot' at the end of the command, like this:

`start ckan.exe --asroot`
