### ISSUE TITLE
Linux gui widgets sized wrong

### ISSUE THREAD

**Issue by CRHough** [KSP-CKAN/CKAN#1044] opened 2015-05-31 12:39 UTC
Tested with both Chiral Abnormality and Oberon.

Gentoo Linux 3.19.2
Mono 3.2.8

Console output:

```
exception inside UnhandledException handler: Cannot call Invoke or BeginInvoke on a control until the window handle is created

exception inside UnhandledException handler: Cannot call Invoke or BeginInvoke on a control until the window handle is created

exception inside UnhandledException handler: Cannot call Invoke or BeginInvoke on a control until the window handle is created

exception inside UnhandledException handler: Cannot call Invoke or BeginInvoke on a control until the window handle is created

exception inside UnhandledException handler: Cannot call Invoke or BeginInvoke on a control until the window handle is created

exception inside UnhandledException handler: Cannot call Invoke or BeginInvoke on a control until the window handle is created

exception inside UnhandledException handler: Cannot call Invoke or BeginInvoke on a control until the window handle is created

exception inside UnhandledException handler: Cannot call Invoke or BeginInvoke on a control until the window handle is created

exception inside UnhandledException handler: Cannot call Invoke or BeginInvoke on a control until the window handle is created

exception inside UnhandledException handler: Cannot call Invoke or BeginInvoke on a control until the window handle is created

exception inside UnhandledException handler: Cannot call Invoke or BeginInvoke on a control until the window handle is created

exception inside UnhandledException handler: Cannot call Invoke or BeginInvoke on a control until the window handle is created
```

Notice the menu has only two characters. The other two menu buttons appear when moused over. Each menu item has only one character. The menu dialogs have all the widgets smushed to one side or the other, screenshots on request.
![ckan_managemods](https://cloud.githubusercontent.com/assets/1259012/7901937/bf0fa6fc-075e-11e5-9e5f-e4d8e6ead416.png)

Information pane exists and can be resized, as can columns
![ckan_managepane](https://cloud.githubusercontent.com/assets/1259012/7901951/3457ca20-075f-11e5-8032-264ddb5e911c.png)

![ckan_changeset](https://cloud.githubusercontent.com/assets/1259012/7901938/c38e10b0-075e-11e5-823b-4ba225fd7c84.png)

**Comment by pjf** [comment] 2015-05-31 13:19
@houghcr : This is super-weird! Just to confirm, it happens with *both* v1.16.18 and v1.16.19? Did it have the same troubles with v1.16.17? (If we can find an example where it *was* working correctly, we can help narrow down a change that induced it.)

**Comment by pjf** [comment] 2015-05-31 13:22
I've got a similar setup, but *can't* reproduce this:

```
$ mono --version
Mono JIT compiler version 3.2.8 (Debian 3.2.8+dfsg-4ubuntu1.1)

$ ckan version
You are using CKAN version v1.6.19-0-g5686c90 (beta)
```

I get the `Cannot call Invoke or BeginInvoke on a control until the window handle is created` messages, but only when closing the client not opening it. (I'm on Debian 14.04)

**Comment by Postremus** [comment] 2015-05-31 13:25
Ubuntu 14.04, ckan 1.6.18, gui looks mostly ok to me

----- Ursprüngliche Nachricht -----
Von: "Paul Fenwick" <notifications@github.com>
Gesendet: ‎31.‎05.‎2015 15:22
An: "KSP-CKAN/CKAN" <CKAN@noreply.github.com>
Betreff: Re: [CKAN] Linux gui widgets sized wrong (#1044)

I've got a similar setup, but can't reproduce this:
$ mono --version
Mono JIT compiler version 3.2.8 (Debian 3.2.8+dfsg-4ubuntu1.1)

$ ckan version
You are using CKAN version v1.6.19-0-g5686c90 (beta)
I get the Cannot call Invoke or BeginInvoke on a control until the window handle is created messages, but only when closing the client not opening it. (I'm on Debian 14.04)

**Comment by houghcr** [comment] 2015-05-31 13:26
I just tried 1.16.17, 1.16.16, and 1.16.15. All the same.

**Comment by Dazpoet** [comment] 2015-05-31 14:17
Have you attempted the nuclear option of removing the entire CKAN folder from the KSP root directory and seeing it that solves it? I'm 99% sure nothing in there should lead to this happening nor even has anything to do with these errors but it at least removes the possibility.

**Comment by houghcr** [comment] 2015-05-31 19:24
I hadn't before as I just discovered this tool yesterday and this happened on initial use. For completeness I did just now remove it and no change.

**Comment by houghcr** [comment] 2015-06-01 02:09
I don't know if this helps at all but I just noticed I'm intermittently getting the message "Could not set X locale modifiers" when launching CKAN. Maybe 1 time in 10 or 20. I know my locale is set right.

**Comment by pjf** [comment] 2015-06-26 04:35
Also reported in v1.8.4 by @triffid in #1188. :(

Upping the priority on this and popping it in a more visible milestone.

**Comment by houghcr** [comment] 2015-09-06 22:46
Just tried v1.14.0-0-g4242285 (beta) after not having touched either KSP or CKAN for a while and the columns start expanded and nicely sized. The menu and button bar text is still the same as the above screenshots and the buttons are all still missing but something changed.

**Comment by HebaruSan** [comment] 2020-05-16 20:04
Looks like an old Mono bug. If there was a spot where CKAN was misusing Invoke, I think it's fixed now.

**Closed by HebaruSan** 2020-05-16 20:04 UTC
Labels: Bug, GUI, Linux, ★★☆
