### ISSUE TITLE
Can't "forget" an install that has been removed on disk

### ISSUE THREAD

**Issue by lamont-granquist** [KSP-CKAN/CKAN#1836] opened 2016-07-23 17:20 UTC
**CKAN Version:** 

v1.18.1-0-g0d2c4f0

**Operating System:** 

MacOS 10.11.4

**The issue you are experiencing:** 
**How to recreate this issue:** 

```
% ckan ksp forget rss133
194 [1] WARN CKAN.KSPManager (null) - rss at /Users/lamont/ksp_rss is not a vaild install
204 [1] WARN CKAN.KSPManager (null) - rss133 at /Users/lamont/ksp_rss_1.3.3 is not a vaild install
Couldn't find install with name "rss133", aborting..
```

ckan first prunes out all the invalid installs, then when you try to 'forget' the install it can't find it in its list to remove...

**Comment by Dazpoet** [comment] 2016-10-18 16:08
I had this issue on Windows and managed to solve it, not that it makes you happier but I thought I should share my solution incase someone else stumbles over this just like I did.

I used regedit to remove the KSPInstanceName keys under HKEY_CURRENT_USER/Software/CKAN and then changed the KSPInstanceCount to 1.

**Comment by juleskers** [comment] 2017-01-02 11:00
likely duplicate of https://github.com/KSP-CKAN/CKAN/issues/896

**Comment by politas** [comment] 2017-01-03 03:55
If you add a new install, the missing ones will be removed, though See #1859

**Closed** 2017-12-29 07:01 UTC
Labels: Bug, ckan.dll, ★★☆
