### ISSUE TITLE
Crashs upon trying to change near anything

### ISSUE THREAD

**Issue by Ignorantsiren** [KSP-CKAN/CKAN#3715] opened 2022-11-20 00:23 UTC
Background
----------
* Operating System: Windows 10
* CKAN Version: 1.32.2
* KSP Version: 1.12.4

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
**Describe the bug**
It will crash if i try to uncheck/check a mod as if i was trying to add it. Cant acess settings without it crashing. Crashes if i attempt to apply changes aswell.

**Steps to reproduce**
* Go to... Ckan
* Click on... Settings, Checkmark or open box, or apply changes. 
* See error

**Expected behavior**
It will crash upon doing any of those above within a few seconds, doesnt get to do anything.

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment] 2022-11-20 00:27
Thanks, we just finished fixing this, you can try the latest dev build if you'd like to test:

- https://ksp-ckan.s3-us-west-2.amazonaws.com/ckan.exe

**Comment by HebaruSan** [comment] 2022-11-20 00:27
Duplicate of #3707

**Closed by HebaruSan** 2022-11-20 00:27 UTC

**Comment by Ignorantsiren** [comment] 2022-11-20 00:28
thanks so much, sorry i didnt realise that there was one already open about this same thing thanks for the help
