### ISSUE TITLE
Latest updated mods / New for this KSP-version

### ISSUE THREAD

**Issue by ErinaceusLinnaeus** [KSP-CKAN/CKAN#1960] opened 2016-12-17 10:15 UTC
I really like the "New in repository" Filter.
Very helpful yould be a new filter under which the latest updated mods are listed.

Because every time a new KSP version drops, I would like to know when my favourite mods are ready and I can let steam auto-update.

**Comment by politas** [comment] 2016-12-17 21:52
If you are stopping Steam from auto-updating, you can use the "Installed" filter to see the Max KSP version of all your current mods. We don't keep any information about when mods are updated, because we recreate the metadata for all the current mods every three hours. It's not impossible to add, but it involves some major code changes.

**Comment by HebaruSan** [comment] 2018-08-08 19:38
Duplicate of #1923; both are asking for "New in repository" to also show new compatible updates of existing mods. Let's merge these over there.

**Closed by HebaruSan** 2018-08-08 19:38 UTC
Labels: Enhancement
