### ISSUE TITLE
[Bug]: ckan.exe hangs during installation.

### ISSUE THREAD

**Issue by AdmerW** [KSP-CKAN/CKAN#3845] opened 2023-05-28 10:28 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows 10

### CKAN Version

v1.32.0 (from site)

### Game Version

1.12.3.3173

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

No

### Describe the bug

The first time you run ckan.exe after downloading, it tries to download the file at the address "https://github.com/KSP-CKAN/CKAN-meta/archive/master.tar.gz", but when I go to this address, I get an error on the site, because this address (more precisely, the file) no longer exists. Because of what ckan.exe freezes.

![321231231](https://github.com/KSP-CKAN/CKAN/assets/134841894/079b3693-36d6-4dec-85d1-f6789c0a4b93)

### Steps to reproduce

Go to run ckan.exe
Wait to download "https://github.com/KSP-CKAN/CKAN-meta/archive/master.tar.gz"
Error (not responding)

### Relevant log output

_No have_

**Comment by HebaruSan** [comment] 2023-05-28 15:54
Duplicate of #3844

**Closed by HebaruSan** 2023-05-28 15:54 UTC
