### ISSUE TITLE
CKAN 1.25.2 not running on windows 10 (64bit)

### ISSUE THREAD

**Issue by Tabris83** [KSP-CKAN/CKAN#2489] opened 2018-08-07 12:27 UTC
Background
----------

**CKAN Version:** 
1.25.2

**KSP Version:** 
1.45+MH(64bit)

**Operating System:** 
Window 10 Pro(64bit)

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
no.

Problem
-------

**What steps did you take in CKAN?**
attempted to run file.

**What did you expect to happen?**
CKAN to load as it has done for last few years

**What happened instead?**
See screenshot below
See full contents of error message below

**Screenshots:**
![image](https://user-images.githubusercontent.com/8855255/43775649-d1222fea-9a90-11e8-9c79-092563f166bd.png)

**CKAN error codes (if applicable):** 

https://gist.github.com/Tabris83/9caa163e00748f346b0aec7646d6925d

**Comment by Toonu** [comment] 2018-08-07 13:29
Have exact same problem. 
![image](https://user-images.githubusercontent.com/4078304/43778660-92a9558e-9a56-11e8-8526-39178b165bc6.png)

If you need some logs, let me know.

**Comment by HebaruSan** [comment] 2018-08-07 14:51
This is a duplicate of #2481, fixed in #2486.

@Toonu, yours is a duplicate of #2483, fixed in #2482.

**Closed by HebaruSan** 2018-08-07 14:51 UTC
