### ISSUE TITLE
AJE Not Appearing

### ISSUE THREAD

**Issue by Maeyanie** [KSP-CKAN/CKAN#1963] opened 2016-12-22 01:10 UTC
**CKAN Version:** 
Both v1.20.1-0-gd41fe54 and 5ce5a099ed7011200497471d656e5bba3f75bd24

**Operating System:** 
Windows 10 x64

**The issue you are experiencing:** 
The mod "Advanced Jet Engine" isn't currently appearing in the list for me, including in "All" filter mode, despite being in the [repository](https://github.com/KSP-CKAN/CKAN-meta/tree/master/AdvancedJetEngine). Maybe other mods too, that's just the one I happened to notice the NetKAN commit and went looking for it.

**How to recreate this issue:** 
Launch CKAN, Refresh, note the list goes from "Active Ablation" to "Aircraft Carrier Accessories" (in Compatible filter) or "Advanced Fly-By-Wire" to "Advanced SAS For All" (in All filter) with no "Advanced Jet Engine" in between where one would expect to find it.

**CKAN error codes (if applicable):** 
N/A

**Comment by Maeyanie** [comment] 2016-12-22 01:21
I also note that running the following PHP script:
```
$json = json_decode(file_get_contents("registry.json"), true); 
echo count($json["available_modules"]);
```
indicates 1539 modules in the registry, while the "All" filter GUI button thing reports exactly 1500, suggesting that there may be 39 total missing entries.

**Comment by politas** [comment] 2016-12-23 14:19
Duplicate of #1695

**Closed by politas** 2016-12-23 14:19 UTC
