### ISSUE TITLE
Repository Update Failed due to forbidden access

### ISSUE THREAD

**Issue by MattAcker1987** [KSP-CKAN/CKAN#2445] opened 2018-05-15 16:46 UTC
Background
----------

**CKAN Version:** 
1.25.1

**KSP Version:** 
1.4.3

**Operating System:** 
Windows 10
Version 1709
OS Build 16299.431

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
Added Luna  Multiplayer

Problem
-------

**What steps did you take in CKAN?**
Tried to refresh my repository

**What did you expect to happen?**
Repository would have been filled

**What happened instead?**
The update failed

**Screenshots:**

![image](https://user-images.githubusercontent.com/31703142/40071053-a27af20c-5824-11e8-978d-92ce004a7934.png)

**CKAN error codes (if applicable):** 
Complete verbage:

```
Updating repositories...
Failed to download https://github.com/KSP-CKAN/CKAN-meta/archive/master.tar.gz: System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions 192.30.255.112:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at CKAN.Net.Download(String url, String filename, IUser user)
   at CKAN.Repo.UpdateRegistry(Uri repo, KSP ksp, IUser user)
Repository update failed!
```

**Comment by HebaruSan** [comment] 2018-05-15 17:05
Does this happen every time?

Looks like this [might be a problem with Window Firewall or your network hardware](https://social.technet.microsoft.com/Forums/windows/en-US/e0cc1b3e-2c63-451a-abc8-8e1e66a23287/an-attempt-was-made-to-access-a-socket-in-a-way-forbidden-by-its-access-permissions?forum=w7itpronetworking). Can you try the suggestions at that link?

**Comment by MattAcker1987** [comment] 2018-05-15 17:26
Yes this occurs every time.

tried the suggested link and that solved the problem. 

Thanks for your help!

Sent from Mail for Windows 10

**Comment by HebaruSan** [comment] 2018-05-15 17:43
Cool! Closing as confirmed Windows Firewall issue.

**Closed by HebaruSan** 2018-05-15 17:43 UTC
Labels: Network, Windows
