### ISSUE TITLE
Latest release (v1.26.0) launches, but there is no GUI.

### ISSUE THREAD

**Issue by e2cool** [KSP-CKAN/CKAN#2739] opened 2019-04-22 01:17 UTC
Background
----------

**CKAN Version:** v1.26.0

**KSP Version:** 1.7.0

**Operating System:** Win 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** Yes, a few mods (not from CKAN), but I'm sure they have nothing to do with the issue.

Problem
-------

**What steps did you take in CKAN?** Ran the executable.

**What did you expect to happen?** I expected CKAN to run as normal.

**What happened instead?** The command prompt looking thing comes up and I can select my game directory, but after that there is no GUI. I can see in the taskbar that CKAN is open, but there is no window/window preview.

**Screenshots:** Will a video of the issue in question do?
https://youtu.be/P2hmaYQY1gs

**CKAN error codes (if applicable):** N/A

**Comment by HebaruSan** [comment] 2019-04-22 01:19
Looks like a duplicate of #2717. There are workaround instructions on that issue if you're interested.

**Closed by HebaruSan** 2019-04-22 01:19 UTC
Labels: Duplicate

**Comment by e2cool** [comment] 2019-04-22 01:25
> 
> 
> Looks like a duplicate of #2717. There are workaround instructions on that issue if you're interested.

That seems to have been the issue. My apologies for the duplicate issue. My search must not have been thorough enough. Thank you for pointing me in the right direction! Have a good one.
