### ISSUE TITLE
[Bug]: Metapackages cannot be installed using command line.

### ISSUE THREAD

**Issue by heyimastopsign** [KSP-CKAN/CKAN#4175] opened 2024-09-06 08:02 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

MacOS

### CKAN Version

1.34.4

### Games

KSP 1

### Game Version

1.12.5

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

no

### Describe the bug

<img width="1510" alt="Screenshot 2024-09-06 at 6 00 46 PM" src="https://github.com/user-attachments/assets/38f6df2c-8f9d-4dc5-925a-b8f826dd7145">

### Steps to reproduce

run the command detailed on https://github.com/KSP-CKAN/CKAN/wiki/Sharing-a-modlist-%28metapackages%29 and note that it does not work

**Comment by heyimastopsign** [comment] 2024-09-06 08:03
on a related note, there's also an option to export your modlist in the console UI, but no option to import modlists.

**Comment by HebaruSan** [comment] 2024-09-06 14:15
Duplicate of #4108

**Closed by HebaruSan** 2024-09-06 14:15 UTC

**Comment by HebaruSan** [comment] 2024-09-06 14:17
Hi @heyimastopsign, thanks for the report. See #4108 for previous discussion of this issue.
