### ISSUE TITLE
600 kbps to ... 0kbps

### ISSUE THREAD

**Issue by Scientifouc** [KSP-CKAN/CKAN#1714] opened 2016-05-06 13:05 UTC
Hey ! I'm a Mac user ! (OS X El Capitain)

I always have problems during the download of my mods and I don't understand why the connection goes to 600kbps to 0kbps with no reason. My connection works but CKAN says that the connection doesn't work and the download speed fall down !
![capture d ecran 2016-05-06 a 15 04 30](https://cloud.githubusercontent.com/assets/19224796/15073812/eb70de4c-139b-11e6-96ff-a1935df5ca26.png)

**Comment by rsparkyc** [comment] 2016-05-09 02:21
I have a very similar issues.  If I navigate away from the window, it drops down to 1, however if I stay focused in the window, I seem to cap out at around 113 kbps.

**Comment by rsparkyc** [comment] 2016-05-09 02:30
It might be worth noting that the command line version is lightning fast.

**Comment by techman83** [comment] 2016-05-17 02:43
This sounds like a duplicate of #840, it's a known bug in the OSX Winforms + Threading.

**Closed** 2016-08-11 00:00 UTC
Labels: OSX, support
