### ISSUE TITLE
[Bug] Recently-compatible installed mods missing from compatible filter

### ISSUE THREAD

**Issue by skalou** [KSP-CKAN/CKAN#2883] opened 2019-10-07 16:56 UTC
Background
----------
* Operating System: windows 10
* CKAN Version: v1.26.4
* KSP Version: v1.7.3.2594

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
**Describe the bug**

Hello, I'm the owner of 2 mods:

- **Mk1-Cabin-Hatch**
https://forum.kerbalspaceprogram.com/index.php?/topic/151443-1xx-mk1-cabin-hatch-v020-3-november-2016/page/3/

- **Ablative-Airbrake**
https://forum.kerbalspaceprogram.com/index.php?/topic/157353-1xx-ablative-airbrake-v030-7-october-2017/

I installed them a long time ago, and now I can't see them with compatibility filter unless i set it to allow KSP version 1.3, but my MOD.version file on my github page describe it as compatible with KSP 1.7.3 and CKAN see it well (in the Max KSP version collumn)
However the MOD.version file in the GameData/MOD is set to old KSP version, but i update the MOD.version file on my github pages for KSP-AVC.

Uninstalling and reinstalling fixes the problem.

**Steps to reproduce**

1. Open CKAN with KSP 1.3.1 installed when AblativeAirbrake and Mk1CabinHatch were only compatible with KSP 1.3.1 (approx. March 2018 and earlier)
2. Install AblativeAirbrake and Mk1CabinHatch
3. Upgrade KSP to 1.7.3
4. Wait for AblativeAirbrake and Mk1CabinHatch to add support up to KSP 1.7 (approx. May 2019 and later)
5. Settings > Compatible  KSP version > tick only 1.7
6. set filter to "compatible", 
7. search for my mods "Mk1-Cabin-Hatch" or "Ablative-Airbrake", they are not visible
8. Settings > Compatible  KSP version > tick 1.3
9. my mods are now visible

CKAN folder generated by the above steps for testing:
- [CKAN.zip](https://github.com/KSP-CKAN/CKAN/files/3698848/CKAN.zip)

**Comment by HebaruSan** [comment] 2019-10-07 17:16
When did you last refresh the registry? Prior to May 4, both of these were only marked as compatible up to 1.6.99. If you haven't done a refresh since then, then you'd be using old data, which would explain this.

**Comment by skalou** [comment] 2019-10-07 17:45
The registry update when launching CKAN? ( i restarted it maybe 20x, with windows restart too, during maybe 2 month.
Or how to refresh the registry please ? Or totally remove CKAN and reinstall it?
 i tried to delete the download cache in Settings > CKAN settings > Purge > purge All
but i still don't see my mod with the filter (compatible)

![image](https://user-images.githubusercontent.com/10555351/66335213-d0aec380-e93a-11e9-8b45-3b5a10a85a4e.png)

 thank you HebaruSan

**Comment by HebaruSan** [comment] 2019-10-07 17:46
Click the refresh button:  ![image](https://user-images.githubusercontent.com/1559108/66335341-7c86ed80-e900-11e9-8bb2-c5bd0af2e270.png)

**Comment by skalou** [comment] 2019-10-07 18:10
If i delete the CKAN folder inside my Kerbal Space Program folder install, it works as it should.
So it's OK for me.


 i saved the old CKAN folder ( with GUIConfig.xml files etc... inside), do you want it to check for a bug ?
here it is: [CKAN.zip](https://github.com/KSP-CKAN/CKAN/files/3698848/CKAN.zip)

thank you for your help ( it's better a bug just for myself than for all of the users)

**Comment by HebaruSan** [comment] 2019-10-09 14:35
OK, I'm able to reproduce the problem using your files, but a crucial piece of information was missing:
Both mods are already installed! That should be in the steps to reproduce; I'll add it now.

**Comment by HebaruSan** [comment] 2019-10-09 14:43
... aaand that makes sense. The `InstalledModule` still has the old compatibility info from when it was installed. So either we need to update the installed module, or the filter needs to look at the available module instead.

```json
"AblativeAirbrake": {
	"install_time": "2018-03-19T19:49:28.4893785+01:00",
	"source_module": {
		"abstract": "A derived stockalike airbrake coated with ablator. ",
		"author": [
			"Skalou2"
		],
		"depends": [
			{
				"name": "ModuleManager"
			}
		],
		"download": "https://spacedock.info/mod/1245/Ablative-Airbrake/download/0.3.0",
		"download_size": 39032,
		"download_hash": {
			"sha1": "FA445D3E2FBB8BFE7F2C18C44759C1CFB500DC82",
			"sha256": "CFFE8DDEB606BE2C0C68C9E08B6714A33A4599B0EDDEF40CE8BFE78E23290F27"
		},
		"identifier": "AblativeAirbrake",
		"ksp_version": "1.3.1",
		"license": [
			"GPL-3.0"
		],
		"name": "Ablative-Airbrake",
		"resources": {
			"homepage": "http://forum.kerbalspaceprogram.com/index.php?/topic/157353-122-ablative-airbrake-v010-5-march-2017/",
			"spacedock": "https://spacedock.info/mod/1245/Ablative-Airbrake"
		},
		"version": "0.3.0",
		"install": [
			{
				"find": "Ablative-Airbrake"
			}
		],
		"spec_version": "v1.4"
	},
```

**Comment by skalou** [comment] 2019-10-10 16:52
i'm happy to contribute for this great add-on, thank you for your help anyway.
 tell me if u need something more from me, test etc...

**Comment by HebaruSan** [comment] 2019-10-10 17:08
Thanks @skalou ! Saving your CKAN folder for inspection was a master stroke, I think we have this one figured out now thanks to that.

**Closed** 2019-10-19 17:19 UTC
Labels: Bug, GUI
