### ISSUE TITLE
Exception thrown when double-clicking on ModList_Cell, while mod dll has been autodetected

### ISSUE THREAD

**Issue by nimobeeren** [KSP-CKAN/CKAN#1301] opened 2015-07-16 15:53 UTC
When I manually install a mod by copying its folder to KSP's GameData folder, it shows up as autodetected dll (AD). Double-clicking on any part of the mod's row in the ModList throws an InvalidCastException.

Here's the exception text:
```
System.InvalidCastException: De opgegeven conversie is ongeldig.
   bij CKAN.Main.ModList_CellMouseDoubleClick(Object sender, DataGridViewCellMouseEventArgs e)
   bij System.Windows.Forms.DataGridView.OnMouseDoubleClick(MouseEventArgs e)
   bij System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bij System.Windows.Forms.Control.WndProc(Message& m)
   bij System.Windows.Forms.DataGridView.WndProc(Message& m)
   bij System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

Here's the list loaded assemblies:
http://pastebin.com/cBk78UKw

Go handle that!

**Comment by plague006** [comment] 2015-07-16 16:32
Closing this as a duplicate of #1235, should be fixed with #1237.
Thanks for the report. =)

**Closed by plague006** 2015-07-16 16:32 UTC
