### ISSUE TITLE
ModuleNotFoundKraken: Cannot install mod which is not related

### ISSUE THREAD

**Issue by bokrif** [KSP-CKAN/CKAN#2003] opened 2017-02-06 03:09 UTC
I tried ticking in the box of a mod that I wanted to install and this error keeps popping up no matter what mod I try to install.

AtomicAge is installed but it is completely unrelated to the mod I wanted to install (namely ConfigurableContainers, Chatterer but it happens with others too)

Here is the error log

```
************** Kivétel szövege **************
CKAN.ModuleNotFoundKraken: Cannot install AtomicAge, module not available
   a következő helyen: CKAN.CkanModule.FromIDandVersion(IRegistryQuerier registry, String mod, KspVersionCriteria ksp_version)
   a következő helyen: CKAN.RelationshipResolver.<RelationshipResolver>c__AnonStorey0.<>m__0(String name)
   a következő helyen: System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   a következő helyen: System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   a következő helyen: System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   a következő helyen: CKAN.RelationshipResolver..ctor(IEnumerable`1 module_names, RelationshipResolverOptions options, IRegistryQuerier registry, KspVersionCriteria kspversion)
   a következő helyen: CKAN.MainModList.ComputeConflictsFromModList(IRegistryQuerier registry, IEnumerable`1 change_set, KspVersionCriteria ksp_version)
   a következő helyen: CKAN.Main.<UpdateChangeSetAndConflicts>c__async1.MoveNext()
--- Verem vége nyomkövetés a kivétel előző előfordulási helyétől kezdve ---
   a következő helyen: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   a következő helyen: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   a következő helyen: CKAN.Main.<ModList_CellValueChanged>c__async0.MoveNext()
--- Verem vége nyomkövetés a kivétel előző előfordulási helyétől kezdve ---
   a következő helyen: System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)


************** Betöltött szerelvények **************
mscorlib
    Szerelvény verziója: 4.0.0.0
    Win32-verzió: 4.6.1586.0 built by: NETFXREL2
    Kódbázis: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ckan
    Szerelvény verziója: 0.0.0.0
    Win32-verzió: 0.0.0.0
    Kódbázis: file:///C:/Users/Kriszti%C3%A1nF/Google%20Drive/KSP/CKAN/ckan.exe
----------------------------------------
System.Configuration
    Szerelvény verziója: 4.0.0.0
    Win32-verzió: 4.6.1586.0 built by: NETFXREL2
    Kódbázis: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System
    Szerelvény verziója: 4.0.0.0
    Win32-verzió: 4.6.1586.0 built by: NETFXREL2
    Kódbázis: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Szerelvény verziója: 4.0.0.0
    Win32-verzió: 4.6.1586.0 built by: NETFXREL2
    Kódbázis: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Szerelvény verziója: 4.0.0.0
    Win32-verzió: 4.6.1586.0 built by: NETFXREL2
    Kódbázis: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms
    Szerelvény verziója: 4.0.0.0
    Win32-verzió: 4.6.1586.0 built by: NETFXREL2
    Kódbázis: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Szerelvény verziója: 4.0.0.0
    Win32-verzió: 4.6.1586.0 built by: NETFXREL2
    Kódbázis: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Transactions
    Szerelvény verziója: 4.0.0.0
    Win32-verzió: 4.6.1586.0 built by: NETFXREL2
    Kódbázis: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.Windows.Forms.resources
    Szerelvény verziója: 4.0.0.0
    Win32-verzió: 4.6.1586.0 built by: NETFXREL2
    Kódbázis: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_hu_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
mscorlib.resources
    Szerelvény verziója: 4.0.0.0
    Win32-verzió: 4.6.1586.0 built by: NETFXREL2
    Kódbázis: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_hu_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Numerics
    Szerelvény verziója: 4.0.0.0
    Win32-verzió: 4.6.1586.0 built by: NETFXREL2
    Kódbázis: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Szerelvény verziója: 4.0.0.0
    Win32-verzió: 4.6.1586.0 built by: NETFXREL2
    Kódbázis: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Szerelvény verziója: 4.0.0.0
    Win32-verzió: 4.6.1586.0 built by: NETFXREL2
    Kódbázis: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Szerelvény verziója: 4.0.0.0
    Win32-verzió: 4.6.1636.0 built by: NETFXREL3STAGE
    Kódbázis: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Microsoft.GeneratedCode
    Szerelvény verziója: 1.0.0.0
    Win32-verzió: 4.6.1586.0 built by: NETFXREL2
    Kódbázis: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Szerelvény verziója: 0.0.0.0
    Win32-verzió: 4.6.1586.0 built by: NETFXREL2
    Kódbázis: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
Microsoft.CSharp
    Szerelvény verziója: 4.0.0.0
    Win32-verzió: 4.6.1586.0
    Kódbázis: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    Szerelvény verziója: 4.0.0.0
    Win32-verzió: 4.6.1586.0
    Kódbázis: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Microsoft.CSharp.resources
    Szerelvény verziója: 4.0.0.0
    Win32-verzió: 4.6.1586.0
    Kódbázis: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp.resources/v4.0_4.0.0.0_hu_b03f5f7f11d50a3a/Microsoft.CSharp.resources.dll
----------------------------------------
Accessibility
    Szerelvény verziója: 4.0.0.0
    Win32-verzió: 4.6.1586.0 built by: NETFXREL2
    Kódbázis: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** Igény szerinti (JIT) hibakeresés **************
Az igény szerinti (JIT) hibakeresés engedélyezéséhez fel kell venni
a jitDebugging értéket az alkalmazás .config fájljába, illetve a
gépkonfigurációs fájlba (machine.config), a system.windows.forms
szakaszba. Emellett az alkalmazást a hibakeresés engedélyezésével
kell lefordítani.

Példa:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>
```

**Comment by bokrif** [comment] 2017-02-06 03:21
Also this error prevents me exporting the list of installed mods.

**Comment by Blu3wolf** [comment] 2017-02-06 08:04
I seem to have a related issue. Logs below:
`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
CKAN.ModuleNotFoundKraken: Cannot install notes, module not available
   at CKAN.CkanModule.FromIDandVersion(IRegistryQuerier registry, String mod, KspVersionCriteria ksp_version)
   at CKAN.RelationshipResolver.<RelationshipResolver>c__AnonStorey0.<>m__0(String name)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CKAN.RelationshipResolver..ctor(IEnumerable`1 module_names, RelationshipResolverOptions options, IRegistryQuerier registry, KspVersionCriteria kspversion)
   at CKAN.MainModList.ComputeConflictsFromModList(IRegistryQuerier registry, IEnumerable`1 change_set, KspVersionCriteria ksp_version)
   at CKAN.Main.<UpdateChangeSetAndConflicts>c__async1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKAN.Main.<ModList_CellValueChanged>c__async0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1076.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ckan
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///E:/Program%20Files%20(x86)/Steam/steamapps/common/Kerbal%20Space%20Program/ckan.exe
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1075.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1067.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1068.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1067.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1082.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.6.1076.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.


`

**Comment by Commissar0617** [comment] 2017-02-24 21:41
likely related #2011 #2010

**Comment by Commissar0617** [comment] 2017-03-09 21:01
@politas any updates towards this at all? it seems to be a pretty widespread issue.

**Comment by politas** [comment] 2017-03-12 09:29
I think this is actually related to #1864

**Comment by politas** [comment] 2017-03-12 09:36
Almost certainly a duplicate of #1864

**Closed by politas** 2017-03-12 09:36 UTC
