### ISSUE TITLE
MOD Conflict

### ISSUE THREAD

**Issue by Bit-Fiddler** [KSP-CKAN/CKAN#973] opened 2015-05-28 12:47 UTC
About to remove:

Done!

About to install...

 * OPTSpacePlaneParts V1.6.9.1 (cached)
 * OrbitalSurveyPlus 1.2 (cached)
 * PersistentRotation 0.5.3 (cached)
 * PhoenixIndustriesCargoResupplySystem-large 1.2 (cached)
 * ProceduralParts v1.1.2 (cached)
 * Workshop 0.7.2 (cached)

Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/CKAN-meta/issues/new

Please including the following information in your report:

File           : GameData/OPT/Parts/mk3_cockpit/mk3_cockpit.cfg
Installing Mod : OPTSpacePlaneParts V1.6.9.1
Owning Mod     : Mk3MiniExpansionPack
CKAN Version   : v1.6.17-0-g0000000 (beta)

Your GameData has been returned to its original state.

Error!

**Comment by Dazpoet** [comment] 2015-05-28 20:20
Duplicate of #974 so I'm closing this.

**Closed by Dazpoet** 2015-05-28 20:20 UTC
Labels: support
