### ISSUE TITLE
CKAN freezes when i check the box to install or uninstall a mod

### ISSUE THREAD

**Issue by SpaghetMaster1** [KSP-CKAN/CKAN#3746] opened 2022-12-14 21:38 UTC
Background
----------
Windows 11
v1.31.2
* KSP Version: 1.12.4.3187

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

Problem
-------
CKAN freezes and i have to Alt+F4 whenever i click the checkbox that installs and uninstalls games.

**Steps to reproduce**
* Go to the installed page
* Click on the installed checkbox for any mod
* See error CKAN will freeze

**Expected behavior**
it will freeze

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment] 2022-12-14 23:00
Thanks, we just finished fixing this, you can try the latest dev build if you'd like to test:

- https://ksp-ckan.s3-us-west-2.amazonaws.com/ckan.exe

**Comment by HebaruSan** [comment] 2022-12-14 23:00
Duplicate of #3707

**Closed by HebaruSan** 2022-12-14 23:00 UTC
