### ISSUE TITLE
[Bug]: CKAN refuses to open without "--asroot" command line operator when the user *is* the "Administrator"

### ISSUE THREAD

**Issue by Mjrlun** [KSP-CKAN/CKAN#3992] opened 2024-01-03 03:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows 11 64bit

### CKAN Version

1.34.2

### Games

KSP 1, KSP 2

### Game Version

1.12.5, 0.2.0

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

This is not mod related.

### Describe the bug

The title says it all. If you are running windows as the general Administrator account, CKAN will "force-close" due to be ran "as root," since this account type can only run applications in administrator mode.

I would suggest rather than force closing CKAN when ran in Administrator, instead ask the user whether to open the program, and make an option within the CKAN settings to allow normal opening without the "--asroot" command line flair since opening the command line every time (or using a batch file) to use a GUI-based executable is not user friendly.

I marked this as a bug rather than a "feature request" due to it not really being a large ask, and is either not intended, or user unfriendly design.

### Steps to reproduce

>Become the general Administrator account
>Open CKAN normally.
>Be confused because it doesn't open
>Open it using command line
>Be frustrated because of the "as root" implementation.

### Relevant log output

You are trying to run CKAN as an administrator user.
This is a bad idea and there is absolutely no good reason to do it. Please run CKAN from a user account (or use --asroot if you are feeling brave).

**Comment by HebaruSan** [comment] 2024-01-03 03:16
Duplicate of #3956

**Closed by HebaruSan** 2024-01-03 03:16 UTC
Labels: Duplicate

**Comment by Mjrlun** [comment] 2024-01-03 03:20
This issue should be fixed, rather than simply closed, so I will leave it open.
