### ISSUE TITLE
clicking literally anything crashes ckan

### ISSUE THREAD

**Issue by TotallyBonkers** [KSP-CKAN/CKAN#3710] opened 2022-11-17 04:37 UTC
Background
----------
* Operating System: Windows
* CKAN Version: 1.31.2
* KSP Version: 1.12.4

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
yes

Problem
-------
Opening ckan and clicking anything such as a mod, "apply changes," "add available updates" just causes it to stop responding.

**Steps to reproduce**
Open ckan
Click on almost anything
Stops responding

**Expected behavior**
The application working, where you can in fact do things

A lot of people are experiencing this

**Comment by HebaruSan** [comment] 2022-11-17 04:38
Thanks, we just finished fixing this, you can try the latest dev build if you'd like to test:

- https://ksp-ckan.s3-us-west-2.amazonaws.com/ckan.exe

**Comment by HebaruSan** [comment] 2022-11-17 04:38
Duplicate of #3707

**Closed by HebaruSan** 2022-11-17 04:38 UTC
Labels: Duplicate
