### ISSUE TITLE
[Bug]: CKAN First time URLHandlersPrompt fails due to running as root protection

### ISSUE THREAD

**Issue by Lewis98** [KSP-CKAN/CKAN#4139] opened 2024-08-01 12:28 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows 10 Home V22H2 (OS Build 19045.4651)

### CKAN Version

v1.34.4

### Games

KSP 1

### Game Version

1.12.5.3190

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

None, Fresh KSP Install, should be unrelated

### Describe the bug

Received the following prompt on first time launching CKAN:
![image](https://github.com/user-attachments/assets/3f599a6c-04ee-44da-a7d1-7aac43aff24f)

Responding yes provides the following command prompt warning:
![image](https://github.com/user-attachments/assets/4090e8f9-0715-41b0-b366-7d31b29b9928)

The action attempted by the CKAN launcher appears to be unsuccessful.

### Steps to reproduce

Pre-requisite: Machine with no prior installation or usage of CKAN

1) Download CKAN executable

2) Run CKAN

3) Respond yes to the following prompt:
![image](https://github.com/user-attachments/assets/a1a93880-d7a0-471c-98cf-a69a9b8100ac)

4) Warning is displayed on command prompt
 

### Relevant log output

Couldn't find any relevant log output

**Comment by Lewis98** [comment] 2024-08-01 12:44
Checked \CKAN\GUI\URLHandlers.cs lines 69-80 and there seems to be a workaround for this issue already implemented, not entirely sure what's causing it to fail

Running ckan.exe manually as administrator with the '--asroot' flag appears to function fine, without warning, and resolves the issue on future launches (without admin perms).

\CKAN\GUI\URLHandlers.cs lines 69-80 for reference:
![image](https://github.com/user-attachments/assets/c9d650da-05ce-470d-a4f5-d4a77a28618f)

**Comment by HebaruSan** [comment] 2024-08-01 15:01
Hi @Lewis98, thanks for the report. You're right, this was already fixed in #3996, but there hasn't been a major release since then. If you like, you can try the dev build to see the fix in action:

- <https://ksp-ckan.s3-us-west-2.amazonaws.com/ckan.exe>

**Comment by HebaruSan** [comment] 2024-08-01 15:01
Duplicate of #4032

**Closed by HebaruSan** 2024-08-01 15:01 UTC
