### ISSUE TITLE
[Bug] Recent modules missing for some users

### ISSUE THREAD

**Issue by cumber** [KSP-CKAN/CKAN#3699] opened 2022-11-10 05:30 UTC
Background
----------
* Operating System: Windows
* CKAN Version: 1.31.2, and probably previous versions based on how long ago the latest successful refresh was
* KSP Version: 1.12.4

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
**Describe the bug**

First time playing KSP in some months, I opened CKAN to check whether there were any mod updates. None were found. However, on starting up KSP, the Addon Version Checker reports that updates are available for several mods.

I dug into one case further, the ClickthroughBlocker mod:

CKAN reports the latest available version is 0.1.10.17 (which the versions tab lists as `1:0.1.10.17` - I don't know what the `1:` prefix means or why it's shown differently in the actual metadata file and the versions tab than it is in the main GUI). This seems to correspond to this file in the CKAN-meta repository: https://github.com/KSP-CKAN/CKAN-meta/blob/master/ClickThroughBlocker/ClickThroughBlocker-1-0.1.10.17.ckan

Addon Version Checker tells me that ClickThroughBlocker has version 2.1.10.18 available.

I can also see that in the CKAN-meta repository there is this file: https://github.com/KSP-CKAN/CKAN-meta/blob/master/ClickThroughBlocker/ClickThroughBlocker-1-2.1.10.18.ckan, which contains `"version": "1:2.1.10.18"`. This does seem to be the version that Addon Version Checker is telling me about.

I don't know why CKAN isn't seeing this updated version (or of any of the other mods). It's like it's simply not updating the repository, but when I click refresh it claims that it is, I don't see any indication of any failure to update.

**Expected behavior**

I expect the CKAN client to show me mod versions available that are in the CKAN-meta repository, after refreshing.

**Comment by HebaruSan** [comment] 2022-11-10 12:58
Click "Refresh" in the toolbar to update your registry with the latest metadata.

**Comment by HebaruSan** [comment] 2022-11-10 13:19
Alternately, set all of 1.12 compatible:

https://github.com/KSP-CKAN/CKAN/wiki/User-guide#Choosing-compatible-game-versions

CKAN will detect an update as incompatible if you're on 1.12.4 and the update was released for 1.12.3.

**Comment by cumber** [comment] 2022-11-10 23:23
@HebaruSan I don't wish to be rude, but even if I hadn't explicitly mentioned clicking refresh in my post it would have seemed a bit disrespectful for you to have simply closed this as invalid assuming I didn't know enough to click the refresh button when I wanted to refresh the repository (rather than asking, to check whether I had refreshed). But I did mention that (twice), so it doesn't feel like you read my post all that thoroughly before you assumed it was invalid.

I didn't explicitly mention that I already had 1.12 in my list of compatible versions. But I did talk about looking into the versions tab, where **all** versions that CKAN has found are listed (with the compatible ones highlighted in green). If it *was* seeing the updates and they just weren't classified as compatible, they would have showed up there. So again, I had already ruled out this basic issue in my post.

Today the issue seems to have resolved itself; CKAN has pulled in all the updated versions it wasn't seeing yesterday (no matter how many times I clicked refresh). But the ClickThroughBlocker update was released months ago (and as I had confirmed in my original post, had definitely made it into the CKAN-meta repository), so it can't be explained by something like the registry state before the update being cached (at least not unless the registry cache is kept for months without checking for updates, which itself would seem like a bug). I also tried refreshing a number of times over the course of hours, so it wasn't a one-off glitch, either; the error state persisted for a long time, and across multiple separate times I started the CKAN client.

I suspect there is either some sort of intermittent bug where the check whether the repository is up-to-date failed, or else the repository download failed for external reasons and the issue in CKAN is that it didn't report the failed update to the user. But if the problem is intermittent it may not be worth reopening this unless lots of other people are noticing it.

**Comment by HebaruSan** [comment] 2022-11-10 23:45
Sorry, I'm preoccupied with some urgent home maintenance projects at the moment so I indeed skimmed your post because the problem superficially sounded very familiar. I did re-read later and see that you mentioned refreshing, so I added the second comment about compatibility, which seemed like the next most likely reason for what you described.

If it happens again, check your `<Game dir>/CKAN/registry.json` file and let us know what the `last_server_etag` value is near the top. This is a hash value that GitHub sends to represent whether a file has changed, which CKAN uses to skip updates when you already have the latest metadata, so my next best guess is that you're getting a weird value there that short circuits the update.

**Comment by cumber** [comment] 2022-11-11 00:45
Thank you for acknowledging. And thank you for continuing to volunteer time here despite being overloaded at home!

Ah, good tip; I'll take a look at that next time (if there's a next time). I found the `AppData\Local\CKAN` folder, but couldn't see any logs or relevant state there. Didn't realise CKAN also kept some state in the Kerbal installation folder.

**Comment by HebaruSan** [comment] 2022-11-16 15:15
This has been reported by another user on Discord, to which a third replied "Thank you.", presumably meaning they've encountered it as well. Re-opening for investigation.

![image](https://user-images.githubusercontent.com/1559108/202219185-6258ac62-efcb-4bd1-b82b-0ce91a78d80f.png)

To any users who see this problem: If you can, please share a copy of your `<Game dir>/CKAN/registry.json` file (_before_ you apply any workarounds, while the problem is still happening). The fact that re-adding the same repo with a different name fixes it suggests that it is in fact a problem with the etag, and a `registry.json` file would allow us to check that.

**Comment by belkorin** [comment] 2022-11-17 01:47
I'm seeing this same issue. I've attached my registry.json file (zipped because github doesn't want to let me attach a json file)
[registry.zip](https://github.com/KSP-CKAN/CKAN/files/10027008/registry.zip)

**Comment by HebaruSan** [comment] 2022-11-17 02:06
Thanks! Checking your `last_server_etag` property, it actually matches what I get if I do a refresh right now! So that's not the cause, back to the drawing board...

**Comment by cumber** [comment] 2022-11-17 02:18
> Thanks! Checking your `last_server_etag` property, it actually matches what I get if I do a refresh right now! So that's not the cause, back to the drawing board...

That actually sounds extremely interesting to me. It implies that @belkorin has recorded the etag from the *current* state of the repository, but CKAN is acting on an older state of the repository that doesn't match that etag. That suggests a bug somewhere in the sequence for updating the repository, where it could have written a new etag in the registry.json without having updated the cached copy of the repository. Could potentially even be a race condition if the refresh is aborted (or fails, or the program is killed) at the wrong point; say if it writes the etag and *then* downloads the newer repository.

If the @belkorin's etag didn't match, it would more likely mean that it simply wasn't updating at all.

**Comment by HebaruSan** [comment] 2022-11-17 02:19
One possible clue, there are no occurrences of `install_size` outside of the `installed_module`s, but there should be lots. Possibly a problem deserializing mods with that property during the update.

**Comment by HebaruSan** [comment] 2022-11-17 02:43
Based on which versions are missing, that's definitely what's happening. But it also makes no sense; there's nothing special about `install_size` that could stop a module from serializing or deserializing. It's set up exactly the same as `download_size`.

https://github.com/KSP-CKAN/CKAN/blob/aeb2388b8d042a1aefa54a1633157f56597fe88f/Core/Types/CkanModule.cs#L133-L146

**Comment by HebaruSan** [comment] 2022-11-17 03:15
@cumber or @belkorin or anyone else who is seeing this issue, there's a log message that's printed when we skip adding a module to the registry, that might give us another clue:

https://github.com/KSP-CKAN/CKAN/blob/aeb2388b8d042a1aefa54a1633157f56597fe88f/Core/Converters/JsonLeakySortedDictionaryConverter.cs#L24-L33

Please try this if you can:

1. Run `ckan --show-console` to keep the terminal window open for the message to appear in
2. Refresh
3. Check the terminal window for "Failed to deserialize" messages
4. If there are any such messages, please copy/paste them here

**Comment by belkorin** [comment] 2022-11-17 06:11
nope, no messages in the terminal window. Another point of interest on this - I manually downloaded the master file that it's grabbing from github, tossed it on my own server and added that as another source, and it read that in from there without any issue.

**Comment by randomguyingithub** [comment] 2022-11-17 07:21
Is the "ghost" apply change and pressing it causing ckan freezes related to it? Few days ago my ckan has apply change button always on/clickable even nothing is ticked and if you click on it the ckan will freeze. I  had to remove CKAN folder in my KSP instance and reinstall all mods again to fix it.

**Comment by HebaruSan** [comment] 2022-11-17 14:42
@randomguyingithub that's a different issue, see #3707.

**Comment by HebaruSan** [comment] 2022-11-17 16:36
I got confused about the log messages; "Failed to deserialize" is for when it's reading data out of `registry.json`, which used to be able to crash if you switched back and forth between CKAN versions (see #3526).

But we want the messages for errors during the repo update, which is in a different spot:

https://github.com/KSP-CKAN/CKAN/blob/aeb2388b8d042a1aefa54a1633157f56597fe88f/Core/Net/Repo.cs#L416-L451

So the previous test didn't check what I wanted to check.
@cumber or @belkorin or anyone else again, these are the actual steps to find messages related to the registry refresh:

1. Edit your registry.json file
2. Delete the `last_server_etag` line to force a refresh (otherwise the refresh will be skipped if your registry is already up to date)
3. Run `ckan --show-console --verbose` to keep the terminal window open and enable INFO-level logging messages
4. Refresh
5. Check the terminal window for messages that start with "Skipping " followed by a filename from the metadata archive
6. Also check for anything starting with "Error processing" (which will also appear without `--verbose`, so I'm guessing you would have seen it already)
7. If there are any such messages, please copy/paste them here

**Comment by HebaruSan** [comment] 2022-11-17 16:46
> That actually sounds extremely interesting to me. It implies that belkorin has recorded the etag from the _current_ state of the repository, but CKAN is acting on an older state of the repository that doesn't match that etag. That suggests a bug somewhere in the sequence for updating the repository, where it could have written a new etag in the registry.json without having updated the cached copy of the repository. Could potentially even be a race condition if the refresh is aborted (or fails, or the program is killed) at the wrong point; say if it writes the etag and _then_ downloads the newer repository.

If you can think of ways to test any of these ideas, please go for it! We are in the "fumbling around in the dark" stage of investigating this issue; the main task is to make guesses and then find ways to rule them out (like science does!). If you happen to be a coder, CKAN is all open source, and I can try to point you toward the relevant snippets for a given idea.

**Comment by HebaruSan** [comment] 2022-11-17 17:06
Trying to collect data and summarize the investigation so far...

Candidate failure point | Relevant evidence
:-- | :--
Server sending old version of the file | Manual download unaffected
ISP caching files | Manual download unaffected
`last_server_etag` | Matches unaffected user's value
Parsing the .ckan files | Works if the repo is deleted and re-added
`install_size` | Missing from the only registry.json we have so far
Race condition | ?

**Comment by HebaruSan** [comment] 2022-11-17 17:21
Brainstorming everything that might be different between affected and unaffected users...

- Auto-refresh-on-startup setting
- Number or order of configured repositories
- Firewalls
- SSL certificates
- Free space on disk

... will expand as I think of more.

**Comment by belkorin** [comment] 2022-11-17 21:47
> 

On deleting the last server etag line from the file, it updates without issue. Here's the verbose output anyway, in case it's useful

`463 [1] INFO CKAN.CmdLine.CommonOptions (null) - Verbose logging enabled
496 [1] INFO CKAN.Main (null) - Starting the GUI
3519 [1] INFO CKAN.RegistryManager (null) - Loaded CKAN registry at D:/steam games/steamapps/common/Kerbal Space Program/CKAN\registry.json
3633 [1] INFO CKAN.Main (null) - Making auto-update call
6227 [1] INFO CKAN.URLHandlers (null) - Adding URL handler to registry
6228 [1] INFO CKAN.URLHandlers (null) - URL handler already exists with the same path
6612 [1] INFO CKAN.Registry (null) - Registering ModuleManager from GameData/ModuleManager.4.2.2.dll
6612 [1] INFO CKAN.Registry (null) - Not registering GameData/000_ClickThroughBlocker/Plugins/ClickThroughBlocker.dll, it belongs to ClickThroughBlocker
6613 [1] INFO CKAN.Registry (null) - Not registering GameData/000_Toolbar/Plugins/aaa_Toolbar.dll, it belongs to Toolbar
6614 [1] INFO CKAN.Registry (null) - Not registering GameData/001_ToolbarControl/Plugins/ToolbarControl.dll, it belongs to ToolbarController
6616 [1] INFO CKAN.Registry (null) - Not registering GameData/DistantObject/Plugins/DistantObject.dll, it belongs to DistantObject
6616 [1] INFO CKAN.Registry (null) - Not registering GameData/DistantObject/Plugins/KSPe.Light.DOE.dll, it belongs to DistantObject
6616 [1] INFO CKAN.Registry (null) - Not registering GameData/DistantObject/Plugins/PluginData/MeshEngine.dll, it belongs to DistantObject
6616 [1] INFO CKAN.Registry (null) - Not registering GameData/DistantObject/Plugins/PluginData/MeshEngineStock.dll, it belongs to DistantObject
6616 [1] INFO CKAN.Registry (null) - Not registering GameData/DistantObject/Plugins/PluginData/MeshEngineTweakScale.dll, it belongs to DistantObject
6617 [1] INFO CKAN.Registry (null) - Not registering GameData/EnvironmentalVisualEnhancements/Plugins/Atmosphere.dll, it belongs to EnvironmentalVisualEnhancements
6617 [1] INFO CKAN.Registry (null) - Not registering GameData/EnvironmentalVisualEnhancements/Plugins/CelestialShadows.dll, it belongs to EnvironmentalVisualEnhancements
6617 [1] INFO CKAN.Registry (null) - Not registering GameData/EnvironmentalVisualEnhancements/Plugins/CityLights.dll, it belongs to EnvironmentalVisualEnhancements
6617 [1] INFO CKAN.Registry (null) - Not registering GameData/EnvironmentalVisualEnhancements/Plugins/EVEManager.dll, it belongs to EnvironmentalVisualEnhancements
6618 [1] INFO CKAN.Registry (null) - Not registering GameData/EnvironmentalVisualEnhancements/Plugins/PartFX.dll, it belongs to EnvironmentalVisualEnhancements
6618 [1] INFO CKAN.Registry (null) - Not registering GameData/EnvironmentalVisualEnhancements/Plugins/PQSManager.dll, it belongs to EnvironmentalVisualEnhancements
6618 [1] INFO CKAN.Registry (null) - Not registering GameData/EnvironmentalVisualEnhancements/Plugins/ShaderLoader.dll, it belongs to EnvironmentalVisualEnhancements
6618 [1] INFO CKAN.Registry (null) - Not registering GameData/EnvironmentalVisualEnhancements/Plugins/Terrain.dll, it belongs to EnvironmentalVisualEnhancements
6618 [1] INFO CKAN.Registry (null) - Not registering GameData/EnvironmentalVisualEnhancements/Plugins/TextureConfig.dll, it belongs to EnvironmentalVisualEnhancements
6619 [1] INFO CKAN.Registry (null) - Not registering GameData/EnvironmentalVisualEnhancements/Plugins/Utils.dll, it belongs to EnvironmentalVisualEnhancements
6619 [1] INFO CKAN.Registry (null) - Not registering GameData/EnvironmentalVisualEnhancements/Plugins/_BuildManager.dll, it belongs to EnvironmentalVisualEnhancements
6619 [1] INFO CKAN.Registry (null) - Not registering GameData/KerbalEngineer/KerbalEngineer.dll, it belongs to KerbalEngineerRedux
6619 [1] INFO CKAN.Registry (null) - Not registering GameData/KerbalEngineer/KerbalEngineer.Unity.dll, it belongs to KerbalEngineerRedux
6622 [1] INFO CKAN.Registry (null) - Not registering GameData/KRASH/Plugins/KRASH.dll, it belongs to KRASH
6622 [1] INFO CKAN.Registry (null) - Not registering GameData/KSP-AVC/Plugins/KSP-AVC.dll, it belongs to KSP-AVC
6622 [1] INFO CKAN.Registry (null) - Not registering GameData/SpaceTuxLibrary/Plugins/ButtonManager.dll, it belongs to SpaceTuxLibrary
6623 [1] INFO CKAN.Registry (null) - Not registering GameData/SpaceTuxLibrary/Plugins/KSP_ColorPicker.dll, it belongs to SpaceTuxLibrary
6623 [1] INFO CKAN.Registry (null) - Not registering GameData/SpaceTuxLibrary/Plugins/KSP_Log.dll, it belongs to SpaceTuxLibrary
6623 [1] INFO CKAN.Registry (null) - Not registering GameData/SpaceTuxLibrary/Plugins/KSP_PartHighlighter.dll, it belongs to SpaceTuxLibrary
6623 [1] INFO CKAN.Registry (null) - Not registering GameData/SpaceTuxLibrary/Plugins/SpaceTuxUtility.dll, it belongs to SpaceTuxLibrary
6624 [1] INFO CKAN.Registry (null) - Not registering GameData/SpaceTuxLibrary/Plugins/VesselModuleSave.dll, it belongs to SpaceTuxLibrary
6656 [1] INFO CKAN.Registry (null) - Not registering GameData/StageRecovery/Plugins/StageRecovery.dll, it belongs to StageRecovery
6657 [1] INFO CKAN.Registry (null) - Not registering GameData/Waterfall/Plugins/Waterfall.dll, it belongs to Waterfall
6659 [1] INFO CKAN.Registry (null) - Not registering GameData/ZeroMiniAVC/Plugins/KSP-AVC.dll, it belongs to ZeroMiniAVC
6659 [1] INFO CKAN.Registry (null) - Not registering GameData/ZeroMiniAVC/Plugins/ZeroMiniAVC.dll, it belongs to ZeroMiniAVC
6732 [1] INFO CKAN.Main (null) - GUI started
7089 [7] INFO CKAN.Registry (null) - Registering ModuleManager from GameData/ModuleManager.4.2.2.dll
7090 [7] INFO CKAN.Registry (null) - Not registering GameData/000_ClickThroughBlocker/Plugins/ClickThroughBlocker.dll, it belongs to ClickThroughBlocker
7092 [7] INFO CKAN.Registry (null) - Not registering GameData/000_Toolbar/Plugins/aaa_Toolbar.dll, it belongs to Toolbar
7092 [7] INFO CKAN.Registry (null) - Not registering GameData/001_ToolbarControl/Plugins/ToolbarControl.dll, it belongs to ToolbarController
7093 [7] INFO CKAN.Registry (null) - Not registering GameData/DistantObject/Plugins/DistantObject.dll, it belongs to DistantObject
7093 [7] INFO CKAN.Registry (null) - Not registering GameData/DistantObject/Plugins/KSPe.Light.DOE.dll, it belongs to DistantObject
7093 [7] INFO CKAN.Registry (null) - Not registering GameData/DistantObject/Plugins/PluginData/MeshEngine.dll, it belongs to DistantObject
7093 [7] INFO CKAN.Registry (null) - Not registering GameData/DistantObject/Plugins/PluginData/MeshEngineStock.dll, it belongs to DistantObject
7094 [7] INFO CKAN.Registry (null) - Not registering GameData/DistantObject/Plugins/PluginData/MeshEngineTweakScale.dll, it belongs to DistantObject
7094 [7] INFO CKAN.Registry (null) - Not registering GameData/EnvironmentalVisualEnhancements/Plugins/Atmosphere.dll, it belongs to EnvironmentalVisualEnhancements
7094 [7] INFO CKAN.Registry (null) - Not registering GameData/EnvironmentalVisualEnhancements/Plugins/CelestialShadows.dll, it belongs to EnvironmentalVisualEnhancements
7095 [7] INFO CKAN.Registry (null) - Not registering GameData/EnvironmentalVisualEnhancements/Plugins/CityLights.dll, it belongs to EnvironmentalVisualEnhancements
7095 [7] INFO CKAN.Registry (null) - Not registering GameData/EnvironmentalVisualEnhancements/Plugins/EVEManager.dll, it belongs to EnvironmentalVisualEnhancements
7095 [7] INFO CKAN.Registry (null) - Not registering GameData/EnvironmentalVisualEnhancements/Plugins/PartFX.dll, it belongs to EnvironmentalVisualEnhancements
7095 [7] INFO CKAN.Registry (null) - Not registering GameData/EnvironmentalVisualEnhancements/Plugins/PQSManager.dll, it belongs to EnvironmentalVisualEnhancements
7095 [7] INFO CKAN.Registry (null) - Not registering GameData/EnvironmentalVisualEnhancements/Plugins/ShaderLoader.dll, it belongs to EnvironmentalVisualEnhancements
7095 [7] INFO CKAN.Registry (null) - Not registering GameData/EnvironmentalVisualEnhancements/Plugins/Terrain.dll, it belongs to EnvironmentalVisualEnhancements
7096 [7] INFO CKAN.Registry (null) - Not registering GameData/EnvironmentalVisualEnhancements/Plugins/TextureConfig.dll, it belongs to EnvironmentalVisualEnhancements
7096 [7] INFO CKAN.Registry (null) - Not registering GameData/EnvironmentalVisualEnhancements/Plugins/Utils.dll, it belongs to EnvironmentalVisualEnhancements
7096 [7] INFO CKAN.Registry (null) - Not registering GameData/EnvironmentalVisualEnhancements/Plugins/_BuildManager.dll, it belongs to EnvironmentalVisualEnhancements
7096 [7] INFO CKAN.Registry (null) - Not registering GameData/KerbalEngineer/KerbalEngineer.dll, it belongs to KerbalEngineerRedux
7097 [7] INFO CKAN.Registry (null) - Not registering GameData/KerbalEngineer/KerbalEngineer.Unity.dll, it belongs to KerbalEngineerRedux
7098 [7] INFO CKAN.Registry (null) - Not registering GameData/KRASH/Plugins/KRASH.dll, it belongs to KRASH
7098 [7] INFO CKAN.Registry (null) - Not registering GameData/KSP-AVC/Plugins/KSP-AVC.dll, it belongs to KSP-AVC
7099 [7] INFO CKAN.Registry (null) - Not registering GameData/SpaceTuxLibrary/Plugins/ButtonManager.dll, it belongs to SpaceTuxLibrary
7099 [7] INFO CKAN.Registry (null) - Not registering GameData/SpaceTuxLibrary/Plugins/KSP_ColorPicker.dll, it belongs to SpaceTuxLibrary
7099 [7] INFO CKAN.Registry (null) - Not registering GameData/SpaceTuxLibrary/Plugins/KSP_Log.dll, it belongs to SpaceTuxLibrary
7099 [7] INFO CKAN.Registry (null) - Not registering GameData/SpaceTuxLibrary/Plugins/KSP_PartHighlighter.dll, it belongs to SpaceTuxLibrary
7099 [7] INFO CKAN.Registry (null) - Not registering GameData/SpaceTuxLibrary/Plugins/SpaceTuxUtility.dll, it belongs to SpaceTuxLibrary
7100 [7] INFO CKAN.Registry (null) - Not registering GameData/SpaceTuxLibrary/Plugins/VesselModuleSave.dll, it belongs to SpaceTuxLibrary
7128 [7] INFO CKAN.Registry (null) - Not registering GameData/StageRecovery/Plugins/StageRecovery.dll, it belongs to StageRecovery
7130 [7] INFO CKAN.Registry (null) - Not registering GameData/Waterfall/Plugins/Waterfall.dll, it belongs to Waterfall
7131 [7] INFO CKAN.Registry (null) - Not registering GameData/ZeroMiniAVC/Plugins/KSP-AVC.dll, it belongs to ZeroMiniAVC
7131 [7] INFO CKAN.Registry (null) - Not registering GameData/ZeroMiniAVC/Plugins/ZeroMiniAVC.dll, it belongs to ZeroMiniAVC
7306 [7] INFO CKAN.Repo (null) - Downloading https://github.com/KSP-CKAN/CKAN-meta/archive/master.tar.gz
7536 [7] INFO CKAN.Net (null) - Redirecting to https://codeload.github.com/KSP-CKAN/CKAN-meta/tar.gz/refs/heads/master
8699 [7] INFO CKAN.JsonIgnoreBadUrlConverter (null) - http://Included%20in%20download is not a valid URL, ignoring
8846 [7] INFO CKAN.JsonIgnoreBadUrlConverter (null) - http://the%20mod%20is%20the%20code is not a valid URL, ignoring
8949 [7] INFO CKAN.JsonIgnoreBadUrlConverter (null) - http://Included%20in%20download is not a valid URL, ignoring
8949 [7] INFO CKAN.JsonIgnoreBadUrlConverter (null) - http://Included%20in%20download is not a valid URL, ignoring
8949 [7] INFO CKAN.JsonIgnoreBadUrlConverter (null) - http://Included%20in%20download is not a valid URL, ignoring
8950 [7] INFO CKAN.JsonIgnoreBadUrlConverter (null) - http://Included%20in%20download is not a valid URL, ignoring
9171 [7] INFO CKAN.JsonIgnoreBadUrlConverter (null) - http://Included%20in%20Zip is not a valid URL, ignoring
9172 [7] INFO CKAN.JsonIgnoreBadUrlConverter (null) - http://Included%20in%20Zip is not a valid URL, ignoring
9275 [7] INFO CKAN.JsonIgnoreBadUrlConverter (null) - http://in%20the%20zip is not a valid URL, ignoring
9275 [7] INFO CKAN.JsonIgnoreBadUrlConverter (null) - http://in%20the%20zip is not a valid URL, ignoring
9277 [7] INFO CKAN.JsonIgnoreBadUrlConverter (null) - http://in%20the%20zip is not a valid URL, ignoring
9386 [7] INFO CKAN.JsonIgnoreBadUrlConverter (null) - http://The%20config%20itself is not a valid URL, ignoring
9387 [7] INFO CKAN.JsonIgnoreBadUrlConverter (null) - http://The%20config%20itself is not a valid URL, ignoring
9387 [7] INFO CKAN.JsonIgnoreBadUrlConverter (null) - http://The%20config%20itself is not a valid URL, ignoring
9388 [7] INFO CKAN.JsonIgnoreBadUrlConverter (null) - http://The%20config%20itself is not a valid URL, ignoring
9388 [7] INFO CKAN.JsonIgnoreBadUrlConverter (null) - http://The%20config%20itself is not a valid URL, ignoring
9388 [7] INFO CKAN.JsonIgnoreBadUrlConverter (null) - http://The%20config%20itself is not a valid URL, ignoring
9510 [7] INFO CKAN.JsonIgnoreBadUrlConverter (null) - http://included%20in%20download is not a valid URL, ignoring
10110 [7] INFO CKAN.JsonIgnoreBadUrlConverter (null) - http://Config%20File. is not a valid URL, ignoring
11001 [7] INFO CKAN.JsonIgnoreBadUrlConverter (null) - http://the%20mod%20is%20the%20code is not a valid URL, ignoring
11156 [7] INFO CKAN.JsonIgnoreBadUrlConverter (null) - http://Included%20in%20archive is not a valid URL, ignoring
11448 [7] INFO CKAN.JsonIgnoreBadUrlConverter (null) - http://on%20the%20zip is not a valid URL, ignoring
12052 [7] INFO CKAN.RegistryManager (null) - Saving CKAN registry at D:/steam games/steamapps/common/Kerbal Space Program/CKAN\registry.json
12645 [8] INFO CKAN.ManageMods (null) - Updating the mod list
12830 [8] INFO CKAN.RelationshipResolver (null) - Dependency on B9PartSwitch found but it is not listed in the index, or not available for your version of KSP.
13146 [8] INFO CKAN.RelationshipResolver (null) - Dependency on B9PartSwitch found but it is not listed in the index, or not available for your version of KSP.`

**Comment by belkorin** [comment] 2022-11-17 21:53
Something else that might be of interest - The first time I opened up CKAN yesterday, I was on a version from a year ago.

**Comment by superepicname** [comment] 2022-11-18 17:21
[Ckan registry.zip](https://github.com/KSP-CKAN/CKAN/files/10043442/Ckan.registry.zip)
Another registry right here

**Comment by HebaruSan** [comment] 2022-11-18 18:29
Thanks, @superepicname. Your registry also has no `install_size` properties outside of the `installed_module`s, but this time you do have modules that _should_ have it. So it's not that the modules are filtered out, but `install_size` was just stripped.

Have you also been switching back and forth between CKAN versions as @belkorin reported above? That's one way `install_size` might disappear.

> Something else that might be of interest - The first time I opened up CKAN yesterday, I was on a version from a year ago.

I'll have to give that a try...

**Comment by superepicname** [comment] 2022-11-23 08:04
> 

well i didnt switch back and forth with the CKAN versions. I didn't play ksp for a while before i came back and the problem was there (haven't had it before). But as you might've seen in the discord the problem fixed itself. Idk how but should i maybe send the registry file again now that its fixed?

**Comment by xPROxSLASHERx** [comment] 2022-11-23 09:52
[registry.zip](https://github.com/KSP-CKAN/CKAN/files/10074277/registry.zip)

**Comment by HebaruSan** [comment] 2022-11-23 15:08
@xPROxSLASHERx, the freezing issue is different and has already been solved, see #3707.

**Comment by JonnyOThan** [comment] 2022-12-11 22:04
Here's one from someone who wasn't able to find FreeIVA:
[registry.zip](https://github.com/KSP-CKAN/CKAN/files/10203387/registry.zip)

**Comment by HebaruSan** [comment] 2022-12-11 22:37
OK, latest speculation:

1. User upgrades to and launches CKAN v1.31.2
2. User refreshes registry (may not happen right away if the etag is the same)
3. User is prompted to reinstall all mods (because `install_size` is set on the available mods but not the installed mods)
4. User clicks Yes, and the reinstall succeeds
6. After this, ZeroMiniAVC becomes auto-uninstallable, which triggers the bug from #3707
7. The crash from #3707 prevents the available modules from being updates as they should be during a registry update
8. Eventually the etag changes again and a subsequent registry update succeeds

If this is correct, then we could consider this already fixed with #3707. I thought we had conflicting reports that the bug still happened even after that was fixed and the `last_server_etag` was cleared, but maybe some of those steps didn't occur as we thought, since they're kind of complex.

**Comment by realstrategos** [comment] 2023-01-14 18:51
Just loaded it up today, it is reporting no updates available. looking at registry.json i see duplicate entries
[registry.zip](https://github.com/KSP-CKAN/CKAN/files/10418581/registry.zip)

**Comment by realstrategos** [comment] 2023-01-14 19:03
deleting the last_server_etag fixed the issue for me, updates are appearing now

**Comment by cletusw** [comment] 2023-01-26 06:43
> OK, latest speculation:
> 
>     1. User upgrades to and launches CKAN v1.31.2
> 
>     2. User refreshes registry (a full refresh that actually changes the available modules, which may not happen right away if the etag is the same)
> 
>     3. User is prompted to reinstall all mods (because `install_size` is set on the available mods but not the installed mods)
> 
>     4. User clicks Yes, and the reinstall succeeds. `registry.json` is saved with the reinstalled mods alongside the old available mods, somehow.
> 
>     5. After this, ZeroMiniAVC becomes auto-uninstallable, which triggers the bug from [[Bug] GUI freezes on switch to changeset tab after refresh removing ZeroMiniAVC dependencies #3707](https://github.com/KSP-CKAN/CKAN/issues/3707)
> 
>     6. The crash from [[Bug] GUI freezes on switch to changeset tab after refresh removing ZeroMiniAVC dependencies #3707](https://github.com/KSP-CKAN/CKAN/issues/3707) prevents the available modules from being updated as they should be during a registry update
> 
>     7. Some users eventually work around the crash, either by running the fixed client, or by finding another way to uninstall ZeroMiniAVC
> 
>     8. For the short term, the etag prevents the registry from updating
> 
>     9. Eventually the etag changes again and a subsequent registry update succeeds
> 
> 
> If this is correct, then we could consider this already fixed with #3707. I thought we had conflicting reports that the bug still happened even after that was fixed and the `last_server_etag` was cleared, but maybe some of those steps didn't occur as we thought, since they're kind of complex.

This matches my experience of opening CKAN today after a couple years away. Did a CKAN reinstall (https://github.com/KSP-CKAN/CKAN/wiki/Clean-and-reinstall-process), now using the dev version of the client from https://ksp-ckan.s3-us-west-2.amazonaws.com/ckan.exe, and I can see new modules now. Definitely ready to ship, IMO :-D Thanks!

FWIW I got this error on the first fresh load of CKAN (on 1.13.2 as well as the dev version):

```
37 [1] INFO CKAN.CmdLine.MainClass (null) - Verbose logging enabled
53 [1] INFO CKAN.CmdLine.MainClass (null) - CKAN started.
53 [1] INFO CKAN.CmdLine.MainClass (null) - CKAN exiting.
69 [1] INFO CKAN.CmdLine.MainClass (null) - CKAN exiting.
269 [1] INFO CKAN.GameInstanceManager (null) - Loading KSP instances
300 [1] INFO CKAN.GameInstance (null) - Initialising c:/program files (x86)/steam/SteamApps/common/Kerbal Space Program/CKAN
Setting up CKAN for the first time...
Creating c:/program files (x86)/steam/SteamApps/common/Kerbal Space Program/CKAN
Scanning for installed mods...
307 [1] INFO CKAN.RegistryManager (null) - Creating new CKAN registry at c:/program files (x86)/steam/SteamApps/common/Kerbal Space Program/CKAN\registry.json
322 [1] INFO CKAN.RegistryManager (null) - Saving CKAN registry at c:/program files (x86)/steam/SteamApps/common/Kerbal Space Program/CKAN\registry.json
591 [1] INFO CKAN.RegistryManager (null) - Loaded CKAN registry at c:/program files (x86)/steam/SteamApps/common/Kerbal Space Program/CKAN\registry.json
672 [1] INFO CKAN.GameInstance (null) - Initialised c:/program files (x86)/steam/SteamApps/common/Kerbal Space Program/CKAN
682 [1] INFO CKAN.CmdLine.CommonOptions (null) - Verbose logging enabled
690 [1] INFO CKAN.GUI.Main (null) - Starting the GUI
979 [1] INFO CKAN.GameInstance (null) - KSP found at C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program
979 [1] INFO CKAN.GameInstance (null) - Initialising C:/Program Files (x86)/Steam/steamapps/common/Kerbal Space Program/CKAN
979 [1] INFO CKAN.GameInstance (null) - Initialised C:/Program Files (x86)/Steam/steamapps/common/Kerbal Space Program/CKAN
979 [1] ERROR CKAN.GUI.ErrorDialog (null) - CKAN is already running for this instance!

If you're certain this is not the case, then delete:
"C:/Program Files (x86)/Steam/steamapps/common/Kerbal Space Program/CKAN\registry.locked"
16637 [1] INFO CKAN.CmdLine.MainClass (null) - CKAN exiting.
```

But I just ran it again and it worked.

**Comment by DaniLucky06** [comment] 2023-03-02 19:50
[registry.zip](https://github.com/KSP-CKAN/CKAN/files/10875306/registry.zip)
My register Hebaru

**Comment by HebaruSan** [comment] 2023-04-08 16:36
This is probably fixed in the new version we just released (hard to say for sure because we weren't able to fully investigate, but it's similar to issues that were fixed and likely shared a common root cause). Please make sure you're using it:

- <https://github.com/KSP-CKAN/CKAN/releases/tag/v1.32.0>

... then make sure you're on a clean install:

- <https://github.com/KSP-CKAN/CKAN/wiki/Clean-and-reinstall-process>

If this problem still occurs after that, we can re-open this. Cheers!

**Closed by HebaruSan** 2023-04-08 16:36 UTC
Labels: Bug, Needs more info, Registry, Network

**Comment by HebaruSan** [comment] 2023-05-07 18:37
Reported as still happening in v1.32.0 on Discord, but not re-opening because I think #3828 will address it (since it eliminates the changed-metadata exception thrown in the middle of refreshing).

**Comment by rfried1** [comment] 2023-07-16 22:26
> deleting the last_server_etag fixed the issue for me, updates are appearing now

Thx. Had the same issue after upgrade CKAN from 1.31.2 to 1.32.0.

Before about 1-2 month ago 1.31.2 start do error out with
**Failed to connect to repository. Exception: `any_of` should not be combined with other properties**
The Error vanished after upgrade, but new updates are ignored until I deleted the _last_server_etag_ from _registry.json_
