### ISSUE TITLE
CKAN doesn't work, weird error.

### ISSUE THREAD

**Issue by KrolCwanPL** [KSP-CKAN/CKAN#2395] opened 2018-03-30 12:44 UTC
**CKAN Version:** 
1.24.0

**KSP Version:** 
1.4.2.2110

**Operating System:** 
Windows 7

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

Problem
-------

**What steps did you take in CKAN?**
I tried to update it, via settings and via Auto Updater (file from github)
then completely redownloading new, fresh CKAN file

**What did you expect to happen?**
uh, help?

**What happened instead?**

CKAN seems to not connect with web, I can't get any new mods or update current mods.
There's a weird error, I screenshotted it but it's in my national language - Polish so I don't think if I can help.

Settings show current version as "0.0.0"
Auto Updater instantly closes itself
In new CKAN problem is still there

**Screenshots:**

![obraz](https://user-images.githubusercontent.com/22566530/38137937-1e5fbf2c-3428-11e8-9dae-b46eed2d9ee5.png)
![obraz](https://user-images.githubusercontent.com/22566530/38137944-27ee2380-3428-11e8-93b3-3d59698b010d.png)
![obraz](https://user-images.githubusercontent.com/22566530/38138013-88a495b0-3428-11e8-89e8-6384720a434a.png)

**CKAN error codes (if applicable):**

**Comment by KrolCwanPL** [comment] 2018-03-30 12:46
And I'm rarely available on GitHub and I very rarely read e-mails. I promise I'll check this topic to give answers to possible questions, but I'm accessible 24/7 on discord - Krolon#0697

**Comment by HebaruSan** [comment] 2018-03-30 12:58
Please note this from the [description of the release](https://github.com/KSP-CKAN/CKAN/releases/tag/v1.24.0):

> You don't need to download AutoUpdate.exe. This is used internally by CKAN when a new version is released.

That leaves the settings error, which is a duplicate of #2300, fixed in #2301. In the meantime you can work around the issue by clicking Continue and adding a fake auth token.

**Closed by HebaruSan** 2018-03-30 12:58 UTC

**Comment by KrolCwanPL** [comment] 2018-03-30 15:11
adding what?

**Comment by HebaruSan** [comment] 2018-03-30 15:12
There's a box in the middle of the settings called Authentication Tokens, and inside that box is a button called New.

**Comment by KrolCwanPL** [comment] 2018-03-30 15:12
And what should I type there?

**Comment by HebaruSan** [comment] 2018-03-30 15:13
Any gibberish you like. Just don't set the host field to a real host that's used for KSP mod downloads.

**Comment by KrolCwanPL** [comment] 2018-03-30 15:14
Should I fill both boxes?

**Comment by HebaruSan** [comment] 2018-03-30 15:14
Can you just try it and see what happens?

**Comment by KrolCwanPL** [comment] 2018-03-30 15:16
eh, nothing
