### ISSUE TITLE
TACLS (TAC Life Support)

### ISSUE THREAD

**Issue by Mimic4** [KSP-CKAN/CKAN#805] opened 2015-04-13 05:00 UTC
When installing TAC Life Support from CKAN, you are prompted to choose a configuration (stock, or Realism Overhaul). However, when installing either CKAN gets upset that the config has tried to overwrite the former and rejects the install. Must be a packaging error or something... 

Cannot install TAC Life Support from CKAN. Tried multiple approaches and installs, problem should be easy to reproduce. 

Good luck, thanks so much for CKAN and happy flying!

**Comment by Dazpoet** [comment] 2015-04-13 07:31
Unable to reproduce in both GUI and Commandline using CKAN 1.6.6 on Windows 7.

Can you tell me the exact steps you are doing to get this error? Do you by any chance have a leftover file somewhere in GameData/ThunderAerospace which might interfere with the install?

**Comment by Dazpoet** [comment] 2015-05-24 01:21
No answer in over 2 months, closing this.

**Closed by Dazpoet** 2015-05-24 01:21 UTC
