### ISSUE TITLE
CKAN GUI not usable on OS X El Capitan

### ISSUE THREAD

**Issue by satoi8080** [KSP-CKAN/CKAN#1501] opened 2015-10-21 09:57 UTC
In the homebrew cache there are mono-4.2.0.179.el_capitan.bottle.1.tar.gz and can-1.14.3.exe
I started Terminal and ran
ckan gui
The Terminal shows:

exception inside UnhandledException handler: Object reference not set to an instance of an object

```
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'System.Windows.Forms.WindowsFormsSynchronizationContext' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Windows.Forms.ThemeEngine' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Windows.Forms.ThemeWin32Classic' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Drawing.KnownColors' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Drawing.GDIPlus' threw an exception. ---> System.DllNotFoundException: libgdiplus.dylib
   at (wrapper managed-to-native) System.Drawing.GDIPlus:GdiplusStartup (ulong&,System.Drawing.GdiplusStartupInput&,System.Drawing.GdiplusStartupOutput&)
   at System.Drawing.GDIPlus..cctor () in <filename unknown>:line 0
  --- End of inner exception stack trace ---
   at System.Drawing.KnownColors..cctor () in <filename unknown>:line 0
  --- End of inner exception stack trace ---
   at System.Drawing.Color.get_Black () in <filename unknown>:line 0
   at System.Windows.Forms.ThemeWin32Classic..cctor () in <filename unknown>:line 0
  --- End of inner exception stack trace ---
   at System.Windows.Forms.ThemeVisualStyles..ctor () in <filename unknown>:line 0
   at System.Windows.Forms.ThemeEngine..cctor () in <filename unknown>:line 0
  --- End of inner exception stack trace ---
   at System.Windows.Forms.SystemInformation.get_MenuAccessKeysUnderlined () in <filename unknown>:line 0
   at System.Windows.Forms.Control..ctor () in <filename unknown>:line 0
   at (wrapper remoting-invoke-with-check) System.Windows.Forms.Control:.ctor ()
   at System.Windows.Forms.WindowsFormsSynchronizationContext..cctor () in <filename unknown>:line 0
  --- End of inner exception stack trace ---
   at System.Windows.Forms.Control..ctor () in <filename unknown>:line 0
   at System.Windows.Forms.ScrollableControl..ctor () in <filename unknown>:line 0
   at System.Windows.Forms.ContainerControl..ctor () in <filename unknown>:line 0
   at System.Windows.Forms.Form..ctor () in <filename unknown>:line 0
   at CKAN.Main..ctor (System.String[] cmdlineArgs, CKAN.GUIUser User, Boolean showConsole) in <filename unknown>:line 0
   at (wrapper remoting-invoke-with-check) CKAN.Main:.ctor (string[],CKAN.GUIUser,bool)
   at CKAN.GUI.Main_ (System.String[] args, Boolean showConsole) in <filename unknown>:line 0
   at CKAN.CmdLine.MainClass.Gui (CKAN.CmdLine.GuiOptions options, System.String[] args) in <filename unknown>:line 0
   at CKAN.CmdLine.MainClass.Main (System.String[] args) in <filename unknown>:line 0
```

---

**It seems that CKAN gui isn't compatible with Mono4, but Mono3 isn't compatible with OS X El Capitan**

**Comment by josefdlange** [comment] 2015-11-02 21:14
+1

**Comment by STLCajun** [comment] 2015-11-08 04:04
+1

**Comment by dcrockwell** [comment] 2015-11-10 04:12
+1

**Comment by kadlugan** [comment] 2015-11-11 22:54
+1

**Comment by gromwalh** [comment] 2015-11-14 14:20
+1

**Comment by rposborne** [comment] 2015-11-26 01:25
+1

**Comment by imichaeldotorg** [comment] 2015-12-05 21:52
+1

**Comment by imichaeldotorg** [comment] 2015-12-06 00:34
I was able to get the gui working by installing the latest Mono from http://www.mono-project.com/download instead of using Mono from homebrew.

**Comment by tetsuchou** [comment] 2015-12-10 17:06
@imichaeldotorg Anyway, it works.
I'm going to edit the guide https://github.com/KSP-CKAN/CKAN/wiki/Installing-CKAN-on-OSX

**Comment by Olympic1** [comment] 2015-12-10 18:08
@tetsuchou If it works you can close this.
@imichaeldotorg thx for finding a fix.

**Comment by kenjura** [comment] 2016-03-31 07:12
The guide does not appear to have been so amended. Installing via homebrew does not work as of 2016-03-31, but installing mono per @imichaeldotorg's comment does work. I have amended the document.

**Comment by plague006** [comment] 2016-04-01 13:46
@imichaeldotorg added the line "_NOTE_: On OS X El Capitan you should download and install [Mono 4](http://download.mono-project.com/archive/4.2.1/macos-10-universal/MonoFramework-MDK-4.2.1.102.macos10.xamarin.universal.pkg)" on line 5 of the wiki article, and it was not reverted. https://github.com/KSP-CKAN/CKAN/wiki/Home/_history

**Comment by tetsuchou** [comment] 2016-04-01 17:23
I added that line 5 right after I said "I'm going to edit the guide" in history d0a0746 , and it's still there. So what's wrong? I'm a little confused.

But the problem remains according to @kenjura , but there is already a solution, so I think it not necessary to reopen this issue.In stead, the wiki should be edited.

@kenjura has added  another note, but I think it is not eye-catching enough, and the guide is a little messy, so I'm going to do some adjustment.

In brief,

El Capitan + Mono3 (Homebrew, automatically) + CKAN = NO
El Capitan + Mono4 (official site, manually) + CKAN = YES
Yosemite + Mono3 (Homebrew, automatically) +CKAN =YES
Yosemite + Mono4 (official site, mannually) + CKAN =NOT TESTED (as for me)

If there are mistakes in what I've said above or wrote in wiki, please point out. I'm just a player and not so familiar about homebrew or Mono.

Thank you.

**Comment by politas** [comment] 2016-04-02 14:02
If CKAN is working on a Homebrew Mono install on Yosemite, then I would expect Yosemite is actually on Mono 4.CKAN doesn't work on Mono 3.

**Comment by Dazpoet** [comment] 2016-04-02 14:25
There used to be a workaround for these kinds of issues which was to install some homebrew package that included libgdiplus.dylib which is, for some reason, lacking in the homebrew installation of certain mono-versions.

**Comment by 100ideas** [comment] 2016-09-23 05:47
I added some log info to this closed thread: https://github.com/KSP-CKAN/CKAN/issues/1844#issuecomment-249102514

basically it looks like mono on osx is having trouble finding the assembly for `UIAutomationWinforms`. I've been browsing around on the mono site, repo, mailing lists etc and haven't found much info about it... just some outdated docs from 2011.

```shell
$ mono --trace=N:nothing ckan.exe gui -v    
...
[0xa3878000:] EXCEPTION handling: System.IO.FileNotFoundException: Could not load file or assembly 'UIAutomationWinforms, Version=1.0.0.0, Culture=neutral, PublicKeyToken=f4ceacb585d99812' or one of its dependencies
```

**Comment by HebaruSan** [comment] 2020-05-16 20:48
Homebrew confirmed as disaster. The wiki currently says not to use it (after one user's remarks suggesting that he was at least able to run ConsoleUI with it).

**Closed by HebaruSan** 2020-05-16 20:48 UTC
Labels: Bug, macOS
