### ISSUE TITLE
[Bug]: Repository update failed

### ISSUE THREAD

**Issue by danilayemets** [KSP-CKAN/CKAN#4112] opened 2024-06-29 09:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows 10

### CKAN Version

v1.34.4

### Games

KSP 1

### Game Version

v1.12.5.3190

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

Yes, only placed a few mods manual

### Describe the bug

When I run CKAN the following text appears:
Scanning for DLCs and manually installed modules...
Loading cached repository data
Updating repositories...
Refreshing game version data
Checking for updates
Object reference not set to an instance of an object.
Repository update failed!

### Steps to reproduce

I launch CKAN, wait a few seconds, it checks and gives this error
![issue](https://github.com/KSP-CKAN/CKAN/assets/174178786/ecb5cfd1-8933-494f-8c67-e6ecbd8dcd66)

**Comment by danilayemets** [comment] 2024-06-29 09:20
Forgot CKAN log
[CKAN.log](https://github.com/user-attachments/files/16039477/CKAN.log)

**Comment by HebaruSan** [comment] 2024-06-29 19:43
Duplicate of #4107

**Comment by HebaruSan** [comment] 2024-06-29 19:43
Hi @danilayemets, thanks for the report. This looks the same as the issues fixed in #4077 and #4078. Can you please try the dev build and let us know if you still have this issue?

- <https://ksp-ckan.s3-us-west-2.amazonaws.com/ckan.exe>

Thanks!

**Comment by danilayemets** [comment] 2024-06-30 08:58
I'm used this dev build and everything is work now, thanks for help!

**Comment by HebaruSan** [comment] 2024-06-30 08:59
Excellent, glad you got it working!

**Closed by HebaruSan** 2024-06-30 08:59 UTC
Labels: Bug, Support, Core (ckan.dll), Duplicate
