### ISSUE TITLE
Mac CKAN crashes on run

### ISSUE THREAD

**Issue by DrEthan77** [KSP-CKAN/CKAN#2485] opened 2018-08-06 17:00 UTC
Background
----------

**CKAN Version:** 
1.25.2

**KSP Version:** 
1.4.5.2243

**Operating System:** 
OSX El Capitan 10.11.6

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
no (other than importing one flag into the squad flags folder)

Problem
-------

**What steps did you take in CKAN?**
None it didn't open

**What did you expect to happen?**
Open CKAN

**What happened instead?**
It crashed, I tried opening both the .app and the .exe, the .app opened for like 1 second then closed and the .exe crash log is below

**Screenshots:**

![screen shot 2018-08-06 at 10 48 09 am](https://user-images.githubusercontent.com/20546072/43729984-40ac4b82-9967-11e8-815c-30477a9b6f20.png)

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment] 2018-08-06 17:04
Duplicate of #2483, fixing in #2482.

**Closed by HebaruSan** 2018-08-06 17:04 UTC
