### ISSUE TITLE
[Feature] Convert AD mods to CKAN control

### ISSUE THREAD

**Issue by APAeroDan** [KSP-CKAN/CKAN#2186] opened 2017-11-14 15:15 UTC
CKAN v1.22.6

Windows 7 sp1

modmanager was previously installed and autodetected with everything working fine
I selected modmanager from CKAN so that CKAN would update it automatically.
That part works fine.  It updated Modmanager, but killed most of my mods due to some automatic dependencies.
I understand why it did it and why autodetect won't overwrite anything from a safety policy standpoint.
its just a good idea.  But can we add a manual override to the autodetect in the instance that it is already installed, but we want it to be updated from CKAN?

I'm sorry if I'm doing this wrong.  I've never used github before.  I usually code by myself.

**Comment by HebaruSan** [comment] 2017-12-15 00:27
Possible duplicate of #949.

**Closed** 2020-05-20 16:53 UTC
Labels: Enhancement
