### ISSUE TITLE
"System.String,CKAN.Version> CKAN.Registry.Installed"

### ISSUE THREAD

**Issue by iNFaMoUZGaming** [KSP-CKAN/CKAN#1345] opened 2015-08-01 00:23 UTC
I'm getting an error which occours everytime I try to install or uninstall a mod, it doesn't break the program but makes me unable to close it without using the task manager.

Here's the error message: 
************** Exception Text **************
System.MissingMethodException: Method not found: 'System.Collections.Generic.Dictionary`2<System.String,CKAN.Version> CKAN.Registry.Installed()'.
   at PartManagerPlugin.PartManagerUI.RefreshInstalledModsList()
   at PartManagerPlugin.PartManagerUI.OnModChanged(CkanModule module, GUIModChangeType changeType)
   at CKAN.Main.PostInstallMods(Object sender, RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)

How can I fix this?

**Comment by iNFaMoUZGaming** [comment] 2015-08-01 00:26
I'm sorry, I'm stupid, it was blatantly obvious as I saw the name of the plugin which was causing the error "Part manager".

**Comment by mgsdk** [comment] 2015-08-01 02:23
I'm not sure if the PartManager plugin works with the latest versions of CKAN. It hasn't been updated in a while.

**Comment by Postremus** [comment] 2015-08-09 06:34
Someone should probably update most of nlight's plugins. Some of them (like the Kerbalstuff plugin) were really nice.

**Comment by Dazpoet** [comment] 2015-08-18 07:32
pretty sure the most stable CKAN version for nlights plugins to work is still 1.5.6, although the changes to the registry makes going back to that one very hard nowadays.

Closing this since the issue is resolved.

**Closed by Dazpoet** 2015-08-18 07:32 UTC
