### ISSUE TITLE
Attempting to add new repository "fails to fetch master list"

### ISSUE THREAD

**Issue by ArceusMI** [KSP-CKAN/CKAN#1289] opened 2015-07-13 23:20 UTC
![ckan list](https://cloud.githubusercontent.com/assets/9756523/8662999/cda78c14-2993-11e5-81e5-4b0ff0ef1e9a.png)

This is what I see when trying to access the list of repositories for CKAN. I click the "New" button, and it hangs for about 30+ seconds before popping up the window to the right. Just uninstalled every mod, going for a fresh install.

**Comment by plague006** [comment] 2015-07-14 00:09
Duplicate of #1242 and fixed in #1264.

The server that hosts the metadata repositories master list is down. No ETA on it coming back up, so in the next version of CKAN that will be corrected (to use an alternate source).

**Closed by plague006** 2015-07-14 00:09 UTC
