### ISSUE TITLE
CmdLine: Installing from a .ckan file that depends on incompatible mods produces an unhelpful error message

### ISSUE THREAD

**Issue by philpax** [KSP-CKAN/CKAN#4108] opened 2024-06-20 09:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

macOS Sonoma, Apple Silicon

### CKAN Version

1.34.4 / Niven

### Games

KSP 1

### Game Version

KSP 1.12.5

### Describe the bug

I wanted to install the [Community Lifeboat Project](https://old.reddit.com/r/KerbalSpaceProgram/comments/1cm8n9y/making_ksp1_into_ksp2_with_mods_the_community/) on my vanilla KSP install on macOS. I installed CKAN from the releases and noted that ConsoleUI had no option for installing ckan files (#4084, which has been fixed in the development branch).

I downloaded the mod list from GitHub and used the command mentioned in that issue to install it (manually navigating to `/Applications/CKAN.app/Contents/MacOS` to use `ckan.exe`):

```
mono ckan.exe install -c ~/Downloads/Community\ Lifeboat\ Modpack2.ckan
```

but it appears that the modpack itself is being interpreted as a module, resulting in installation failing immediately:
```
Module installed-Auto-KSP 2024.05.15.01.03.25 required but it is not listed in the index, or not available for your version of KSP
If you're lucky, you can do a `ckan update` and try again.
Try `ckan install --no-recommends` to skip installation of recommended modules.
Or `ckan install --allow-incompatible` to ignore module compatibility.
```

This name is the identifier of the modlist:
```json
{
    "spec_version": "v1.18",
    "identifier": "installed-Auto-KSP",
    "name": "installed-Auto KSP",
    "abstract": "A list of modules installed on the Auto KSP KSP instance",
    "author": "Myst",
    "version": "2024.05.15.01.03.25",
    "ksp_version_min": "1.12.5",
    "ksp_version_max": "1.12.5",
    "license": "unknown",
    "...": "..."
}
```

`-c` is reading the file, as the behaviour is different without the switch:
```
# mono ckan.exe install ~/Downloads/Community\ Lifeboat\ Modpack2.ckan   
Module [home]/Downloads/Community Lifeboat Modpack2.ckan required but it is not listed in the index, or not available for your version of KSP
```

This happens with both versions of the modpack `.ckan` in that thread, and with both local and remote installations (i.e. `mono ckan.exe install -c https://raw.githubusercontent.com/mystwalkerKSP/Kerbal-Space-Program-Community-Lifeboat-Project/main/Community%20Lifeboat%20Modpack2.ckan` also fails.)

I'm unsure if this is specific to macOS / Rosetta 2; please feel free to narrow the issue if it is. Just to confirm, my game version appears to be correct:
```
# mono ckan.exe compat list
Version      Actual
-----------  ------
1.12.5.3190  True  
```

### Steps to reproduce

- Install the latest version of KSP from Steam on macOS on an Apple Silicon with Rosetta 2.
- Start the game at least once and confirm it starts up.
- Install CKAN 1.34.4 into the Applications directory.
- `cd /Applications/CKAN.app/Contents/MacOS`
- `mono ckan.exe install -c https://raw.githubusercontent.com/mystwalkerKSP/Kerbal-Space-Program-Community-Lifeboat-Project/main/Community%20Lifeboat%20Modpack2.ckan` or `mono ckan.exe install -c https://share.snowlab.tech/-ruvvmPQwgn` (different exports of the ~same modlist):
  - `Module installed-Auto-KSP 2024.05.15.01.03.25 required but it is not listed in the index, or not available for your version of KSP`
  - `Module lifeboat-modpack 2024.05.07.03.05.44 required but it is not listed in the index, or not available for your version of KSP`

**Comment by philpax** [comment] 2024-06-20 10:00
`# mono ckan.exe install $(jq -r '.depends | map(.name) | join(" ")' ~/Downloads/Community\ Lifeboat\ Modpack2.ckan)` (i.e. direct CLI installation by injecting the deps into the commandline) fails on AT-Utils, as reported in #4084. Adding `--allow-incompatible` fixes this.

Is it possible that the failure with AT-Utils is being propagated upwards and being reported as a failure of the modpack?

**Comment by JonnyOThan** [comment] 2024-08-06 15:25
> Is it possible that the failure with AT-Utils is being propagated upwards and being reported as a failure of the modpack?

Yes that's exactly what's happening.  The error message just isn't very helpful.

**Comment by heyimastopsign** [comment] 2024-09-09 06:15
Is there any way to force override this?

**Comment by JonnyOThan** [comment] 2024-09-09 12:01
@heyimastopsign This issue is saying that the error message should be changed to something that actually indicates what the problem is.  I'm not sure what you want to "force override."

If you mean you want to force ckan to install incompatible mods, it was in the screenshot you posted in the other issue.

![image](https://github.com/user-attachments/assets/17eea7ab-e130-442e-8100-0f6c9b2a96be)

**Comment by heyimastopsign** [comment] 2024-09-10 00:24
<img width="1021" alt="Screenshot 2024-09-10 at 10 23 45 AM" src="https://github.com/user-attachments/assets/38716418-6bef-463c-9815-3b65445b7167">
Sorry for being such an annoyance, but that appears to not work.

**Comment by heyimastopsign** [comment] 2024-09-10 00:29
Various attempts by an idiot 
<img width="1044" alt="Screenshot 2024-09-10 at 10 29 13 AM" src="https://github.com/user-attachments/assets/a6d4c4d1-a2cf-4ce5-bc82-2fbe5fe66cac">

**Comment by JonnyOThan** [comment] 2024-09-12 15:36
@heyimastopsign can you post the .ckan file you're using?

**Comment by heyimastopsign** [comment] 2024-09-14 04:22
@JonnyOThan Sure, here you go.
[installed-Auto KSP-2024-09-05_21-08-59.ckan.zip](https://github.com/user-attachments/files/17000977/installed-Auto.KSP-2024-09-05_21-08-59.ckan.zip)

**Comment by heyimastopsign** [comment] 2024-09-18 03:08
> @heyimastopsign can you post the .ckan file you're using? And what version of KSP do you have installed?

Oh, I just realised I didn't let you know what version. It's 1.12.5. Sorry!

**Comment by HebaruSan** [comment] 2024-10-04 01:05
This is extremely thorny and requires core changes to the relationship resolver, but at last, some progress!

![image](https://github.com/user-attachments/assets/439b4f1f-0cbb-4b59-95f9-75601b812c30)

**Comment by JonnyOThan** [comment] 2024-10-08 17:35
Hey @HebaruSan  if you check above: https://github.com/KSP-CKAN/CKAN/issues/4108#issuecomment-2339382787 - `--allow-incompatible` was used but there was still some kind of error.  Any idea what that's about?  I notice that the file name isn't exactly the same as the one that was posted later though, so maybe that's not a repro case.

**Comment by HebaruSan** [comment] 2024-10-08 17:36
@JonnyOThan yes https://github.com/KSP-CKAN/CKAN/issues/4084#issuecomment-2100950480

**Comment by JonnyOThan** [comment] 2024-10-08 17:41
that seems...surprising?  Any thoughts on changing it?

**Comment by HebaruSan** [comment] 2024-10-08 17:45
Aaaaaanyway, back to the actual topic, here is the output for @heyimastopsign's modpack with those same changes and no extra versions other than 1.12.5 marked as compatible in CKAN:

```
> .\_build\ckan.exe install -c '..\..\Downloads\support\heyimastopsign\installed-Auto KSP-2024-09-05_21-08-59.ckan'
```

<details><summary>Click to expand output</summary>

Unsatisfied dependency B9PartSwitch needed for: BluedogDB v1.13.0 (needed for CommunityLifeBoat 2024.09.05.11.08.59); BluedogDB v1.13.0 (needed for BluedogDB-CommunityCategoryKit v1.13.0, needed for CommunityLifeBoat 2024.09.05.11.08.59); BluedogDB v1.13.0 (needed for BluedogDB-Methalox v1.13.0, needed for CommunityLifeBoat 2024.09.05.11.08.59); CryoTanks 1.6.6 (needed for BluedogDB-Methalox v1.13.0, needed for CommunityLifeBoat 2024.09.05.11.08.59); CryoEngines 1:2.0.7 (needed for CommunityLifeBoat 2024.09.05.11.08.59); CryoTanks 1.6.6 (needed for CryoEngines 1:2.0.7, needed for CommunityLifeBoat 2024.09.05.11.08.59); CryoEngines 1:2.0.7 (needed for CryoEngines-NFAero 2.0.7, needed for CommunityLifeBoat 2024.09.05.11.08.59); CryoTanks 1.6.6 (needed for CryoEngines 1:2.0.7, needed for CryoEngines-NFAero 2.0.7, needed for CommunityLifeBoat 2024.09.05.11.08.59); CryoEngines 1:2.0.7 (needed for CryoEnginesExtensions 1.0.3, needed for CommunityLifeBoat 2024.09.05.11.08.59); CryoTanks 1.6.6 (needed for CryoEngines 1:2.0.7, needed for CryoEnginesExtensions 1.0.3, needed for CommunityLifeBoat 2024.09.05.11.08.59); CryoTanks 1.6.6 (needed for CommunityLifeBoat 2024.09.05.11.08.59); CryoTanks 1.6.6 (needed for CryoTanks-Core 1.6.6, needed for CommunityLifeBoat 2024.09.05.11.08.59); FarFutureTechnologies 1.3.0 (needed for CommunityLifeBoat 2024.09.05.11.08.59); CryoTanks 1.6.6 (needed for FarFutureTechnologies 1.3.0, needed for CommunityLifeBoat 2024.09.05.11.08.59); SpaceDust 0.5.3 (needed for FarFutureTechnologies 1.3.0, needed for CommunityLifeBoat 2024.09.05.11.08.59); HabTech2 1.0.0 (needed for CommunityLifeBoat 2024.09.05.11.08.59); HabTechRobotics v1.0.1 (needed for HabTech2 1.0.0, needed for CommunityLifeBoat 2024.09.05.11.08.59); HeatControl 0.6.2 (needed for CommunityLifeBoat 2024.09.05.11.08.59); KerbalAtomics 1:1.3.4 (needed for CommunityLifeBoat 2024.09.05.11.08.59); CryoTanks 1.6.6 (needed for KerbalAtomics 1:1.3.4, needed for CommunityLifeBoat 2024.09.05.11.08.59); Mk2Expansion 2:1.9.1.4 (needed for CommunityLifeBoat 2024.09.05.11.08.59); Mk3Expansion 1.6.1.4 (needed for CommunityLifeBoat 2024.09.05.11.08.59); ModularLaunchPads 2.7.0 (needed for CommunityLifeBoat 2024.09.05.11.08.59); NearFutureAeronautics 2.1.2 (needed for CommunityLifeBoat 2024.09.05.11.08.59); NearFutureElectrical 1.2.3 (needed for CommunityLifeBoat 2024.09.05.11.08.59); NearFutureElectrical 1.2.3 (needed for NearFutureElectrical-DecayingRTGs 1.2.3, needed for CommunityLifeBoat 2024.09.05.11.08.59); NearFutureExploration 1.1.3 (needed for CommunityLifeBoat 2024.09.05.11.08.59); NearFutureLaunchVehicles 2.2.1 (needed for CommunityLifeBoat 2024.09.05.11.08.59); NearFuturePropulsion 1.3.6 (needed for CommunityLifeBoat 2024.09.05.11.08.59); NearFutureSolar 1.3.3 (needed for CommunityLifeBoat 2024.09.05.11.08.59); NearFutureSolar 1.3.3 (needed for NearFutureSolar-Core 1.3.3, needed for CommunityLifeBoat 2024.09.05.11.08.59); NearFutureSpacecraft 1.4.5 (needed for CommunityLifeBoat 2024.09.05.11.08.59); OmicronFlyingSpaceCar 0.6.6.6 (needed for CommunityLifeBoat 2024.09.05.11.08.59); PlanetsideExplorationTechnologies 1.0.2 (needed for CommunityLifeBoat 2024.09.05.11.08.59); RaginCaucasian 1.5.3.1 (needed for CommunityLifeBoat 2024.09.05.11.08.59); RocketMotorMenagerie v1.1.2 (needed for CommunityLifeBoat 2024.09.05.11.08.59); ShuttleOrbiterConstructionKit 1.1.8 (needed for CommunityLifeBoat 2024.09.05.11.08.59); HabTechRobotics v1.0.1 (needed for ShuttleOrbiterConstructionKit 1.1.8, needed for CommunityLifeBoat 2024.09.05.11.08.59); ShuttleOrbiterConstructionKit 1.1.8 (needed for ShuttleOrbiterConstructionKitRecolored 1.3, needed for CommunityLifeBoat 2024.09.05.11.08.59); HabTechRobotics v1.0.1 (needed for ShuttleOrbiterConstructionKit 1.1.8, needed for ShuttleOrbiterConstructionKitRecolored 1.3, needed for CommunityLifeBoat 2024.09.05.11.08.59); ShuttlePayloadDeliverySystems 3.0 (needed for CommunityLifeBoat 2024.09.05.11.08.59); BluedogDB v1.13.0 (needed for ShuttlePayloadDeliverySystems 3.0, needed for CommunityLifeBoat 2024.09.05.11.08.59); ShuttleOrbiterConstructionKit 1.1.8 (needed for ShuttlePayloadDeliverySystems 3.0, needed for CommunityLifeBoat 2024.09.05.11.08.59); HabTechRobotics v1.0.1 (needed for ShuttleOrbiterConstructionKit 1.1.8, needed for ShuttlePayloadDeliverySystems 3.0, needed for CommunityLifeBoat 2024.09.05.11.08.59); SillyPhotonDrives 1.0.1 (needed for CommunityLifeBoat 2024.09.05.11.08.59); SpaceDust 0.5.3 (needed for SpaceDustUnbound 1.0.2, needed for CommunityLifeBoat 2024.09.05.11.08.59); StationPartsExpansionRedux 2.0.11 (needed for CommunityLifeBoat 2024.09.05.11.08.59); StationPartsExpansionRedux 2.0.11 (needed for StationPartsExpansionRedux-IVAs 2.0.11, needed for CommunityLifeBoat 2024.09.05.11.08.59); StockWaterfallEffects 0.8.0 (needed for CommunityLifeBoat 2024.09.05.11.08.59); WaterfallExtensions 0.4.0 (needed for CommunityLifeBoat 2024.09.05.11.08.59); Wyvern-5 0.5 (needed for CommunityLifeBoat 2024.09.05.11.08.59)

Unsatisfied dependency SimpleAdjustableFairings needed for: BluedogDB v1.13.0 (needed for CommunityLifeBoat 2024.09.05.11.08.59); BluedogDB v1.13.0 (needed for BluedogDB-CommunityCategoryKit v1.13.0, needed for CommunityLifeBoat 2024.09.05.11.08.59); BluedogDB v1.13.0 (needed for BluedogDB-Methalox v1.13.0, needed for CommunityLifeBoat 2024.09.05.11.08.59); BluedogDB v1.13.0 (needed for ShuttlePayloadDeliverySystems 3.0, needed for CommunityLifeBoat 2024.09.05.11.08.59); TantaresSAF v3.0 (needed for CommunityLifeBoat 2024.09.05.11.08.59)

Unsatisfied dependency AdditionToTantaresSP 0.2 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency AircraftCarrierAccessories 1:1.9.1 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency AirplanePlus 26.5 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency AoATechnologies 1.4.1.1 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency AutomatedAerialRefueling 1:1.9.1 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency B9 1:v6.6.0 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency B9AerospaceHX 1:v6.6.0 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency B9AerospaceLegacy 1:v6.6.0 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency B9AnimationModules v1.7.0 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency B9HXReconfig 1.1.0 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency B9PartSwitch v2.20.0 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency B9-props needed for: RecycledParts 0.2.4.2 (needed for CommunityLifeBoat 2024.09.05.11.08.59)

Unsatisfied dependency B9-props 1:v6.6.0 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency BavarianAerospaceTubes 0.1.0 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency BeamedPowerPlugin 1.1.0 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency BeyondSpace1999 1.0.0 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency BonVoyage 1:1.4.1 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency ChopShop 1:0.11.4.5 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency CompletelyNonAggressiveRocketry 1.0.2 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency ContractConfigurator-EpicSpaceProgram 0.5 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency ContractConfigurator-PlanesWithPurposes 1.6.1 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency ContractsWindowPlus 9.4 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency CST100Starliner v2.1 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency DaedalusConsortiumMegastationsContinued 0.3 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency DavonTCsystemsMod 1:0.1.0.5 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency DeepSpaceSurfaceHabitatUnitPack 1.10.1 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency DMagicOrbitalScience 1.4.3 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency DMTanks-AeroRTG 1:1.1.0.1 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency DMTanks-CargoBays 1:1.1.0.1 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency DMTanks-Fuselage 1.1.0.2 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency DMTanks-SphericalTanks 1:1.1.0.0 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency DunaDirect 1.10.1 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency ExplodiumBreathingEngines 2:1.8.0 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency ExtremePlaneContracts 1.2 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency FirespitterExtended 2.2 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency FishyAntiMissileSpam 1.5 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency FuelTanksPlus 2.0.2 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency GoliathPatch v0.0.0.2 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency Hangar 3.6.2.2 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency HindMI24andMI17partspack 1.0.0 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency HueyAndChinookHelicopterPartsPack 1.0.1 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency HyperEdit 1.5.8.0 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency Impact v1.8.0 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency ImprovedTreeEnginePlacement v1.4.0 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency ImpulseParty 0.6 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency InternalRCS 1.3 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency JamesWebbForKerbal 1.12.x needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency JDLiquidFuelCell 1 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency KARE 1.2 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency KerbalField 3:V2.5.1 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency KerbalFlightworksCompany Relase_6 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency KerbalMotorbikes 1.1.0 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency KerbinRoverRedux 1.1.0 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency KerbinSideRemastered 1.0.1 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency KerbinSideRemasteredGAP 1:v2.1.7 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency KerbinSideRemasteredGapExtras v1.0.5 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency KerbinSideRemasteredTLA v2.0.0 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency KeridianDynamicsVesselAssembly 0.8.99.5-prerelease needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency KerwisChinaAerospacePack 1.1.3 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency kOS-SpaceCore 1.1.1 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency KSCHarbor 1.2 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency KSPRescueContractFix 1.1.0 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency LoadingTipsPlus V1.9 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency MarkIVSpaceplaneSystem 3.2.0 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency MEVHeavyIndustries 1:1.0.2 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency MiniMoke 2.0.1 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency MissingHistory 1.9.3 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency Mk2Y 0.0.5.0 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency Mk3HypersonicSystems 1:1.2 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency MoarFEConfigs 1.0.5.2 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency MoarKerbals 1.1.1.0 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency NearFutureConstruction 1.3.1 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency NetherdyneMassDriver 1:1.3.4.2 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency NewTantaresLV v16.1 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency OPTSpacePlaneMain 1:3.1.1 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency OPTSpacePlaneParts 1:3.1.2 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency PhoenixIndustries 1.7 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency PlusFlags 1.6 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency PreciseManeuver 2:2.4.99.0-adoption needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency ProceduralFairings-ForEverything v0.3.0 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency ProvenanceAerospace v1.0 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency Pteron 0.9.0.0 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency SCANsat v20.4 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency ShadowWorksStockalikeSLSandMore 2.0.5.1 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency SimpleLogistics 2.0.5.0 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency SinkEmAll needed for: MOISTUnderwaterTechnologies 1.12.1 (needed for CommunityLifeBoat 2024.09.05.11.08.59)

Unsatisfied dependency SixCrewScienceLab 1.2 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency SpikeX 1.01 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency SRC 1.0.0 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency StockalikeAircraftCarrierDecks 1.0.1 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency StockalikeMiningExtension 1.1.6 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency SuperBattery 1.2.3 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency TeaKettleRCS 1.2 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency TRPHire 0.6.11 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency VentralDrill 1.11.1 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency VexarpIVA 0.6.1 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency WorkingUnderwaterLite 1.2.1 needed for: CommunityLifeBoat 2024.09.05.11.08.59

Unsatisfied dependency XenonISRU 0.0.1 needed for: CommunityLifeBoat 2024.09.05.11.08.59
If you're lucky, you can do a `ckan update` and try again.
Or `ckan install --allow-incompatible` to ignore module compatibility.

</details>

It's extremely long and verbose, but there are a *ton* of problems to report, so I'm ambivalent about that.

**Comment by HebaruSan** [comment] 2024-10-08 18:20
About time to update that error footer with some advice that might actually help, I suppose.

```
You can use the `ckan compat` commands to change which game versions are treated as compatible.
If a newly compatible version was just released, you can do a `ckan update` and try again.
Or `ckan install --allow-incompatible` to ignore compatibility of the modules on the command line (but not dependencies).
```

**Closed** 2024-10-17 18:13 UTC
Labels: Enhancement, Cmdline, Core (ckan.dll), Relationships
