### ISSUE TITLE
Can't add hidden KSP directory

### ISSUE THREAD

**Issue by Enderman-Lelo** [KSP-CKAN/CKAN#793] opened 2015-03-18 08:16 UTC
Build: Linux Mint 17.1
CKAN 1.6.5

Upon first load of CKAN, when clicking "Add new" you would have to browse to the KSP folder, but if you have the KSP folder under a hidden directory, the hidden files wouldn't show up in the CKAN browser window. 

(Steam on linux will install under /home/username/.local/share/Steam/steamapps/)
.local is hidden.

CKAN framework should have an option to show hidden files.

**Comment by mgsdk** [comment] 2015-03-18 10:37
Duplicate of https://github.com/KSP-CKAN/CKAN-support/issues/58.

**Comment by birdspider** [comment] 2015-03-18 12:57
I personally recommend a symlink from `~/games/steam/` to `~/.local/share/Steam/steamapps/common` - workes nicely for all games.  Any other name/dir than `~/games/steam/` is of course possible.

**Comment by plague006** [comment] 2015-05-21 20:11
KSP-CKAN/CKAN-support#58 is #894

**Comment by plague006** [comment] 2015-07-20 04:13
Closing in favour of #894

**Closed by plague006** 2015-07-20 04:13 UTC
