### ISSUE TITLE
[Bug] Briefly summarize your issue here

### ISSUE THREAD

**Issue by Sergenplaysmobile** [KSP-CKAN/CKAN#3752] opened 2022-12-25 02:27 UTC
Background
----------
* Operating System: 
* CKAN Version: 
* KSP Version: 1.12.3

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**  yes

Problem
-------
**Describe the bug** whenever i press changeset it crashes or stops working even after i restart the program

**Steps to reproduce** idk
* Go to...
* Click on...
* See error

**Expected behavior**

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment] 2022-12-25 02:28
Thanks, we just finished fixing this, you can try the latest dev build if you'd like to test:

- https://ksp-ckan.s3-us-west-2.amazonaws.com/ckan.exe

**Comment by HebaruSan** [comment] 2022-12-25 02:29
Duplicate of #3707

**Closed by HebaruSan** 2022-12-25 02:29 UTC
