### ISSUE TITLE
Mac version doesn't find my external Hard disk

### ISSUE THREAD

**Issue by rbcsky5** [KSP-CKAN/CKAN#2347] opened 2018-03-06 06:34 UTC
Background
----------

**CKAN Version:** 
1.24.0

https://github.com/KSP-CKAN/CKAN/files/1756778/CKAN.zip (Using this version since the original .DMG version didn't work)

**KSP Version:** 
1.3.1

**Operating System:** 
10.13.3 (17D102)

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 

Problem
-------

**What steps did you take in CKAN?**
Open the app and tried to select my KSP path

**What did you expect to happen?**
Let me select my external harddisk

**What happened instead?**
It can't be found

**Screenshots:**

![screenshot](https://i.imgur.com/CebCjRA.png)
(The HDD named as "mac stuffs" is my external disk. Those red bars are just names of my other unrelated folders on my desktop.)

![screenshot2](https://user-images.githubusercontent.com/37041568/37139524-2e098f5c-22e9-11e8-9e86-f9cdf1c3524d.png)

![screenshot3](https://user-images.githubusercontent.com/37041568/37139583-6ad831fe-22e9-11e8-8345-b70725c42caf.png)

**Comment by HebaruSan** [comment] 2018-03-06 16:00
What's listed under "My Computer"? That's where Windows typically shows your disks.

**Comment by rbcsky5** [comment] 2018-03-07 22:28
"Personal" Which is mac's version of "User documents"

**Comment by HebaruSan** [comment] 2018-03-07 22:50
Hmm, are you sure? From the screenshot it looks like both of those folders are under Desktop, next to each other rather than one contained in the other. Did you try double clicking on My Computer?

**Comment by rbcsky5** [comment] 2018-03-08 07:57
<img width="564" alt="screen shot 2018-03-08 at 15 55 30" src="https://user-images.githubusercontent.com/37041568/37139524-2e098f5c-22e9-11e8-9e86-f9cdf1c3524d.png">

<img width="566" alt="screen shot 2018-03-08 at 15 56 27" src="https://user-images.githubusercontent.com/37041568/37139583-6ad831fe-22e9-11e8-8345-b70725c42caf.png">


I am sure

**Comment by linuxgurugamer** [comment] 2018-03-08 12:34
I can confirm both problems, first, that the CKAN.dmg version doesn't work, and second, that extra drives aren't shown.

**Comment by Maxzhao1999** [comment] 2018-03-08 22:46
The CKAN.dmg sends me to the CKAN wiki page

**Comment by rbcsky5** [comment] 2018-03-08 23:27
@Maxzhao1999 You will need mono 5 and this file ( https://github.com/KSP-CKAN/CKAN/files/1756778/CKAN.zip ) to work

**Comment by HebaruSan** [comment] 2018-03-09 02:46
@rbcsky5, thanks, it's a big help to our investigations when we can firmly rule out user error. :)
My gut says this is a Mono bug (that file dialog is a standard one, not CKAN-owned), but I'll check whether there are extra flags we can pass to control the popup.

In the meantime, running `ckan consoleui` in a Terminal might work for you. You would have to type the full path to your KSP folder yourself (I think it would start with `/Volumes` ?), but it shouldn't be limited like the GUI apparently is.

**Comment by HebaruSan** [comment] 2018-03-09 03:54
Found someone else suffering from this, with no solution:

- https://stackoverflow.com/questions/34503898/monos-system-windows-forms-openfiledialog-wont-allow-me-to-access-usb-drive-i

I experimented with [`OpenFileDialog.CustomPlaces`](https://msdn.microsoft.com/en-us/library/system.windows.forms.filedialogcustomplacescollection(v=vs.110).aspx), but it seems to do nothing, even on Linux (where My Computer _does_ contain all the drives). The rest of [`OpenFileDialog`](https://msdn.microsoft.com/en-us/library/system.windows.forms.openfiledialog(v=vs.110).aspx)'s properties don't seem to relate to controlling which drives show up.

**Comment by rbcsky5** [comment] 2018-03-09 07:26
LOL if it is a bug of mono would you mind to open an issue there for us/me? Since I have no idea what to do if they ask about codes.

**Comment by HebaruSan** [comment] 2018-03-10 07:50
Confirmed, Mono's `FileDialog` hard-codes a Linux-specific path `/proc/mounts` in its mounted device search, and it completely ignores any exceptions that may cause. This path doesn't exist on MacOSX from what I can tell, hence Mono not being able to find mounted devices on MacOSX:

https://github.com/mono/mono/blob/e456f910530906612291e0db09ac81d04e4b87ca/mcs/class/System.Windows.Forms/System.Windows.Forms/FileDialog.cs#L4736-L4740

I did a quick search for "FileDialog" in Mono's issues list and nothing came up, so this may not have been reported formally yet. I'm guessing they'd rather have a pull request for a fix, though, and I don't have a Mac with which to do the development. The only person I know doing any CKAN-related development on a Mac recently is @phardy, but I don't know whether he'd be interested in this kind of problem.

**Comment by HebaruSan** [comment] 2018-03-13 17:32
This is a duplicate of #1276, though the appearance of the window apparently has changed since then.
I'm going to close that one and keep this one, though, since this one has useful investigation info in it.

**Comment by rbcsky5** [comment] 2018-03-26 16:50
@HebaruSan According to this post: https://github.com/mono/mono/pull/7791

it was fixed by this may be unstable file

https://download.mono-project.com/archive/nightly/macos-10-universal/MonoFramework-MDK-master@e610e443cd6-dirty-5.13.0.559.macos10.xamarin.universal.pkg

May be you guys wanna add this to to ckan page :)

**Comment by HebaruSan** [comment] 2018-03-26 19:37
Cool! Nice job getting this addressed, @rbcsky5!

I don't think we necessarily want to recommend nightly builds in general, in case they have other bugs that would cause problems for people, but it's good to have an option for folks who need to use external drives, and we can update the wiki once there's a new release of Mono with this fix.

No need to keep this issue open anymore; CKAN isn't going to do development on it, and Mono already did.

**Closed by HebaruSan** 2018-03-26 19:37 UTC
Labels: GUI, Mono, OS X, ★★☆
