### ISSUE TITLE
Disk Full exception

### ISSUE THREAD

**Issue by gitAcceptance** [KSP-CKAN/CKAN#1422] opened 2015-08-27 21:02 UTC
I don't know if you care, but when trying to apply updates the program crashes with an unhandled exception if the disk it's trying to write to is full. I know it's silly but I figured you might want to know.

**Comment by plague006** [comment] 2015-08-27 21:44
Can you tell us the message that CKAN gives you, your CKAN version, your operating system, and what mod(s) you were trying to update? Thanks.

Possible duplicate of #1236.

**Comment by sramsay64** [comment] 2016-12-25 14:15
This bug shouldn't be closed because you haven't fixed it. I'm a bit lazy with cleaning my files and I've had this a number of times. Before you ask me to add all the specs etc. Try it yourself, fill up your hard drive with junk and install a ton of mods to some vanilla copy of KSP. For such a textbook error you should have the burden of proof to show that there is some mechanism in the code or external libraries for handling free space errors. Therefor I wouldn't close this until such evidence is shown.

P.S. for Linux users:
`dd if=/dev/urandom of=~/bigJunkFile bs=1M count=<megabytes of free space you have minus a few>`

**Comment by politas** [comment] 2016-12-25 21:06
This was closed because it's a duplicate of #1236

**Closed** 2016-12-25 21:06 UTC
Labels: bug, ckan.dll, ★☆☆
