### ISSUE TITLE
Sort by 'Last Updated'

### ISSUE THREAD

**Issue by legacynl** [KSP-CKAN/CKAN#1519] opened 2015-11-15 11:54 UTC
So with the new update I keep finding myself browsing the KSP forums to check if the mods I'm interested are updated to 1.0.5. This takes a lot of time, and it is easy for certain mods to be buried to the Xth page because other mods have more users.

So I thought it would be neat if the CKAN modlist could be sorted on when a mod was updated. So for example sorting on "Last updated" will give you a list that has the mods that were most recently updated on top. So if this were the case, you would only need to keep an eye on the CKAN-list, and install the mods that you like that pop up at the top.

**Comment by CharonM72** [comment] 2016-05-16 18:23
I want to second this. This would be super useful, even to see which mods were updated recently and which were not, but especially for new version upgrades.

**Comment by HebaruSan** [comment] 2018-08-26 14:47
This is a duplicate of #1155.

**Closed by HebaruSan** 2018-08-26 14:47 UTC
Labels: Enhancement, Spec, ckan.dll, ★☆☆
