### ISSUE TITLE
Mods disappear from the Manage Mods tab

### ISSUE THREAD

**Issue by PetertheGray** [KSP-CKAN/CKAN#1799] opened 2016-06-26 23:13 UTC
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

CKAN Version:v1.18.0-0geeb9127 (beta)

Operating System: Latest Windows 10 version

The issue you are experiencing: Mods disappearing from the Manage Mods tab and sometimes not installing when being installed

How to recreate this issue: Install multiple mods that have dependencies and/or recommendations (in the case of recommendations, install them) (sometimes works)

CKAN error codes (if applicable): Did not think of copying them at the time, was unable to recreate

![bug](https://cloud.githubusercontent.com/assets/16978149/16365572/a775d692-3bc9-11e6-9812-f5ac87f55648.png)

**Comment by nobodyhasthis** [comment] 2016-06-27 12:02
@PetertheGray was this a temporary problem caused by the delisting of module manager?
if you refresh the locally held data does it clear the problem ?

**Comment by PetertheGray** [comment] 2016-06-27 12:49
Refreshing does not clear the problem.

**Comment by niekbergboer** [comment] 2016-06-27 14:42
Not sure if my problem is the same, but in my case the Real Solar System mod does not exist anymore, and even reinstalling KSP and ckan does not work.

**Comment by PetertheGray** [comment] 2016-06-30 14:49
Some mods that required updates just appeared out of nowhere, so...

**Comment by sparkybear** [comment] 2016-07-05 00:09
This issue has recently popped up in my CKAN installation. After uninstalling mods, specifically USI and the associated mods, they no longer appear in CKAN at all. Refreshing CKAN, or doing a 'clean' CKAN installation don't seem to solve the problem. The mods were reinstalled manually, but are not picked up by CKAN at all.

**Comment by PetertheGray** [comment] 2016-07-05 15:33
I remember USI causing most of it for me.

On Monday, July 4, 2016, Ryan Richardson <notifications@github.com> wrote:
> This issue has recently popped up in my CKAN installation. After
uninstalling mods, specifically USI and the associated mods, they no longer
appear in CKAN at all. Refreshing CKAN, or doing a 'clean' CKAN
installation don't seem to solve the problem. The mods were reinstalled
manually, but are not picked up by CKAN at all.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci6.googleusercontent.com/proxy/yuOfuJuU7jUbTMO5i2tvquNP5stE_FLJeDkZMUNevkRw4r3LCZEJelrjbePWGj2xy-mBpV-viYOEttlQodAIm5h_x62Lm_wKe_eUyiEZKuk3eEYIO-rUMsB2xWFv6xk4nq8IqBAhXL-NltUrwkN_4U5sV9p4eA=s0-d-e1-ft#https://github.com/notifications/beacon/AQMQ5eX24ZVsf7-nheqbmAAz7Dks1MbZks5qSaCugaJpZM4I-qsp.gif
>

**Comment by sparkybear** [comment] 2016-07-05 19:50
I basically did a complete removal of all Mods and CKAN files, but the mods are still not showing up for whatever reason.

**Comment by politas** [comment] 2016-07-24 20:05
All the USI mods disappeared due to a dependency failure for a time. They should all be back now.

**Comment by PetertheGray** [comment] 2016-07-25 16:22
Yep, I just reinstalled a lot of RoverDude's mods, it is fixed. I am rather new here, do I close the bug or does a moderator do it?

**Comment by politas** [comment] 2016-07-25 22:52
Since you opened the issue, you could close it if you feel it has been resolved. In this case, another user has reported experiencing the same issue, so it might be better to give them a chance to weigh in. It is possible for people to re-open closed issues and comment on closed issues, so it wouldn't be a problem either way.

**Comment by PetertheGray** [comment] 2016-07-25 23:18
Oops just accidentally closed it

**Comment by politas** [comment] 2016-07-26 03:50
Barring further reports by @sparkybear , let's call this closed.

**Closed by politas** 2016-07-26 03:50 UTC

**Comment by sparkybear** [comment] 2016-07-26 04:23
It's fixed on my end. There was a very old KSP folder that was empty that started to be picked up for some reason. Removing that fixed the issue, though I don't know why it started to pick that up after months of working correctly.
