### ISSUE TITLE
CKAN says installed mod needs upgrading, but it is already upgraded

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/CKAN#959] opened 2015-05-26 03:15 UTC
KWRocketry apparently installs Moduleanimateemissive.  When I went to do an update, I got the following message:

About to remove:

Done!

Installing previously uninstalled mod ModuleAnimateEmissive
    ModuleAnimateEmissive provided by KWRocketry already installed, skipped
Success!

**Comment by Dazpoet** [comment] 2015-05-26 09:39
What are you attempting to update? When did you last Refresh?

KWRocketry used to provide ModuleAnimateEmissive but it was changed [here](https://github.com/KSP-CKAN/NetKAN/pull/1402) but I supposed that if you still have that version of KW installed then yes you do have it installed still.

You can probably resolve any and all inconsistencies by removing and reinstalling KW.

**Comment by linuxgurugamer** [comment] 2015-05-26 10:33
I see, thank you.

Is it possible that when I updated KW, that it didn't remove the old ModuleAnimateEmissive?  If so, is that a problem?

Anyway, your suggestion worked, so go ahead and close this, I'm leaving it open so you can see this comment

**Comment by Dazpoet** [comment] 2015-05-26 10:35
You can easily check if it left the Module by searching your GameData for a folder named ModuleAnimateEmissive which in that case should have a similarly named .dll file in it.

If that file is there please report back since it means we have a consistency problem in the uninstallation step :o 

Closing this for now

**Comment by valuial** [comment] 2015-05-26 10:42
Same Problem here:
 ckan update; ckan upgrade just finished;
Package ModuleAnimateEmissive not installed, but KWRocketry 2.7, which ckan reports as newest version, provides ModuleAnimateEmissive and contains ModuleAnimateEmissive/plugin/ModuleAnimateEmissive.dll

**Comment by Dazpoet** [comment] 2015-05-26 11:10
does the problem persist after a remove and reinstall of KW?

**Comment by valuial** [comment] 2015-05-26 14:02
Remove KWRocketry removes the ModuleAnimateEmissive Files, reinstall of KWRocketry pulls in ModuleAnimateEmissive as dependency and installs as intended, all ModuleAnimateEmissive files show up as belonging to the Package of the same name:

Pastebins after reinstall of KW:
https://bpaste.net/show/450bb58dc418 (KWRocketry)
https://bpaste.net/show/0808a00f2025 (ModuleAnimateEmissive)

**Comment by Dazpoet** [comment] 2015-05-27 22:22
I'm afraid this is the expected, non-ideal, behaviour and we'll have to stick to workarounds like these until such a time that we have a better way of handling these situations.

I'll close this since the reinstall resolves the situation.

**Closed by Dazpoet** 2015-05-27 22:22 UTC
