### ISSUE TITLE
Can not open settings, getting the following error.

### ISSUE THREAD

**Issue by merket** [KSP-CKAN/CKAN#2384] opened 2018-03-23 04:21 UTC
System.NullReferenceException: Nesne başvurusu bir nesnenin örneğine ayarlanmadı.
   konum: CKAN.SettingsDialog.RefreshAuthTokensListBox()
   konum: CKAN.SettingsDialog.UpdateDialog()
   konum: System.Windows.Forms.Form.OnLoad(EventArgs e)
   konum: System.Windows.Forms.Form.OnCreateControl()
   konum: System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   konum: System.Windows.Forms.Control.CreateControl()
   konum: System.Windows.Forms.Control.WmShowWindow(Message& m)
   konum: System.Windows.Forms.Control.WndProc(Message& m)
   konum: System.Windows.Forms.Form.WmShowWindow(Message& m)
   konum: System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by HebaruSan** [comment] 2018-03-23 04:39
Duplicate of #2300, fixed in #2301, to work around, click Continue and add a fake auth token.

**Closed by HebaruSan** 2018-03-23 04:39 UTC
