### ISSUE TITLE
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by TheSpatulaCity** [KSP-CKAN/CKAN#2507] opened 2018-08-21 10:02 UTC
Background
----------

**CKAN Version:** 
v1.25.2

**KSP Version:** 
1.4.5.2243

**Operating System:** 
Windows 7 x64
.Net 4.5.1 RC

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
Used previous CKAN and there is some stuff in there.  I deleted it once this version of CKAN gave me the fits but CKAN still doesn't like me.

Problem
-------
CKAN crashes upon startup. 
I have tried executing it from the KSP main folder, my desktop, my downloads folder... 
I took a screenshot of the error and did an OCR conversion to get the text, I checked it for accuracy as best as I could.  I even deleted and re installed KSP, but it seems to bring back the exact same version and produce the same error.  I have no problems running KSP.

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object. 
at CKAN.GUIUser.DisplayMessage(String message, Object[] args) 
at CKAN.HSP.SetupGhanDirectories() 
at CKAN.HSP..ctor(String gameDir, String name, IUser user) 
at CKAN.HSPManager.LoadInstancesFromRegistry() 
at CKAN.Main..ctor(String[ ] cmdlineArgs, HSPManager mgr, GUIUser user, Boolean showConsole) 
at CKAN.CmdLine.MainClass.Gui(HSPManager manager, GuiOptions options, String[ ] args) 
at CKAN.CmdLine.MainClass.Main(String[ ] args) 

**What steps did you take in CKAN?**
Nothing, I could not load it.

**What did you expect to happen?**

**What happened instead?**

**Screenshots:**
![captureksp](https://user-images.githubusercontent.com/42571355/44395150-d30f4d80-a4ed-11e8-8526-3f3a9df5e6f7.PNG)

**CKAN error codes (if applicable):**

**Comment by uejji** [comment] 2018-08-21 13:04
Same issue.  I personally resolved on my system by running the previous release and letting it auto update.

**Comment by HebaruSan** [comment] 2018-08-21 15:54
Duplicate of #2483, fixed in #2482.

**Closed by HebaruSan** 2018-08-21 15:54 UTC
