### ISSUE TITLE
Got a crash while updating the Mod "Hullcam VDS"

### ISSUE THREAD

**Issue by BiZZKeryear** [KSP-CKAN/CKAN#1365] opened 2015-08-10 03:11 UTC
Got a crash while updating the Mod "Hullcam VDS"

Something about a path, sorry about this localized error message.

    Informationen über das Aufrufen von JIT-Debuggen
    anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

    ************** Ausnahmetext **************
    System.NotSupportedException: Das angegebene Pfadformat wird nicht unterstützt.
       bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
       bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
       bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
       bei CKAN.ModuleInstaller.CopyZipEntry(ZipFile zipfile, ZipEntry entry, String fullPath, Boolean makeDirs)
       bei CKAN.ModuleInstaller.InstallModule(CkanModule module, String zip_filename)
       bei CKAN.ModuleInstaller.Install(CkanModule module, String filename)
       bei CKAN.ModuleInstaller.AddRemove(IEnumerable`1 add, IEnumerable`1 remove)
       bei CKAN.ModuleInstaller.Upgrade(IEnumerable`1 modules, IDownloader netAsyncDownloader)
       bei CKAN.Main.WasSuccessful(Action action)
       bei CKAN.Main.InstallMods(Object sender, DoWorkEventArgs e)
       bei System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

    ************** Geladene Assemblys **************
    mscorlib
        Assembly-Version: 4.0.0.0.
        Win32-Version: 4.0.30319.34209 built by: FX452RTMGDR.
        CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll.
    ----------------------------------------
    ckan
        Assembly-Version: 0.0.0.0.
        Win32-Version: 0.0.0.0.
        CodeBase: file:///C:/Program%20Files%20(x86)/Steam/SteamApps/common/Kerbal%20Space%20Program/ckan.exe.
    ----------------------------------------
    System.Core
        Assembly-Version: 4.0.0.0.
        Win32-Version: 4.0.30319.34209 built by: FX452RTMGDR.
        CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll.
    ----------------------------------------
    System
        Assembly-Version: 4.0.0.0.
        Win32-Version: 4.0.30319.34238 built by: FX452RTMGDR.
        CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll.
    ----------------------------------------
    System.Windows.Forms
        Assembly-Version: 4.0.0.0.
        Win32-Version: 4.0.30319.34251 built by: FX452RTMGDR.
        CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.
    ----------------------------------------
    System.Drawing
        Assembly-Version: 4.0.0.0.
        Win32-Version: 4.0.30319.34209 built by: FX452RTMGDR.
        CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.
    ----------------------------------------
    System.Configuration
        Assembly-Version: 4.0.0.0.
        Win32-Version: 4.0.30319.34209 built by: FX452RTMGDR.
        CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll.
    ----------------------------------------
    System.Xml
        Assembly-Version: 4.0.0.0.
        Win32-Version: 4.0.30319.34234 built by: FX452RTMGDR.
        CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
    ----------------------------------------
    System.Windows.Forms.resources
        Assembly-Version: 4.0.0.0.
        Win32-Version: 4.0.30319.34209 built by: FX452RTMGDR.
        CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Windows.Forms.resources.dll.
    ----------------------------------------
    mscorlib.resources
        Assembly-Version: 4.0.0.0.
        Win32-Version: 4.0.30319.34209 built by: FX452RTMGDR.
        CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_de_b77a5c561934e089/mscorlib.resources.dll.
    ----------------------------------------
    Microsoft.GeneratedCode
        Assembly-Version: 1.0.0.0.
        Win32-Version: 4.0.30319.34234 built by: FX452RTMGDR.
        CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
    ----------------------------------------
    Microsoft.CSharp
        Assembly-Version: 4.0.0.0.
        Win32-Version: 4.0.30319.34209.
        CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll.
    ----------------------------------------
    System.Numerics
        Assembly-Version: 4.0.0.0.
        Win32-Version: 4.0.30319.34209 built by: FX452RTMGDR.
        CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll.
    ----------------------------------------
    System.Dynamic
        Assembly-Version: 4.0.0.0.
        Win32-Version: 4.0.30319.34209.
        CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll.
    ----------------------------------------
    Microsoft.CSharp.resources
        Assembly-Version: 4.0.0.0.
        Win32-Version: 4.0.30319.34209.
        CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp.resources/v4.0_4.0.0.0_de_b03f5f7f11d50a3a/Microsoft.CSharp.resources.dll.
    ----------------------------------------
    Anonymously Hosted DynamicMethods Assembly
        Assembly-Version: 0.0.0.0.
        Win32-Version: 4.0.30319.34209 built by: FX452RTMGDR.
        CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll.
    ----------------------------------------
    System.Transactions
        Assembly-Version: 4.0.0.0.
        Win32-Version: 4.0.30319.34209 built by: FX452RTMGDR.
        CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll.
    ----------------------------------------
    System.EnterpriseServices
        Assembly-Version: 4.0.0.0.
        Win32-Version: 4.0.30319.34209 built by: FX452RTMGDR.
        CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll.
    ----------------------------------------
    System.Runtime.Serialization
        Assembly-Version: 4.0.0.0.
        Win32-Version: 4.0.30319.34234 built by: FX452RTMGDR.
        CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll.
    ----------------------------------------
    System.Xml.Linq
        Assembly-Version: 4.0.0.0.
        Win32-Version: 4.0.30319.34209 built by: FX452RTMGDR.
        CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll.
    ----------------------------------------
    System.Data
        Assembly-Version: 4.0.0.0.
        Win32-Version: 4.0.30319.34209 built by: FX452RTMGDR.
        CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll.
    ----------------------------------------
    System.resources
        Assembly-Version: 4.0.0.0.
        Win32-Version: 4.0.30319.34209 built by: FX452RTMGDR.
        CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.resources.dll.
    ----------------------------------------

    ************** JIT-Debuggen **************
    Um das JIT-Debuggen (Just-In-Time) zu aktivieren, muss in der
    Konfigurationsdatei der Anwendung oder des Computers
    (machine.config) der jitDebugging-Wert im Abschnitt system.windows.forms festgelegt werden.
    Die Anwendung muss mit aktiviertem Debuggen kompiliert werden.

    Zum Beispiel:

    <configuration>
        <system.windows.forms jitDebugging="true" />
    </configuration>

    Wenn das JIT-Debuggen aktiviert ist, werden alle Ausnahmefehler an den JIT-Debugger gesendet, der auf dem
    Computer registriert ist, und nicht in diesem Dialogfeld behandelt.

P.S.: `System.NotSupportedException: Das angegebene Pfadformat wird nicht unterstützt.` means The used formatting for the path is not supported (or alike)

**Comment by plague006** [comment] 2015-08-10 11:11
Duplicate of #1365

**Closed by plague006** 2015-08-10 11:11 UTC
