### ISSUE TITLE
[Suggestion] CKAN in the System Tray & CKAN/Mod Update Notifier

### ISSUE THREAD

**Issue by ReiDaTecnologia** [KSP-CKAN/CKAN#2377] opened 2018-03-19 15:16 UTC
_This is not a issue and yes a suggestioni so i think don't need the issue layout when open a new issue (I think, if i wrong tell me and i fix it)_

This is a idea i have, while waiting to mods get updated (And opening some times) to CKAN.
This is not a **_really_** important feature is just a good util, you can put in low priority if you want or you can tell for yourself "Do it! Just do it!!" (old meme reference xD)

How work:
System Tray - Method 1:
If you click in the "X" (To close the program) instead of him close he minimizes to the System Tray and to show again just click in the icon and to close him, right-click in the icon>Exit or close normally File>Exit or Ctrl + Q (Shortcut)
Method 2:
Add a new button in the left of "Minimize button" or in the right of "X" (Good for not close the CKAN instead of minimize him by mistake) to minimize to System Tray and close same of Method 1.
Notification
Show a info box in the screen talking the mod name, version installed and the new version available and the same if is a CKAN and for blind (Like i xD) can make a sound. Note: I really like if while in fullscreen (Games and video player, web and app) the notification don't minimized the game to desktop and players to show the task bar because this already happen with me and this is really annoying (The notification sound is useful to this situation).

Images i made by editing for exemples:
System Tray - Method 1 (Can have others options if you want, this is just a options exemple)
[![System_Tray_-_Method_1.png](https://s14.postimg.org/5fy2smiht/System_Tray_-_Method_1.png)](https://postimg.org/image/arczdc4kd/)
System Tray - Method 2
Left
[![System_Tray_-_Method_2_Left.png](https://s14.postimg.org/p3x8kbezl/System_Tray_-_Method_2_Left.png)](https://postimg.org/image/3u9m9gyot/)
Right
[![System_Tray_-_Method_2_Right.png](https://s14.postimg.org/yr5c7la5t/System_Tray_-_Method_2_Right.png)](https://postimg.org/image/e70i93uel/)
Notification
[![CKAN_-_Mod_Notification.png](https://s14.postimg.org/6w9latya9/CKAN_-_Mod_Notification.png)](https://postimg.org/image/k0f5niqbx/)

**Comment by Olympic1** [comment] 2018-03-19 22:05
IMO, method 1 is the most used.

**Comment by Olympic1** [comment] 2018-03-20 21:31
Thought this out a little bit and these are my ideas/suggestions:

### Options in the settings menu
**Tray Behavior**
- [x] Enable system tray icon
- [ ] Minimize to tray
- [ ] Close to tray

`Enable system tray icon`: When enabled, enables the other two options and the tray icon.
`Minimize to tray`: When disabled, minimizes CKAN to task bar. When enabled, minimizes to system tray.
`Close to tray`: When disabled, closes CKAN. When enabled, closes to system tray.

### System tray icon
The tray icon should logically be the CKAN logo. An idea could be that it shows a (blinking) `!` when there are notifications or mod updates.

### Left-click tray icon
One of these options should happen:
* Open CKAN
* A list of notifications (new to old)

### Right-click tray icon
Opens a menu with following options:
```
Open CKAN
Open KSP folder
Settings
Help > Report an issue...
       Wiki
Quit
```

`Open CKAN`: Opens CKAN again.
`Open KSP folder`: Opens the KSP directory.
`Settings`: Opens CKAN and the settings menu.
`Help`: Some useful help options.
`Quit`: Closes CKAN completely.

**Comment by politas** [comment] 2018-03-21 11:41
Would also need a setting for how often to refresh the repos

**Comment by magico13** [comment] 2018-03-26 01:45
I'm not really associated with ckan, just reading through some stuff for fun. Something else that might be useful to see in the right click menu would be a count of available updates and when you click it it would open up CKAN to the same screen that the "Add available updates" button does in the main UI. If there are no updates then it could grey out and say "No updates available". 

Then I could just leave it running in the background and only have to press two buttons to update everything and without having to navigate any extra UIs. I'd use that far more often than accessing the settings, KSP  folder, or Help which are all things I never touch but are available through the main UI.

**Comment by politas** [comment] 2018-03-27 00:02
I'm thinking this would have to run as a different UI, similar to how we cross-load between CLI and GUI, and the way we handle switching into and out of administrator mode for URL-handler registration.

`ckan.exe tray` could load it up, and I can't see why we couldn't program it to load and test multiple KSP instances in the background. It would need to have its own settings dialog where you select which KSP instances you wanted to auto-refresh and notify, and the cycle time.

**Comment by HebaruSan** [comment] 2018-03-27 00:45
I wonder whether Mono has cross-platform support for this.

**Comment by Rohaq** [comment] 2018-04-07 01:25
Just a note from a UX perspective: "Minimize to tray" would be great, but "Close to tray" is a bane of poor UX design, IMHO: Closing a program should have the expected behaviour of closing the program, especially if that program might be making regular connections to update the mod list.

Additionally, if you wanted a notification when mod updates are available, this would also need a "Check for updates every X hours" feature to be added to be particularly useful, since CKAN current only checks for updates on launch, or at the user's manual request at the minute.

**Comment by politas** [comment] 2018-04-27 10:57
I was thinking about this the other night, and I think we would basically need to write it as a completely separate UI, based on the KSP Install list. Call it CKAN Watcher; it could be run with `ckan.exe watcher`, and have a "launch at startup" option.

When expanded from the tray, it shows the list of installs with checkboxes for active Repo refreshing and auto-updating mods. Double-click on an install to go to a settings box for that install, with the timing settings for refresh and mod updating, and a "launch CKAN" to go to the full GUI for that install.

It would largely use the CLI code for actually refreshing the repos and updating mods, and should have a log of actions taken including when it couldn't do its job due to an active CKAN running on an instance. Users should be able to mark log entries as read and delete them.

**Closed** 2018-11-06 01:43 UTC
Labels: Enhancement, GUI
