### ISSUE TITLE
CKAN displays white screen

### ISSUE THREAD

**Issue by OnionSam** [KSP-CKAN/CKAN#2683] opened 2019-02-12 02:23 UTC
Background
----------

**CKAN Version:** 
1.25.4

**KSP Version:** 
1.6.1

**Operating System:** 

OS X(Mojave, 10.14)
**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 

Yes
Problem
-------
When launching CKAN, it only displays a white screen
**What steps did you take in CKAN?**

Entered mono --arch=32 ckan.exe into the terminal
**What did you expect to happen?**

CKAN to launch normally. 
**What happened instead?**

It displayed a white screen.
**Screenshots:**

**CKAN error codes (if applicable):** Displayed this in the terminal:
System.DllNotFoundException: libX11.dylib
  at (wrapper managed-to-native) CKAN.X11.XSetClassHint(intptr,intptr,intptr)
  at CKAN.X11.SetWMClass (System.String name, System.String wmClass, System.IntPtr handle) [0x0004c] in <2c2371fb3f2949b2a6dfae930758e6ee>:0 
  at CKAN.Main.<.ctor>b__37_5 (System.Object sender, System.EventArgs e) [0x00010] in <2c2371fb3f2949b2a6dfae930758e6ee>:0 
  at (wrapper delegate-invoke) <Module>.invoke_void_object_EventArgs(object,System.EventArgs)
  at System.Windows.Forms.Control.OnHandleCreated (System.EventArgs e) [0x00019] in <556a6ba2c0a546f1ad2318c309ce0945>:0 
  at System.Windows.Forms.Form.OnHandleCreated (System.EventArgs e) [0x00016] in <556a6ba2c0a546f1ad2318c309ce0945>:0 
  at System.Windows.Forms.Control.WmCreate (System.Windows.Forms.Message& m) [0x00000] in <556a6ba2c0a546f1ad2318c309ce0945>:0 
  at System.Windows.Forms.Control.WndProc (System.Windows.Forms.Message& m) [0x0021c] in <556a6ba2c0a546f1ad2318c309ce0945>:0 
  at System.Windows.Forms.ScrollableControl.WndProc (System.Windows.Forms.Message& m) [0x00000] in <556a6ba2c0a546f1ad2318c309ce0945>:0 
  at System.Windows.Forms.ContainerControl.WndProc (System.Windows.Forms.Message& m) [0x00029] in <556a6ba2c0a546f1ad2318c309ce0945>:0 
  at System.Windows.Forms.Form.WndProc (System.Windows.Forms.Message& m) [0x00166] in <556a6ba2c0a546f1ad2318c309ce0945>:0 
  at System.Windows.Forms.Control+ControlWindowTarget.OnMessage (System.Windows.Forms.Message& m) [0x00000] in <556a6ba2c0a546f1ad2318c309ce0945>:0 
  at System.Windows.Forms.Control+ControlNativeWindow.WndProc (System.Windows.Forms.Message& m) [0x0000b] in <556a6ba2c0a546f1ad2318c309ce0945>:0 
  at System.Windows.Forms.NativeWindow.WndProc (System.IntPtr hWnd, System.Windows.Forms.Msg msg, System.IntPtr wParam, System.IntPtr lParam) [0x00085] in <556a6ba2c0a546f1ad2318c309ce0945>:0 

Also, I'm not that great w/ computers so sorry if I'm missing something obvious!

**Comment by DasSkelett** [comment] 2019-02-12 02:26
See #2595. Already fixed in #2600.

**Comment by HebaruSan** [comment] 2019-02-12 03:12
Thanks for the report, closing as a duplicate of #2595.

**Closed by HebaruSan** 2019-02-12 03:12 UTC
Labels: Duplicate
