### ISSUE TITLE
Can't even open CKAN

### ISSUE THREAD

**Issue by FrostFree** [KSP-CKAN/CKAN#2469] opened 2018-07-07 05:14 UTC
Background
---

I suck at computers so please explain if I'm not supposed to open it or I downloaded it incorrectly because honestly I need step by step simple instructions to understand these things. I have redownloaded it multiple times and it crashes on start everytime.

**CKAN Version:** 
1.25.1 (I think)

**KSP Version:** 
1.4.4

**Operating System:** 
Windows

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

Problem
---

Whenever I try to open ckan.exe it immediately crashes and stops working. This is my first time opening it after downloading it today.

**What steps did you take in CKAN?**
Can't even open it.

**What did you expect to happen?**
For CKAN to actually open. 

**What happened instead?**
Just instant crashing.

**Screenshots:**

![screenshot 2](https://user-images.githubusercontent.com/40907587/42407088-07388e16-8183-11e8-9c51-0cb22111067c.png)

**CKAN error codes (if applicable):** 
None. Just "stopped working"

**Comment by HebaruSan** [comment] 2018-07-07 06:59
Try installing .NET 4.5 like the release notes say:
- https://www.microsoft.com/en-au/download/details.aspx?id=30653

**Comment by FrostFree** [comment] 2018-07-08 02:46
I Tried downlaoding .NET 4.5 and I apparently already have it.

**Comment by HebaruSan** [comment] 2018-07-08 03:46
Actually can you scroll the command window up and capture the start of the error message? That part at the bottom may or may not be related directly to the cause of the problem.

**Comment by FrostFree** [comment] 2018-07-08 04:41
That is the enitre message there is nothing else sadly

**Comment by HebaruSan** [comment] 2018-07-08 04:46
The top of the window clearly shows partial text from a longer message, and there's a scrollbar scrolled downwards from the top position:

![image](https://user-images.githubusercontent.com/1559108/42416890-d27a00dc-8269-11e8-941e-4d9505ebc0f7.png)

That's what I meant about scrolling up.

**Comment by FrostFree** [comment] 2018-07-08 05:47
Oh yes it closes automatically too fast for me to scroll up. I can attempt to get a screenshot where the top shows.

**Comment by FrostFree** [comment] 2018-07-08 05:49
![screenshot 4](https://user-images.githubusercontent.com/40907587/42417182-15f1e0aa-8251-11e8-9b77-7070b5f1a38d.png)

Here I just held the screenshot button down I hope this works

**Comment by HebaruSan** [comment] 2018-07-08 05:52
Based on #849, it sounds like this may be caused by crosstalk with other files in your downloads folder. Can you try moving it to a different folder and running it from there?

**Comment by FrostFree** [comment] 2018-07-08 06:18
I moved it out of the downloads folder and it had the same message. And I'm very disappointed as I cannot download mods manually either.

**Comment by politas** [comment] 2018-07-08 08:42
Why can you not download mods manually? That may be indicative.

**Comment by FrostFree** [comment] 2018-07-08 22:20
I tried to download them and put them into my gamedata folder however they don't seem to work

**Comment by negis02** [comment] 2018-07-13 07:20
You shuld run ckan.exe in administrator rights.

**Comment by politas** [comment] 2018-07-14 03:11
No, you should not run CKAN with Administrator privileges. That is a crazy thing to do!

**Comment by HebaruSan** [comment] 2018-08-08 23:11
@FrostFree, that exception says your system is missing the System.Xml reference. That really looks like a missing .NET framework. How did you confirm you have it?

**Comment by Jabberwokey** [comment] 2018-08-19 17:39
@HebaruSan I am experiencing a similar issue. I've delete and redownloaded both my KSP and CKAN instances and checked my .NET version.

![ksp-ckan-8192018 edited](https://user-images.githubusercontent.com/42519872/44311430-50837280-a3b5-11e8-9d5a-9a12b0bee0da.jpg)

**Comment by HebaruSan** [comment] 2018-08-19 17:42
Hi @Jabberwokey, that's a different unrelated issue, see #2483, fixed in #2842. To avoid causing further confusion with other issues in this thread, I'll prune your comment.

**Comment by politas** [comment] 2019-03-25 19:09
Presumably @FrostFree has sorted out their .Net installation by now.

**Closed by politas** 2019-03-25 19:09 UTC
Labels: Needs more info, Windows
