### ISSUE TITLE
[Bug]: Trying to install XXXXXXX, but it's not downloaded or download is corrupted

### ISSUE THREAD

**Issue by PhildeCube** [KSP-CKAN/CKAN#3977] opened 2023-12-24 02:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows 11

### CKAN Version

v1.34.2

### Games

KSP 2

### Game Version

0.2.0.0.30292

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

No, I've only used CKAN.

### Describe the bug

Yesterday (first day with CKAN in KSP2) I have managed to download 7 mods using CKAN, but I had to retry a couple because they gave me multiple iterations of this error "Trying to install "mod name and version", but it's not downloaded or download is corrupted". I gave up and tried again some hours later and managed to get them then.
Today I updated a couple of yesterday's mods no problems, but Micro Engineer 1.6.0 continually gives me the same error as above. Also, new mods today, K2-D2, Maneuver Node Controller, and Node Manager constantly do the same.

### Steps to reproduce

Try and install the mods. Error message appears. I have tried clearing the cache multiple times, but this doesn't help.

### Relevant log output

About to install:
 * K2-D2 v0.11.1 (spacedock.info, 1.0 MiB)
Downloading "https://spacedock.info/mod/3325/K2-D2/download/0.11.1"
Finished downloading K2D2 v0.11.1, validating and storing to cache...
Trying to install K2D2 v0.11.1, but it's not downloaded or download is corrupted
Error during installation!

**Comment by HebaruSan** [comment] 2023-12-24 02:32
Duplicate of #3972

**Closed by HebaruSan** 2023-12-24 02:32 UTC

**Comment by PhildeCube** [comment] 2023-12-24 03:30
Sorry to be a duplicate. So, it's a time zone thing? I'm in UTC +11.

**Comment by HebaruSan** [comment] 2023-12-24 03:35
Hi @PhildeCube, no apology is needed, thank you for filing a report.

Yes, to the best of my knowledge, this happens when a mod release is newer than your distance from GMT. Oof, UTC+11 is rough; I guess you could check or sort by the release date column to avoid things less than 11 hours old? Sorry for the inconvenience!
