### ISSUE TITLE
[Feature] Only install certain Files

### ISSUE THREAD

**Issue by JovietUnion** [KSP-CKAN/CKAN#3486] opened 2021-11-21 22:55 UTC
Problem
-------
**Is your feature request related to a problem? Please describe.**
Ex. I'm always frustrated when... I can't install certain mods because of file errors.

Suggestions
-----------
**Describe the solution you'd like**
Add an option to only install certain files to a mod to prevent file issues.

**Describe alternatives you've considered**
In the install tab, add a right-click option with the option to delete and reinstall certain mods.

**Additional context**
None

**Comment by HebaruSan** [comment] 2021-11-21 23:01
There's already an install date column. Does that help you? If not, can you help us to understand why not?

![image](https://user-images.githubusercontent.com/1559108/142782355-016f9e49-152f-4d0c-a75c-164c95ee51c4.png)

**Comment by HebaruSan** [comment] 2021-11-21 23:04
Whoa, this issue changed to something else while I was capturing that screenshot. :confused: 

So in this new description, are you asking for an option to only install certain files, or are you asking for a right click reinstall option? Those are two very different things, but this issue mentions both as if they are part of the same idea.

**Comment by HebaruSan** [comment] 2021-11-21 23:17
What kind of file errors/issues are you referring to? Is it this?

https://github.com/KSP-CKAN/CKAN/blob/6d24c67114a6a1e6446af2841d5afabbbf237cd3/GUI/Properties/Resources.resx#L229-L256

**Comment by JovietUnion** [comment] 2021-11-22 00:11
Yes I realized there was an install date already and edited the issue.

**Comment by JovietUnion** [comment] 2021-11-22 00:11
Yes.

**Comment by HebaruSan** [comment] 2021-11-22 00:28
OK, we are already adding global and instance-level install filters in #3458, so we can consider that part of this a duplicate of #3129.

However, this idea is not really an appropriate solution to the "Oh no!" errors, since there is no guarantee that any given mod will work without all of the files it is supposed to install. If you notice this error coming up in cases where two mods actually do work together, please [submit an issue](https://github.com/KSP-CKAN/NetKAN/issues/new/choose) about specific cases so we can look into whether there are ways to fix them by changing the metadata. In other cases, you probably shouldn't try to install those two mods at the same time, rather than trying to force it by working around the error with new features.

**Closed by HebaruSan** 2021-11-22 00:28 UTC
Labels: Support, Needs more info
