### ISSUE TITLE
Unhandled Exception: System.NullReferenceException

### ISSUE THREAD

**Issue by The-Spanish-Inquisition1** [KSP-CKAN/CKAN#2484] opened 2018-08-06 12:59 UTC
Background
----------

**CKAN Version:** 
1.25.2

**KSP Version:** 
1.4.5

**Operating System:** 
Windows 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
Yes

Problem
-------

**What steps did you take in CKAN?**
It didn't open.

**What did you expect to happen?**
CKAN to open.

**What happened instead?**
The console showed an error message, then closed very quickly.

**Screenshots:**

![ckan bug](https://user-images.githubusercontent.com/42143988/43717870-e850cf4a-9956-11e8-801f-c834218bc6a2.PNG)

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment] 2018-08-06 13:00
Duplicate of #2483, fixing in #2482.

**Closed by HebaruSan** 2018-08-06 13:00 UTC
