### ISSUE TITLE
Crashes while downloading update/new mods

### ISSUE THREAD

**Issue by PhildeCube** [KSP-CKAN/CKAN#1712] opened 2016-05-05 07:06 UTC
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.
Couldn't see anything the same.
**CKAN Version:**
![image](https://cloud.githubusercontent.com/assets/8325792/15037939/de10d05e-12e2-11e6-9f40-86d95c5231d8.png)
This has occurred for many months over many versions of CKAN,
**Operating System:** 
Windows 7 Pro
**The issue you are experiencing:** 
Many times when installing updated and/or new mods CKAN crashes with an exception error. Restarting CKAN usually reveals the mods actually installed.
![image](https://cloud.githubusercontent.com/assets/8325792/15037971/2917bd92-12e3-11e6-9213-956c6f65921b.png)
![image](https://cloud.githubusercontent.com/assets/8325792/15037973/2f0e475c-12e3-11e6-983a-90b6bb165d8a.png)
![image](https://cloud.githubusercontent.com/assets/8325792/15037975/34807732-12e3-11e6-82ff-5542f6f55196.png)
![image](https://cloud.githubusercontent.com/assets/8325792/15037977/3b715c64-12e3-11e6-9c3b-4e14c7b987ec.png)
![image](https://cloud.githubusercontent.com/assets/8325792/15037982/421f7c26-12e3-11e6-8600-7fa22df1669c.png)
![image](https://cloud.githubusercontent.com/assets/8325792/15037988/4683905e-12e3-11e6-9985-13b9ab2b413f.png)

**How to recreate this issue:** 
Select mods to be updated and/or installed, click on Apply Changes, click on Apply, wait. Sometime during the process the error will appear. I thought it might have something to do with the user folder having some read only sub-folders, but setting all files in the user folder as not read only does not help.
**CKAN error codes (if applicable):** 
See above.

**Comment by plague006** [comment] 2016-05-05 08:43
Duplicate of https://github.com/KSP-CKAN/CKAN/issues/1367

**Comment by PhildeCube** [comment] 2016-05-05 21:17
"Workaround for now is just not to install AND upgrade mods in one changeset."

I don't always get this error when doing an install AND upgrade in one changeset. 95% of the time I get it when doing an install OR an upgrade. The workaround, if I am reading #1367 correctly, doesn't help.

**Comment by Blu3wolf** [comment] 2016-05-08 07:52
Got the same issue - 
`Unhandled exception:
System.IO.IOException: The process cannot access the file 'E:\User\Blue\AppData\Local\Temp\tmp4B83.tmp' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at CKAN.NetAsyncDownloader.ModuleDownloadsComplete(NetFileCache cache, Uri[] urls, String[] filenames, Exception[] errors)
   at CKAN.NetAsyncDownloader.<DownloadModules>c__AnonStorey2.<>m__1(Uri[] _uris, String[] paths, Exception[] errors)
   at CKAN.NetAsyncDownloader.FileDownloadComplete(Int32 index, Exception error)
   at System.ComponentModel.AsyncCompletedEventHandler.Invoke(Object sender, AsyncCompletedEventArgs e)
   at System.Net.WebClient.OnDownloadFileCompleted(AsyncCompletedEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch() `

**Comment by PhildeCube** [comment] 2016-05-12 05:56
Update: I ran a Disk Cleanup and a Disk Defrag procedure on the PC. This seems to have stopped the error appearing (presumably through emptying out the temp folders). I have only tested with updating mods so far, but have had no instances of problems in a few days.

**Comment by Blu3wolf** [comment] 2016-05-12 06:52
Havent seen this since I stopped doing upgrades and fresh installz at the same time.

**Comment by plague006** [comment] 2016-05-18 11:36
Closing this as it can no longer be replicated.

**Closed by plague006** 2016-05-18 11:36 UTC
