### ISSUE TITLE
[Bug]: CKAN no longer opening after update

### ISSUE THREAD

**Issue by TheMainMan23** [KSP-CKAN/CKAN#4198] opened 2024-09-27 06:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows 10 Interprise

### CKAN Version

1.35.0.24270

### Games

KSP 1

### Game Version

1.12.5 (latest Version)

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

None

### Describe the bug

I just opened CKAN and it told me there was an update available and if I wanted to update. I updated and CKAN only displays a black box with text for a few seconds before closing now. Deleting the CKAN folder and opening CKAN.exe does nothing expect bring up that same black box with text.

### Steps to reproduce

CKAN asked me If I wanted to update, I did and nothing happened. I clicked on CKAN.exe but only opens black text for a few seconds before closing now.

### Relevant log output

![CKAN Error](https://github.com/user-attachments/assets/f769c0a8-94f0-4d09-9e46-22cd1f9ea5de)

**Comment by eecano** [comment] 2024-09-27 07:25
Same issue here

**Comment by kretze** [comment] 2024-09-27 08:02
New version no longer starts

![image](https://github.com/user-attachments/assets/ced0ddab-5a43-489f-af8a-805b42cb1a7c)

**Comment by JonnyOThan** [comment] 2024-09-27 11:58
Dupe of #4197

**Closed by JonnyOThan** 2024-09-27 11:58 UTC
Labels: Duplicate

**Comment by HebaruSan** [comment] 2024-09-27 16:07
Duplicate of #4197

**Comment by HebaruSan** [comment] 2024-09-27 16:09
(If you use the "Saved replies" template thing rather than typing, GitHub will officially mark the duplicate. I don't know whether this does something useful, but maybe?

![image](https://github.com/user-attachments/assets/887e7f0e-3529-4e11-a718-c17a55622e5b)

![image](https://github.com/user-attachments/assets/70dd10c3-89f0-47e4-9d62-153e200633de))
