### ISSUE TITLE
[Suggestion] Show Mods in All section even if dependencies are outdated

### ISSUE THREAD

**Issue by Blu3wolf** [KSP-CKAN/CKAN#1801] opened 2016-06-27 13:37 UTC
Presently, the client hides mods whose dependencies have not been updated. This is not a bad thing, for the Compatible view of mods. However, it also hides them from the All mods view, which is very inconvenient. 
This can be easily solved, by not hiding mods whose dependencies have not updated, from the list of All mods.

**Comment by politas** [comment] 2016-06-28 03:44
This is a duplicate of #1695

**Closed** 2016-06-28 03:44 UTC
