### ISSUE TITLE
"Install from .ckan" claims mod isn't available (also additional weirdness)

### ISSUE THREAD

**Issue by Kemp-J** [KSP-CKAN/CKAN#1614] opened 2016-02-25 10:29 UTC
**CKAN Version:** 1.16.0

**Operating System:** Windows 10

As per title, I'm moving my mods over to a new install of KSP. I did "Export installed mods", switched install, and then "Install from .ckan". The error is with Docking Port Alignment Indicator, but that's just the first one on the list. The error given is:

> Module DockingPortAlignmentIndicator required, but not listed in index, or not available for your version of KSP

I can install this mod manually from the list perfectly fine, so presumably there is some other error going on that is being reported in a confusing way.

After installing manually and then attempting to install from the .ckan file (to get the remaining mods) gives the following error:

> The following inconsistencies were found:
> DockingPortAlignmentIndicator requires a version 6.2.0. However a incompatible version, 6.2, is already installed

So perhaps the issue is caused by odd version numbering?

**Bonus weirdness:**

After removing the mod manually in order to test importing again, the version numbers are messed up in the mod description. It previously said the max KSP version is "1.0.5 (using mod version 6.2)", but now it says "0.25.99 (using mod version 4.0)". _However_, the list itself says the max KSP version is 0.25.99 with mod version 6.2. Restarting ckan fixes the description.

**Comment by plague006** [comment] 2016-02-25 19:06
Can you post your .ckan or its contents somewhere for us to see? Pastebin, gist, wherever. Either the .ckan you're running is trying to install a specific version of `DockingPortAlignmentIndicator`, or one of the other mods you're trying to install is. Either way, they're running into each other and that's what's causing the issue.

If this .ckan `depends` a specific version of `DockingPortAlignmentIndicator` then https://github.com/KSP-CKAN/CKAN/pull/1609 would have likely avoided this issue.

**Comment by Kemp-J** [comment] 2016-02-25 19:13
.ckan file here: http://pastebin.com/UPK1aCsZ

I believe you are right about it not being able to find the requested version from the .ckan file (6.2.0 versus 6.2). It looks like #1609 would be the solution, as the specific version of the mod isn't important to me.

However, the error message given doesn't seem appropriate, as DockingPortAlignmentIndicator is both listed in the index and is available for my version of KSP. The message could probably do with rephrasing in this case.

**Comment by plague006** [comment] 2016-02-25 20:09
I'll also probe this a little deeper to figure out what's breaking, but for your purpose: on line 4 change the word `depends` to `recommends`.

**Comment by plague006** [comment] 2016-02-25 20:28
`DockingPortAlignmentIndicator` specifically fails because https://github.com/KSP-CKAN/CKAN-meta/pull/915 removed version `6.2.0` of the mod because it was considered a duplicate of `6.2`.

However, regardless of `DockingPortAlignmentIndicator`'s status this would have failed  because the list was generated from a KSP 1.0.4 install and many of the versions of mods trying to be installed are incompatible with 1.0.5.

Lastly to address the "bonus weirdness", I had this bug occur once but have been unable to replicate it. Because of the difficulty in consistent reproduction as well as its transient and benign nature I'm going to close this unless there's a consistent reproduction method.

By following my previous comment's directions you should have no issue running your .ckan file, but feel free to re-open this if anything wasn't addressed or if any of these issues persist.

**Closed by plague006** 2016-02-25 20:28 UTC
