### ISSUE TITLE
Contents tree view still disabled after downloading contents

### ISSUE THREAD

**Issue by rkagerer** [KSP-CKAN/CKAN#1936] opened 2016-11-03 13:12 UTC
CKAN Version: 1.20.1-0-gd41fe54 (beta)
OS: Win 7 64-bit

The tree view control showing the contents of a mod is disabled.  As a result you can't scroll it (either horizontally or vertically).  For example, try highlighting the "Filter Extensions - Plugin" mod, then clicking Contents, then Download.  There are a lot of files and it's impossible to preview them all.

Also the Download button doesn't go away after you download it.  CKAN doesn't seem to realize the mod has been added to the cache.

Screenshot [here](http://i.imgur.com/M16pQyx.png).

I *think* if you hit Refresh afterwards (or some other GUI action - haven't nailed down precise mitigation steps) the issue is corrected.

**Comment by ayan4m1** [comment] 2016-11-04 02:55
Has the same root cause as #1928 and is fixed by https://github.com/KSP-CKAN/CKAN/pull/1930

**Comment by Dazpoet** [comment] 2016-11-15 16:07
if this was fixed by #1930 can we close it?

**Comment by rkagerer** [comment] 2016-11-15 16:26
I will retest when I get a chance. If you don't hear back in a couple days (or prefer not to wait) feel free to close and I can reopen if necessary. Thanks for the fix, much appreciated.

**Comment by HebaruSan** [comment] 2018-12-04 22:15
Confirming this as fixed. I'm able to scroll the contents after downloading.

**Closed by HebaruSan** 2018-12-04 22:15 UTC
Labels: Bug, GUI
