### ISSUE TITLE
Ckan failures 1.4

### ISSUE THREAD

**Issue by PGTBoos** [KSP-CKAN/CKAN#2358] opened 2018-03-12 22:04 UTC
Started with module manager no mod will update since 1.4 download ssl failures
Windows 10

Background
----------

**CKAN Version:** 
1.2.4.0

**KSP Version:** 
1.4

**Operating System:** 
windows 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
no

Problem
-------

**What steps did you take in CKAN?**
trying to update mods

**What did you expect to happen?**
updates

**What happened instead?**
nothing SSL failures

**Screenshots:**

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment] 2018-03-12 22:13
Duplicate of #2293, GitHub changed their servers in a way that broke all older versions of CKAN. Install this:

- https://github.com/KSP-CKAN/CKAN/releases/tag/v1.24.0

You may get an error at startup. Click Continue, then Refresh.

**Closed by HebaruSan** 2018-03-12 22:13 UTC

**Comment by PGTBoos** [comment] 2018-03-12 23:42
thnx it worked, i hope the answer might be usefull to others as well
