### ISSUE TITLE
.exe file won't run

### ISSUE THREAD

**Issue by mchety** [KSP-CKAN/CKAN#3174] opened 2020-10-12 22:55 UTC
Whenever I try to run the .exe, this message briefly shows up in command prompt then disappears:

```
Unhandled Exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at CurlSharp.NativeMethods.curl_global_init(Int32 flags)
   at CurlSharp.Curl.GlobalInit(CurlInitFlag flags)
   at CKAN.Curl.Init()
   at CKAN.CmdLine.MainClass.Main(String[] args)

```
I am also making sure to run it not on administrator, and I am running the latest version of windows.

**Comment by HebaruSan** [comment] 2020-10-12 22:58
Duplicate of #3115

**Closed by HebaruSan** 2020-10-12 22:58 UTC

**Comment by HebaruSan** [comment] 2020-10-12 23:07
@mchety, sorry for the terse response, but I wanted GitHub to detect the duplicate text and link it up, and my experience has been that this fails if I add _any_ further text or clarification (see #3151).

To sum up, this is a known issue that has already been investigated and will be fixed in the next release. There are also some workarounds described in the comments of #3115.

**Comment by mchety** [comment] 2020-10-12 23:09
Ok, I checked the other issue and got it working, thanks for your help.
