### ISSUE TITLE
Error upgrading with leftover files files

### ISSUE THREAD

**Issue by PiggyWhiskey** [KSP-CKAN/CKAN#1688] opened 2016-04-30 03:13 UTC
CKAN v1.16.1-0-g2e91715 (beta)
KSP 1.1.1
Windows 10

Attempting to update Kerbal Engineer Redux from 1.1.0.2 to 1.1.1.0
Select Update and Apply
Status Log shows

```
The following inconsistencies were found:
E:/Program Files/Steam/steamapps/common/Kerbal Space Program/GameData/KerbalEngineer/images.manifest is registered to KerbalEngineerRedux but has not been removed!
 * E:/Program Files/Steam/steamapps/common/Kerbal Space Program/GameData/KerbalEngineer/KerbalEngineer.dll is registered to KerbalEngineerRedux but has not been removed!
Error!

```
Attempting a second time worked.

And then upgrading another mod crashed with temp file error
```
************** Exception Text **************
System.UnauthorizedAccessException: Access to the path 'C:\Users\Nathan\AppData\Local\Temp\CdFileMgr\78ed3de8-25c8-45.mu' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at ChinhDo.Transactions.SingleFileOperation.InnerDispose()
   at ChinhDo.Transactions.SingleFileOperation.Dispose()
   at ChinhDo.Transactions.TxEnlistment.DisposeJournal()
   at ChinhDo.Transactions.TxEnlistment.Rollback(Enlistment enlistment)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.127.1 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ckan
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///E:/Program%20Files/cKan/ckan.exe
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1075.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1068.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.6.127.1 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.127.1 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
```

What I've found is, if the second install attempt works, the next install/upgrade will cause the temp file crash.
The other option is after the failed install (with the leftover file error) CKAN will crash with the Temp File error.

**Comment by plague006** [comment] 2016-04-30 07:09
Duplicate of https://github.com/KSP-CKAN/CKAN/issues/1367?

**Comment by PiggyWhiskey** [comment] 2016-04-30 09:33
Kind of?

That issue recommends a work around of keeping upgrades/installs separate.

This issue is when I was only upgrading 4 mods. 
And the issue occurs with a single mod upgrade too.
Not a combination

**Comment by plague006** [comment] 2016-04-30 09:38
My mistake I didn't read this as well as I should have originally. Are you running KSP at the same time as CKAN? 2 instances of CKAN? Anything else that might be tying up files like an anti-virus?

**Comment by PiggyWhiskey** [comment] 2016-04-30 09:44
Nothing else major running.
Steam/Chrome/Windows Explorer/MultiMC (for minecraft)

I've cleaned the temp files too.
CKAN seems to create the folder and the temp file, then try to delete/modify the file while it is still locked.

**Comment by PiggyWhiskey** [comment] 2016-05-01 02:07
After forking the code and stepping through, it appears ModuleInstaller:Uninstall file_transaction.Delete() randomly doesn't like actually deleting the files. There seems to be no reason for it. Not specific formats/attributes/file size.

I was curious to note the in built FileSystemObject wasn't used.

**Comment by Sakata-MC** [comment] 2016-05-06 01:52
Hey @PiggyWhiskey can you check to see if this is OS dependant? Perhaps this doesnt' happen in Linux/older version of Windows?  My linux gaming machine decided to throw a fit and toast its board, so I can't test myself.

I'm wondering since this is reported not-so-often, that it might be OS dependant and since 90% of windows users keep my business running, they probably aren't going to be reporting issues here.

**Comment by PiggyWhiskey** [comment] 2016-05-06 04:31
@Sakata-MC Unfortunately I don't have any other OS's apart from Windows 10. I'm not sure I have the skills/knowledge to install a Linux OS for a Dual Boot

**Comment by PiggyWhiskey** [comment] 2016-05-14 05:50
@plague006 , as the issue with these temp files is the deletion of old mods before upgrading caused by the Transaction Manager, would it be better to change it to just using .NET File management?

That will make the program fully functional and useful and allows you to work on fixing the ASync nature of the Transaction Manager easier.

Also, the Transaction Manager temp file issue is because it's trying to keep a backup of the files to undo, but that would never bee needed because we've already successfully downloaded the new mod.

**Comment by plague006** [comment] 2016-05-14 10:45
@PiggyWhiskey you're pinging the wrong person. I'm not a coder, I'm a metadata maintainer. I simply pitch in with issues when and where I can.

**Closed** 2016-08-11 00:00 UTC
Labels: support
