### ISSUE TITLE
[Bug] Win 10 detects the latest release as "Trojan:Win32/Emali.A!cl"ere

### ISSUE THREAD

**Issue by Draconomial** [KSP-CKAN/CKAN#3311] opened 2021-03-06 13:14 UTC
Basically subj.

Win 10 with the latest updates. Only built-in antivirus, no 3rd party ones.

Detected: Trojan:Win32/Emali.A!cl

Simple false positive. Just need to submit the installer file to Microsoft at https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by DasSkelett** [comment] 2021-03-06 13:50
Duplicate of #3310

**Comment by DasSkelett** [comment] 2021-03-06 13:50
> Simple false positive. Just need to submit the installer file to Microsoft at microsoft.com/en-us/wdsi/filesubmission

Thanks for that link. I gave it a try, let's see if it helps. Did you  submit it as well? I guess the more people report it as false positive, the more likely someone looks at it soon.

**Closed by DasSkelett** 2021-03-06 13:50 UTC
