### ISSUE TITLE
[Feature] Font size & UI scaling

### ISSUE THREAD

**Issue by ghGhost-cs** [KSP-CKAN/CKAN#3147] opened 2020-08-27 09:42 UTC
Problem
-------
When screen too far font in app is unreadable.

Suggestions
-----------
Add font size or UI scaling option.

**Comment by Razunter** [comment] 2020-10-05 18:23
Also High DPI isn't supported by the app.

**Comment by HebaruSan** [comment] 2020-11-11 05:57
Duplicate of #878

**Closed by HebaruSan** 2020-11-11 05:57 UTC
Labels: Enhancement, GUI
