### ISSUE TITLE
Mods with missing/incompatible dependencies should list somewhere, even if they can't be installed

### ISSUE THREAD

**Issue by neurovertex** [KSP-CKAN/CKAN#844] opened 2015-05-05 12:00 UTC
I've spent some time trying to figure out why some mods weren't showing up, even though they had been updated, and were correctly referenced in CKAN-meta. Turns out when a mod has an incompatible (or uninstallable for any reason) dependency, it won't show in any list, not even 'incompatible'.

Maybe list them in 'incompatible', along with the reason why they are so ? Or add a separate category ?

**Comment by Postremus** [comment] 2015-08-22 07:00
Any example for an mod where this is the case?

**Comment by plague006** [comment] 2015-08-22 14:36
This might have been around the time of an update where this effect would have been more readily seen. A way to replicate this now might be: in a custom repo update your ksp rear and a mod that depends on MM to ksp_ver 1.1. That should demonstrate the effect.

**Comment by ayan4m1** [comment] 2016-08-29 11:11
I realize this issue is the older of the two, but fixing https://github.com/KSP-CKAN/CKAN/issues/844 will likely resolve this enhancement request.

**Comment by politas** [comment] 2016-08-29 15:45
This looks like a duplicate of #1695 to me. (Or #1695 is a duplicate of this, is probably a more correct way of putting it, but there's more discussion in that, so I'll close this..)

**Closed by politas** 2016-08-29 15:45 UTC
Labels: enhancement, gui
