### ISSUE TITLE
Repo update freezes with bad certificate

### ISSUE THREAD

**Issue by KiriPole** [KSP-CKAN/CKAN#3844] opened 2023-05-25 12:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows 11

### CKAN Version

v1.32.0

### Game Version

1.12.5.3190

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

No, I didn't install anything manually, but because I used CKAN before and installed the Tantares mods there are now about 300 "stock" ships in the game.
![image_2023-05-25_15-18-18](https://github.com/KSP-CKAN/CKAN/assets/117577140/c1522fbf-fe9a-46b0-9da2-5a256e66abd0),

### Describe the bug

After running the ckan.exe file CKAN freezes on the "checking for updates" stage. Because I used CKAN v1.31.1 on this computer and on this OS I expected CKAN to launch as usual.
![image_2023-05-25_15-23-18](https://github.com/KSP-CKAN/CKAN/assets/117577140/345c467d-910c-4249-b772-26b3d2874e76)

### Steps to reproduce

- Run ckan.exe
- It freezes. If any button is pressed Windows says "CKAN-CmdLine is not responding"

**Comment by KiriPole** [comment] 2023-05-25 12:57
It looks like the problem appears because of a bad certificate for "https://github.com/KSP-CKAN/CKAN-meta/archive/master.tar.gz" 
Probably my internet provider Cyta blocks it somehow. I will try to use VPN and get back here. 
![image](https://github.com/KSP-CKAN/CKAN/assets/117577140/49dc813e-f083-45e6-beda-7e9d06c20801)

**Comment by HebaruSan** [comment] 2023-05-27 20:30
@KiriPole, have you had any luck getting the certificate problem worked out?

**Comment by AdmerW** [comment] 2023-05-29 09:36
@HebaruSan you close my bug ticket by reason "Duplicate of https://github.com/KSP-CKAN/CKAN/issues/3844"

But there is no solution here. You just don't have a valid link from which ckan.exe is trying to download the file. A VPN won't help here in any way.

**Comment by HebaruSan** [comment] 2023-05-29 13:48
Hi @AdmerW, a duplicate means the same problem is being described, not that there is a solution already. You posted the same screenshot of a repo update in Russian. Having multiple issues tracking that same problem won't help more than having one. Cheers!

**Closed** 2023-06-06 04:56 UTC
Labels: Support, Network
