### ISSUE TITLE
Search/filter for mods recommended/suggested by installed mods

### ISSUE THREAD

**Issue by wisq-minted** [KSP-CKAN/CKAN#1764] opened 2016-06-01 03:18 UTC
Hi!  Happy CKAN user here.  Just thought I'd offer a suggested feature that could help me out:

So, sometimes I install mods but elect not to install some of their "Recommended" or "Suggested" mods, because I'm not sure, but I'd like to find those mods later and inspect them.  Or, sometimes mod A recommends mod B, and that doesn't seem to trigger a page re: the mods that mod B recommends (unless I wasn't paying attention, which is possible).

I was thinking there are a few things that could be added to the filter menu:
- Mods recommended by installed mods
- Mods suggested by installed mods

Some other lower-priority ideas (maybe in a sub-menu, because it's a lot of options):
- Mods that depend on installed mods
- Mods that recommend installed mods
- Mods that suggest installed mods
  - These three could be useful to e.g. find a new mod B that extends or just plays nicely with an installed mod A, even if installed mod A isn't aware of new mod B.
- Mods that conflict with installed mods
  - As the inverse of the above, this could be useful to find mods that provide (incompatible) alternatives to mods you already have installed.
  - I'm imagining this would be bidirectional, i.e. the union of "uninstalled mods that our installed mods say they conflict with" and "uninstalled mods that say they conflict with our installed mods".

(Not that I'm trying to create a bunch of work here, I just figured that if someone's already mucking about in the filters, it shouldn't be too tricky to add several / all of the above. 😉 )

Thanks for this awesome tool!  133 mods installed at once and rising!  😄

**Comment by plague006** [comment] 2016-06-01 03:29
Appreciate your thoughts, but closing this as a duplicate of https://github.com/KSP-CKAN/CKAN/issues/1100

**Comment by wisq-minted** [comment] 2016-06-01 03:49
It's not really a duplicate; #1100 deals with looking at any particular mod, while this is a global filter for the list.

To be clear, I'm not talking about looking at a mod and looking at the tabs on that mod.  I'm talking about the "filter" with the magnifying glass in the main window.

**Comment by politas** [comment] 2016-06-01 14:22
Agreed, this is not a duplicate, and it could be a nice feature.

**Closed** 2018-11-21 07:42 UTC
Labels: Enhancement, GUI
