### ISSUE TITLE
CKAN theme usage

### ISSUE THREAD

**Issue by 7ranceaddic7** [KSP-CKAN/CKAN#2525] opened 2018-09-23 21:13 UTC
Background
----------
**CKAN Version:** 
1.25.3

**KSP Version:** 
n/a

**Operating System:** 
Ubuntu 18.04, Linux 4.15

**Gnome Theme**
Arc-Dark

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
n/a

Problem
-------
Main Window, Menu Bar, Action Bar: White background, pale font.

Any ideas how to get the background color to theme standard, #383c4a>
![screenshot from 2018-09-23 13-56-52](https://user-images.githubusercontent.com/4062616/45932931-17509c00-bf39-11e8-91f9-294c5fe51c66.png)

**Comment by StripedMonkey** [comment] 2018-09-26 00:35
This is also an issue with Adwita-dark. Certain UI Elements just don't seem to follow any sort of theming. In older versions of Ckan I believe I just used `GTK_THEME=` and set Ckan to a light theme to let it even be usable however it doesn't appear that Ckan follows this anymore Using the GTK2 method doesn't work either.

**Comment by Orochimarufan** [comment] 2018-09-28 12:44
The GTK2 way worked for me:
$ env GTK2_RC_FILES=/usr/share/themes/Breeze/gtk-2.0/gtkrc ckan
(substitute Breeze for your light theme of choice)

Still would be nice if it properly worked w/ dark themes, but most mono apps seem to be broken in this regard

**Comment by LastStarDust** [comment] 2018-09-28 14:20
Same problem here with Adapta-Nokto theme. The Orochimarufan workaround has no effect in my case (tested with Adwaita light theme)

**Comment by HebaruSan** [comment] 2018-10-02 14:40
Can someone please post installation/setup instructions for Arc-Dark, Adwita-dark, or Adapta-Nokto? The dark theme I use is available via `apt install numix-gtk-theme`, then using the old (and [now removed!?](https://forum.antergos.com/topic/9515/gnome-tweaks-no-more-global-dark-theme/3)) dark theme toggle. I don't see APT packages by these other names.

**Comment by HebaruSan** [comment] 2018-10-02 15:58
- The menu bar has no color properties set
- The toolbar has `BackColor` set to `SystemColors.Control`
- The mod list has `BackgroundColor` set to `SystemColors.Window`

It looks like Mono's ToolStrip (and MenuStrip which inherits from it) may ignore its BackColor property; it always passes SystemColors.Control to ToolStripRenderEventArgs.BackColor instead of its own BackColor:

https://github.com/mono/mono/blob/f0921fd850b0c8e61d5954fa71471189d2a55447/mcs/class/System.Windows.Forms/System.Windows.Forms/ToolStrip.cs#L1021

That could be both the cause of the problem and a barrier preventing it from being fixed in CKAN code.

**Comment by HebaruSan** [comment] 2018-10-02 16:14
Submitted mono/mono#10942.

**Comment by HebaruSan** [comment] 2018-10-17 13:42
Also submitted mono/mono#11196 to fix message boxes, but we only use that in the notification of game update shown in that screenshot.

**Comment by HebaruSan** [comment] 2018-10-19 21:46
Submitted mono/mono#11287 to really fix the toolbar backgrounds. See that link for the gory details.
In the process of investigating that I think I also discovered a way to do a workaround in CKAN code, stay tuned...

**Closed** 2018-10-21 15:37 UTC
Labels: Bug, GUI, Linux, Mono
