### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by xmkxgepi** [KSP-CKAN/CKAN#3921] opened 2023-10-27 12:44 UTC
### Problem

When downloading spacedock, the connection is slow, but it can be downloaded.  However, ckan will forcefully disconnect the download due to slow connection and use the unreachable Archive.org mirror, which is a very stupid design.

### Suggestion

Give this function a switch, or add multithreaded download function.

### Alternatives

Copy the download link of Spacedock to other download tools.

**Comment by HebaruSan** [comment] 2023-10-27 15:01
@xmkxgepi, you click click the "ellipsis" button to "Edit" an existing issue rather than submitting it again.

**Comment by HebaruSan** [comment] 2023-10-27 15:01
Duplicate of #3922

**Closed by HebaruSan** 2023-10-27 15:01 UTC
