### ISSUE TITLE
Dependee

### ISSUE THREAD

**Issue by anxcon** [KSP-CKAN/CKAN#1233] opened 2015-07-03 14:31 UTC
the droplist for relationships, perhaps add dependee

often i find something nice, like coolrockets for smokescreen, but takes forever to scroll down list looking at "depends" to see if anything else depends on smokescreen to see what other effects there are, and the forum may not list everything, and every base mod potentially has this issue

ckan already has "depends" listing in the database, so shouldn't be too hard for it to ask "what mods depend on me?" and list in dependee :) fully auto, no missin if a modder isnt aware

**Comment by dbent** [comment] 2015-07-05 14:23
Closing as duplicate of #1100.

**Closed by dbent** 2015-07-05 14:23 UTC
