### ISSUE TITLE
[Feature] Display all directories not associated with a known mod

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/CKAN#3757] opened 2023-01-07 23:27 UTC
Problem
-------
Sometimes I'll install a mod by hand, a mod not known by CKAN.   Then, when doing some cleanup, I may not be sure if a specific directory was installed by CKAN or not, especially when a lot of mods are installed

Suggestions
-----------
On the main CKAN screen, add a filter to show "Unknown" mod directories.  This would be usable after doing at least one refresh, and it would list the unknown directories

**Comment by HebaruSan** [comment] 2023-01-08 00:47
The suggestion isn't really viable, since the main screen and filters operate on a list of _mods_, not directories. This would have to be a separate, new screen.

**Comment by HebaruSan** [comment] 2023-01-08 00:57
Duplicate of #2045

**Closed by HebaruSan** 2023-01-08 00:57 UTC
Labels: Enhancement, GUI
