### ISSUE TITLE
CKAN opens cmd, then crashes right away - going to cmd and using "ckan gui" doesn't work

### ISSUE THREAD

**Issue by VfarhatF** [KSP-CKAN/CKAN#3151] opened 2020-09-10 22:34 UTC
Background
----------
* Operating System: Win10
* CKAN Version:  Dyson - 1.28.0
* KSP Version: 1.10.1

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No, it is a fresh install (after a thousand times)

Problem
CKAN opens cmd, then crashes right away - going to cmd and using "ckan gui" doesn't work

**Describe the bug**

**Steps to reproduce**
* Go to... ckan.exe
* Click on... it
* See error

**Expected behavior**

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```
Microsoft Windows [versão 10.0.18362.1016]
(c) 2019 Microsoft Corporation. Todos os direitos reservados.

C:\Users\Master>cd C:\Steam\steamapps\common\Kerbal Space Program

C:\Steam\steamapps\common\Kerbal Space Program>ckan

Exceção Sem Tratamento: System.BadImageFormatException: Foi feita uma tentativa de se carregar um programa com um formato incorreto. (Exceção de HRESULT: 0x8007000B)
   em CurlSharp.NativeMethods.curl_global_init(Int32 flags)
   em CurlSharp.Curl.GlobalInit(CurlInitFlag flags)
   em CKAN.Curl.Init()
   em CKAN.CmdLine.MainClass.Main(String[] args)

**Comment by HebaruSan** [comment] 2020-09-10 22:36
Duplicate of #3115
See that issue for workarounds

**Closed by HebaruSan** 2020-09-10 22:36 UTC
