### ISSUE TITLE
Certificate error updating a repository

### ISSUE THREAD

**Issue by sqrtie** [KSP-CKAN/CKAN#3970] opened 2023-12-20 16:05 UTC
![надо](https://github.com/KSP-CKAN/CKAN/assets/154074476/139bbc48-a6c1-4492-be48-88b8a7f26012)
Hello! Faced with such a problem. What should I do? I have the original KSP installed in the Steam

**Comment by HebaruSan** [comment] 2023-12-20 16:07
What does this part say in English?

![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/bbec8676-a590-43ef-b508-59303a170bea)

**Comment by sqrtie** [comment] 2023-12-20 16:07
> What does this part say in English?
> 
> ![image](https://private-user-images.githubusercontent.com/1559108/291949557-bbec8676-a590-43ef-b508-59303a170bea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwODg3MzQsIm5iZiI6MTcwMzA4ODQzNCwicGF0aCI6Ii8xNTU5MTA4LzI5MTk0OTU1Ny1iYmVjODY3Ni1hNTkwLTQzZWYtYjUwOC01OTMwM2ExNzBiZWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjBUMTYwNzE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzBhMWQwYmZiYTkxMjJmMDlmZGYzNDU5Y2RhYWIwZGU0YTU5YmNiYTYwZmE3YmIzMjhkMmQ3OGI4N2I3NTZmMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.389jidvfSDxmHF1zQdmLgsl8Cvq09ydZQRZt5xswDmQ)

It says: "The deleted certificate is invalid according to the authentication results"

**Comment by HebaruSan** [comment] 2023-12-20 16:10
There's a good chance you've been infected by some crypto malware. Check your hosts file (see #3802 and #3814).

If not, the next thing to check is your routers, firewalls, and antivirus. From the message you quoted, something is stopping CKAN from accessing this URL:

- https://github.com/KSP-CKAN/KSP2-CKAN-meta/archive/main.tar.gz

If you can figure out what that is and fix it, then the repository update should succeed.

**Comment by sqrtie** [comment] 2023-12-20 16:12
> There's a good chance you've been infected by some crypto malware. Check your hosts file (see #3802 and #3814).
> 
> If not, the next thing to check is your routers, firewalls, and antivirus. From the message you quoted, something is stopping CKAN from accessing this URL:
> 
> * https://github.com/KSP-CKAN/KSP2-CKAN-meta/archive/main.tar.gz
> 
> If you can figure out what that is and fix it, then the repository update should succeed.

![image](https://github.com/KSP-CKAN/CKAN/assets/154074476/86ccd27f-b40d-4d20-9f34-42d75b27fecd)
it seems to me that the browser itself is blocking access

**Comment by HebaruSan** [comment] 2023-12-20 16:14
CKAN doesn't go through your browser. Rather, there is probably an underlying problem elsewhere, such as at your ISP, which is causing both CKAN and your browser to have problems.

Closing because the cause is external to CKAN. I think this will still allow new comments if anyone else has suggestions for you, but this isn't something the CKAN team will be working on.

**Closed by HebaruSan** 2023-12-20 16:14 UTC
Labels: Support, Network

**Comment by sqrtie** [comment] 2023-12-20 16:16
> CKAN doesn't go through your browser. Rather, there is probably an underlying problem elsewhere, such as at your ISP, which is causing both CKAN and your browser to have problems.
> 
> Closing because the cause is external to CKAN. I think this will still allow new comments if anyone else has suggestions for you, but this isn't something the CKAN team will be working on.

k, btw sorry for wasting your time!
