### ISSUE TITLE
[Bug] stuck in screen for 'X is provided by more than one available module"

### ISSUE THREAD

**Issue by tjanke42** [KSP-CKAN/CKAN#2862] opened 2019-09-03 03:29 UTC
The Choose Mods tab can become stuck, such that the only thing that works is the Cancel button.

----------
* Operating System: Windows 7 Ultimate SP1
* CKAN Version: 1.26.2, 1.26.4
* KSP Version: 1.7.3

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No.

Problem
-------
I've already installed the mods that were fully compatible with KSP 1.7.3.  I then forced compatibility for 1.7.2.

I select Pood's Milky Way Skybox and hit Apply Changes.  Focus shifts to the Changeset tab, I click Apply.

The focus then shifts to the Choose Mods tab, with the message 

> Module TextureReplacer OR TextureReplacerReplaced OR SigmaReplacements-Skybox OR DiRT is provided by more than one available module. please choose one of the following mods:

The available mods are TextureReplacer or DiRT.  I choose either one (doesn't matter), click Continue.  The status bar reports "Success!" in the bottom right of the window, but nothing else happens.  Clicking any of the other tabs does nothing (focus stays on Choose Mods tab).  The only thing that works as intended is the Cancel button.

Clicking Cancel returns focus to the Manage Mods tab.

**Steps to reproduce**
See above.  Might depend on my specific mod selections.  If you'd like me to post a list of those, let me know.

**Expected behavior**
Focus should shift to the Status Log tab and the installation should proceed.

**Screenshots (if applicable)**
![image](https://i.imgur.com/nWBBrM2.png)

**CKAN error code (if applicable):**
None.

**Comment by HebaruSan** [comment] 2019-09-03 03:43
Can you test with the latest release?
https://github.com/KSP-CKAN/CKAN/releases/tag/v1.26.4

I don't recall any changes that might affect this, but it's best to be current for tracking purposes.

**Comment by tjanke42** [comment] 2019-09-03 04:29
Ok, updated to latest, v1.26.4, same behavior.

I've narrowed it down to Pood's Milky Way Skybox as the mod for which ckan is showing the Choose Mods tab.  It has a Max KSP Version of 1.7.0, I'm forcing compatibility with 1.7.x.

**Comment by HebaruSan** [comment] 2019-09-03 21:46
For what it's worth, I tried it in Linux, and it worked fine. I'll try again the next time I boot into Windows.

**Comment by HebaruSan** [comment] 2019-09-12 03:43
OK, I just tried installing Pood's Milky Way Skybox on Windows, and it still worked fine regardless of which retexturing mod I chose.

@tjanke42, can you share your mod list? Maybe there's a conflict between some modules or something like that.

**Comment by HebaruSan** [comment] 2019-10-09 21:51
Issue author not responsive to follow-up questions, closing.
@tjanke42, if you have a chance to return to this issue, please see above regarding sharing more information about your setup. We can't reproduce this, so we need to tease more details about the issue from your setup to figure out what's going on.

**Closed by HebaruSan** 2019-10-09 21:51 UTC
Labels: Bug, GUI, Needs more info
