### ISSUE TITLE
[Bug]: CKAN wants Ferram Aerospace Research to be reinstalled every time I launch KSP

### ISSUE THREAD

**Issue by Clayell** [KSP-CKAN/CKAN#4281] opened 2024-12-30 22:54 UTC
### Is there an existing issue for this?

- [X] I have checked the existing issues for an existing issue. I even actually looked at the ones that are pinned to the top!

### Operating System

Windows 11

### CKAN Version

1.35.2

### Games

KSP 1

### Game Version

1.12.5

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

Principia and KSPTOT Connect

### Describe the bug

I believe something within FAR or another mod is deleting some files, causing ckan to want to reinstall it every time I launch KSP. Specifically, it seems to be FARForceDataUpdate.cfg and Plugins/PluginData/FerramAerospaceResearch (the 2nd one is present, but ckan wants it to be a file instead of a folder?)
![image](https://github.com/user-attachments/assets/64b785fe-a14f-4c64-967f-65bf44c79f42)
![image](https://github.com/user-attachments/assets/24a66ed2-2870-43bd-8522-313f5728dabb)

![image](https://github.com/user-attachments/assets/f88428c4-c0cd-433e-ae64-8107fdbd77e9)
![image](https://github.com/user-attachments/assets/a499ee43-3b24-40c1-998f-22d090c608f4)

I don't think this is necessarily a CKAN bug, but CKAN should not want to reinstall a mod every time that the file format is different from expected (or should at least allow you to tick an option that makes it ignore when a file format is different from expected).

I have put my modlist into the logs below.

### Steps to reproduce

- Install FAR via CKAN
- Launch KSP
- Exit KSP
- Refresh CKAN
- CKAN wants you to reinstall FAR due to missing files

**Comment by HebaruSan** [comment] 2024-12-30 22:57
Hi @Clayell, thanks for the report. Yes, FAR deletes one of its own files in-game 😵‍💫.
See #4213 for how to make a label to skip the missing file check for this mod.

**Comment by HebaruSan** [comment] 2024-12-30 22:58
Duplicate of #4204

**Closed by HebaruSan** 2024-12-30 22:57 UTC
