### ISSUE TITLE
Cant find KSP_x64.exe when launching KSP 1.0.5 64bit

### ISSUE THREAD

**Issue by leoponka** [KSP-CKAN/CKAN#3545] opened 2022-03-13 17:36 UTC
Background
----------
* Operating System: WIndows 10
* CKAN Version: 1.30.4
* KSP Version: 1.05.1028

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
yeah

Problem
-------
**Describe the bug**
When i try to open KSP with mods by CKAN or Steam it wont work

**Steps to reproduce**
* Go to... 
* Click on...
* See error

**Expected behavior**
launch with BDarmory on KSP 1.0.5

**Screenshots (if applicable)**
![Zrzut ekranu (3)](https://user-images.githubusercontent.com/101520025/158071968-c8c7e80c-524c-4d5c-976f-544f7ecfcbed.png)

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment] 2022-03-13 17:39
Duplicate of #3544

**Comment by HebaruSan** [comment] 2022-03-13 17:39
Hi @leoponka, please don't open new issues for the exact same problem previously reported in another issue. Thanks!

**Closed by HebaruSan** 2022-03-13 17:39 UTC
Labels: Support, Duplicate
