### ISSUE TITLE
i was told to download the .exe -_-

### ISSUE THREAD

**Issue by coolamazing** [KSP-CKAN/CKAN#2512] opened 2018-08-22 00:50 UTC
Background
----------

**CKAN Version:** 
1.25.2

**KSP Version:** 
1,4,4

**Operating System:** 
windows 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 

no
Problem
-------the .exe doesn't work

**What steps did you take in CKAN?**

**What did you expect to happen?**
-_- for it to not fail again

**What happened instead?**
it failed

**Screenshots:**

![thx genius](https://user-images.githubusercontent.com/42589471/44436518-a574e380-a583-11e8-8936-9b54ff09c3c3.png)

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment] 2018-08-22 00:51
Duplicate of #2483, fixed in #2482.

**Closed by HebaruSan** 2018-08-22 00:51 UTC
