### ISSUE TITLE
[Bug]: Found end of file when another token type was expected

### ISSUE THREAD

**Issue by oldmantom-nkn** [KSP-CKAN/CKAN#4201] opened 2024-09-27 17:37 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows 10

### CKAN Version

1.35

### Games

KSP 1

### Game Version

Latest via Steam

### Describe the bug

Crashes on launch since updating to the latest.
![image](https://github.com/user-attachments/assets/cac3e4bc-446e-4f79-9012-d3784067d70f)

### Steps to reproduce

Simply downloaded and double clicked.

**Comment by HebaruSan** [comment] 2024-09-27 17:38
Duplicate of #4197

**Closed by HebaruSan** 2024-09-27 17:38 UTC
