### ISSUE TITLE
[Feature] Convert exisitng instance into CKAN

### ISSUE THREAD

**Issue by Monniasza** [KSP-CKAN/CKAN#3075] opened 2020-06-12 13:32 UTC
Problem
-------
**Is your feature request related to a problem? Please describe.**
Manually converting large instances takes too much time

Suggestions
-----------
**Describe the solution you'd like**
When the user creates a new instance and CKAN detects mods, the user gets following prompt:

CKAN has found 220 mods which can be converted from AD into CKAN managed mods. Do you want to convert? 

Some mods meet multiple criteria.

- 196 mods with .version files
- 100 mods with unique directories
- 12 mods with plugins

[Yes] [No] [More options]

6 mods can't be converted.

**Describe alternatives you've considered**

**Additional context**

**Comment by HebaruSan** [comment] 2020-06-12 14:48
Duplicate of #2186.

**Closed by HebaruSan** 2020-06-12 14:48 UTC
