### ISSUE TITLE
[Bug] SYSTEM.BADIMAGEFORMATEXCEPTION when opening

### ISSUE THREAD

**Issue by LucasSeren** [KSP-CKAN/CKAN#3148] opened 2020-09-05 18:38 UTC
Background
----------
* Operating System: Windown 10
* CKAN Version: 1.28.1
* KSP Version: 1.10.1

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
Yes

Problem
-------
**Describe the bug**
CKAN opens the cmd shows this error (SYSTEM.BADIMAGEFORMATEXCEPTION) and closes.

**Steps to reproduce**
Just click to open CKAN

**Expected behavior**
Open CKAN

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/68658108/92311482-c6070f00-ef8d-11ea-9271-00f13aa0eb2f.png)

**CKAN error code (if applicable):**

Exceção Sem Tratamento: System.BadImageFormatException: Foi feita uma tentativa de se carregar um programa com um formato incorreto. (Exceção de HRESULT: 0x8007000B)
   em CurlSharp.NativeMethods.curl_global_init(Int32 flags)
   em CurlSharp.Curl.GlobalInit(CurlInitFlag flags)
   em CKAN.Curl.Init()
   em CKAN.CmdLine.MainClass.Main(String[] args)

```
PLACE CODE HERE !
```

**Comment by LucasSeren** [comment] 2020-09-05 18:39
Yes i have .NET 4.5

**Comment by DasSkelett** [comment] 2020-09-05 18:49
Duplicate of #3115, see that issue for possible workarounds.

**Closed by DasSkelett** 2020-09-05 18:49 UTC
