### ISSUE TITLE
Cerproblem with roverdude/Firespitter mod

### ISSUE THREAD

**Issue by www2000** [KSP-CKAN/CKAN#2308] opened 2018-02-23 23:43 UTC
Background
----------

**CKAN Version:**
1.24

**KSP Version:**
1.3.1

**Operating System:**
Ubuntu 17.10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
Clean install

Problem
-------

**What steps did you take in CKAN?**
Install one of over 

**What did you expect to happen?**
Download and install the mod.

**What happened instead?**

Most of RoverDude and Firespitter mods fall to download.

Download say that i have a cert problem

**CKAN error codes (if applicable):**

```
About to install...

 * Firespitter Core v7.6.0 (github.com, 29,2 MB)

Downloading "https://github.com/snjo/Firespitter/releases/download/v7.6.0/Firespitter_7.6.0.zip"
Oh no! Our download failed with a certificate error!

Consult this page for help:
	https://github.com/KSP-CKAN/CKAN/wiki/SSL-certificate-errors
Error!
```

**Comment by HebaruSan** [comment] 2018-02-23 23:49
Did you try the steps on the wiki page in the message?

**Comment by www2000** [comment] 2018-02-23 23:58
I can confirm that i have done the steps on that wiki page and done the RTFM.

**Comment by HebaruSan** [comment] 2018-02-24 00:02
Which version of Mono do you have?

**Comment by www2000** [comment] 2018-02-24 00:03
$ mono -V
Mono JIT compiler version 4.6.2 (Debian 4.6.2.7+dfsg-1ubuntu1)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen

**Comment by HebaruSan** [comment] 2018-02-24 00:09
Thanks. It seems that you need Mono 4.8 or later to access GitHub URLs now (since they require TLS 1.2), and in some versions you have to set this environment variable:

http://www.mono-project.com/docs/about-mono/releases/4.8.0/

> TLS 1.2 Support
> Mono now ships with TLS 1.2, powered by Google’s BoringSSL project. (*)
> 
> To use it, you must set the environment variable MONO_TLS_PROVIDER to the value “btls”, like this:
> 
> `export MONO_TLS_PROVIDER=btls`

Can you try that?

**Comment by www2000** [comment] 2018-02-24 00:32
Current work around for this problem is :
```
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
echo "deb http://download.mono-project.com/repo/debian stable-stretch main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
sudo apt-get update
```

**Comment by HebaruSan** [comment] 2018-02-24 00:43
So you got it working?

**Comment by www2000** [comment] 2018-02-24 00:46
Yes

**Comment by HebaruSan** [comment] 2018-02-24 00:56
Cool. Is your solution something we could add to the wiki to help other Ubuntu users? It looks like you just installed the latest mono from their main repo.

**Comment by HebaruSan** [comment] 2018-02-24 01:11
@www2000, I made some edits to the cert errors page. If you have a chance, please take a look to make sure that it's accurate and helpful.

https://github.com/KSP-CKAN/CKAN/wiki/SSL-certificate-errors/_compare/eb891aa48662caf124d8a45fd6edfc4fcc551713...01e83e134d3bd9a602bb85877fda969a070aa7ef

Closing this now as the issue is resolved and documentation updated.

**Closed by HebaruSan** 2018-02-24 01:11 UTC
Labels: Linux, Mono, Network, Support
