### ISSUE TITLE
Installing mods fails / CKAN.InvalidModuleFileKraken /// Menu Error

### ISSUE THREAD

**Issue by MomoxStudios** [KSP-CKAN/CKAN#2383] opened 2018-03-22 16:58 UTC
Background
----------

**CKAN Version:** 1.24.0

**KSP Version:** 1.4.1.2089

**Operating System:** Windows 10 Ultimate, 64bit

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** No.

**Description:**
Just to mention, everything worked fine until v1.24 came out. After that CKAN does no longer do a useful job and seems to die on whatever I do. I reinstalled it several times including re-downloading the .exe, went over the troubleshoot, cleaned the installation properly also using cmd and trying out the repair function via cmd. I tried whatever I could to fix this error and I'm not a pc amateur so opening this issue was really the last option for me. Whatever I've done whatever I could. Maybe you can help me?

Problem (2 of them)
-------

**What steps did you take in CKAN?**
First Problem: Opening the CKAN settings dialog
Second one: Downloading various mods

**What did you expect to happen?**
First Problem: I expected a working menu (see screenshots)
Second one: The download would succeed as it usually did

**What happened instead?**
First problem: An application error has occoured, the m

**Screenshots:**
Error upon opening the settings dialog:
https://i.momoxstudios.net/hb5c.png
Settings dialog after pressing continue:
https://i.momoxstudios.net/7ghj.png
Complete JIT Error message:
https://pastebin.com/iRtXQNfa
2nd Problem Download Log + Error
https://pastebin.com/cYzSdMfb
Powershell Dialog:
https://i.momoxstudios.net/u4aw.png

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment] 2018-03-22 17:03
Duplicate of #2300 and #2285. See those issues for status and workarounds.

**Closed by HebaruSan** 2018-03-22 17:03 UTC
