### ISSUE TITLE
Directory %TEMP%\CdFileMgr not exist cause install mod fail

### ISSUE THREAD

**Issue by studentmain** [KSP-CKAN/CKAN#2474] opened 2018-07-11 10:06 UTC
Background
----------

**CKAN Version:** 
1.25.1

**KSP Version:** 
1.4.4.2215

**Operating System:** 
Windows 10 1803 Pro x64

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

Problem
-------

**What steps did you take in CKAN?**
Select a mod, install

**What did you expect to happen?**
Install success

**What happened instead?**
Download success, then throw error

> System.IO.DirectoryNotFoundException: 未能找到路径“C:\Users\Zch\AppData\Local\Temp\CdFileMgr\b5565c89-ff5d-4a.json”的一部分。

I manually create %TEMP%\CdFileMgr folder, then everything goes well

**CKAN error codes (if applicable):** 
Full stack trace:

<pre>
************** 异常文本 **************
System.IO.DirectoryNotFoundException: 未能找到路径“C:\Users\Zch\AppData\Local\Temp\CdFileMgr\b5565c89-ff5d-4a.json”的一部分。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   在 ChinhDo.Transactions.WriteAllTextOperation.Execute()
   在 ChinhDo.Transactions.TxFileManager.EnlistOperation(IRollbackableOperation operation)
   在 CKAN.RegistryManager.Save(Boolean enforce_consistency)
   在 CKAN.ModuleInstaller.InstallList(ICollection`1 modules, RelationshipResolverOptions options, IDownloader downloader)
   在 CKAN.Main.InstallMods(Object sender, DoWorkEventArgs e)
   在 System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   在 System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
</pre>

**Comment by politas** [comment] 2018-07-11 10:32
Hmm. Normally, that folder gets created automatically without any problem.

**Comment by HebaruSan** [comment] 2018-07-11 16:01
This is a duplicate of #2342 (as was #2461). Apparently this is affecting a few people, but so far there are no clues as to the cause. If you're able to figure out why the folder creation fails, please post comments on #2342.

**Closed by HebaruSan** 2018-07-11 16:01 UTC
Labels: Windows
