### ISSUE TITLE
[Bug]: ckan will not open after the update

### ISSUE THREAD

**Issue by Klkdd** [KSP-CKAN/CKAN#4220] opened 2024-10-04 17:00 UTC
### Is there an existing issue for this?

- [X] I have checked the existing issues for an existing issue. I even actually looked at the ones that are pinned to the top!

### Operating System

windows

### CKAN Version

1.33.2.0=>1.35.0.24270

### Games

KSP 1

### Game Version

Any

### Describe the bug

After updating ckan, a cmd page opens and the program closes
![Screenshot (388)](https://github.com/user-attachments/assets/4ac98bf6-dc7a-4a9c-aa29-571375557331)

### Steps to reproduce

Update (ckan)

**Comment by Klkdd** [comment] 2024-10-04 17:00
How can I fix it?

**Comment by HebaruSan** [comment] 2024-10-04 17:14
Duplicate of #4197

**Closed by HebaruSan** 2024-10-04 17:14 UTC
