### ISSUE TITLE
Application stopped downloading at 25% on initial install of a LOT of addons..

### ISSUE THREAD

**Issue by Acecool** [KSP-CKAN/CKAN#1072] opened 2015-06-04 21:21 UTC
I ended up closing the application and downloaded everything manually ( one click at a time ) and then it worked... It was stuck at 25% for an hour on 50MBit connection ( wireless with interference ) and when I downloaded one at a time I had no issues.

Reporting this so that the download system may be fixed ( incorrect handling of time-out and system doesn't check if downloads are still on-going [ ie it should check that speed is > 0 || percent not hanging ] )...

**Comment by ayan4m1** [comment] 2016-08-01 22:30
Hi, I'm trying to work on the backlog of issues in the CKAN project. Would you mind retesting your scenario and providing an updated problem report including:

**CKAN Version:** 

**Operating System:** 

**The issue you are experiencing:** 

**How to recreate this issue:** 

**CKAN error codes (if applicable):** 

If you cannot reproduce your issue or feel that it has been resolved, please take a moment to close this issue. Thank you for your time!

**Closed** 2016-08-10 00:00 UTC
Labels: support
