### ISSUE TITLE
Feature request:  Centralized location for all downloads

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/CKAN#1861] opened 2016-08-07 03:01 UTC
Right now, CKAN downloads and stores  the downloaded zip files in the CKAN/downloads directory in each game install.  This can use a lot of disk space if you have a lot of installs, also can mean extra time when setting up a new install.

It would be nice if there was an option to use a single location for all CKAN-managed installs, and to be able to specify the location.  It could mimic the current behaviour by assuming the game directory if the patch didn't start with a drive (as in Windows c:), or a forward or backslash

**Comment by politas** [comment] 2016-08-07 04:58
Duplicate of #584

**Closed by politas** 2016-08-07 04:58 UTC
