### ISSUE TITLE
Importing from .ckan doesn't give feedback for unselected KSP versions

### ISSUE THREAD

**Issue by damccull** [KSP-CKAN/CKAN#2693] opened 2019-03-04 22:57 UTC
Background
----------

**CKAN Version:** 
1.25.4

**KSP Version:** 
1.6.1.2401

**Operating System:** 
Windows  10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

Problem
-------

**What steps did you take in CKAN?**
Tried to import a ckan file to a fresh install of ckan on a new computer.

**What did you expect to happen?**
I expected to see all mods in my CKAN file installed, or a notification explaining that some of the mods in the CKAN file are incompatible with the currently selected KSP compatible version set.

**What happened instead?**
Mods that were not supported in the currently selected set of KSP Compatible Versions silently failed installation.

[ksp-installed-mods.txt](https://github.com/KSP-CKAN/CKAN/files/2947249/ksp-installed-mods.txt)

**Comment by HebaruSan** [comment] 2019-03-04 23:13
Please share the .ckan file you tried to import.
And please input the actual version of CKAN you're using; there's a pre-release out now, and this may be one of the things that was fixed in it.

**Comment by damccull** [comment] 2019-03-08 19:55
CKAN 1.25.4
File is attached. I renamed from .ckan to .txt so it would upload.
[ksp-installed-mods.txt](https://github.com/KSP-CKAN/CKAN/files/2947249/ksp-installed-mods.txt)

**Comment by damccull** [comment] 2019-03-08 20:04
Possible further info: I pre-checked all 3 "supported versions" i was using (1.4, 1.5, and 1.6) before I tried to import, but only about 6 of the plugins even tried to install. The others just....didn't show up. But I can check them manually in the list without having to change any settings.

**Comment by HebaruSan** [comment] 2019-03-08 20:07
Thanks! Confirmed duplicate of #2652.

Try the pre-release, which contains the fix: https://github.com/KSP-CKAN/CKAN/releases/tag/v1.26.0-PRE1

**Closed by HebaruSan** 2019-03-08 20:07 UTC
Labels: Needs more info

**Comment by tofof** [comment] 2019-06-28 20:10
This behavior remains present in 'Dragon'. 
Should this actually be closed?

**Comment by HebaruSan** [comment] 2019-06-28 20:13
@totof, no it's not; please open a new issue with a complete description if you're seeing a bug.
