### ISSUE TITLE
Error in CKAN client 

### ISSUE THREAD

**Issue by helloworld1025** [KSP-CKAN/CKAN#3133] opened 2020-08-06 11:07 UTC
Background
----------
* Operating System: Windows 10
* CKAN Version: 1.28,0
* KSP Version: 1.10.1

I just installed mods

Problem
-------
After running CKAN I get this error:
Scanning for DLCs and manually installed modules...
Updating repositories...
Failed to download https://github.com/KSP-CKAN/CKAN-meta/archive/master.tar.gz: System.Net.WebException: Невозможно соединиться с удаленным сервером ---> System.Net.Sockets.SocketException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:443
   в System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   в System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Конец трассировки внутреннего стека исключений ---
   в System.Net.WebClient.DownloadFile(Uri address, String fileName)
   в System.Net.WebClient.DownloadFile(String address, String fileName)
   в CKAN.Net.Download(String url, String& etag, String filename, IUser user)
   в CKAN.Repo.UpdateRegistry(Uri repo, KSP ksp, IUser user, SortedDictionary`2& downloadCounts, String& currentETag)
Repository update failed!

I have last .NET Framework 4.8
I don't have problems with internet 
I have purchased KSP

**Comment by DasSkelett** [comment] 2020-08-06 11:18
@helloworld1025 you've already opened an issue regarding this: #3077 
The answer is still the same, some firewall or antivirus software is causing this by overwriting the DNS responses for GitHub domains. Nothing we can do on CKAN's side about that.
Closing as duplicate of #3077

**Closed by DasSkelett** 2020-08-06 11:18 UTC
