### ISSUE TITLE
AntennaRange is missing from CKAN after updated on Kerbalstuff

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/CKAN#1532] opened 2015-12-07 12:06 UTC
This is a duplicate of the TweakableEverything post.  AntennaRange seems to have disappeared from CKAN (filter All) after it was updated to 1.0.5 on Kerbalstuff

**Comment by plague006** [comment] 2015-12-07 14:35
`AntennaRange` was not removed from CKAN. You currently can't find it in the mods list due to its dependency on `EVAManager` which hasn't been updated (or confirmed working for) 1.0.4. This is a bug and was previously reported in https://github.com/KSP-CKAN/CKAN/issues/1529. Sorry for the inconvenience and/or confusion this may have caused. If the un-updated mod I mentioned is compatible with 1.0.5, re-open this issue and let us know, this will result in a faster fix for this particular mod.

Thanks for bringing us this report, but closing this for now as it's a duplicate of #1529.

**Comment by linuxgurugamer** [comment] 2015-12-07 15:53
Thank you for a concise explanation.


JBB

**Comment by tivec** [comment] 2015-12-07 17:37
Just thought I'd chip in on this issue - the EVAManager.dll file is included with the download from the specified location (kerbalstuff) and has the same "modified" date as AntennaRange.dll, so it could probably be considered that it has been updated (or at least recompiled), just not released by Toadicus. I poked him on IRC about this, but haven't heard anything back.

**Comment by Olympic1** [comment] 2015-12-07 19:03
AntennaRange now shows up in CKAN because EVAManager has updated in https://github.com/KSP-CKAN/CKAN-meta/commit/6503e8dd0032f3b0bdc1ae2cd72bf6be068214f7

**Closed by Olympic1** 2015-12-07 19:03 UTC
