### ISSUE TITLE
restarting after CKAN upgrade fails if spaces in path to ckan.exe

### ISSUE THREAD

**Issue by juleskers** [KSP-CKAN/CKAN#1970] opened 2017-01-02 11:11 UTC
CKAN's Command line interface's auto-update functionality is broken in a (non-critical) way:
after downloading and installing a new version of CKAN, it doesn't restart properly if ckan.exe is installed in a location with spaces in the path.
Restarting CKAN manually works as normal.

### expected behaviour
CKAN offers to download a new version, and should restart automatically after the update is downloaded and installed.

### Actual behaviour
Update is downloaded succesfully, but CKAN doesn't restart, instead showing an error (see below) in the terminal.

### What steps can be taken to reproduce the issue? 
1) Install CKAN in a path that has spaces in it:
for me: `~/.local/share/Steam/steamapps/common/Kerbal\ Space\ Program/ckan.exe` 
(Note the escaped spaces in "Kerbal Space Program")
2) Start CKAN (from a terminal) when there is an update available:
`mono ~/.local/share/Steam/steamapps/common/Kerbal\ Space\ Program/ckan.exe`
3) CKAN provides the "There is a new version of CKAN available" popup, agree to download now.
4) Update is downloaded and unpacked
5) 'old' CKAN exits, but new one doesn't start. In the terminal there is the following error, and a new terminal prompt, indicating the process has terminated:
````
Cannot open assembly '/home/install/.local/share/Steam/steamapps/common/Kerbal': No such file or directory.
exception inside UnhandledException handler: 

install@corsair:~$ _
````
Note that the assembly that cannot be found is the partial installation path, truncated at the first space.

### CKAN error codes (if applicable)
N/A

### CKAN Version
both versions before "CKAN v1.22.1-0-g174271a (beta)".
(CKAN offered to auto-update twice this week, both updates had the error;
the listed version is the one after the second update+restart)

### Operating System
Ubuntu linux 14.04

`````
mono --version
Mono JIT compiler version 4.6.2 (Stable 4.6.2.7/08fd525 Mon Nov 21 12:08:40 UTC 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen
`````
cert-bundle is synced
libcurl4-openssl-dev is installed

### Note
Initially posted to the wrong (non-KSP) CKAN:
https://github.com/ckan/ckan/issues/3383
It seems this happens enough that the other CKAN has a label for this specific user error:
https://github.com/ckan/ckan/issues?q=label%3A%22Wrong%20CKAN%22

**Comment by politas** [comment] 2017-01-03 08:19
Did you use this method for starting CKAN and have successful restarts after upgrading with previous versions of CKAN?

**Comment by juleskers** [comment] 2017-01-03 16:03
Yes, I always start CKAN via the terminal, because it's in my command history, and I generally prefer to see console output for all programs, in case something goes wrong.

I indicated the "last two versions" because those are the times I explicitly noticed it.
Thinking back, I'm not sure if it has ever successfully restarted after an upgrade. It could be that it stopped working long ago, or that it never worked at all. It's not something I paid specific attention to, to be honest.

Hope this helps!

**Comment by juleskers** [comment] 2017-01-03 16:16
P.S. I've done some browsing in the source-code, and found a promising candidate:
https://github.com/KSP-CKAN/CKAN/blob/master/AutoUpdate/Main.cs
It's the bit that restarts CKAN after an auto-update: lines 77-88

From the looks of it, if "isOnMono()" returns true, the process is started correctly escaped.
However, the alternate branch doesn't escape the path. I'm not sure it's required in that instance?

Of course, there could be something else going on, maybe it's looking for another assembly that it can't find.
Is there some way to increase logging in CKAN? (preferably without compiling)
I checked the --help, and there aren't any logging options.
I don't have a CKAN.log file, and the log4net config seems to indicate only WARN and higher is logged.

**Comment by politas** [comment] 2017-01-04 02:54
You can customise  an xml file for logging - https://github.com/KSP-CKAN/CKAN/blob/master/GUI/log4net.xml grab a copy of that, and try some different options. I think if you change WARN to INFO on line 23, you'll get everything logged.

**Comment by juleskers** [comment] 2017-01-04 13:55
Thanks! That worked!
I made a copy of the log4net.xml in my home folder*, and set loglevel to DEBUG.
That provides a nice amount of log spew :-)
We'll know more the next time CKAN gets an update.

* It seems CKAN looks for the log-config in whatever the current directory is. Putting the log-config next to ckan.exe didn't do anything.
I start CKAN from my home-folder (default where the terminal opens), using a full absolute path, so the log-config must be in that default (home) folder.

P.S. The raw config puts the logfile in "./CKAN.log".
THAT however, turns out to land in the folder next to CKAN.exe. Apparently CKAN.exe `cd`-s into there

P.P.S: The default 1MB logfile is a bit tiny for DEBUG levels, the mod-compatibility-checking alone takes up 4MB :-)

**Comment by politas** [comment] 2017-01-05 01:23
It's probably mono that makes the working directory the location of the exe you're feeding it. That's the default for running Windows programs.

**Comment by ayan4m1** [comment] 2017-09-17 20:57
@politas Can we close this out?

**Comment by politas** [comment] 2017-09-18 02:27
I don't think we've resolved the original issue, have we? @juleskers, we have a few changes in dev so I could push a new release if you are set up to capture the info you need for your investigation.

**Comment by juleskers** [comment] 2017-09-18 05:30
Hi! It's been a while since I've last opened ksp, but I am all set up to log stuff!

**Closed** 2017-09-26 00:00 UTC
Labels: Support

**Comment by juleskers** [comment] 2017-09-26 06:51
Thanks dear bit, but the underlying issue is still not resolved.

(I also believe the "support" label isn't really applicable (anymore))

**Comment by ayan4m1** [comment] 2017-09-26 20:50
Something else is going on, because I cannot reproduce your problem given the steps you have provided. I am on Windows, maybe it is platform-specific.
