### ISSUE TITLE
CKAN doesn't install dependencies for recommended and suggested mods

### ISSUE THREAD

**Issue by lOmicronl** [KSP-CKAN/CKAN#1073] opened 2015-06-04 22:23 UTC
I'm opening this up in wondering whether or not this is a "working as intended" scenario - I can only guess. This issue is not listed under "known errors" in the user guide and no open GitHub issue mentions it.

At the same, considering that I am a new CKAN user, and I got this error on the very first mod installation I ever attempted with CKAN, I keep thinking "it can't possibly be that nobody has noticed this before... can it?"

To wrap my head around how the client works, I looked up the mod with the largest number of nested recommendations and suggestions I could find at a glance - this happened to be DMagic Orbital Science. I selected this mod to install, and when prompted by the wizard, I also selected all recommendations and all suggestions. This ended up installing 9 other mods.

And then, after the installation successfully completed, CKAN spit out this:

"The following inconsistencies were found:
 * OuterPlanetsMod requires ModuleManager but nothing provides it
 * UniversalStorage requires ModuleManager but nothing provides it
 * CommunityTechTree requires ModuleManager but nothing provides it
 * Error!"

But, the forum thread says:
"The CKAN provides strong guarantees on consistency. It will not allow (...) a mod to be installed without its dependencies. It will never leave mods in a half-installed state."

I mean, it's nice that it points this error out to me in the log so that I can manually fix it, but... isn't CKAN supposed to automatically do this for me? That's why I want to use it, so I don't have to manually fix dependencies... and I wouldn't even have looked at the log output if I hadn't been doing this as a test to see how the client works. Other users will most certainly miss things like this on occasion.

**Comment by Dazpoet** [comment] 2015-06-04 23:05
I'm unable to reproduce this problem using the latest CKAN client 1.6.20-0-g3c4f781 on fresh 1.0.2 install.

Was ModuleManager part of your Changeset while installing? Did you get any other errors? Do you have any manually installed mods laying around?

**Comment by lOmicronl** [comment] 2015-06-04 23:19
ModuleManager was not part of the Changeset, as DMagic does not list it as a dependency. Only (some of) the mods selected after confirming the Changeset, in the Recommended and Suggested wizard dialogs, require it.

There were no other errors.

There were no manually installed mods present.

However, I notice that I have a v1.6.16 client, as I had downloaded it previously but didn't have time to play KSP until today. Perhaps this was a transient issue that randomly popped up in that build and was fixed again before most people noticed. I'm going to try again with the 1.6.20 version.

**Comment by lOmicronl** [comment] 2015-06-04 23:33
Update: I removed all installed mods using the client, updated to 1.6.20, and tried again to install DMagic Orbital Science with all Recommendations and Suggestions. This time the error did not appear. ModuleManager was still not part of the Changeset, but after selecting everything, the client correctly detected the dependency and proceeded to install it.

Weird! I must have tripped up some sort of rare edge case in that build? Oh well, it doesn't really matter. What's important is that you guys seem really on the ball :) I didn't expect four new releases in a mere week.

**Comment by Dazpoet** [comment] 2015-06-05 00:09
I'm glad that the newest version resolved your problem! If I may I'd recommend you activate autoupdates inside the client. It pings the github api to check if a version with a higher number than your current one exists and if so prompts you for an update.

Either way since the issue is resolved I'll close this and hope you enjoy your future CKAN experience :+1:

**Closed by Dazpoet** 2015-06-05 00:09 UTC
Labels: support

**Comment by pjf** [comment] 2015-06-05 06:39
My guess is that if you managed to get a batch of metadata during the Netkarmageddon ( #979 ) then you'd see errors of *exactly* this sort. :) Delighted to hear it's fixed, and we're definitely making sure a Metapocalypse doesn't happen again. :)
