### ISSUE TITLE
[Bug] GUI doesn't display any mods (available or installed); "Add available updates" button spawns error dialog

### ISSUE THREAD

**Issue by Teslamax** [KSP-CKAN/CKAN#3732] opened 2022-12-02 18:30 UTC
Background
----------

- Windows 11 Pro  - 22H2 - 22621.819
- CKAN v1.31.2
- KSP 1.12.4.3187

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
I have added very few mods sans using CKAN. For example I have a soft link to the GitHub repo of BDB-dev.

I've tried using the command line and all seems well.

Problem
-------
When I open the CKAN GUI:
- it refreshes the available mods but doesn't show any
- clicking on the enabled "Add available updates" button triggers an *unhandled exception* dialog box.

**Steps to reproduce**
* Open CKAN GUI
* (Refresh occurs automatically but displays nothing)
* Click on "Add available updates"
* See error

```
Unhandled exception has occurred in your application. If you click 
Continue, the application will ignore this error and attempt to continue. If 
you click Quit, the application will close immediately.

Object reference not set to an instance of an object.
```
The content of the *Details* popup is listed below in the error code section.

**Expected behavior**
- visible list of mods in the GUI
- updated list of upgradable mods and continued dialog to install them

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/10249750/205360384-54429f98-e793-437a-8ca7-853bc113c3e0.png)
![image](https://user-images.githubusercontent.com/10249750/205360307-13ac1da2-8a0e-46fc-bdcc-369d3255b6f6.png)

**CKAN error code (if applicable):**

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at CKAN.GUI.ManageMods.MarkAllUpdates()
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.MenuStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by HebaruSan** [comment] 2022-12-02 18:32
This looks a lot like #3707, but it's hard to tell for sure. Can you please try the current dev build with the fix and let us know if the problem still occurs?

- https://ksp-ckan.s3-us-west-2.amazonaws.com/ckan.exe

**Comment by Teslamax** [comment] 2022-12-02 23:02
I get the same error with 1.31.3.

**Comment by HebaruSan** [comment] 2022-12-02 23:34
OK, so that confirms something else is happening then, thanks.

Can you please share your `<KSP dir>/CKAN/registry.json` file? Maybe there's something weird with how your CKAN is configured to retrieve metadata.

**Comment by Teslamax** [comment] 2022-12-02 23:36
[registry.zip](https://github.com/KSP-CKAN/CKAN/files/10145043/registry.zip)

**Comment by HebaruSan** [comment] 2022-12-02 23:44
Ahh, interesting, you've got two of the additional repositories set up:

```json
"sorted_repositories": {
"default": {
"name": "default",
"uri": "https://github.com/KSP-CKAN/CKAN-meta/archive/master.tar.gz",
"last_server_etag": "f2b58e3c55b3771f0ae9272ba989ccd30f9ea9c6111edfa56a8de50ad4c9300d",
"priority": 0
},
"Kopernicus_BE": {
"name": "Kopernicus_BE",
"uri": "https://github.com/R-T-B/CKAN-meta-dev-Kopernicus_BE/archive/master.tar.gz",
"last_server_etag": "867e065d1b599893d1648703803635038f4a765d7ccb14677856bea2e9f863c5",
"priority": 0
},
"MechJeb2-dev": {
"name": "MechJeb2-dev",
"uri": "https://ksp.sarbian.com/ckan/MechJeb2-ci.tar.gz",
"last_server_etag": "6378008b-e45d",
"priority": 1
}
},
```

But you do have the all the available modules in the registry, so it's very weird that the grid would be empty. Can you try turning off "Update repositories on launch" in the settings, to see whether that's a factor?

**Comment by Teslamax** [comment] 2022-12-02 23:47
![image](https://user-images.githubusercontent.com/10249750/205410112-14c8b22a-c3ac-41be-abdb-ec402585dbc0.png)

doesn't show anything more during update than that...

error still occurs

**Comment by HebaruSan** [comment] 2022-12-02 23:48
Sorry, if you turn **off** that setting, then it shouldn't go to that screen at startup anymore, and we can see whether it's able to load the modules without that step interfering. Can you try that?

**Comment by Teslamax** [comment] 2022-12-02 23:51
I did turn off that setting. 

This is shown: 
![image](https://user-images.githubusercontent.com/10249750/205410300-6a185db0-60c4-4c6f-b45a-787bf7023d92.png)

The previous image is what's shown when I manually hit the *Refresh* button.

**Comment by HebaruSan** [comment] 2022-12-02 23:51
And that's a fresh start, closing CKAN and opening it again? Or is that right after closing the settings?

**Comment by Teslamax** [comment] 2022-12-02 23:52
Correct. I closed CKAN and opened it again.

**Comment by Teslamax** [comment] 2022-12-02 23:55
Are there any files which may have gotten corrupted which I can clear?

**Comment by HebaruSan** [comment] 2022-12-03 00:17
Hmm, good suggestion; try deleting `%LOCALAPPDATA%\CKAN\builds.json`. We had someone see problems with that file recently.

**Comment by Teslamax** [comment] 2022-12-03 00:21
No change until I deleted the whole `%LOCALAPPDATA%\CKAN\` directory.

**Comment by Teslamax** [comment] 2022-12-03 00:23
![image](https://user-images.githubusercontent.com/10249750/205412449-af9e8b32-45eb-4fab-9f5f-2f0a4dbccd67.png)

**Comment by HebaruSan** [comment] 2022-12-03 00:24
Well that just looks like #3707 again. If you stick to running the dev build, we could rule out that possibility.

**Comment by Teslamax** [comment] 2022-12-03 00:31
Ok. 

1. Cleared the directory again. 
2. Started up the dev build.
3. Seemed ok.
4. There were some changes it wanted to make, so I hit "Apply changes"
5. No errors but it didn't take effect.
6. Hit "Add available Updates" and it proceeded as it should until it started downloading a mod. Got halfway and stalled.

**Comment by HebaruSan** [comment] 2022-12-03 01:40
Let's try to focus on the original problem report here; we can start a new issue if you're having problems downloading mods.

To confirm, are you seeing any of the problems in the original report with the dev build? Empty mod grid, error on clicking "Add available updates"?

**Comment by Teslamax** [comment] 2022-12-03 02:41
Earlier it didn't make a difference. I have removed the release version and replaced it with the dev.

After running a repair on the command line and performing a few operations on the *consoleui*, the GUI seems to be working properly.

To be honest I'd like to know why.

**Comment by HebaruSan** [comment] 2022-12-03 02:44
> Earlier it didn't make a difference. I have removed the release version and replaced it with the dev.
> 
> After running a repair on the command line and performing a few operations on the _consoleui_, the GUI seems to be working properly.

That's great news! :tada: 

> To be honest I'd like to know why.

If you happened to get the two files confused and ran the old version unintentionally, it wouldn't have been the first time we've seen that.

> I'm sorry to have taken up your time. I'd rather have had a repeatable bug that could be fixed. It might just be some transient config on my computer.

Don't worry about it, you did spur me to take care of #3733 by asking about files that might be corrupted.

Closing as likely duplicate of #3707.

**Closed by HebaruSan** 2022-12-03 02:44 UTC
