### ISSUE TITLE
CKAN Minimizes after launch, GUI not shown.

### ISSUE THREAD

**Issue by ResinSmoker** [KSP-CKAN/CKAN#2726] opened 2019-04-12 06:10 UTC
**CKAN Version:** 
1.26

**KSP Version:** 
Up to Date

**Operating System:** 
Win 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
Not within the last month. CKAN was working fine till this week.

Problem
-------

**What steps did you take in CKAN?**
After launch CKAN minimizes as if it's waiting for something. Tried launching as Admin and providing AV exclusions. Neither of which helped. Later tried DL'n a new copy of CKAN, only to have the same issue.

**What did you expect to happen?**
The GUI to open.

**What happened instead?**
Nothing exciting.

**Screenshots:**
Would love to but as I said, it refuses to open fully.

**CKAN error codes (if applicable):** 
None seen.

**Comment by HebaruSan** [comment] 2019-04-12 08:10
Looks like a duplicate of #2717, can you confirm that you exited via the tray icon while minimized?

**Comment by ResinSmoker** [comment] 2019-04-12 08:18
That's just it, there is nothing to click on other than the minimized
program pin'd to Windowd task tray. Really with that all i can effectively
do is terminate it. (waiting does not help) Initially after opening there
is a Black window that shows for 3-5 seconds before the process
self-minimizes.

**Comment by HebaruSan** [comment] 2019-04-12 08:25
Yeah, that sounds like #2717, thanks.

**Closed by HebaruSan** 2019-04-12 08:25 UTC
Labels: Duplicate
