### ISSUE TITLE
Can't add another KSP install location after setting default install

### ISSUE THREAD

**Issue by JamesFaraday** [KSP-CKAN/CKAN#740] opened 2015-01-11 14:43 UTC
When navigating to settings > CKAN settings > Choose another KSP install. The windows close for a second and then CKAN just starts back up again with the same default KSP install location. Thus, not allowing me to select another one. To set the current install location, I used the cli commands from https://github.com/KSP-CKAN/CKAN-support/issues/58 . I do not know if that is causing this, but even if it is, entering cli commands should not stop someone in the gui from selecting another install.

**Comment by pjf** [comment] 2015-05-22 06:21
Oh no! We've been terrible and somehow failed to respond to your issue in *four months*. o_O

We've had a number of releases since then, so just to check, is this still an issue?

**Comment by plague006** [comment] 2015-05-22 06:23
Persists through 1.6.16

**Comment by pjf** [comment] 2015-05-22 06:27
Drat. Throwing this in our bug queue, then.

@plague006, which OS can you reproduce this on? I'm sure I *did* use this myself recently on Linux, but we may be seeing regressions and/or platform specific oddities.

**Comment by RichardLake** [comment] 2015-05-22 06:28
Might be solved by https://github.com/KSP-CKAN/CKAN-GUI/pull/122

**Comment by plague006** [comment] 2015-05-22 06:28
Win 7 - 64bit

**Comment by Blu3wolf** [comment] 2015-05-22 06:44
I had this bug on windows like a week ago. Didnt bother with trying to reproduce it as I didnt know ckan well enough and was moving to linux anyway.

was on Win 7 64 bit here.

**Comment by Dazpoet** [comment] 2015-05-22 07:58
This happens when your CKAN.exe is within the root directory of a KSP install iirc, try moving it outside the KSP folder if you have it there.

**Comment by plague006** [comment] 2015-05-22 08:06
Did have it in KSP folder, moved it out and on-launch it brought up the "Select install" prompt (yay). But then if you try opening the prompt from the settings it reverts its behavior. Similarly later launches from any location result in it going straight to the mod management screen.

**Comment by Postremus** [comment] 2015-06-28 15:47
@plague006 Does this still happen with 1.8.4?

**Comment by plague006** [comment] 2015-06-30 23:49
@Postremus No.

**Comment by Postremus** [comment] 2015-07-01 06:21
Great. Thank you :)

----- Ursprüngliche Nachricht -----
Von: "Matthew" <notifications@github.com>
Gesendet: ‎01.‎07.‎2015 01:49
An: "KSP-CKAN/CKAN" <CKAN@noreply.github.com>
Cc: "Martin Panzer" <postremus1996@googlemail.com>
Betreff: Re: [CKAN] Can't add another KSP install location after settingdefault install (#740)

@Postremus No.

**Closed** 2015-07-01 06:30 UTC
Labels: bug, gui, ★★☆

**Comment by Blu3wolf** [comment] 2016-01-14 00:54
Hello!

 

New message, please read <http://heoconshop.vn/of.php?hia>

 

blue@blu3wolf.com

**Comment by Blu3wolf** [comment] 2016-01-14 00:54
Hello!

 

New message, please read <http://kooking.vn/settled.php?f>

 

blue@blu3wolf.com

**Comment by plague006** [comment] 2016-01-16 03:33
@Blu3wolf I'm editing your posts because they look like spam or some such.

**Comment by Blu3wolf** [comment] 2016-01-16 05:12
Cheers for bringing this to my attention, I think my mail server has been hacked... looking into this. Apparently you can email posts to github. 

Apologies for the inconvenience.

**Comment by Blu3wolf** [comment] 2016-01-29 06:16
Hello!

 

New message, please read <http://hydrodevices.kiev.ua/out.php?7v3m7>

 

blue@blu3wolf.com

**Comment by Blu3wolf** [comment] 2016-05-03 13:43
Hello!

 

You have a new message, please read <http://www.smited79.fr/base.php?rt>

 

blue@blu3wolf.com

**Comment by Blu3wolf** [comment] 2016-05-19 02:52
Hi,

I've just found something really interesting and OMG ... it's  amazing, just take a look <http://xirdebika.webdesigningconsultancy.com/safety.php?b2x6>

Wishes, blue@blu3wolf.com

**Comment by Blu3wolf** [comment] 2016-06-05 01:01
Hello, That stuff is just gorgeous, you have to read about it more at <http://nkivezycru.coinsplus.net/aecxdba>

Pardon my monkey thumbs, blue@blu3wolf.com

**Comment by Blu3wolf** [comment] 2016-06-05 01:01
hi,
I think this story is really awesome, you're gonna love it, please read it here <http://ngacryfusi.monthlycarrentals.com/aexdz>

Good wishes, blue@blu3wolf.com

**Comment by nobodyhasthis** [comment] 2016-06-05 02:23
@Blu3wolf is your email account still hacked? 
Looks like it is spamming Github again.

**Comment by Blu3wolf** [comment] 2016-06-05 02:36
Again, its never been hacked. Its spoofing. Folks with a mail server and nothing better to do are sending out emails with a return-path the same as my email address. Not my server, not my account. 

Ive published SPF records, Ive set up DKIM, ive published DMARC records, and I digitally sign every email I send. Github and every other mail server out there has the tools to identify what is spoofed emails, and what is legit. Github at least is choosing not to use those tools. As I lack any kind of control over this use of my digital likeness, I will not be held accountable for Githubs acceptance of it in the presence of suitable tools of discrimination.

Ill delete any such comments I find on here, but thats the extent of my ability.

**Comment by politas** [comment] 2016-06-05 04:07
It must have some access to your old emails, in order to have these thread details for replies.

**Comment by Blu3wolf** [comment] 2016-06-05 06:14
Making it either complicity on the part of my hosting provider, or the result of google scraping.

**Comment by Blu3wolf** [comment] 2016-08-22 17:05
Dear friend! 

Something  reaaly nice  happened to  me recently, it turned out to be a great surprise.  Just take  a look <http://zykypaba.way2cart.com/aefhu>

Sincerely, blue



-- 
Esta mensagem foi verificada pelo sistema de antiv�rus e
 acredita-se estar livre de perigo.
