### ISSUE TITLE
[Bug] ckan.exe crashes after selecting a button, menu, or tab

### ISSUE THREAD

**Issue by Tom-Dude** [KSP-CKAN/CKAN#3711] opened 2022-11-18 08:54 UTC
Background
----------
* Operating System: Windows 10 22H2
* CKAN Version: 1.31.2
* KSP Version: 1.12.4.3187

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No.

Problem
-------
CKAN crashes upon any action after fully starting up; it crashes when I click settings, it crashes when I press "Apply changes", it crashes when I click "Add Available Updates", it crashes when looking at the "Changeset" tab, but oddly enough it doesn't crash when I click "Refresh".

Steps to Reproduce:
Open ckan.exe
click on aforementioned buttons
ckan.exe stops responding, no error message.

ckan.exe should show the menus and do the actions when pressing these buttons, or at the very least produce an error code rather
than just crashing.

https://imgur.com/a/tvWtzjP
I'm not sure how relevant this screenshot is, but it shows ckan.exe crashing after selecting "Changeset".

Again, no error code.

**Comment by randomguyingithub** [comment] 2022-11-18 09:14
https://github.com/KSP-CKAN/CKAN/issues/3707

**Comment by HebaruSan** [comment] 2022-11-18 13:55
Duplicate of #3707

**Closed by HebaruSan** 2022-11-18 13:55 UTC

**Comment by Tom-Dude** [comment] 2022-11-18 22:09
> Thanks, we just finished fixing this, you can try the latest dev build if you'd like to test:
> 
>     * https://ksp-ckan.s3-us-west-2.amazonaws.com/ckan.exe

I tested it with the new build and the problem is solved, CKAN functions as expected.
