### ISSUE TITLE
[Bug] Briefly summarize your issue here

### ISSUE THREAD

**Issue by Christian-Schwarz2003** [KSP-CKAN/CKAN#3719] opened 2022-11-20 10:41 UTC
Background
----------
* Operating System: Windows 11 Pro 64 bit
* CKAN Version: 1.31.2
* KSP Version: -

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
**Describe the bug**
I can search but as soon as i try to do anything else it freezes (can't add checkmark to mod can't refresh cant launch ksp, can't accept changes)

**Steps to reproduce**
* Start CKAN 
* try to install any mod
* ckan.exe not responding (waited at least 5 mins once)

**Notes**
* downgrading to 1.31.0 fixed the issue

**Comment by HebaruSan** [comment] 2022-11-20 14:51
Thanks, we just finished fixing this, you can try the latest dev build if you'd like to test:

- https://ksp-ckan.s3-us-west-2.amazonaws.com/ckan.exe

**Comment by HebaruSan** [comment] 2022-11-20 14:51
Duplicate of #3707

**Closed by HebaruSan** 2022-11-20 14:51 UTC
