### ISSUE TITLE
Error in autoupdate - when opening CKAN

### ISSUE THREAD

**Issue by Fett2oo5** [KSP-CKAN/CKAN#2346] opened 2018-03-05 22:13 UTC
Background
----------

**CKAN Version:** 
v1.22.6

**KSP Version:** 
1.3.1

**Operating System:** 
Win 7

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

Problem
-------

**What steps did you take in CKAN?**
Trying to open the program

**What did you expect to happen?**
The program to open

**What happened instead?**
I got an error message

**Screenshots:**

![image](https://user-images.githubusercontent.com/6272194/37002460-6b29e41a-208f-11e8-8a58-4317e516ecdc.png)

After I click dismiss, a Microsoft .NET error window appears:
![image](https://user-images.githubusercontent.com/6272194/37002555-bc0fc1ba-208f-11e8-8a5b-d3b0e3de1805.png)

After I click continue CKAN opens.

However when I click the refresh button in the GUI, I get the following:
![image](https://user-images.githubusercontent.com/6272194/37002591-d80b2a4e-208f-11e8-82be-b5d14e79ffb0.png)

And the following text is displayed in the status area:
![image](https://user-images.githubusercontent.com/6272194/37002637-00803b36-2090-11e8-92e1-36db0ea53c76.png)

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment] 2018-03-05 22:24
Yup, GitHub broke 1.22.6. Duplicate of #2293 (and probably thirty other issues). Install this:

- https://github.com/KSP-CKAN/CKAN/releases/tag/v1.24.0

You'll probably get an error when you launch it. Click Continue, then Refresh.

**Closed by HebaruSan** 2018-03-05 22:24 UTC
Labels: Duplicate
