### ISSUE TITLE
Make "download" a list?

### ISSUE THREAD

**Issue by janbrohl** [KSP-CKAN/CKAN#1760] opened 2016-05-29 13:45 UTC
Sometimes specific download sources for a mod are not availabe like stated in #1758 but the file is mirrored at a different site.

By allowing download to be a list several well-defined mirror locations could be tried before giving up.

Also non-http(s) links like torrent or magnet could be supported in a backwards-compatible way (because unsupported URLs could just be ignored)

Other fields like download_hash would not be touched by this because for the same file there should be no difference for them.

**Comment by HebaruSan** [comment] 2017-12-16 17:46
Possible duplicate of #487.

**Comment by HebaruSan** [comment] 2023-07-26 22:38
Additional use case for this from Discord:

![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/26ccc69c-70b8-4d5b-adda-7f7fd0c8aaaf)

To generate multiple values for `download`, Netkan would need to be able to associate a mod with multiple hosts. I have a dev branch capable of this now, using the `---` document separator from YAML, and merging inflated modules according to `version`:

```yaml
spec_version: v1.32
identifier: SpaceWarp
name: SpaceWarp
$kref: '#/ckan/spacedock/3277'
$vref: '#/ckan/space-warp'
license: MIT
tags:
  - plugin
  - library
depends:
  - name: BepInEx
  - name: UITKforKSP2
install:
  - find: BepInEx
    install_to: GameRoot
    include_only:
      - patchers
      - plugins
---
spec_version: v1.32
identifier: SpaceWarp
name: SpaceWarp
$kref: '#/ckan/github/SpaceWarpDev/SpaceWarp'
x_netkan_version_edit:
  find: 'spacewarp-'
  replace: ''
  strict: false
$vref: '#/ckan/space-warp'
license: MIT
tags:
  - plugin
  - library
depends:
  - name: BepInEx
  - name: UITKforKSP2
install:
  - find: BepInEx
    install_to: GameRoot
    include_only:
      - patchers
      - plugins
```

&rArr;

```json
    "download": [
        "https://spacedock.info/mod/3277/Space%20Warp%20+%20BepInEx/download/1.4.0",
        "https://github.com/SpaceWarpDev/SpaceWarp/releases/download/spacewarp-1.4.0/spacewarp-release-1.4.0.zip"
    ],
```

The complex part is what to do in the client. Clearly some user-configured prioritization would be helpful for users that experience slow downloads from SpaceDock, but a fallback behavior also seems fairly obvious in case of downtimes, with or without prioritization. And of course we're talking about another spec version increment for this.

**Comment by HebaruSan** [comment] 2023-07-26 23:03
A mod with multiple hosts has a more complex update schedule. The author would pick one place to update first, then get to the others when possible, which creates a window where the hosts do not have the same latest version available.

With a naïve implementaiton that still just inflates the current latest version from each host, this would result in indexing the new version at just one host initially (not a problem in itself), but also stripping the previous release of one of its download links. Then later after the other host was updated, the latest version would have two links, but nothing would re-add the removed link to the previous release. One way to deal with this might be to check _two_ releases, merge them according to `version` properties, then discard the oldest if we end up with three in the final list.

**Comment by techman83** [comment] 2023-07-27 07:21
We could on the inflation side, specify multiple sources, and merge them together, or have some alternate download source provider. Have a source of the truth for the metadata, but allow it to add extra download sources. Client side would be an option to "Prefer host", but default to first in the list, which would come the primary source of the truth.

**Closed** 2023-08-09 02:40 UTC
Labels: Enhancement, Metadata, Network
