### ISSUE TITLE
Unhandled expection error

### ISSUE THREAD

**Issue by MigLucena** [KSP-CKAN/CKAN#3600] opened 2022-06-30 20:56 UTC
Background
----------
* Operating System: Windows 11
* CKAN Version: 1.30.4
* KSP Version: 1.12.3.3173

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
Just deleted all mods and only left squad and squad expansion

Problem
-------
**Describe the bug**

**Steps to reproduce**
* Open ckan (obvious)
* Mark RP-1 Express install
* Apply Changes
* Wait a while
* See error

**Expected behavior**
Downloading RP-1 express install

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/108354120/176776592-a8a8e793-7fba-496c-81a2-ebdd560b3c4f.png)

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```
I didnt got any code

**Comment by HebaruSan** [comment] 2022-06-30 20:57
Thanks, this is a known issue that we have investigated and fixed in #3512, to be included in the next release (whenever that happens).

**Comment by HebaruSan** [comment] 2022-06-30 20:58
Duplicate of #3483

**Closed by HebaruSan** 2022-06-30 20:58 UTC

**Comment by HebaruSan** [comment] 2022-06-30 21:03
Fixing this requires code changes. You could try the latest test build:

- https://ksp-ckan.s3-us-west-2.amazonaws.com/ckan.exe

**Comment by MigLucena** [comment] 2022-06-30 21:28
Worked thanks :)
