### ISSUE TITLE
[Bug]  DependencyNotSatisfied installing OPM

### ISSUE THREAD

**Issue by SilverlightPony** [KSP-CKAN/CKAN#2849] opened 2019-08-21 01:13 UTC
Background
----------
* Operating System: Windows 10 Pro
* CKAN Version: 1.26.4
* KSP Version: 1.7.3

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
**Describe the bug**
CKAN throws an error when I check the box to add OPM.  Error message below.

**Steps to reproduce**
1. Open CKAN, select 1.7.3 install
2. Don't mark any other KSP versions as compatible
3. Check the box for `OuterPlanetsMod`
4. Exception!
   ![image](https://user-images.githubusercontent.com/1559108/63658072-5d406080-c797-11e9-8faa-e7ef640fae86.png)

**Expected behavior**
No error.

**CKAN error code (if applicable):**

```
************** Exception Text **************
CKAN.DependencyNotSatisfiedKraken: Exception of type 'CKAN.DependencyNotSatisfiedKraken' was thrown.
   at CKAN.RelationshipResolver.ResolveStanza(IEnumerable`1 stanza, SelectionReason reason, RelationshipResolverOptions options, Boolean soft_resolve, IEnumerable`1 old_stanza)
   at CKAN.RelationshipResolver.Resolve(CkanModule module, RelationshipResolverOptions options, IEnumerable`1 old_stanza)
   at CKAN.RelationshipResolver.AddModulesToInstall(IEnumerable`1 modules)
   at CKAN.MainModList.ComputeConflictsFromModList(IRegistryQuerier registry, IEnumerable`1 change_set, KspVersionCriteria ksp_version)
   at CKAN.Main.<UpdateChangeSetAndConflicts>d__63.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKAN.Main.<ModList_CellValueChanged>d__284.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
```

<details><summary>Mod list</summary>

https://pastebin.com/WXaz7j7h

```json
{
	"kind": "metapackage",
	"abstract": "A list of modules installed on the KSP_1.7.3 KSP instance",
	"name": "installed-KSP_1.7.3",
	"license": "unknown",
	"version": "2019.08.21.12.25.40",
	"identifier": "installed-KSP_1.7.3",
	"spec_version": "v1.6",
	"recommends": [
		{
			"name": "ToolbarController"
		},
		{
			"name": "ProceduralFairings"
		},
		{
			"name": "NehemiahEngineeringOrbitalScience"
		},
		{
			"name": "DistantObject"
		},
		{
			"name": "NearFutureElectrical-Core"
		},
		{
			"name": "KerbalJointReinforcementContinued"
		},
		{
			"name": "EasyVesselSwitch"
		},
		{
			"name": "DockingPortSoundFX"
		},
		{
			"name": "Chatterer"
		},
		{
			"name": "NearFutureProps"
		},
		{
			"name": "CommunityCategoryKit"
		},
		{
			"name": "MechJeb2"
		},
		{
			"name": "EditorTime"
		},
		{
			"name": "ContractConfigurator"
		},
		{
			"name": "RemoteTech"
		},
		{
			"name": "KAS"
		},
		{
			"name": "ModuleManager"
		},
		{
			"name": "KRASH"
		},
		{
			"name": "CommunityTechTree"
		},
		{
			"name": "ContractConfigurator-CleverSats"
		},
		{
			"name": "ContractConfigurator-FieldResearch"
		},
		{
			"name": "TextureReplacer"
		},
		{
			"name": "ContractConfigurator-Tourism"
		},
		{
			"name": "CrowdSourcedScience"
		},
		{
			"name": "DistantObject-default"
		},
		{
			"name": "BetterBurnTime"
		},
		{
			"name": "NearFuturePropulsion"
		},
		{
			"name": "NearFutureSpacecraft"
		},
		{
			"name": "JSIAdvancedTransparentPods"
		},
		{
			"name": "KerbalPlanetaryBaseSystems"
		},
		{
			"name": "TweakScale"
		},
		{
			"name": "HideEmptyTechNodes"
		},
		{
			"name": "NearFutureLaunchVehicles"
		},
		{
			"name": "TacFuelBalancer"
		},
		{
			"name": "SCANsat"
		},
		{
			"name": "StageRecovery"
		},
		{
			"name": "CommunityResourcePack"
		},
		{
			"name": "BetterCrewAssignment"
		},
		{
			"name": "DynamicBatteryStorage"
		},
		{
			"name": "MagiCore"
		},
		{
			"name": "ExtraPlanetaryLaunchpads"
		},
		{
			"name": "DeployableEngines"
		},
		{
			"name": "ContractConfigurator-RemoteTech"
		},
		{
			"name": "NearFutureSolar"
		},
		{
			"name": "REPOSoftTech-Agencies"
		},
		{
			"name": "CommunityTerrainTexturePack"
		},
		{
			"name": "KIS"
		},
		{
			"name": "DMagicScienceAnimate"
		},
		{
			"name": "ContractConfigurator-KerbinSpaceStation"
		},
		{
			"name": "CustomAsteroids-Pops-Stock-Stockalike"
		},
		{
			"name": "CustomAsteroids-Pops-Stock-Inner"
		},
		{
			"name": "B9PartSwitch"
		},
		{
			"name": "CustomAsteroids-Pops-Stock-Outer"
		},
		{
			"name": "MechJebForAll"
		},
		{
			"name": "FMRSContinued"
		},
		{
			"name": "RecoveryController"
		},
		{
			"name": "SmokeScreen"
		},
		{
			"name": "NearFutureSolar-Core"
		},
		{
			"name": "K2CommandPodCont"
		},
		{
			"name": "SmartParts"
		},
		{
			"name": "KerbalKrashSystem"
		},
		{
			"name": "CustomAsteroids"
		},
		{
			"name": "OrbitalTug"
		},
		{
			"name": "AnimatedDecouplers"
		},
		{
			"name": "AutoAsparagus"
		},
		{
			"name": "EnvironmentalVisualEnhancements"
		},
		{
			"name": "EnvironmentalVisualEnhancements-HR"
		},
		{
			"name": "KEI"
		},
		{
			"name": "ClickThroughBlocker"
		},
		{
			"name": "BurstAtomicThrust"
		},
		{
			"name": "xScienceContinued"
		}
	]
}
```

</details>

**Comment by HebaruSan** [comment] 2019-08-21 17:42
I don't get an error, but it does highlight a conflict with CustomAsteroids-Pops-Stock-Outer and prevent installation:

![image](https://user-images.githubusercontent.com/1559108/63454560-9648a000-c43a-11e9-9ca7-bebdb08cfc03.png)

![image](https://user-images.githubusercontent.com/1559108/63454751-ef183880-c43a-11e9-9b35-8410e62de0a8.png)

That's probably the root cause of the error as well. If you want OPM, try uninstalling CustomAsteroids-Pops-Stock-Outer.

**Comment by HebaruSan** [comment] 2019-08-26 00:21
Finally got this one to happen!

1. Uninstall everything
2. Check the box for `CustomAsteroids-Pops-Stock-Outer`
3. Check the box for `OuterPlanetsMod`
4. Exception!
   ![image](https://user-images.githubusercontent.com/1559108/63658072-5d406080-c797-11e9-8faa-e7ef640fae86.png)

Just having `CustomAsteroids-Pops-Stock-Outer` already installed doesn't seem to do it. Don't know why.

**Comment by politas** [comment] 2019-08-26 00:25
Is there a conflict between CustomAsteroids-Pops-Stock-Outer and one of OuterPlanetsMod's dependencies? That would explain why we're throwing a DependencyNotSatisfiedKraken.

**Comment by HebaruSan** [comment] 2019-08-26 00:27
There's directly a conflict between those two modules.
https://github.com/KSP-CKAN/NetKAN/pull/3832

The thing I was trying to pin down was why the OP was seeing an unhandled exception instead of it being caught and used to paint the rows red.

**Comment by HebaruSan** [comment] 2019-08-26 01:28
Oh! This is a duplicate of #2231! OuterPlanetsMod doesn't belong in the Compatible list at all; if our filtering algorithm was perfect, it would be marked as incompatible.

OPM depends on Kopernicus depends on ModularFlightIntegrator. MFI is only compatible up to KSP 1.6 so far, and originally I was testing with 1.4-1.7 marked as compatible. If I take that away, then trying to install OPM by itself on KSP 1.7.3 throws that error without any conflict involved!

@SilverlightPony , mark KSP 1.6 as compatible and try again:
https://github.com/KSP-CKAN/CKAN/wiki/User-guide#choosing-compatible-game-versions

**Closed** 2020-01-16 02:41 UTC
Labels: GUI, Relationships
