### ISSUE TITLE
after last update ckan freezes when trying to do anything

### ISSUE THREAD

**Issue by timmyislol** [KSP-CKAN/CKAN#3729] opened 2022-12-01 16:57 UTC
Background
----------
* Operating System: windows 11
* CKAN Version: 1.31.2
* KSP Version: 1.12.4.3187

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** <No I have not

Problem
-------
Since the latest ckan update the app freezes when I click anything (apply changes, the update box for mods and pretty much anything else except help since that takes me to an external site). I can no longer install or update mods and neither can I update or try to do anything to ckan.

**Steps to reproduce**
* start ckan
* Click on anything
* See error (It freezes and does not respond at all)

**Expected behavior**
it not freezing and being able to install, remove or update mods. (Assuming "expected behavior" means how it is supposed to work without the glitch. 

**Screenshots (if applicable)**
![Screenshot 2022-12-01 175428](https://user-images.githubusercontent.com/86678532/205112767-d1b18e36-2cac-42d7-8ab5-6007bef137ee.png)
(the screen just kinda greys out for lack of a better term, like it does when any other app does not respond.)

**CKAN error code (if applicable):**
non, it just freezes

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment] 2022-12-01 16:59
Thanks, we just finished fixing this, you can try the latest dev build if you'd like to test:

- https://ksp-ckan.s3-us-west-2.amazonaws.com/ckan.exe

**Comment by HebaruSan** [comment] 2022-12-01 16:59
Duplicate of #3707

**Closed by HebaruSan** 2022-12-01 16:59 UTC

**Comment by timmyislol** [comment] 2022-12-01 17:05
> Thanks, we just finished fixing this, you can try the latest dev build if you'd like to test:
> 
> * https://ksp-ckan.s3-us-west-2.amazonaws.com/ckan.exe

Yes, it functions now, thank you very much
