### ISSUE TITLE
[Bug] Briefly summarize your issue here

### ISSUE THREAD

**Issue by bedstag** [KSP-CKAN/CKAN#3720] opened 2022-11-20 16:17 UTC
Background
----------
* Operating System: Windows 10 Home
* CKAN Version: 1.31.2
* KSP Version: 1.12.4.3187

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
**Describe the bug**
Program hangs whenever you try to implement a change anything.  It's un-useable.

**Steps to reproduce**
* Go to...List of MODS
* Click on...Any mod to install/remove, or simply click apply to anything.
* See error - No error, just hangs the program and requires killing in task manager

**Expected behavior**
To enable or disable MODS and to apply changes.

**Screenshots (if applicable)**
Would look like a still image of the program.

**CKAN error code (if applicable):**
No code is given.
```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment] 2022-11-20 16:30
Thanks, we just finished fixing this, you can try the latest dev build if you'd like to test:

- https://ksp-ckan.s3-us-west-2.amazonaws.com/ckan.exe

**Comment by HebaruSan** [comment] 2022-11-20 16:30
Duplicate of #3707

**Closed by HebaruSan** 2022-11-20 16:30 UTC
