### ISSUE TITLE
My CKAN is in japanese or chinese how do i fix this?

### ISSUE THREAD

**Issue by The-Building-man** [KSP-CKAN/CKAN#3421] opened 2021-07-26 03:52 UTC
Background
----------
* Operating System: Asus vivobook
* CKAN Version: Newest Version
* KSP Version: 1.8.1

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**

Problem
-------
**ckan in different language**

**Steps to reproduce**
* Go to...
* Click on...
* See error

**Expected behavior**

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by vinix38** [comment] 2021-07-26 10:06
Seems to be a duplicate of #3244 . The solution is in that previous issue.

**Comment by HebaruSan** [comment] 2021-07-26 11:38
Duplicate of #3244

**Closed by HebaruSan** 2021-07-26 11:38 UTC
