### ISSUE TITLE
[Mod]

### ISSUE THREAD

**Issue by Kspenjoyer** [KSP-CKAN/CKAN#3678] opened 2022-10-20 06:20 UTC
Mod info
--------
*Mod name: Planetside exploration technologies
*Creators: Benjee_10 and ValiZockt
*licenses: All rights reserved 
*homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/201439-112x-bg-planetside-exploration-technologies-surface-bases-nasa-mmsev-wind-turbines-more-v102/
*download: https://spacedock.info/mod/2681/Planetside%20Exploration%20Technologies#info

**Comment by HebaruSan** [comment] 2022-10-21 01:38
Duplicate of KSP-CKAN/NetKAN#9386

**Closed by HebaruSan** 2022-10-21 01:38 UTC
