### ISSUE TITLE
[Bug]: Mods install failed: [...] transaction failed!

### ISSUE THREAD

**Issue by Babilinx** [KSP-CKAN/CKAN#4179] opened 2024-09-09 15:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Linux

### CKAN Version

1.34.4

### Games

KSP 1

### Game Version

v12.5.3190

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

No

### Describe the bug

After installing CKAN on the Heroic Game Luncher (followed the guide for the Steam Deck), I wanted to install mods. I select them, and click on install. Everything is downloading fine except the install failed.

EDIT: After switching to English to capture the install log, the install seems to have worked. I'm still opening this issue as the problem exist.

### Steps to reproduce

- Select some mods
- Install them
- See the error and install failed

I've reproduced the bug 2 times, but after switching to English (and back to French) unable to do it again.

### Relevant log output

(Sorry for the French)

```
Vont être installés :

 * Easy Vessel Switch (EVS) 2.3 (en cache)
 * Kerbal Engineer Redux 1.1.9.5 (en cache)
 * RCS Build Aid v1.0.6 (en cache)
 * Trajectories v2.4.5.3 (en cache)
 * Waterfall Core 0.9.0 (en cache)
Installation du mod "EasyVesselSwitch 2.3"
EasyVesselSwitch 2.3 déjà installé, ignoré
Installation du mod "KerbalEngineerRedux 1.1.9.5"
KerbalEngineerRedux 1.1.9.5 déjà installé, ignoré
Installation du mod "RCSBuildAid v1.0.6"
RCSBuildAid v1.0.6 déjà installé, ignoré
Installation du mod "Trajectories v2.4.5.3"
Trajectories v2.4.5.3 déjà installé, ignoré
Installation du mod "Waterfall 0.9.0"
Waterfall 0.9.0 déjà installé, ignoré
Mise à jour du registre
Validation des changements du système de fichiers
Terminé !
Number must be either non-negative and less than or equal to Int32.MaxValue or -1.
Parameter name: timeout
Transaction failed
Erreur lors de l'installation !
Si le message ci-dessus indique une erreur de téléchargement, veuillez réessayer. Sinon, veuillez signaler le problème pour que nous puissions enquêter.
Si vous suspectez un problème de métadonnées : https://github.com/KSP-CKAN/NetKAN/issues/new/choose
Si vous suspectez un problème client : https://github.com/KSP-CKAN/CKAN/issues/new/choose
```

**Comment by HebaruSan** [comment] 2024-09-09 15:40
Duplicate of #3370

**Closed by HebaruSan** 2024-09-09 15:40 UTC
