### ISSUE TITLE
[Bug] Briefly summarize your issue here

### ISSUE THREAD

**Issue by nmarmanis** [KSP-CKAN/CKAN#3721] opened 2022-11-20 17:48 UTC
Background
----------
* Operating System: Win10, latest version as of 11/20/2022
* CKAN Version: 1.31.2
* KSP Version: 1.12.3.3173

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
* It is an immediate crash of the CKAN client as soon as I attempt either to open the settings, check or uncheck a box in the UI, or use the 'Apply Changes' button. It becomes unresponsive immediately Interestingly, the game still launches and afaik still works fine, with all mods loaded.

**Steps to reproduce**
* Go to...
* Click on...
* Any box in the mod catalog, or the 'Apply Changes' button. 

**Screenshots (if applicable)**

* Not really applicable.

**CKAN error code (if applicable):**
* None given unless it's in the logs. I'll attach them below if I can figure out how to get them. 
```
* when attempting to use ```ckan repair registry```, the following exception is thrown:
\NonSteam\CKAN>ckan repair registry

Unhandled Exception: CKAN.RegistryInUseKraken: Exception of type 'CKAN.RegistryInUseKraken' was thrown.
   at CKAN.RegistryManager..ctor(String path, GameInstance inst)
   at CKAN.RegistryManager.Instance(GameInstance inst)
   at CKAN.CmdLine.Repair.Registry(GameInstance ksp)
   at CKAN.CmdLine.Repair.<>c__DisplayClass1_0.<RunSubCommand>b__0(String option, Object suboptions)
   at CommandLine.Parser.ParseArgumentsStrict(String[] args, Object options, Action`2 onVerbCommand, Action onFail)
   at CKAN.CmdLine.Repair.RunSubCommand(GameInstanceManager manager, CommonOptions opts, SubCommandOptions unparsed)
   at CKAN.CmdLine.MainClass.Execute(GameInstanceManager manager, CommonOptions opts, String[] args)
   at CKAN.CmdLine.MainClass.Main(String[] args)


```

**Comment by HebaruSan** [comment] 2022-11-20 17:49
Thanks, we just finished fixing this, you can try the latest dev build if you'd like to test:

- https://ksp-ckan.s3-us-west-2.amazonaws.com/ckan.exe

**Comment by HebaruSan** [comment] 2022-11-20 17:49
Duplicate of #3707

**Closed by HebaruSan** 2022-11-20 17:49 UTC

**Comment by nmarmanis** [comment] 2022-11-20 18:23
Oh! Thanks. 
Im reinstalling my mods at the moment, which seems to have worked. 
Will definitely use this dev release, thanks again!
