### ISSUE TITLE
CKAN won't run for me

### ISSUE THREAD

**Issue by asklepian** [KSP-CKAN/CKAN#820] opened 2015-04-25 18:49 UTC
http://pastebin.com/zPSVnXwX

**Comment by Dazpoet** [comment] 2015-04-25 18:55
See https://github.com/KSP-CKAN/CKAN-support/issues/113#issuecomment-96232753 for a workaround.

Closing this due to it being a duplicate of https://github.com/KSP-CKAN/CKAN-support/issues/113

**Closed by Dazpoet** 2015-04-25 18:55 UTC
