### ISSUE TITLE
CKAN freezes constantly

### ISSUE THREAD

**Issue by Matthias32** [KSP-CKAN/CKAN#3745] opened 2022-12-14 09:18 UTC
Background
----------
* Operating System: Win 11
* CKAN Version: Newest
* KSP Version: Newest

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
CKAN freezes constantly. After I open it any click on Updates or Apply if freezes and needs to be shut down.

**Steps to reproduce**
* Open ckan
* Click on Select Updates or Apply
* ckan freezes

**Expected behavior**

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment] 2022-12-14 16:31
Thanks, we just finished fixing this, you can try the latest dev build if you'd like to test:

- https://ksp-ckan.s3-us-west-2.amazonaws.com/ckan.exe

**Comment by HebaruSan** [comment] 2022-12-14 16:31
Duplicate of #3707

**Closed by HebaruSan** 2022-12-14 16:31 UTC
