### ISSUE TITLE
Add whitelist for launch button check

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/CKAN#3179] opened 2020-10-23 19:06 UTC
Problem
-------
I always get a warning that the game might not be safe to launch, even though I know all the ones listed are ok

Suggestions
-----------
A whitelist would be useful.  Initially just have a file to read with the netkan identifier in it.

Later on, would be nice to have a UI for adding/removing mods

**Comment by HebaruSan** [comment] 2020-10-23 19:19
Duplicate of #2955

**Closed by HebaruSan** 2020-10-23 19:19 UTC
Labels: Enhancement
