### ISSUE TITLE
Remote server returned an error: (401) Unauthorized

### ISSUE THREAD

**Issue by Lprsti99** [KSP-CKAN/CKAN#819] opened 2015-04-24 20:58 UTC
Yesterday CKAN was working fine, but today when I load it up, the cmd window flashes like normal, then I get a .NET unhandled exception error.  Continuing loads the GUI like normal, but none of my mods appear, and if I try to refresh the window locks up and I have to kill the task.

Running on Win7x64.

************** Exception Text **************
System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at CKAN.AutoUpdate.MakeRequest(Uri url)
   at CKAN.AutoUpdate.FetchLatestCkanVersion()
   at CKAN.Main.Main_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)</addr>

**Comment by jbi1031** [comment] 2015-04-24 21:01
Same here but running OSX 10.10.3 Have done mozroots --import --ask-remove
--------------------------------------------------------See pasted log below---------------------------------
You are using CKAN version v1.6.10-0-g0000000 (beta)
Jordan1:common Jordan$ mono ckan.exe
1421 [1] ERROR CKAN.AutoUpdate (null) - WebException while accessing https://api.github.com/repos/KSP-CKAN/CKAN/releases/latest: System.Net.WebException: The remote server returned an error: (401) Unauthorized.
  at System.Net.HttpWebRequest.CheckFinalStatus (System.Net.WebAsyncResult result) [0x00000] in <filename unknown>:0 
  at System.Net.HttpWebRequest.SetResponseData (System.Net.WebConnectionData data) [0x00000] in <filename unknown>:0 
System.Net.WebException: The remote server returned an error: (401) Unauthorized.
  at System.Net.HttpWebRequest.CheckFinalStatus (System.Net.WebAsyncResult result) [0x00000] in <filename unknown>:0 
  at System.Net.HttpWebRequest.SetResponseData (System.Net.WebConnectionData data) [0x00000] in <filename unknown>:0

**Comment by dsibilly** [comment] 2015-04-24 22:33
Same as @Lprsti99: On Windows 7 x64, just downloaded a fresh copy of [Akatsuki](https://github.com/KSP-CKAN/CKAN/releases/tag/v1.6.10), and get a HTTP 401 error on startup that renders the CKAN client unusable.

```
************** Exception Text **************
System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at CKAN.AutoUpdate.MakeRequest(Uri url)
   at CKAN.AutoUpdate.FetchLatestCkanVersion()
   at CKAN.Main.Main_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ckan
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///E:/Games/ckan.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34238 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34234 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.0.30319.34234 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
```

**Comment by VictorRogers** [comment] 2015-04-25 00:00
Ubuntu 14.04 Same issue here

**Comment by 7ranceaddic7** [comment] 2015-04-25 00:49
The problem arises because of the auto-update feature.  CKAN is looking for something that is not there and throws the errors.

Here is a workaround:

cd ~/.../<ksp_directory>/CKAN

<editor> GUIConfig.xml

change line 6:
<CheckForUpdatesOnLaunch>true</CheckForUpdatesOnLaunch>

to 

<CheckForUpdatesOnLaunch>false</CheckForUpdatesOnLaunch>

save.

Do this for each KSP install you have.  

Profit.

Bang.  Zoom.  Straight to the Mun.

**Comment by Lprsti99** [comment] 2015-04-25 01:16
Yeah, that sorted it.

**Comment by VictorRogers** [comment] 2015-04-25 01:42
@7ranceaddic7 That fix does not work for me. Every time I run CKAN it reverts the values to true no matter if I hit yes or no for automatic updates.

**Comment by 7ranceaddic7** [comment] 2015-04-25 02:19
@VictorRogers post your GUIConfig.xml

**Comment by VictorRogers** [comment] 2015-04-25 02:29
At work until 6am, but I will post it as soon as I get home in the morning.

**Comment by Tabris83** [comment] 2015-04-25 02:47
having the same problem here. 7ranceaddic7's fix sorted it for me.

**Comment by Jiraiyah** [comment] 2015-04-25 04:16
this is how i made it work, first, copy your download cache somewhere so that you don't lose it, then run ckan and when it gives the error choose continue, then go to settings and remove your ksp instance and close ckan (it may close by itself), then back to ksp folder fix the update in the xml to false, when you run ckan again, it will ask if you want to look for update or not, DON'T USE NO OR YES ! just close that prompt window, then ckan will work

**Comment by Dazpoet** [comment] 2015-04-25 16:24
See https://github.com/KSP-CKAN/CKAN-support/issues/113 which this issue is a duplicate of

**Comment by VictorRogers** [comment] 2015-04-25 20:34
@Jiraiyah That worked for me.

**Comment by seanCodes** [comment] 2015-04-27 01:04
+1 getting this error also

**Comment by jbi1031** [comment] 2015-04-27 23:32
latest release fixed my problem.

**Comment by Dazpoet** [comment] 2015-04-27 23:45
issue resolved, closing this

**Closed by Dazpoet** 2015-04-27 23:45 UTC
