### ISSUE TITLE
Ever since the update. I have been getting an error pop up at start up. continue leads to infinite loading. 

### ISSUE THREAD

**Issue by rkirmeier** [KSP-CKAN/CKAN#3320] opened 2021-03-08 22:19 UTC
Unhandled exception has occurred in your application. If you click continue...

```
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at CKAN.ManageMods._UpdateModsList(Dictionary`2 old_modules)
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKAN.ManageMods.<UpdateModsList>d__91.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

**Comment by DasSkelett** [comment] 2021-03-08 22:34
Duplicate of #3312

**Closed by DasSkelett** 2021-03-08 22:34 UTC

**Comment by DasSkelett** [comment] 2021-03-08 22:35
Please try the workaround [in this comment](https://github.com/KSP-CKAN/CKAN/issues/3312#issuecomment-792339047), it should make CKAN start successfully again.
