### ISSUE TITLE
Reinstall will install ALL recommended mods

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/CKAN#2688] opened 2019-02-26 19:42 UTC
Current verison of CKAN

When doing a reinstall of a mod, and deselecting all recommended, they all get installed regardless of the settings

**Comment by HebaruSan** [comment] 2019-02-26 19:49
Looks like a duplicate of #2604.
Can you try the pre-release?
https://github.com/KSP-CKAN/CKAN/releases/tag/v1.26.0-PRE1

**Closed** 2019-02-27 22:06 UTC
Labels: Bug, Easy, GUI, Relationships
