### ISSUE TITLE
[Bug] CKAN Failing to install mod repositories and show installed mods upon first run.

### ISSUE THREAD

**Issue by samcarroll76** [KSP-CKAN/CKAN#3813] opened 2023-03-12 12:58 UTC
Background
----------
* Operating System: Windows 10
* CKAN Version: 1.31.2
* KSP Version: 1.12.4.3187

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
* Yes

**Problem**
* When running the CKAN.exe executable for the first time, it tries to install a repository from the following link "https://github.com/KSP-CKAN/CKAN-meta/archive/master.tar.gz" (see screenshots) and although the download bar reaches the end, the screen never progresses. Instead after about 20-30 seconds it says, "failed to roll back.". It then allows you to progress to the main page where no mods show up on the installed list and there is no tab to install new mods.

**Describe the bug**
* Explained above ^^^

**Steps to reproduce**
* Use KSP version 1.12.4.3187 (also happened with latest 1.12.5 install) and use the latest version of CKAN (1.31.2)
* Delete the CKAN folder form the KSP folder to simulate running the executable for the first time.
* Run executable and the download not completing screen should arise.
* Wait 20-30 seconds for "Failed to roll back." error to show.
* Progress to main screen by clicking "Ok."

**Expected behavior**
* Explained above ^^^

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/75050004/224545293-7faf2939-40b9-4a22-b705-931177220ff6.png)
^^^ Download not completing and preventing progression to next page.

![image](https://user-images.githubusercontent.com/75050004/224545339-223c9ec2-cffa-4c0b-addf-5467aabb23d5.png)
^^^ After 20-30 seconds it throws a "Failed to roll back." error and then allows progression to next page.

![image](https://user-images.githubusercontent.com/75050004/224545442-520ddad6-9781-47bb-86c9-0f8aabb3a688.png)
^^^ after progressing to main page no installed mods are shown (i have several already in the game data folder) and there is no tab to install new mods.

**CKAN error code (if applicable):**

```
Scanning for DLCs and manually installed modules...
Updating repositories...
Refreshing game version data
Downloading "https://github.com/KSP-CKAN/CKAN-meta/archive/master.tar.gz"
Loading modules from default repository...
Loaded download counts from default repository
Repository update failed!
Failed to roll back.

```

**Comment by HebaruSan** [comment] 2023-03-12 14:23
Duplicate of #3763

**Closed by HebaruSan** 2023-03-12 14:23 UTC
