### ISSUE TITLE
Mods are conflicting with themselves after attempted update.

### ISSUE THREAD

**Issue by Aegius** [KSP-CKAN/CKAN#2441] opened 2018-05-08 12:37 UTC
Background
----------

**CKAN Version:** 
1.25.1

**KSP Version:** 
1.4.2

**Operating System:** 
Windows

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

Problem
-------
When I attempted to update mods after re downloading CKAN to the newest version, several mods such as BD Armory and Next Star Industries were conflicting. When I attempted to remove them, they would cause CKAN to say that they conflicted. 
**What steps did you take in CKAN?**
I Downloaded the newest version of CKAN (1.25.1), attempted to update several mods

**What did you expect to happen?**
Mods to update and finish as normal

**What happened instead?**
An alert opened saying that mods were conflicting with each other and CKAN had to be closed through task manager.

**Screenshots:**

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment] 2018-05-08 15:33
Thanks for the report. [BDArmoryContinued](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/BDArmoryContinued.netkan) both provides and conflicts with BDArmory, which makes this a duplicate of #2428.

**Closed by HebaruSan** 2018-05-08 15:33 UTC
Labels: Duplicate
