### ISSUE TITLE
[Bug]: Repository Update Failed Error while Updating

### ISSUE THREAD

**Issue by LuckyHead11** [KSP-CKAN/CKAN#4081] opened 2024-04-28 19:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows 11 x64

### CKAN Version

v1.34.4

### Games

KSP 1

### Game Version

v1.25.5

### Describe the bug

When I start CKAN it automatically updates and checks the GitHub repository for mods, but It fails.
![image](https://github.com/KSP-CKAN/CKAN/assets/93405290/7d591376-d1e4-45ee-95b3-ed23639cd2b9)

CKAN has been running fine until recently, I haven't done anything like installing an antivirus.
(Yes I did see the other issue about this but it didn't help)

I expected for it to fetch the mods from the repo and display them so I could download and install them.

### Steps to reproduce

1. Start CKAN
2. Either press "Refresh" or have it update the mods
3. Then the window will pop up with the log, and then it fails.

### Relevant log output

2225 [1] ERROR CKAN.GUI.Main (null) - Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at CKAN.Extensions.DictionaryExtensions.<>c__DisplayClass0_0`2.<DictionaryEquals>b__1(K k)
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at CKAN.Registry.SetDlcs(Dictionary`2 dlcs)
   at CKAN.RegistryManager.ScanUnmanagedFiles()
   at CKAN.GUI.Main.UpdateRepo(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by HebaruSan** [comment] 2024-04-28 19:30
Duplicate of #4000

**Comment by HebaruSan** [comment] 2024-04-28 19:30
@LuckyHead11, you have an empty folder in `<KSP folder>/GameData/SquadExpansion`. Remove it to fix the issue.

**Closed by HebaruSan** 2024-04-28 19:30 UTC

**Comment by LuckyHead11** [comment] 2024-04-28 19:33
Yep, thank you! I wasn't sure how I didn't see the other issue.

**Comment by LuckyHead11** [comment] 2024-04-28 19:36
(It's extremely uncanny how you responded that fast 😅)

**Comment by mizar1** [comment] 2024-06-02 21:33
CKAN failing because of SquadExpansion is a CKAN bug as SquadExpansion is generated in response to buying/installing a single DLC or using Steam to move KSP from one disk to another.  I had this folder with my single purchased DLC activated.

**Comment by HebaruSan** [comment] 2024-06-02 21:34
@mizar1, please don't spam the same comment across multiple issues.
