### ISSUE TITLE
Null Reference Exception at CKAN.GUIUser.DisplayMessage

### ISSUE THREAD

**Issue by efalder413** [KSP-CKAN/CKAN#2487] opened 2018-08-06 19:53 UTC
Background
----------

**CKAN Version:** 1.25.2

**KSP Version:** 1.4.3

**Operating System:** Windows 7

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** Nope

Problem
-------

**What steps did you take in CKAN?**
Attempted to open

**What did you expect to happen?**
Program to start as normal

**What happened instead?**
Unhandled Exception: System.NullReferenceException: Object reference not set to
an instance of an object.
   at CKAN.GUIUser.DisplayMessage(String message, Object[] args)
   at CKAN.KSP.SetupCkanDirectories()
   at CKAN.KSP..ctor(String gameDir, String name, IUser user)
   at CKAN.KSPManager.LoadInstancesFromRegistry()
   at CKAN.Main..ctor(String[] cmdlineArgs, KSPManager mgr, GUIUser user, Boolea
n showConsole)
   at CKAN.GUI.Main_(String[] args, KSPManager manager, Boolean showConsole)
   at CKAN.CmdLine.MainClass.Main(String[] args)

**Screenshots:**

![image](https://user-images.githubusercontent.com/6841035/43737773-4d7255f4-9977-11e8-91e5-1ebd8490b64b.png)

**CKAN error codes (if applicable):** 

None.

**Comment by efalder413** [comment] 2018-08-06 20:18
Error persists even after uninstalling + re-installing thru Steam.

**Comment by HebaruSan** [comment] 2018-08-06 20:48
Duplicate of #2483, fixed in #2482.

**Closed by HebaruSan** 2018-08-06 20:48 UTC
