### ISSUE TITLE
System.IO.FileNotFoundException: Could not load file or assembly System.Core

### ISSUE THREAD

**Issue by Phantomblazecat** [KSP-CKAN/CKAN#3730] opened 2022-12-01 21:05 UTC
Background
----------
* Operating System: Windows 10
* CKAN Version: 1.31.0
* KSP Version: 1.12.4

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
Ever since a few weeks ago, CKAN just straight up refuses to launch, instead handing me an error before instantly closing, even after deleting everything related to CKAN off my computer

**Steps to reproduce**
Just open up CKAN

**Screenshots (if applicable)**

![image](https://user-images.githubusercontent.com/61366666/205159003-12421799-1987-44d3-87c2-515ae671b5bc.png)

**Comment by HebaruSan** [comment] 2022-12-01 21:05
Thanks, we just finished fixing this, you can try the latest dev build if you'd like to test:

- https://ksp-ckan.s3-us-west-2.amazonaws.com/ckan.exe

**Comment by HebaruSan** [comment] 2022-12-01 21:05
Duplicate of #3707

**Comment by Phantomblazecat** [comment] 2022-12-01 21:15
> Thanks, we just finished fixing this, you can try the latest dev build if you'd like to test:
> 
> * https://ksp-ckan.s3-us-west-2.amazonaws.com/ckan.exe

Nothing's changed, still the same insta crashed followed by "CKAN-CmdLine has stopped working"

**Comment by HebaruSan** [comment] 2022-12-01 21:19
Ahh, sorry, we've seen a lot of duplicates of that lately so it's my first resort for vague-ish "it crashes" issues.

"Could not load file or assembly System.Core" means something's badly wrong with your .NET Framework install. Try searching for that error to get suggestions for how to fix it:

- <https://www.google.com/search?q=could+not+load+file+or+assembly+system.core&oq=could+not+load+file+or+assembly+system.core>

**Closed** 2022-12-02 18:45 UTC
Labels: Support, Windows
