### ISSUE TITLE
CKAN unable to establish uplink

### ISSUE THREAD

**Issue by Takori-tano** [KSP-CKAN/CKAN#1390] opened 2015-08-18 06:22 UTC
CKAN is unable to link to the master Archive, and is thus non-functional.

"Connection to https://github.com/KSP-CKAN/CKAN-meta/archive/master.tar.gz could not be established."

This results in a blank mods listing, and I think, the inability to load a CKAN mod list. I downloaded CKAN just today, so I'm trying to figure it out.

I have even shut down firewalls and antivirus programs to check to see if they were the issue.

**Comment by plague006** [comment] 2015-08-18 13:08
This is because GitHub itself was apparently having issues. Closing this as a duplicate of #1389.

**Closed by plague006** 2015-08-18 13:08 UTC
