### ISSUE TITLE
Unhandled Exception: System.NullReferenceException

### ISSUE THREAD

**Issue by dsetzer** [KSP-CKAN/CKAN#2498] opened 2018-08-13 23:04 UTC
Background
----------

**CKAN Version:** 
1.25.2

**KSP Version:** 
1.4.4

**Operating System:** 
Windows 10 (64bit)

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
Yes

Problem
-------

**What steps did you take in CKAN?**
Assuming this to still be standard procedure after updating  I wanted to remove all the mods from my KSP install so I deleted everything from the GameData folder except for the Squad folder then I copied the downloads folder out of the ckan folder as a backup of the cached mods and deleted the ckan folder before reopening ckan as was standard procedure previously..

**What did you expect to happen?**
Expected to reopen ckan and it would do it's thing as if it was a fresh install..

**What happened instead?**
got an error in the console window that pops up saying:

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at CKAN.GUIUser.DisplayMessage(String message, Object[] args)
   at CKAN.KSP.SetupCkanDirectories()
   at CKAN.KSP..ctor(String gameDir, String name, IUser user)
   at CKAN.KSPManager.LoadInstancesFromRegistry()
   at CKAN.Main..ctor(String[] cmdlineArgs, KSPManager mgr, GUIUser user, Boolean showConsole)
   at CKAN.GUI.Main_(String[] args, KSPManager manager, Boolean showConsole)
   at CKAN.CmdLine.MainClass.Main(String[] args)

**Screenshots:**

![image](https://user-images.githubusercontent.com/18156908/44062786-ca17320a-9f12-11e8-907a-739e53a83a49.png)

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment] 2018-08-14 00:15
Duplicate of #2483, fixing in #2482.

**Closed by HebaruSan** 2018-08-14 00:15 UTC
