### ISSUE TITLE
[Bug] CKAN freezes after clicking "Installed" button

### ISSUE THREAD

**Issue by MrBarramundi** [KSP-CKAN/CKAN#3803] opened 2023-03-06 04:20 UTC
Background
----------
* Operating System: Windows 10 Home OS build 19044.2604
* CKAN Version: v1.31.2
* KSP Version: 1.12.5.3190

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
Answer: No, unless installing the DLCs counts.

Problem
-------
Whenever I try to click on the "Installed" check box on a mod in the list, CKAN freezes & goes into "Not Responding". I have to force close the program. I've tried closing then opening multiple time, & I deleted the .exe & re-downloaded it, which I didn't think would help because I see that CKAN creates files elsewhere, but I gave it a try & it still does the same thing.

I've had CKAN for about a week, & I decided to buy the DLCs today (3/5/23). After buying & installing the DLCs, I noticed one of my mods had disappeared ([x] Science! Continued). After playing a few hours I went to re-install the missing mod, & that's when I noticed the issue. It's not just that mod. I've tried clicking other mods & its the same story.

**Steps to reproduce**
* Open CKAN
* Click on a mod's Installed check box
* Watch program freeze forever, or a very long time at least. I've not seen it unfreeze while writing this (about 30min)

**Note:**
I don't know why I didn't do this before submitting, but I deleted the CKAN folder from the Kerbal Space Program folder, then ran the CKAN exe. It fixed the issue, but now all my mods are gone, so it would still be nice to see the issue fixed, which I believe must have been caused by me installing the DLCs after having CKAN do it's thing.

**Comment by k0pyyy** [comment] 2023-03-06 20:40
I am also having this issue...

**Comment by k0pyyy** [comment] 2023-03-06 20:42
actually, doing just about anything seems to crash the program now.

**Comment by KianWalsh** [comment] 2023-03-06 23:21
Me too, had to manually install 20+ mods because it froze when I interacted with any item on the "list"

**Comment by craftersmine** [comment] 2023-03-13 05:54
On my system CKAN freezes when I try to click on "Apply Changes" or go to the "Changeset" tab, it completely locks up and doesn't respond again. Only process kill helps.

**Comment by HebaruSan** [comment] 2023-03-13 14:34
@craftersmine the rest of this issue may or may not be a duplicate of #3707, but your specific report definitely is

**Comment by craftersmine** [comment] 2023-03-13 15:28
> @craftersmine the rest of this issue may or may not be a duplicate of pinned issue #3707, but your specific report definitely is

Well, I didn't really tested anything from that issue yet, but after I've changed repository from local (for some reason, I can't open codeload.github.com because some SSL issues), to default, CKAN began to lock up when it tries to download repository metadata.

**Comment by craftersmine** [comment] 2023-03-13 17:44
> duplicate of pinned issue #3707

The executable provided in this issue has exactly the same issue, just freezes on this screen 
![image](https://user-images.githubusercontent.com/11241645/224784818-2aa306b7-3b40-492a-a412-d194a08a8c02.png)

**Comment by HebaruSan** [comment] 2023-03-13 17:46
That is not the same issue. That looks like a duplicate of #3763 instead.

**Comment by craftersmine** [comment] 2023-03-13 17:49
> That is not the same issue. That looks like a duplicate of #3763 instead.

Well, I deleted `%localappdata%\CKAN` and `%steamappdata%\Kerbal Space Program\CKAN` directories, it relaunched and froze on the exactly the same screen

**Comment by HebaruSan** [comment] 2023-03-13 17:51
@craftersmine please comment on the issue that is related to the problem you're having, not this one.

**Comment by fearvector** [comment] 2023-03-22 02:53
Ok i finally got it to go further enough that i could get the error prompts to come up. I have attached four txt files i made that contain what was under details, for each time i got a prompt. After i click continue on these by the way it just shows a blank output / window under changeset and nothing happens until i close Ckan.

[Error Output 001.txt](https://github.com/KSP-CKAN/CKAN/files/11035761/Error.Output.001.txt)
[Error Output 002.txt](https://github.com/KSP-CKAN/CKAN/files/11035762/Error.Output.002.txt)
[Error Output 003.txt](https://github.com/KSP-CKAN/CKAN/files/11035763/Error.Output.003.txt)
[Error Output 004.txt](https://github.com/KSP-CKAN/CKAN/files/11035764/Error.Output.004.txt)

**Comment by HebaruSan** [comment] 2023-04-08 16:36
This is probably fixed in the new version we just released (hard to say for sure because we weren't able to fully investigate, but it's similar to issues that were fixed and likely shared a common root cause). Please make sure you're using it:

- <https://github.com/KSP-CKAN/CKAN/releases/tag/v1.32.0>

... then make sure you're on a clean install:

- <https://github.com/KSP-CKAN/CKAN/wiki/Clean-and-reinstall-process>

If this problem still occurs after that, we can re-open this. Cheers!

**Closed by HebaruSan** 2023-04-08 16:36 UTC
