### ISSUE TITLE
[Bug] Scatterer conflicts with Scatterer Config

### ISSUE THREAD

**Issue by Proxiyl** [KSP-CKAN/CKAN#3562] opened 2022-04-12 19:27 UTC
Background
----------
* Operating System: Windows 11
* CKAN Version:  Hubble / v1.30.4
* KSP Version: Can be from 1.8.1 to 1.12.3

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
Very little, only for outside mods not added to CKAN as of now.

Problem
-------
Scatterer and it's config, whenever they are installed, cause am error when trying to download any new mods on the specified versions, i have not yet observed if it will stop the removal of mods.

**Steps to reproduce**
* Go to...  Scatter and Scatterer's config, download them, then look for any mod. 
* Click on... Install.
* See error

**Expected behavior**
Scatterer not conflicting with Scatterer config whilst installing other mods.

**Screenshots (if applicable)**
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/103531526/163034559-8a38cabb-44bb-483e-a0e6-0a8538e55654.png">

**CKAN error code:**

None seen (As of writing this)
```

```

**Comment by HebaruSan** [comment] 2022-04-12 19:28
Duplicate of KSP-CKAN/NetKAN#8866

**Comment by HebaruSan** [comment] 2022-04-12 19:31
Hi, if you look closely, the word "config" isn't anywhere in that error message.

See KSP-CKAN/NetKAN#8866 for details of what's happening. You can probably work around it by opening your GameData folder and renaming the `scatterer` folder (all lowercase) to `Scatterer` (first letter capitalized).

**Closed by HebaruSan** 2022-04-12 19:31 UTC
Labels: Support, Windows
