### ISSUE TITLE
problems with installation because some files are all ready in use. 

### ISSUE THREAD

**Issue by chrissho** [KSP-CKAN/CKAN#3298] opened 2021-02-21 20:04 UTC
Background
----------
* Operating System: windows 10
* CKAN Version: 1.29.2
* KSP Version: 1.6.1

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
yes i had to add ksp alarm clock, and Kopernicus 

Problem
-------
**Describe the bug**
every time i try to install any this i get the message 
The process cannot access the file 'C:\Users\sauci\AppData\Local\Temp\CdFileMgr\973da74b-c4b6-4e.json' because it is being used by another process.
Error during installation!

**Expected behavior**
for it to install probity

**Comment by HebaruSan** [comment] 2021-02-21 20:07
Looks like a duplicate of #3260. First thing to check is whether your antivirus is messing with that file.

**Closed** 2021-03-01 04:56 UTC
Labels: Support, Windows
