### ISSUE TITLE
[Bug]: CKAN can't load mods becase: "Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by CjExists** [KSP-CKAN/CKAN#4068] opened 2024-03-29 21:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

WIN10

### CKAN Version

1.34.4

### Games

KSP 1

### Game Version

1.12.5

### Describe the bug

When CKAN loads, it just says on the tab: "Object reference not set to an instance of an object." and some other stuff, expected it to load like normal.

### Steps to reproduce

no idea...

### Relevant log output

Scanning for DLCs and manually installed modules...
Object reference not set to an instance of an object.
Repository update failed!

**Comment by HebaruSan** [comment] 2024-03-29 21:17
Please share a screenshot so we can investigate this.

**Comment by CjExists** [comment] 2024-03-29 21:19
> Please share a screenshot so we can investigate this.

I don't know what to take a screenshot of.... what you see is what you get

**Comment by CjExists** [comment] 2024-03-29 21:20
![CKAN v1 34 4 - KSP 1 12 5 3190    --    C__Program Files (x86)_Steam_steamapps_common_Kerbal Space Program 3_29_2024 4_19_19 PM](https://github.com/KSP-CKAN/CKAN/assets/112908383/afd4bb3c-9fe0-4a90-bef6-db90dddcf4bc)

**Comment by HebaruSan** [comment] 2024-03-29 21:20
Duplicate of #4000

**Comment by HebaruSan** [comment] 2024-03-29 21:21
Thanks. You probably have a DLC folder without the DLC files. Check `<KSP dir>/GameData/SquadExpansion` for empty folders and remove them if found.

**Closed by HebaruSan** 2024-03-29 21:20 UTC
Labels: Support, Needs more info

**Comment by CjExists** [comment] 2024-03-29 21:21
TYSM, let me try it

**Comment by CjExists** [comment] 2024-03-29 21:22
Also, I really did try to look and I didn't just randomly check it, just saying this so I don't sound like a jerk lol.

**Comment by HebaruSan** [comment] 2024-03-29 21:23
> Also, I really did try to look and I didn't just randomly check it, just saying this so I don't sound like a jerk lol.

Don't worry about it. It's often hard to know what to search for to find a previous bug report. In those cases, submitting a duplicate can sometimes _help_ because other users who search for the terms you use will be able to find your issue instead.

**Comment by CjExists** [comment] 2024-03-29 21:24
I had my DLC off, works like a charm!

**Comment by mizar1** [comment] 2024-06-02 21:30
If CKAN is failing because of SquadExpanion folder then that is a bug in CKAN as SquadExpansion folder is created in response to buying/installing one DLC, or moving the KSP folder from one disk to another.  I had that folder even with my single purchased DLC activated.

**Comment by HebaruSan** [comment] 2024-06-02 21:33
@mizar1, that's correct, this was a bug in CKAN. It has been fixed, but the fix will be in a future version.
