### ISSUE TITLE
[Feature]: Manual UI scaling option

### ISSUE THREAD

**Issue by Real-Gecko** [KSP-CKAN/CKAN#4238] opened 2024-10-22 05:42 UTC
### Problem

I'm on Arch Linux with Plasma 6 and noticed that after update of some package(either Mono or Plasma itself, hard to say) CKAN does not follow global scaling option anymore.

### Suggestion

Maybe we can get some option in CKAN itself for scaling UI manually? So we can scale the UI manually without relying on system settings.

### Alternatives

A few weeks ago scaling did work, however now it does not. I've tried older versions of CKAN, switching between X server and Wayland, nothing helps. So it's hard to pinpoint which package update caused the scaling to break.

**Comment by HebaruSan** [comment] 2024-10-22 14:02
Duplicate of #878

**Closed by HebaruSan** 2024-10-22 14:02 UTC
