### ISSUE TITLE
CKAN will not launch

### ISSUE THREAD

**Issue by Zalson** [KSP-CKAN/CKAN#2511] opened 2018-08-21 22:35 UTC
Background
----------

**CKAN Version:** 
Current: Downloaded today

**KSP Version:** 
Current

**Operating System:** 
Win 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

Problem
-------

**What steps did you take in CKAN?**
CKAN will not launch

**What did you expect to happen?**
CKAN to start

**What happened instead?**
CKAN crashed

**Screenshots:**

![image](https://user-images.githubusercontent.com/8302548/44432643-e57e9b00-a570-11e8-9263-c531ef5c718a.png)

**CKAN error codes (if applicable):** 

See screenshot

**Comment by HebaruSan** [comment] 2018-08-21 22:40
Duplicate of #2483, fixed in #2482.

**Closed by HebaruSan** 2018-08-21 22:40 UTC
