### ISSUE TITLE
SystemNull error when trying to launch CKAN

### ISSUE THREAD

**Issue by flyingmadpakke** [KSP-CKAN/CKAN#2503] opened 2018-08-17 20:50 UTC
Background
----------
I installed the application earlier this day. I modded my game, but I kinda "corrupted" it in the process (basically trying to uninstall an extra planets mod, but it screwed up my game). Therefore I decided to uninstall everything, then reinstall and try again, but now CKAN will not work. 
I have a screenshot of the problem, basically CKAN doesn't start. Instead it gives me a SystemNull error. 
I know almost nothing about programs, but isn' a NullReference error something along the lines of the program calling the listed "components", but they return sort of empty? Or as cmd calls them, the references are sent out, but they don't seem to be linked with any actual code?

**CKAN Version:** 
1.25.2

**KSP Version:** 
1.4.5

**Operating System:** 
Windows 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
Not on my current attempt at running the application, but I did edit it the first time I installed CKAN. (Before I made a clean reinstall, GameData was edited - after clean install it was not)

Problem
-------

**What steps did you take in CKAN?**
Tried to run the application

**What did you expect to happen?**
The application would run and I would be taken to the main screen

**What happened instead?**
The application crashes with a "systemNull" error

**Screenshots:**
![image](https://user-images.githubusercontent.com/42479724/44287196-31c59480-a26c-11e8-841f-b56ec6437efc.png)
 

**CKAN error codes (if applicable):** 
I have the sreenshot :)
(I also have some weird .WER file my system has generated called "AppCrash_ckan.exe_"a long string"")

Hope you can help. 
I was watching a stream of KSP and felt like playing it again, so I'm kinda sad now.

**Comment by HebaruSan** [comment] 2018-08-17 20:59
Duplicate of #2483, fixed in #2482.

**Closed by HebaruSan** 2018-08-17 20:59 UTC
