### ISSUE TITLE
crash when upgrading a module where a 'recommends' was not installed

### ISSUE THREAD

**Issue by akasurak** [KSP-CKAN/CKAN#727] opened 2015-01-03 18:30 UTC
Installed kerbal alarm clock, but not triggerAu-flags. When upgrading alarm clock, ckan will crash because the flags mod could not be found.

**Comment by Dazpoet** [comment] 2015-04-15 17:19
Looking through the CKAN-meta history for KAC I conclude that this was most probably a case of metadata being updated to change a recommendation into no longer being there and as such ckan "spunked out" becasue it wasn't yet equipped to handle such an occurance.

I'm unable to reproduce this problem since KAC no longer recommends triggerAu-flags and hasn't in the last few months. As such I will close this.

**Closed by Dazpoet** 2015-04-15 17:19 UTC
