### ISSUE TITLE
Going to settings, raise exception

### ISSUE THREAD

**Issue by AeonDave** [KSP-CKAN/CKAN#2397] opened 2018-04-03 17:20 UTC
Background
----------

**CKAN Version:** 
1.24.0

**KSP Version:** 
1.4.2.2110

**Operating System:** 
Win10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
no

Problem
-------

**What steps did you take in CKAN?**
After opening CKAN, CKAN settings, raise an exception.

**What did you expect to happen?**
Opening Settings menu

**What happened instead?**
Exception

**Screenshots:**
![immagine](https://user-images.githubusercontent.com/7406886/38264650-f449602c-3773-11e8-9bfb-e495322b7e1b.png)

**CKAN error codes (if applicable):** 
Le informazioni su come richiamare il debug JIT (Just-In-Time) anziché questa finestra
sono riportate in fondo al messaggio.

************** Testo dell'eccezione **************
System.NullReferenceException: Riferimento a un oggetto non impostato su un'istanza di oggetto.
   in CKAN.SettingsDialog.RefreshAuthTokensListBox()
   in CKAN.SettingsDialog.UpdateDialog()
   in System.Windows.Forms.Form.OnLoad(EventArgs e)
   in System.Windows.Forms.Form.OnCreateControl()
   in System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   in System.Windows.Forms.Control.CreateControl()
   in System.Windows.Forms.Control.WmShowWindow(Message& m)
   in System.Windows.Forms.Control.WndProc(Message& m)
   in System.Windows.Forms.Form.WmShowWindow(Message& m)
   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Assembly caricati **************
mscorlib
    Versione assembly: 4.0.0.0
    Versione Win32: 4.7.2633.0 built by: NET471REL1LAST_C
    Base di codice: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ckan
    Versione assembly: 1.24.0.0
    Versione Win32: 1.24.0
    Base di codice: file:///D:/ckan.exe
----------------------------------------
System.Core
    Versione assembly: 4.0.0.0
    Versione Win32: 4.7.2633.0 built by: NET471REL1LAST_C
    Base di codice: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Versione assembly: 4.0.0.0
    Versione Win32: 4.7.2556.0 built by: NET471REL1
    Base di codice: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Configuration
    Versione assembly: 4.0.0.0
    Versione Win32: 4.7.2556.0 built by: NET471REL1
    Base di codice: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Versione assembly: 4.0.0.0
    Versione Win32: 4.7.2612.0 built by: NET471REL1LAST_B
    Base di codice: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms
    Versione assembly: 4.0.0.0
    Versione Win32: 4.7.2556.0 built by: NET471REL1
    Base di codice: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Versione assembly: 4.0.0.0
    Versione Win32: 4.7.2556.0 built by: NET471REL1
    Base di codice: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Transactions
    Versione assembly: 4.0.0.0
    Versione Win32: 4.7.2556.0 built by: NET471REL1
    Base di codice: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.Windows.Forms.resources
    Versione assembly: 4.0.0.0
    Versione Win32: 4.7.2556.0 built by: NET471REL1
    Base di codice: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_it_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
mscorlib.resources
    Versione assembly: 4.0.0.0
    Versione Win32: 4.7.2556.0 built by: NET471REL1
    Base di codice: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_it_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
Microsoft.GeneratedCode
    Versione assembly: 1.0.0.0
    Versione Win32: 4.7.2612.0 built by: NET471REL1LAST_B
    Base di codice: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Numerics
    Versione assembly: 4.0.0.0
    Versione Win32: 4.7.2556.0 built by: NET471REL1
    Base di codice: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Versione assembly: 4.0.0.0
    Versione Win32: 4.7.2612.0 built by: NET471REL1LAST_B
    Base di codice: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Versione assembly: 4.0.0.0
    Versione Win32: 4.7.2633.0 built by: NET471REL1LAST_C
    Base di codice: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Versione assembly: 0.0.0.0
    Versione Win32: 4.7.2633.0 built by: NET471REL1LAST_C
    Base di codice: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
Microsoft.CSharp
    Versione assembly: 4.0.0.0
    Versione Win32: 4.7.2556.0
    Base di codice: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    Versione assembly: 4.0.0.0
    Versione Win32: 4.7.2556.0
    Base di codice: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Microsoft.CSharp.resources
    Versione assembly: 4.0.0.0
    Versione Win32: 4.7.2556.0
    Base di codice: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp.resources/v4.0_4.0.0.0_it_b03f5f7f11d50a3a/Microsoft.CSharp.resources.dll
----------------------------------------
System.EnterpriseServices
    Versione assembly: 4.0.0.0
    Versione Win32: 4.7.2556.0 built by: NET471REL1
    Base di codice: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
System.resources
    Versione assembly: 4.0.0.0
    Versione Win32: 4.7.2556.0 built by: NET471REL1
    Base di codice: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_it_b77a5c561934e089/System.resources.dll
----------------------------------------

************** Debug JIT **************
Per abilitare il debug JIT, è necessario impostare il valore
jitDebugging nella sezione system.windows.forms del file di configurazione
dell'applicazione o del computer (machine.config).
L'applicazione inoltre deve essere compilata con il debug
abilitato.

**Comment by HebaruSan** [comment] 2018-04-03 17:24
Duplicate of #2300, fixed in #2301. To work around this, click Continue, then add a fake auth token.

**Closed by HebaruSan** 2018-04-03 17:24 UTC
