### ISSUE TITLE
[Bug]: Not showing KSP_64.exe in New game instance -> Add instance to CKAN

### ISSUE THREAD

**Issue by ianic-dev** [KSP-CKAN/CKAN#4181] opened 2024-09-12 08:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Arch Linux

### CKAN Version

1.34.4

### Games

KSP 1

### Game Version

1.12.5.3190 (windows version through proton)

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

No

### Describe the bug

When navigating to the KSP game folder in the New game instance -> Add instance to CKAN, only the subfolders are shown. The KSP_x64.exe file, which is in that directory, does not appear and cannot be selected.

### Steps to reproduce

* Install the steam package on Arch Linux
* Install the windows version of KSP by selecting proton experimental in game compatibility options
* Install CKAN through the AUR
* Launch CKAN (the instance management window pops up)
* New game instance -> Add instance to CKAN
* Rightclick -> show hidden files
* Navigate to ~/.steam/steam/steamapps/common/Kerbal Space Program
* KSP_x64.exe is not shown or selectable

**Comment by ianic-dev** [comment] 2024-09-12 09:05
KSP is autodetected and CKAN works when the Linux version is installed

**Comment by HebaruSan** [comment] 2024-09-12 12:59
Duplicate of #4041

**Closed by HebaruSan** 2024-09-12 12:59 UTC
